local extras = Spring.Utilities.AmmoBasedCommands
local SUC = Spring.Utilities.CMD

local configList = {
	{label = "Basic Commands"},
	{cmdID = SUC.AREA_MEX              , default = true, name = "Area Mex"},
	{cmdID = CMD.FIGHT                 , default = true, name = "Attack Move"},
	{cmdID = SUC.BUILD_PLATE           , default = true, name = "Build Plate"},
	{cmdID = SUC.FIELD_FAC_SELECT      , default = true, name = "Copy Factory Blueprint"},
	{cmdID = SUC.EMBARK                , default = true, name = "Embark"},
	{cmdID = CMD.MANUALFIRE            , default = true, name = "Fire Special Weapon"},
	{cmdID = SUC.AIR_MANUALFIRE        , default = true, name = "Fire Special Weapon (Aircraft)"},
	{cmdID = CMD.ATTACK                , default = true, name = "Force Fire"},
	{cmdID = SUC.JUMP                  , default = true, name = "Jump"},
	{cmdID = CMD.LOAD_UNITS            , default = true, name = "Load"},
	{cmdID = SUC.RAW_MOVE              , default = true, name = "Move"},
	{cmdID = CMD.STOP                  , default = true, name = "Stop"},
	{cmdID = SUC.STOP_PRODUCTION       , default = true, name = "Stop Production"},
	{cmdID = CMD.PATROL                , default = true, name = "Patrol"},
	{cmdID = SUC.RECALL_DRONES         , default = true, name = "Recall Drones"},
	{cmdID = SUC.DRONE_SET_TARGET      , default = true, name = "Set Drone Target"},
	{cmdID = SUC.SELECT_DRONES         , default = true, name = "Select Drones"},
	{cmdID = CMD.RECLAIM               , default = true, name = "Reclaim"},
	{cmdID = SUC.GREYGOO               , default = true, name = "Reclaim (Grey Goo)"},
	{cmdID = CMD.REPAIR                , default = true, name = "Repair"},
	{cmdID = SUC.FIND_PAD              , default = true, name = "Resupply"},
	{cmdID = CMD.RESURRECT             , default = true, name = "Resurrect"},
	{cmdID = CMD.UNLOAD_UNITS          , default = true, name = "Unload"},
	{cmdID = SUC.IMMEDIATETAKEOFF      , default = true, name = "Take off"},
	{label = "Advanced Commands (hidden by default)"},
	{cmdID = CMD.AREA_ATTACK           , default = false, name = "Area Attack"},
	{cmdID = SUC.AREA_TERRA_MEX        , default = false, name = "Area Terra Mex"},
	{cmdID = SUC.UNIT_CANCEL_TARGET    , default = false, name = "Cancel Target"},
	{cmdID = SUC.DISEMBARK             , default = false, name = "Disembark"},
	{cmdID = SUC.EXCLUDE_PAD           , default = false, name = "Exclude Airpad"},
	{cmdID = SUC.AREA_GUARD            , default = false, name = "Guard"},
	{cmdID = SUC.UNIT_SET_TARGET_CIRCLE, default = false, name = "Set Target"},
	{cmdID = CMD.WAIT                  , default = false, name = "Wait"},
	
	{label = "Basic States"},
	{cmdID = SUC.WANT_ONOFF            , state = true, default = true, name = "Activation"},
	{cmdID = CMD.IDLEMODE              , state = true, default = true, name = "Air Idle State"},
	{cmdID = SUC.AP_FLY_STATE          , state = true, default = true, name = "Air Factory Idle State"},
	{cmdID = SUC.CLOAK_SHIELD          , state = true, default = true, name = "Area Cloaker"},
	{cmdID = SUC.PREVENT_BAIT          , state = true, default = true, name = "Avoid Bad Targets"},
	{cmdID = SUC.DONT_FIRE_AT_RADAR    , state = true, default = true, name = "Fire At Radar State"},
	{cmdID = SUC.FIRE_TOWARDS_ENEMY    , state = true, default = true, name = "Fire Towards Enemies"},
	{cmdID = SUC.FACTORY_GUARD         , state = true, default = true, name = "Auto Assist"},
	{cmdID = SUC.WANT_CLOAK            , state = true, default = true, name = "Cloak"},
	{cmdID = SUC.PRIORITY              , state = true, default = true, name = "Construction Priority"},
	{cmdID = SUC.TOGGLE_DRONES         , state = true, default = true, name = "Drone Construction"},
	{cmdID = SUC.UNIT_FLOAT_STATE      , state = true, default = true, name = "Float State"},
	{cmdID = SUC.AIR_STRAFE            , state = true, default = true, name = "Gunship Strafe"},
	{cmdID = CMD.FIRE_STATE            , state = true, default = true, name = "Hold Fire (Fire State)"},
	{cmdID = CMD.MOVE_STATE            , state = true, default = true, name = "Hold Position (Move State)"},
	{cmdID = SUC.PUSH_PULL             , state = true, default = true, name = "Impulse Mode"},
	{cmdID = SUC.MISC_PRIORITY         , state = true, default = true, name = "Misc Priority"},
	{cmdID = SUC.GOO_GATHER            , state = true, default = true, name = "Replication"},
	{cmdID = CMD.REPEAT                , state = true, default = true, name = "Repeat"},
	{cmdID = SUC.RETREATSHIELD		   , state = true, default = true, name = "Retreat Shields"},
	{cmdID = SUC.RETREAT               , state = true, default = true, name = "Retreat"},
	{cmdID = CMD.TRAJECTORY            , state = true, default = true, name = "Trajectory"},
	{cmdID = SUC.AUTOJUMP              , state = true, default = true, name = "Autojump"},
	{cmdID = SUC.ARMORSTATE            , state = true, default = true, name = "Hunker Down"},
	{cmdID = SUC.OVERRECLAIM           , state = true, default = true, name = "Overreclaim Prevention"},
	{cmdID = SUC.QUEUE_MODE            , state = true, default = true, name = "Rally Point Edit Mode"},
	{cmdID = SUC.AUTOEXPAND            , state = true, default = true, name = "Autoexpand"},

	{label = "Advanced States (hidden by default)"},
	{cmdID = SUC.DISABLE_ATTACK        , state = true, default = false, name = "Allow Attack Commands"},
	{cmdID = SUC.UNIT_BOMBER_DIVE_STATE, state = true, default = false, name = "Bomber Dive State"},
	{cmdID = SUC.AUTO_CALL_TRANSPORT   , state = true, default = false, name = "Call Transports"},
	{cmdID = SUC.GLOBAL_BUILD          , state = true, default = false, name = "Global Build"},
	{cmdID = SUC.UNIT_KILL_SUBORDINATES, state = true, default = false, name = "Kill Captured"},
	{cmdID = SUC.PREVENT_OVERKILL      , state = true, default = false, name = "Overkill Prevention"},
	{cmdID = SUC.SELECTION_RANK        , state = true, default = false, name = "Selection Rank"},
	{cmdID = SUC.FORMATION_RANK        , state = true, default = false, name = "Formation Rank"},
	{cmdID = SUC.UNIT_AI               , state = true, default = false, name = "Unit AI"},
	{cmdID = SUC.FIRE_AT_SHIELD        , state = true, default = false, name = "Ward Fire"},
	{cmdID = SUC.FIRECYCLE             , state = true, default = false, name = "Spread Napalm"},
	{label = "Ammo States (Shown by default)"},
}

local defaultValues = {
	[CMD.SELFD] = true,
	[CMD.WAIT] = true,
	[SUC.DISEMBARK] = true,
	[CMD.AREA_ATTACK] = true,
	[SUC.AREA_TERRA_MEX] = true,
	[SUC.AREA_GUARD] = true,
	[SUC.UNIT_SET_TARGET_CIRCLE] = true,
	[SUC.UNIT_CANCEL_TARGET] = true,
	[SUC.EXCLUDE_PAD] = true,
	[SUC.AUTOEXPAND] = true,
	--[SUC.EMBARK] = true,
	--[SUC.STOP_PRODUCTION] = true,
	
	-- states
	--[SUC.RETREAT] = true,
	--[SUC.WANT_ONOFF] = true,
	--[CMD.REPEAT] = true,
	--[SUC.WANT_CLOAK] = true,
	--[CMD.TRAJECTORY] = true,
	--[SUC.UNIT_FLOAT_STATE] = true,
	--[SUC.PRIORITY] = true,
	--[SUC.MISC_PRIORITY] = true,
	--[SUC.FACTORY_GUARD] = true,
	--[SUC.TOGGLE_DRONES] = true,
	--[SUC.PUSH_PULL] = true,
	--[CMD.IDLEMODE] = true,
	--[SUC.AP_FLY_STATE] = true,
	[SUC.UNIT_AI] = true,
	--[SUC.CLOAK_SHIELD] = true,
	[SUC.AUTO_CALL_TRANSPORT] = true,
	[SUC.GLOBAL_BUILD] = true,
	--[CMD.MOVE_STATE] = true,
	--[CMD.FIRE_STATE] = true,
	[SUC.UNIT_BOMBER_DIVE_STATE] = true,
	[SUC.UNIT_KILL_SUBORDINATES] = true,
	--[SUC.GOO_GATHER] = true,
	[SUC.DISABLE_ATTACK] = true,
	--[SUC.DONT_FIRE_AT_RADAR] = true,
	[SUC.PREVENT_OVERKILL] = true,
	--[SUC.AIR_STRAFE] = true,
	[SUC.SELECTION_RANK] = true,
	[SUC.FORMATION_RANK] = true,
}

for name, id in pairs(extras) do
	local shownName = UnitDefNames[string.lower(name):gsub("ammo_select_", "")].humanName
	configList[#configList + 1] = {cmdID = id, state = true, default = true, name = "Ammo State (" .. shownName .. ")"}
end

return configList, defaultValues
