local name = "commweapon_riotcannon_fragment_dummy"
weaponDef = {
	name                    = [[Riot Blast]],
	accuracy                = 400,
	areaOfEffect            = 160,
	avoidFeature            = false,
	craterBoost             = 1,
	craterMult              = 2,
	collideEnemy            = false,
	collideFriendly         = false,
	customParams              = {
		projectile1 = "commweapon_clustergrenade_fragment",
		noairburst = "I belive I can fly...",
		timeddeploy = 12,
		commsubmunition = 1,
		--lups_heat_fx = [[firewalker]],
		light_camera_height = 2500,
		light_color = [[0.25 0.13 0.05]],
		light_radius = 500,
		shield_damage = 150,
	},
	damage                  = {
		default = 0,
	},
	firestarter             = 180,
	impulseBoost            = 0,
	impulseFactor           = 0.4,
	interceptedByShieldType = 1,
	myGravity               = 0.31,
	noExplode               = true,
	projectiles             = 10,
	range                   = 900,
	reloadtime              = 12,
	rgbColor                = [[1 0.5 0.2]],
	size                    = 5,
	soundHit                = [[nosound]],
	soundStart              = [[weapon/cannon/wolverine_fire]],
	soundStartVolume        = 3.2,
	sprayangle              = 2500,
	turret                  = true,
	weaponType              = [[Cannon]],
	weaponVelocity          = 320,
}

return name, weaponDef
-- NOTE: This weapon is a SECONDARY STAGE PROJECTILE. It is not intended for use as an actual weapon!
