return {
  ["ataalasergrow"] = {
    groundsmoke = {
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = false,
      air                = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.8 0.3 0 1  0.7 0.4 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 4,
        particlelifespread = 10,
        particlesize       = [[d4]],
        particlesizespread = [[d20]],
        particlespeed      = [[d3]],
        particlespeedspread = [[d10]],
        pos                = [[0 rd-10 rd10, 0 rd-10 rd10, 0 rd-10 rd10]],
        sizegrowth         = [[d1.7]],
        sizemod            = 1,
        texture            = [[smokesmall]],
      },
    },
    flash = {
      count              = 3,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      air                = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.6 0 0.01   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 8,
        particlelifespread = 8,
        particlesize       = [[d4]],
        particlesizespread = [[d18]],
        particlespeed      = [[d2]],
        particlespeedspread = [[d10]],
        pos                = [[0 rd-10 rd10, 0 rd-10 rd10, 0 rd-10 rd10]],
        sizegrowth         = [[d1.5]],
        sizemod            = 1,
        texture            = [[flare]],
      },
    },
    flash2 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      air                = true,
	  unit               = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.9 0.35 0 0.01   0 0 0 0]],
        directional        = 0,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 15,
        particlelifespread = 4,
        particlesize       = [[d8]],
        particlesizespread = [[d4]],
        particlespeed      = [[d1]],
        particlespeedspread = [[d7]],
        pos                = [[0,d15,0]],
        sizegrowth         = [[d1]],
        sizemod            = 1.1,
        texture            = [[flare]],
      },
    },
    stacheln1 = {
      air                = true,
      class              = [[explspike]],
      count              = 8,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 2,
        alphadecay         = 0.25,
        color              = [[1, 0.25, 0]],
        dir                = [[r20 r-15, r-15 r20, r20 r-15]],
        length             = [[d20]],
        lengthgrowth       = -3,
        pos                = [[0, d1, 0]],
        width              = [[d18]],
      },
    },
    funken = {
      class              = [[CSimpleParticleSystem]],
      count              = 5,
      ground             = true,
      air                = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.35 0.2 0.01  0.85 0.45 0.1 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0,1,0]],
        gravity            = [[0,0, 0]],
        numparticles       = 5,
        particlelife       = 12,
        particlelifespread = 15,
        particlesize       = [[d6]],
        particlesizespread = 0,
        particlespeed      = [[d3]],
        particlespeedspread = [[d4]],
        pos                = [[0, d1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[gunshot]],
      },
    },
    yudell = {
      air                = false,
      class              = [[CSimpleGroundFlash]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        colormap           = [[1 0.7 0 0.2  0.7 0.5 0 0.2    0 0 0 0]],
        size               = [[d35]],
        sizegrowth         = [[d-1.25]],
        texture            = [[groundflash]],
        ttl                = 60,
      },
    },
    yudell3 = {
      air                = false,
      class              = [[CSimpleGroundFlash]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        colormap           = [[1 1 0 0.2  1 .45 0 0.2     0 0 0 0]],
        size               = [[d20]],
        sizegrowth         = [[d-1.25]],
        texture            = [[groundflash]],
        ttl                = 60,
      },
    },
  },
}
