return {
	["ion_beam"] = {
		usedefaultexplosions = false,
		groundflash = {
			circlealpha        = 0,
			circlegrowth       = 1,
			flashalpha         = 1.0,
			flashsize          = 26,
			ttl                = 24,
			color = {
				[1]  = 0.11764,
				[2]  = 0.4705,
				[3]  = 0.69019,
			},
		},
		pikes = {
			air                = true,
			class              = [[explspike]],
			count              = 5,
			ground             = true,
			water              = true,
			underwater		   = true,
			properties = {
				alpha              = 1,
				alphadecay         = 0.06,
				color              = [[0.0196,0.61176,0.98039]],
				dir                = [[-2 r4,-2 r4,-2 r4]],
				length             = 7,
				width              = 7,
			},
		},
	},
	["beamerray_dark"] = {
		usedefaultexplosions = false,
		groundflash = {
			circlealpha        = 0,
			circlegrowth       = 1,
			flashalpha         = 1.0,
			flashsize          = 26,
			ttl                = 24,
			color = {
				[1]  = 0,
				[2]  = 0,
				[3]  = 0.56,
			},
		},
		pikes = {
			air                = true,
			class              = [[explspike]],
			count              = 5,
			ground             = true,
			water              = true,
			underwater		   = true,
			properties = {
				alpha              = 1,
				alphadecay         = 0.06,
				color              = [[0.0,0.0,0.37]],
				dir                = [[-2 r4,-2 r4,-2 r4]],
				length             = 11,
				width              = 7,
			},
		},
		sparks_blue = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater		   = true,
			properties = {
				airdrag            = 0.97,
				colormap           = [[0.0 0.0 0.56 0.01   0.1 0.1 0.2 0.01   0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 80,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.1, 0]],
				numparticles       = 5,
				particlelife       = 10,
				particlelifespread = 3,
				particlesize       = 8,
				particlesizespread = 2.5,
				particlespeed      = 4,
				particlespeedspread = 2,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[plasma]],
			},
		},
	},
}
