return {
	["big_meteor_smash"] = {
		groundflash = {
			circlealpha        = 0.2,
			circlegrowth       = 4,
			flashalpha         = 0.9,
			flashsize          = 720,
			ttl                = 26,
			color = {
				[1]  = 1,
				[2]  = 0.60000002384186,
				[3]  = 0.10000000149012,
			},
		},
		sphere = {
			air                = true,
			class              = [[CSpherePartSpawner]],
			count              = 1,
			ground             = true,
			underwater         = 0,
			water              = true,
			properties = {
				alpha              = 0.30,
				color              = [[1,0.6,0]],
				expansionspeed     = 7*3.75,
				ttl                = 14,
			},
		},
		dirta = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			properties = {
				airdrag            = 0.7,
				alwaysvisible      = true,
				colormap           = [[0.1 0.1 0.1 1.0	0.5 0.5 0.5 1.0		0 0 0 0.0]],
				directional        = true,
				emitrot            = 90,
				emitrotspread      = 0,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 25,
				particlelife       = 25,
				particlelifespread = 10,
				particlesize       = 25,
				particlesizespread = 5,
				particlespeed      = 5,
				particlespeedspread = 10,
				pos                = [[r-1 r1, 1, r-1 r1]],
				sizegrowth         = 1.2,
				sizemod            = 1.0,
				texture            = [[dirt]],
				useairlos          = true,
			},
		},
		dirtw1 = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			water              = true,
			properties = {
				airdrag            = 0.9,
				alwaysvisible      = true,
				colormap           = [[0.9 0.9 0.9 1.0	0.5 0.5 0.9 0.0]],
				directional        = true,
				emitrot            = 90,
				emitrotspread      = 0,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.2, 0]],
				numparticles       = 30,
				particlelife       = 25,
				particlelifespread = 10,
				particlesize       = 25,
				particlesizespread = 5,
				particlespeed      = 1,
				particlespeedspread = 10,
				pos                = [[r-1 r1, 1, r-1 r1]],
				sizegrowth         = 1.2,
				sizemod            = 1.0,
				texture            = [[randdots]],
				useairlos          = true,
			},
		},
		dirtw2 = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			water              = true,
			properties = {
				airdrag            = 0.7,
				alwaysvisible      = true,
				colormap           = [[1.0 1.0 1.0 1.0	0.5 0.5 0.8 0.0]],
				directional        = true,
				emitrot            = 90,
				emitrotspread      = 0,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 10,
				particlelife       = 15,
				particlelifespread = 10,
				particlesize       = 25,
				particlesizespread = 5,
				particlespeed      = 1,
				particlespeedspread = 10,
				pos                = [[r-1 r1, 1, r-1 r1]],
				sizegrowth         = 1.2,
				sizemod            = 1.0,
				texture            = [[dirt]],
				useairlos          = true,
			},
		},
		debris2 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 20,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.98,
				colormap           = [[0.22 0.18 0.15 1   0.22 0.18 0.15 1	 0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 20,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.2, 0]],
				numparticles       = 5,
				particlelife       = 150,
				particlelifespread = 0,
				particlesize       = [[1 r10]],
				particlesizespread = 0,
				particlespeed      = 5,
				particlespeedspread = 8,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[debris2]],
			},
		},
		dirt3 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 10,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.8,
				colormap           = [[0 0 0 0.01  0.22 0.18 0.15 1	 0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 25,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.2, 0]],
				numparticles       = 1,
				particlelife       = 80,
				particlelifespread = 5,
				particlesize       = 1.5,
				particlesizespread = 3,
				particlespeed      = 5,
				particlespeedspread = 24,
				pos                = [[0, 2, 0]],
				sizegrowth         = 1,
				sizemod            = 1.0,
				texture            = [[kfoam]],
			},
		},
		explosionsfx = {
			air = true,
			class = [[heatcloud]],
			count = 1,
			ground = true,
			water = true,
			properties = {
				alwaysvisible = true,
				heat = 30,
				--emitvector = [[0, 1, 0]],
				heatfalloff = 0.2,
				maxheat = 45,
				pos = [[r-2 r2, 5, r-2 r2]],
				size = 20,
				sizegrowth = 10,
				speed = [[0, 1 0, 0]],
				texture = [[uglynovaexplo]],
			},
		},
	},
}
