return {
	["beamlaser_hit_emerald"] = {
		usedefaultexplosions = false,
		glow = {
			air                = true,
			class              = [[explspike]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				alpha              = 1,
				alphadecay         = 0.0625,
				alwaysvisible      = false,
				color              = [[0.043, 0.4, 0.274]],
				dir                = [[-4 r8, -4 r8, -4 r8]],
				length             = 1,
				lengthgrowth       = 1,
				width              = 8,
			},
		},
		groundflash = {
			circlealpha        = 1,
			circlegrowth       = 0.125,
			flashalpha         = 0.5,
			flashsize          = 8,
			ttl                = 64,
			color = {
				[1]  = 0.1255,
				[2]  = 0.25098,
				[3]  = 0,
			},
		},
		sphere = {
			air                = true,
			class              = [[CSpherePartSpawner]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater 		 = true,
			properties = {
				alpha              = 0.25,
				color              = [[0.043, 0.4, 0.274]],
				expansionspeed     = 12,
				ttl                = 5,
			},
		},
		sparks = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			unit               = 1,
			properties = {
				airdrag            = 0.97,
				alwaysvisible      = true,
				colormap           = [[0.033 0.28 0.204 0.01   0.01 0.01 0.005 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 80,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.4, 0]],
				numparticles       = 4,
				particlelife       = 15,
				particlelifespread = 0,
				particlesize       = 3,
				particlesizespread = 2,
				particlespeed      = 6,
				particlespeedspread = 4,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[plasma]],
			},
		},
		steam = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			water              = true,
			properties = {
				airdrag            = 0.75,
				alwaysvisible      = false,
				colormap           = [[0.5 0.5 0.5 0.5   0.05 0.05 0.05 0.05]],
				directional        = false,
				emitrot            = 0,
				emitrotspread      = 5,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 1, 0]],
				numparticles       = 1,
				particlelife       = 12,
				particlelifespread = 8,
				particlesize       = 6,
				particlesizespread = 4,
				particlespeed      = 0,
				particlespeedspread = 2,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[smokesmall]],
			},
		},
	},
}