return {
	["disarmaa_explosion_140"] = {
		electric2 = {
			air                = true,
			class              = [[heatcloud]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				alwaysvisible      = true,
				heat               = 10,
				heatfalloff        = 1.3,
				maxheat            = 15,
				pos                = [[r-2 r2, 5, r-2 r2]],
				size               = 3,
				sizegrowth         = 12.74,
				speed              = [[0, 0, 0]],
				texture            = [[flare]],
			},
		},
		electricarcs1 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			properties = {
				airdrag            = 0.8,
				alwaysvisible      = true,
				colormap           = [[1.0 1.0 1.0 0.04	0.2 0.5 0.9 0.01	0.1 0.5 0.7 0.01]],
				directional        = true,
				emitrot            = 45,
				emitrotspread      = 32,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.05, 0]],
				numparticles       = 16,
				particlelife       = 10,
				particlelifespread = 5,
				particlesize       = 20,
				particlesizespread = 0,
				particlespeed      = 7,
				particlespeedspread = 5,
				pos                = [[0, 2, 0]],
				sizegrowth         = 1,
				sizemod            = 1.0,
				texture            = [[lightening]],
				useairlos          = true,
			},
		},
		sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.97,
				colormap           = [[01 1 1 0.01   0.5 0.5 0.5 0.01   0.0 0.0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 60,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 40,
				particlelife       = 20,
				particlelifespread = 5,
				particlesize       = 5,
				particlesizespread = 0,
				particlespeed      = 5,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[spark]],
			},
		},
		whiteglow = {
			air                = true,
			class              = [[heatcloud]],
			count              = 2,
			ground             = true,
			water              = true,
			properties = {
				alwaysvisible      = true,
				heat               = 10,
				heatfalloff        = 1.1,
				maxheat            = 15,
				pos                = [[0, 5, 0]],
				size               = 10,
				sizegrowth         = 15.235,
				speed              = [[0, 1 0, 0]],
				texture            = [[laserend]],
			},
		},
	},
}
