return {
	["emg_hit_le"] = {
		usedefaultexplosions = false,
		groundflash = {
			circlealpha			= 1,
			circlegrowth		= 0,
			flashalpha			= 0.25,
			flashsize			= 24,
			ttl					= 3,
			color = {
				[1]	= 1,
				[2]	= 0.94999998807907,
				[3]	= 0.5,
			},
		},
		groundsmoke = {
			class		= [[CSimpleParticleSystem]],
			count		= 3,
			ground		= true,
			unit		= 1,
			properties = {
				airdrag				= 0.8,
				colormap			= [[1 1 0 1	1 0.25 0 0.8	0 0 0 0.6	0 0 0 0.4	0 0 0 0.2	0 0 0 0]],
				directional			= true,
				emitrot				= 0,
				emitrotspread		= 90,
				emitvector			= [[0, 1, 0]],
				gravity				= [[0, 0.2, 0]],
				numparticles		= 1,
				particlelife		= 5,
				particlelifespread	= 2,
				particlesize		= 2,
				particlesizespread	= 2,
				particlespeed		= 1,
				particlespeedspread	= 1,
				pos					= [[0, 0, 0]],
				sizegrowth			= 1,
				sizemod				= 1.0,
				texture				= [[smokesmall]],
			},
		},
		main = {
			air						= true,
			class					= [[heatcloud]],
			count					= 1,
			ground					= true,
			water					= true,
			properties = {
				heat				= 3,
				heatfalloff			= 1,
				maxheat				= 3,
				pos					= [[0, 1, 0]],
				size				= 1,
				sizegrowth			= 4,
				speed				= [[0, 1, 0]],
				texture				= [[explo]],
			},
		},
		sparks = {
			air						= true,
			class					= [[CSimpleParticleSystem]],
			count					= 1,
			ground					= true,
			water					= true,
			properties = {
				airdrag					= 0.97,
				colormap				= [[1 0.95 0.5 0.01	 1 0.95 0.5 0.01	 1 0.95 0.5 0.01	 0 0 0 0.01]],
				directional				= true,
				emitrot					= 0,
				emitrotspread			= 90,
				emitvector				= [[0, 1, 0]],
				gravity					= [[0, -0.2, 0]],
				numparticles			= 16,
				particlelife			= 5,
				particlelifespread		= 0,
				particlesize			= 1,
				particlesizespread		= 0.5,
				particlespeed			= 0.5,
				particlespeedspread		= 3,
				pos						= [[0, 1, 0]],
				sizegrowth				= 0,
				sizemod					= 1.0,
				texture					= [[plasma]],
			},
		},
		watermist = {
			class							= [[CSimpleParticleSystem]],
			count							= 3,
			water							= true,
			properties = {
				airdrag						= 0.8,
				colormap					= [[0.75 0.75 1 1	0 0 0 0]],
				directional					= true,
				emitrot						= 0,
				emitrotspread				= 90,
				emitvector					= [[0, 1, 0]],
				gravity						= [[0, 0.2, 0]],
				numparticles				= 1,
				particlelife				= 5,
				particlelifespread			= 2,
				particlesize				= 2,
				particlesizespread			= 2,
				particlespeed				= 1,
				particlespeedspread			= 1,
				pos							= [[0, 0, 0]],
				sizegrowth				 	= 1,
				sizemod						= 1.0,
				texture						= [[smokesmall]],
			},
		},
	},
}