-- heatray_ceg
-- heatray_hit

return {
	["heatray_hit"] = {
		usedefaultexplosions = false,
		sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
			   airdrag            = 0.97,
			   colormap           = [[1 0.216 0 0.01   0.9961 0.8471 0.6941 0.01]],
			   directional        = true,
			   emitrot            = 180,
			   emitrotspread      = 60,
			   emitvector         = [[dir]],
			   gravity            = [[0, 0, 0]],
			   numparticles       = [[d1.25]],
			   particlelife       = 4,
			   particlelifespread = 5,
			   particlesize       = [[d0.25]],
			   particlesizespread = 0,
			   particlespeed      = 5,
			   particlespeedspread = 0,
			   pos                = [[0, 0, 0]],
			   sizegrowth         = 0,
			   sizemod            = 1.0,
			   texture            = [[spark]],
			},
		},
		steam = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			air				   = true,
			water              = true,
			ground			   = true,
			properties = {
				airdrag            = 0.75,
				alwaysvisible      = false,
				colormap           = [[0.9961 0.8471 0.6941 0.01    1 0.216 0 0.01]],
				directional        = true,
				emitrot            = 180,
				emitrotspread      = 5,
				emitvector         = [[dir]],
				gravity            = [[0, 1, 0]],
				numparticles       = 1,
				particlelife       = 3,
				particlelifespread = 8,
				particlesize       = [[d0.4]],
				particlesizespread = 4,
				particlespeed      = 0,
				particlespeedspread = 2,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[smokesmall]],
			},
		},
	},
}