-- Derives from roachplosion

return {
	["mineboomexplosion"] = {
		air                = true,
		count              = 10,
		ground             = true,
		water              = true,
		debris1 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 20,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.98,
				alwaysvisible      = true,
				colormap           = [[0.22 0.18 0.15 1   0.22 0.18 0.15 1	 0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 90,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.2, 0]],
				numparticles       = 5,
				particlelife       = [[50 i-0.5]],
				particlelifespread = 0,
				particlesize       = [[3 r3]],
				particlesizespread = 0,
				particlespeed      = 1,
				particlespeedspread = 0.36,
				pos                = [[0, 0, 0]],
				sizegrowth         = [[-0.1 i0.015]],
				sizemod            = 1.0,
				texture            = [[debris2]],
			},
		},
		debris2 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 20,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.98,
				alwaysvisible      = true,
				colormap           = [[0.22 0.18 0.15 1   0.22 0.18 0.15 1	 0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 20,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.2, 0]],
				numparticles       = 5,
				particlelife       = 150,
				particlelifespread = 0,
				particlesize       = [[1 r3]],
				particlesizespread = 0,
				particlespeed      = 1.8,
				particlespeedspread = 2.9,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[debris2]],
			},
		},
		dirt1 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.8,
				alwaysvisible      = true,
				colormap           = [[1 0.6 0 0.1	1 0.4 0 0.1  0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 25,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 30,
				particlelife       = 18.5,
				particlelifespread = 5,
				particlesize       = 0.54,
				particlesizespread = 1.09,
				particlespeed      = 0,
				particlespeedspread = 6.9,
				pos                = [[0, 2, 0]],
				sizegrowth         = 3,
				sizemod            = 1.0,
				texture            = [[dirtplosion2]],
			},
		},
		dirt2 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 0,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.8,
				alwaysvisible      = true,
				colormap           = [[1 0.6 0 0.1	 0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 25,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 30,
				particlelife       = 8.5,
				particlelifespread = 5,
				particlesize       = 0.54,
				particlesizespread = 1.09,
				particlespeed      = 0,
				particlespeedspread = 6.9,
				pos                = [[0, 2, 0]],
				sizegrowth         = 3,
				sizemod            = 1.0,
				texture            = [[dirtplosion2]],
			},
		},
		dirt3 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 10,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.8,
				alwaysvisible      = true,
				colormap           = [[0 0 0 0.01  0.4 0.4 0.4 1	 0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 25,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.2, 0]],
				numparticles       = 1,
				particlelife       = 80,
				particlelifespread = 5,
				particlesize       = 0.54,
				particlesizespread = 1.09,
				particlespeed      = 1.8,
				particlespeedspread = 8.7,
				pos                = [[0, 2, 0]],
				sizegrowth         = 1,
				sizemod            = 1.0,
				texture            = [[kfoam]],
			},
		},
		fanny = {
			air                = true,
			class              = [[CExpGenSpawner]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				delay              = 30,
				explosiongenerator = [[custom:FANNY]],
				pos                = [[0, 0, 0]],
			},
		},
		glow = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 10,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 1,
				alwaysvisible      = true,
				colormap           = [[0 0 0 0.01   1 1 0.8 0.9              0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 180,
				emitvector         = [[-0, 1, 0]],
				gravity            = [[0, 0.00, 0]],
				numparticles       = 1,
				particlelife       = 5,
				particlelifespread = 0,
				particlesize       = 7.92,
				particlesizespread = 3.63,
				particlespeed      = 1,
				particlespeedspread = 0,
				pos                = [[0, 2, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[diamondstar]],
			},
		},
		groundflash = {
			circlealpha        = 0.5,
			circlegrowth       = 0,
			flashalpha         = 1,
			flashsize          = 18,
			ttl                = 250,
			color = {
				[1]  = 1,
				[2]  = 0.40000000596046,
				[3]  = 0.10000000149012,
			},
		},
		sparks = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 0,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.97,
				alwaysvisible      = true,
				colormap           = [[1 1 0 0.01   1 0.7 0.5 0.01   0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 80,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.4, 0]],
				numparticles       = 40,
				particlelife       = 30,
				particlelifespread = 0,
				particlesize       = 0.72,
				particlesizespread = 2.54,
				particlespeed      = 0.72,
				particlespeedspread = 5.8,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[plasma]],
			},
		},
	},
	["mineboom"] = {
		boom = {
			air                = true,
			class              = [[CExpGenSpawner]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				delay              = 0,
				explosiongenerator = [[custom:mineboomexplosion]],
				pos                = [[0, 0,  0]],
			},
		},
		foom = {
			air                = true,
			class              = [[CExpGenSpawner]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				delay              = 0,
				explosiongenerator = [[custom:KLARA]],
				pos                = [[0, 0,  0]],
			},
		},
		groundflash = {
			circlealpha        = 0.5,
			circlegrowth       = 0,
			flashalpha         = 1,
			flashsize          = 150,
			ttl                = 40,
			color = {
				[1]  = 1,
				[2]  = 0.69999998807907,
				[3]  = 0.20000000298023,
			},
		},
	},
}

