return {
  ["sniper_hit"] = {
    usedefaultexplosions = false,
    pillar = {
      air                = true,
      class              = [[heatcloud]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 15,
        heatfalloff        = 2.5,
        maxheat            = 15,
        pos                = [[0,0 i5, 0]],
        size               = 90,
        sizegrowth         = -11,
        speed              = [[0, 10, 0]],
        texture            = [[yellownovaexplo]],
      },
    },
    pop = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.5,
        maxheat            = 15,
        pos                = [[r-2 r2, 5, r-2 r2]],
        size               = 90,
        sizegrowth         = 0.9,
        speed              = [[0, 1 0, 0]],
        texture            = [[yellownovaexplo]],
      },
    },
    airflash = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = false,
        heat               = [[50]],
        heatfalloff        = 2,
        maxheat            = 50,
        pos                = 0,
        size               = [[10]],
        sizegrowth         = 2,
        speed              = [[0, 0, 0]],
        texture            = [[yellownovaexplo]],
      },
    },
    big_pike = {
      air                = true,
      class              = [[explspike]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.03,
        color              = [[1,1,0.15]],
        pos                = [[0, 5, 0]],
        dir                = [[dir]],
        length             = 26,
        lengthgrowth       = 1.8,
        width              = 8,
      },
    },
    sparks_big = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = false,
        colormap           = [[1 1 0.1 0.01   0.05 0.05 0.001 0.01]],
        directional        = true,
        emitrot            = 180,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = [[5]],
        particlelife       = 40,
        particlelifespread = 40,
        particlesize       = [[20]],
        particlesizespread = 0.5,
        particlespeed      = 3,
        particlespeedspread = 24,
        pos                = [[10 r20, 10 r20, 10 r20]],
        sizegrowth         = 0,
        sizemod            = 0.97,
        texture            = [[plasma]],
      },
    },
    sparks_scatter = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = false,
        colormap           = [[1 1 0.1 0.01   0.05 0.05 0.001 0.01]],
        directional        = true,
        emitrot            = 180,
        emitrotspread      = 90,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = [[30]],
        particlelife       = 40,
        particlelifespread = 40,
        particlesize       = [[20]],
        particlesizespread = 0.5,
        particlespeed      = 3,
        particlespeedspread = 24,
        pos                = [[10 r20, 10 r20, 10 r20]],
        sizegrowth         = 0,
        sizemod            = 0.8,
        texture            = [[plasma]],
      },
    },
    sparks_front = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = false,
        colormap           = [[1 1 0.1 0.01   0.05 0.05 0.001 0.01]],
        directional        = true,
        emitrot            = 180,
        emitrotspread      = 90,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = [[30]],
        particlelife       = 40,
        particlelifespread = 40,
        particlesize       = [[40]],
        particlesizespread = 0.5,
        particlespeed      = 3,
        particlespeedspread = 24,
        pos                = [[10 r20, 10 r20, 10 r20]],
        sizegrowth         = 0,
        sizemod            = 0.5,
        texture            = [[plasma]],
      },
    },
  },
  ["sniperrifle"] = {
		alwaysvisible           = false,
		usedefaultexplosions    = false,


		sparks = {
			air                   = true,
			class                 = [[CSimpleParticleSystem]],
			count                 = 1,
			ground                = true,
			water                 = true,
			properties = {
				airdrag             = 0.2,
				colormap            = [[1 1 0.2 0.01   1 1 0.4 0.01   0.0 0.0 0 0.01]],
				directional         = true,
				emitrot             = 0,
				emitrotspread       = 60,
				emitvector          = [[0, 1, 0]],
				gravity             = [[0, 0, 0]],
				numparticles        = 1,
				particlelife        = 8,
				particlelifespread  = 4,
				particlesize        = 5,
				particlesizespread  = 0,
				particlespeed       = 1,
				particlespeedspread = 0,
				pos                 = [[0, 0, 0]],
				sizegrowth          = 0,
				sizemod             = 1.0,
				texture             = [[spark]],
			},
		},

		spikes = {
			air                   = true,
			class                 = [[explspike]],
			count                 = 4,
			ground                = true,
			water                 = true,
			properties = {
				alpha               = 0.75,
				alphadecay          = 0.25,
				color               = [[0.8, 0.7, 0.2]],
				dir                 = [[-6 r12,-6 r12,-6 r12]],
				length              = 12,
				width               = 5,
			},
		},
	},
  ["flashgrav"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1,
      flashalpha         = 0.9,
      flashsize          = 20,
      ttl                = 3,
      color = {
        [1]  = 1,
        [2]  = 0,
        [3]  = 0,
      },
    },
    pikage = {
      air                = true,
      class              = [[explspike]],
      count              = 15,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.8,
        alphadecay         = 0.2,
        color              = [[1,0,0]],
        dir                = [[-5 r10,-5 r10,-5 r10]],
        length             = 6,
        width              = 2,
      },
    },
    sparks_big = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = false,
        colormap           = [[1 0.1 0.1 0.01   0.1 0.001 0.001 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = [[1]],
        particlelife       = 40,
        particlelifespread = 40,
        particlesize       = [[10]],
        particlesizespread = 0.5,
        particlespeed      = 3,
        particlespeedspread = 24,
        pos                = [[10 r20, 10 r20, 10 r20]],
        sizegrowth         = 0,
        sizemod            = 0.97,
        texture            = [[plasma]],
      },
    },
  },
}

