return {
	["beamweapon_hit_purple_steam"] = {
		steam = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			water              = true,
			properties = {
				airdrag            = 0.75,
				alwaysvisible      = false,
				colormap           = [[0.5 0.05 0.5 0.5   0.05 0.05 0.05 0.05]],
				directional        = false,
				emitrot            = 0,
				emitrotspread      = 5,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 1, 0]],
				numparticles       = 1,
				particlelife       = 12,
				particlelifespread = 8,
				particlesize       = 6,
				particlesizespread = 4,
				particlespeed      = 0,
				particlespeedspread = 2,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[smokesmall]],
			},
		},
	},
	["beamweapon_muzzle_purple_small"] = {
		usedefaultexplosions = false,
		glow = {
			air                = true,
			class              = [[explspike]],
			count              = [[8]],
			ground             = true,
			water              = true,
			properties = {
				alpha              = 1,
				alphadecay         = [[d1p-2 0.1]],
				alwaysvisible      = false,
				color              = [[1,0.2,1]],
				dir                = [[-4 r8, -4 r8, -4 r8]],
				length             = [[kd]],
				lengthgrowth       = [[d0.065y0 kx0]],
				width              = [[1dp0.25]],
			},
		},
		white = {
			air                = true,
			class              = [[explspike]],
			count              = 2,
			ground             = true,
			water              = true,
			properties = {
				alpha              = 1,
				alphadecay         = [[d1p-2 0.1]],
				alwaysvisible      = false,
				color              = [[1,1,1]],
				dir                = [[-2 r4, -2 r4, -2 r4]],
				length             = [[kd]],
				lengthgrowth       = 4,
				width              = [[1dp0.25]],
			},
		},
	},

	["beamweapon_hit_purple_tiny"] = {
		usedefaultexplosions = false,
		pikes = {
			air                = true,
			class              = [[CExpGenSpawner]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				delay              = 0,
				dir                = [[dir]],
				explosiongenerator = [[custom:beamweapon_muzzle_purple_small]],
				pos                = [[0, 0, 0]],
				damage			   = [[1kd1]],
			},
		},
		sparks = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			unit               = 1,
			properties = {
				airdrag            = 0.97,
				alwaysvisible      = false,
				colormap           = [[1 0.2 1 0.01   0.01 0.01 0.005 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 80,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.4, 0]],
				numparticles       = 8,
				particlelife       = [[d0.05 1]],
				particlelifespread = 2,
				particlesize       = [[d0.05 1]],
				particlesizespread = 2,
				particlespeed      = 6,
				particlespeedspread = 4,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[plasma]],
			},
		},
		steam = {
			class              = [[CExpGenSpawner]],
			count              = 2,
			nounit             = 1,
			properties = {
				delay              = [[i1]],
				dir                = [[dir]],
				explosiongenerator = [[custom:beamweapon_hit_purple_steam]],
				pos                = [[0, 0, 0]],
			},
		},
	},
}
  