return {
	["scanner_ping"] = {
		usedefaultexplosions = false,
		groundflash = {
			alwaysvisible      = false,
			circlealpha        = 0.1,
			circlegrowth       = 3.6,
			flashalpha         = 0.1,
			flashsize          = 600,
			ttl                = 90,
			color = {
				[1]  = 0,
				[2]  = 0.5,
				[3]  = 1,
			},
		},
		ring1 = {
			air                = true,
			useAirLos 		   = true,
			class              = [[CBitmapMuzzleFlame]],
			ground             = true,
			water              = true,
			count              = 1,
			properties = {
				colormap           = [[0.1 0.15 0.4 .1   .05 0.075 0.2 .1   0 0 0 0]],
				dir                = [[-0.01 r0.01, 1, -0.01 r0.01]],
				frontoffset        = 0,
				fronttexture       = [[shockwave]],
				sidetexture        = [[null]],
				length             = 1,
				pos                = [[0, 0, 0]],
				size               = 1,
				sizegrowth         = 500,
				ttl                = 60,
			},
		},
	},
	["sensortagdeath_400"] = {
		usedefaultexplosions = false,
		groundflash = {
			alwaysvisible      = false,
			circlealpha        = 0.1,
			circlegrowth       = 3.6,
			flashalpha         = 0.1,
			flashsize          = 200,
			ttl                = 10,
			color = {
				[1]  = 0,
				[2]  = 0.5,
				[3]  = 1,
			},
		},
		ring1 = {
			air                = true,
			useAirLos 		   = true,
			class              = [[CBitmapMuzzleFlame]],
			ground             = true,
			water              = true,
			count              = 1,
			properties = {
				colormap           = [[0.5 0.5 0.5 .1   0.1 0.1 0.1 .1   0 0 0 0]],
				dir                = [[-0.01 r0.01, 1, -0.01 r0.01]],
				frontoffset        = 0,
				fronttexture       = [[shockwave]],
				sidetexture        = [[null]],
				length             = 1,
				pos                = [[0, 0, 0]],
				size               = 1,
				sizegrowth         = 100,
				ttl                = 10,
			},
		},
	},
	["scanner_ping_1600"] = {
		usedefaultexplosions = false,
		groundflash = {
			alwaysvisible      = false,
			circlealpha        = 0.1,
			circlegrowth       = 3.6,
			flashalpha         = 0.1,
			flashsize          = 600,
			ttl                = 90,
			color = {
				[1]  = 0,
				[2]  = 0.5,
				[3]  = 1,
			},
		},
		ring1 = {
			air                = true,
			useAirLos 		   = true,
			class              = [[CBitmapMuzzleFlame]],
			ground             = true,
			water              = true,
			count              = 1,
			properties = {
				colormap           = [[0.1 0.15 0.4 .1   .05 0.075 0.2 .1   0 0 0 0]],
				dir                = [[-0.01 r0.01, 1, -0.01 r0.01]],
				frontoffset        = 0,
				fronttexture       = [[shockwave]],
				sidetexture        = [[null]],
				length             = 1,
				pos                = [[0, 0, 0]],
				size               = 1,
				sizegrowth         = 800,
				ttl                = 60,
			},
		},
	},
	["scanner_ping_400"] = {
		usedefaultexplosions = false,
		groundflash = {
			alwaysvisible      = false,
			circlealpha        = 0.1,
			circlegrowth       = 3.6,
			flashalpha         = 0.1,
			flashsize          = 400,
			ttl                = 90,
			color = {
				[1]  = 0,
				[2]  = 0.5,
				[3]  = 1,
			},
		},
		ring1 = {
			air                = true,
			useAirLos 		   = true,
			class              = [[CBitmapMuzzleFlame]],
			ground             = true,
			water              = true,
			unit               = true,
			count              = 1,
			properties = {
				colormap           = [[0.1 0.15 0.4 .1   .05 0.075 0.2 .1   0 0 0 0]],
				dir                = [[-0.01 r0.01, 1, -0.01 r0.01]],
				frontoffset        = 0,
				fronttexture       = [[shockwave]],
				sidetexture        = [[null]],
				length             = 1,
				pos                = [[0, 0, 0]],
				size               = 1,
				sizegrowth         = 200,
				ttl                = 60,
			},
		},
	},
	["scanner_ping_600"] = {
		usedefaultexplosions = false,
		groundflash = {
			alwaysvisible      = false,
			circlealpha        = 0.1,
			circlegrowth       = 3.6,
			flashalpha         = 0.1,
			flashsize          = 600,
			ttl                = 90,
			color = {
				[1]  = 0,
				[2]  = 0.5,
				[3]  = 1,
			},
		},
		ring1 = {
			air                = true,
			useAirLos 		   = true,
			class              = [[CBitmapMuzzleFlame]],
			ground             = true,
			water              = true,
			unit               = true,
			count              = 1,
			properties = {
				colormap           = [[0.1 0.15 0.4 .2   .05 0.075 0.2 .2   0 0 0 0]],
				dir                = [[-0.01 r0.01, 1, -0.01 r0.01]],
				frontoffset        = 0,
				fronttexture       = [[shockwave]],
				sidetexture        = [[null]],
				length             = 1,
				pos                = [[0, 0, 0]],
				size               = 1,
				sizegrowth         = 600,
				ttl                = 30,
			},
		},
	},
	["scanner_slow"] = {
		usedefaultexplosions = false,
		groundflash = {
			alwaysvisible      = false,
			circlealpha        = 0.1,
			circlegrowth       = 3.6,
			flashalpha         = 0.1,
			flashsize          = 600,
			ttl                = 90,
			color = {
				[1]  = 0,
				[2]  = 0.5,
				[3]  = 1,
			},
		},
		ring1 = {
			air                = true,
			useAirLos 		   = true,
			class              = [[CBitmapMuzzleFlame]],
			ground             = true,
			water              = true,
			count              = 1,
			properties = {
				colormap           = [[0.58 0.0 0.82 0.1   .29 0.0 0.51 .05   0 0 0 0]],
				dir                = [[-0.01 r0.01, 1, -0.01 r0.01]],
				frontoffset        = 0,
				fronttexture       = [[shockwave]],
				sidetexture        = [[null]],
				length             = 1,
				pos                = [[0, 0, 0]],
				size               = 1,
				sizegrowth         = 900,
				ttl                = 50,
			},
		},
	},
}
