return {
	["scythe_hit"] = {
		usedefaultexplosions = false,
		pikes = {
			air                = true,
			class              = [[CExpGenSpawner]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
			delay              = 0,
			dir                = [[dir]],
			explosiongenerator = [[custom:BEAMWEAPON_MUZZLE_ORANGE]],
			pos                = [[0, 0, 0]],
			},
		},
		sparks = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			unit               = 1,
			properties = {
				airdrag            = 0.97,
				alwaysvisible      = false,
				colormap           = [[1 1 0.5 0.01   0.01 0.01 0.005 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 80,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, -0.4, 0]],
				numparticles       = 32,
				particlelife       = 15,
				particlelifespread = 0,
				particlesize       = 2,
				particlesizespread = 1.5,
				particlespeed      = 4,
				particlespeedspread = 3,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 1.0,
				texture            = [[plasma]],
			},
		},
		steam = {
			class              = [[CExpGenSpawner]],
			count              = 2,
			nounit             = 1,
			properties = {
				delay              = [[i2]],
				dir                = [[dir]],
				explosiongenerator = [[custom:BEAMWEAPON_HIT_ORANGE_STEAM]],
				pos                = [[0, 0, 0]],
			},
		},
	},
}
