return
{

	["serpent_splosh"] = {
		splosh = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = false,
			water              = true,
			underwater		   = true,
			properties = {
				airdrag            = 0.6,
				colormap           = [[0.7 0.7 0.9 0.8    0.7 0.7 0.9 0.8     0.5 0.5 0.6 0.6     0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 180,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = [[3r 1]],
				particlelife       = 15,
				particlelifespread = 0,
				particlesize       = 6,
				particlesizespread = 1,
				particlespeed      = 0.001,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				sizegrowth         = 2,
				sizemod            = 1.0,
				texture            = [[kfoam]],
			},
		},
	},
	["serpent_trail"]= {
        bubbles = {
            air                = false,
            class              = [[CSimpleParticleSystem]],
            count              = 1,
            ground             = false,
            water              = true,
            underwater         = true,
            properties = {
                airdrag            = [[0.9]],
                --alwaysvisible      = true,
                colormap           = [[0.9 0.9 0.9 0.9
                               0.8 0.8 0.8 0.2
                               0.8 0.8 0.8 0.1
                               0 0 0 0]],
                directional        = true,
                emitrot            = 45,
                emitrotspread      = 32,
                emitvector         = [[0, 1, 0]],
                gravity            = [[0, 0 d0.1 x0.1, 0]],
                numparticles       = [[r8 1]],
                particlelife       = [[10 d0.25]],
                particlelifespread = 10,
                particlesize       = 1,
                particlesizespread = 3,
                particlespeed      = 1,
                particlespeedspread = 3,
                pos                = [[-5 r10, -5 r10, -5 r10]],
                sizegrowth         = [[0.3 r0.2]],
                sizemod            = [[0.98 r0.01]],
                texture            = [[randdots]],
                useairlos          = false,
			},
        },
	},
	["serpent_launch"] = {
		trail = {
			air                = false,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = false,
			underwater         = true,
			water              = true,
			properties = {
				colormap           = [[0.7 0.7 0.9 0.8    0.7 0.7 0.9 0.9]],
				dir                = [[dir]],
				frontoffset        = 1,
				fronttexture       = [[kfoam]],
				length             = 1,
				sidetexture        = [[wake]],
				size               = 2,
				sizegrowth         = 0.4,
				ttl                = 10,
			},
		},
	},
	
	["serpent_hit"] = {
		mainhit = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 4,
			ground             = true,
			water              = true,
			underwater         = false,
			properties = {
				colormap           = [[0.45 0.45 0.5 0.5  0.045 0.045 0.05 0.05]],
				dir                = [[-0.1 r0.2, 1, -0.1 r0.2]],
				frontoffset        = 0,
				fronttexture       = [[splashbase]],
				length             = [[48 r32]],
				sidetexture        = [[splashside]],
				size               = [[12 r8]],
				sizegrowth         = 1.4,
				ttl                = 24,
			},
		},
		splosh = {
			air                = false,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = false,
			water              = true,
			underwater		   = true,
			properties = {
				airdrag            = 0.6,
				colormap           = [[0.7 0.7 0.9 0.8    0.7 0.7 0.9 0.9   0 0 0 0.01]],
				directional        = false,
				emitrot            = 0,
				emitrotspread      = 180,
				emitvector         = [[0, 1, 0]],
				gravity            = [[-0.1 r0.2, 0.5, -0.1 r0.1]],
				numparticles       = 1,
				particlelife       = 30,
				particlelifespread = 0,
				particlesize       = 0.5,
				particlesizespread = 1,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0.01,
				sizemod            = 1.0,
				texture            = [[bubble]],
			},
		},
		splosh2 = {
			air                = false,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater		   = true,
			properties = {
				airdrag            = 0.6,
				colormap           = [[0.8 0.8 0.9 0.9     0 0 0 0.01]],
				directional        = true,
				emitrot            = 0,
				emitrotspread      = 180,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 1,
				particlelife       = 20,
				particlelifespread = 20,
				particlesize       = 8,
				particlesizespread = 8,
				particlespeed      = 0.001,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				sizegrowth         = -0.26,
				sizemod            = 1.0,
				texture            = [[kfoam]],
			},
		},
	},
}