return {
	["snipertrail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		head                 = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.99,
				alwaysvisible       = false,
				colormap            = [[1 1 1 0.05   0.85 0.7215 0.086 0.01]],
				directional         = true,
				emitrotspread       = 0,
				emitvector          = [[dir]],
				gravity             = [[0 0 0]];
				numparticles        = 3,
				particlelife        = 3,
				particlelifespread  = 0,
				particlesize        = 10,
				particlesizespread  = 1,
				particlespeed       = 0.9,
				particlespeedspread = 0.02,
				pos                 = [[0 0 0]],
				sizegrowth          = 0,
				sizemod             = 0.7,
				texture             = [[plasma3]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.85 0.7215 0.086 0.01 0.4392 0.37647 0.0067 0.01 0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[plasma3]],
				size         = 6,
				sizegrowth   = -0.3,
				ttl          = 6,
			},
		},
	},
}
