return {
	["spidersilk"] = {
		useairlos          = false,
		usedefaultexplosions = false,
		groundflash = {
			air                = true,
			alwaysvisible      = false,
			circlealpha        = 0.1,
			circlegrowth       = 0.1,
			count              = 1,
			flashalpha         = 1,
			flashsize          = 30,
			ground             = true,
			ttl                = 15,
			water              = true,
			color = {
				[1]  = 0.8863,
				[2]  = 0.898,
				[3]  = 0.8706,
			},
		},
		ring1 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			ground             = true,
			properties = {
				airdrag            = .9,
				colormap           = [[1 0.8667 0.7922 .1 0.8941 0.8941 0.8941 .1   0 0 0 0]],
				directional        = false,
				emitrot            = 45,
				emitrotspread      = 30,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 1,
				particlelife       = 12,
				particlelifespread = 0,
				particlesize       = 6,
				particlesizespread = 6,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0, 1.0, 0]],
				sizegrowth         = 3,
				sizemod            = 1,
				texture            = [[bloodblastwhite]],
			},
		},
	},

}