return {
	["sunburst_trail"] = {
		alwaysvisible      = false,
		usedefaultexplosions = false,
		largeflash = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = 1,
			water              = true,
			properties = {
				colormap           = [[0.1568 0.251 0.7216 0.01     0.1568 0.4588 0.7216 0.01     0.1568 0.6824 0.7216 0.01      0.0706 0.8784 0.7451 0.01    0.004 0.458824 0.5686276 0.01     0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = 0,
				fronttexture       = [[muzzlefront]],
				length             = -3,
				sidetexture        = [[muzzleside]],
				size               = -6,
				sizegrowth         = 1,
				ttl                = 6,
			},
		},
		pikes1 = {
			air                = true,
			class              = [[explspike]],
			count              = 3,
			ground             = true,
			water              = true,
			underwater		   = true,
			properties = {
				alpha              = 1,
				alphadecay         = 0.5,
				color              = [[0.1568,0.251,0.7216]],
				dir                = [[-2 r4,-2 r4,-2 r4]],
				length             = 11,
				width              = 6,
			},
		},
		pikes2 = {
			air                = true,
			class              = [[explspike]],
			count              = 3,
			ground             = true,
			water              = true,
			underwater		   = true,
			properties = {
				alpha              = 1,
				alphadecay         = 0.5,
				color              = [[0.1568 0.4588 0.7216]],
				dir                = [[-2 r4,-2 r4,-2 r4]],
				length             = 11,
				width              = 6,
			},
		},
		pikes3 = {
			air                = true,
			class              = [[explspike]],
			count              = 3,
			ground             = true,
			water              = true,
			underwater		   = true,
			properties = {
				alpha              = 1,
				alphadecay         = 0.5,
				color              = [[0.1568 0.6824 0.7216]],
				dir                = [[-2 r4,-2 r4,-2 r4]],
				length             = 11,
				width              = 6,
			},
		},
	},
}
