return {
	["toxic_goo_80"] = {
		groundflash = {
			circlealpha        = .4,
			circlegrowth       = 0,
			flashalpha         = .3,
			flashsize          = 40,
			ttl                = 95,
			color = {
				[1]  = 0.20000000298023,
				[2]  = 0.70000002384186,
				[3]  = 0,
			},
		},
	},
	["toxic_goo_splashes"] = {
		splashes = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 0.9,
				colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
				directional        = true,
				emitrot            = 1,
				emitrotspread      = -2,
				emitvector         = [[dir]],
				gravity            = [[0, 0, 0]],
				numparticles       = 1,
				particlelife       = 10,
				particlelifespread = 5,
				particlesize       = 4,
				particlesizespread = 4,
				particlespeed      = 0.05,
				particlespeedspread = 0,
				pos                = [[0, 0, 0]],
				sizegrowth         = 2,
				sizemod            = 1,
				texture            = [[blooddropwhite]],
			},
		},
		pop = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			ground             = true,
			properties = {
				airdrag            = .9,
				colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
				directional        = false,
				emitrot            = 30,
				emitrotspread      = -60,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 1,
				particlelife       = 32,
				particlelifespread = 0,
				particlesize       = 4,
				particlesizespread = 2,
				particlespeed      = 0,
				particlespeedspread = 0,
				pos                = [[0, 1.0, 0]],
				sizegrowth         = 6,
				sizemod            = 1,
				texture            = [[bloodblastwhite]],
			},
		},
	},
	["dodo_goo_splashes"] = {
		splashes = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			ground             = true,
			properties = {
				airdrag            = .96,
				colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
				directional        = true,
				emitrot            = 180,
				emitrotspread      = 80,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 12,
				particlelife       = 30,
				particlelifespread = 20,
				particlesize       = 24,
				particlesizespread = 8,
				particlespeed      = 2,
				particlespeedspread = 3,
				pos                = [[0, 1.0, 0]],
				sizegrowth         = -.1,
				sizemod            = 1,
				texture            = [[blooddropwhite]],
			},
		},
	},
}
