return {
	["waketrail"] = {
		alwaysvisible      = false,
		usedefaultexplosions = false,
		largeflash = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = 1,
			water              = true,
			properties = {
				colormap           = [[0.239 0.643 0.784 0.01 0.1294 0.4549 0.8313 0.01 0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = 0,
				fronttexture       = [[muzzlefront]],
				length             = -45,
				sidetexture        = [[muzzleside]],
				size               = -8,
				sizegrowth         = 0.75,
				ttl                = 8,
			},
		},
	},
	["waketrail_small"] = {
		alwaysvisible      = false,
		usedefaultexplosions = false,
		largeflash = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = 1,
			water              = true,
			properties = {
				colormap           = [[0.239 0.643 0.784 0.01 0.1294 0.4549 0.8313 0.01 0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = 0,
				fronttexture       = [[muzzlefront]],
				length             = -5,
				sidetexture        = [[muzzleside]],
				size               = -8,
				sizegrowth         = 0.75,
				ttl                = 3,
			},
		},
	},
	["waketrail_smallmixed"] = {
		alwaysvisible      = false,
		usedefaultexplosions = false,
		largeflash = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = 1,
			water              = true,
			properties = {
				colormap           = [[0.239 0.643 0.784 0.01 0.1294 0.4549 0.8313 0.01 0 0 0 0.01]],
				dir                = [[dir]],
				frontoffset        = 0,
				fronttexture       = [[muzzlefront]],
				length             = -5,
				sidetexture        = [[muzzleside]],
				size               = -8,
				sizegrowth         = 0.75,
				ttl                = 3,
			},
		},
		exhale = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 1,
				colormap           = [[0.239 0.643 0.784 0.01 0.1294 0.4549 0.8313 0.01 0 0 0 0.01]],
				directional        = false,
				emitrot            = 80,
				emitrotspread      = 5,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 1,
				particlelife       = 4,
				particlelifespread = 3,
				particlesize       = 20,
				particlesizespread = 4,
				particlespeed      = 2,
				particlespeedspread = 2,
				pos                = [[0, 1, 0]],
				sizegrowth         = 0.4,
				sizemod            = 1.2,
				texture            = [[smoke]],
			},
		},
		exhale2 = {
			air                = true,
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			water              = true,
			properties = {
				airdrag            = 1,
				colormap           = [[0.239 0.239 0.784 0.01 0.1294 0.1294 0.8313 0.01 0 0 0 0.01]],
				directional        = false,
				emitrot            = 80,
				emitrotspread      = 5,
				emitvector         = [[0, 1, 0]],
				gravity            = [[0, 0, 0]],
				numparticles       = 1,
				particlelife       = 4,
				particlelifespread = 3,
				particlesize       = 20,
				particlesizespread = 4,
				particlespeed      = 1,
				particlespeedspread = 0,
				pos                = [[0, 1, 0]],
				sizegrowth         = 0.4,
				sizemod            = 1.2,
				texture            = [[smoke]],
			},
		},
	},
	["gluon_tiny"] = {
		alwaysvisible      = false,
		usedefaultexplosions = false,
		largeflash = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = 1,
			water              = true,
			properties = {
				colormap           = [[0.329 0.78 0.8196 0.01 0.251 0.608 0.639 0.01  0.08 0.235 0.251 0.01]],
				dir                = [[dir]],
				frontoffset        = 0,
				fronttexture       = [[muzzlefront]],
				length             = -2,
				sidetexture        = [[muzzleside]],
				size               = -8,
				sizegrowth         = 0.75,
				ttl                = 3,
			},
		},
	},
	["amphraid_trail"] = {
		alwaysvisible      = false,
		usedefaultexplosions = false,
		largeflash = {
			air                = true,
			class              = [[CBitmapMuzzleFlame]],
			count              = 1,
			ground             = true,
			underwater         = 1,
			water              = true,
			properties = {
				colormap           = [[0.329 0.78 0.8196 0.01 0.251 0.608 0.639 0.01  0.08 0.235 0.251 0.01]],
				dir                = [[dir]],
				frontoffset        = 0,
				fronttexture       = [[muzzlefront]],
				length             = -2,
				sidetexture        = [[muzzleside]],
				size               = 2,
				sizegrowth         = 0.55,
				ttl                = 2,
			},
		},
	},
}
