local name = "commweapon_artillery_heavy"
local weaponDef = {
	name                    = "Heavy Plasma Artillery",
	accuracy                = 600,
	areaOfEffect            = 96,
	craterBoost             = 1,
	craterMult              = 2,
	customParams            = {
		is_unit_weapon = 1,
		muzzleEffectFire = "custom:HEAVY_CANNON_MUZZLE",
		miscEffectFire = "custom:RIOT_SHELL_H",
		onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER",
		light_color = "1.4 0.8 0.3",
		reaim_time = 1,
		reveal_unit = 8,
		use_okp = 1,
		okp_speedmult = 0.3,
		okp_radarmult = 1,
		okp_timeout = 80,
		okp_damage = 850,
	},
	damage                  = {
		default = 850,
	},
	edgeEffectiveness       = 0.5,
	explosionGenerator      = "custom:PLASMA_HIT_96",
	impulseBoost            = 0,
	impulseFactor           = 0.4,
	interceptedByShieldType = 9,
	myGravity               = 0.05,
	range                   = 800,
	reloadtime              = 8,
	soundHit                = "weapon/cannon/arty_hit",
	soundStart              = "weapon/cannon/pillager_fire",
	turret                  = true,
	weaponType              = "Cannon",
	weaponVelocity          = 320,
}

return name, weaponDef
