local name = "commweapon_microriftgenerator"
local weaponDef = {
	name                    = "Microrift Generator",
	craterBoost             = 0,
	craterMult              = 0,
	avoidGround             = false,
	avoidFriendly           = false,
	avoidFeature            = false,
	collideFriendly         = false,
	commandfire             = true,
	customParams            = {
		is_unit_weapon = 1,
		manualfire = 1,
		teleportation = 1,
		teleportsound = "sounds/misc/teleport_alt.wav",
		teleportid = 2,
		light_camera_height = 500,
		light_color = "0 .8 1",
		light_radius = 120,
		stats_hide_damage = 1,
		stats_hide_damage = 1,
		stats_custom_tooltip_1 = " - Instantly Teleports this unit to a nearby location",
		stats_custom_tooltip_entry_1 = "",
		teleport_nomomentum = 1,
	},
	damage                  = {
		default = 0,
	},
	explosionGenerator      = "custom:BEAMWEAPON_HIT_ORANGE",
	impulseBoost            = 0,
	impulseFactor           = 0,
	impactOnly              = true,
	interceptedByShieldType = 1,
	myGravity               = 0.05,
	range                   = 800,
	reloadtime              = 12,
	soundStart              = "misc/teleport",
	turret                  = true,
	weaponType              = "Cannon",
	weaponVelocity          = 2250,
	waterweapon				= true,
}

return name, weaponDef
