local name = "commweapon_disruptorprojector"
local weaponDef = {
	name                    = "Disruptor Projector",
	areaOfEffect            = 60,
	beamDecay               = 0.9,
	beamTime                = 0.1,
	beamttl                 = 3,
	coreThickness           = 1.1,
	craterBoost             = 0,
	craterMult              = 0,

	customParams            = {
		is_unit_weapon = 1,
		slot = "5",
		timeslow_damagefactor = "5",
		timeslow_smartretarget = "0.5",
		stats_hide_damage = 1, -- continuous laser
        stats_hide_reload = 1,
		light_camera_height = 1800,
		light_color = "0.6 0.22 0.8",
		light_radius = 200,
		reaim_time = 1,
		antibaitbypass = "ärsytät minua",
	},

	damage                  = {
		default = 9.75,
	},
	edgeEffectiveness		= 0.05,
	explosionGenerator      = "custom:riotballplus2_purple_small60",
	fireStarter             = 30,
	impactOnly              = false,
	impulseBoost            = 0,
	impulseFactor           = 0,
	interceptedByShieldType = 1,
	largeBeamLaser          = true,
	laserFlareSize          = 3,
	minIntensity            = 1,
	noSelfDamage            = true,
	range                   = 450,
	reloadtime              = .1,
	rgbColor                = "0.4 0 0.5",
	soundStart              = "weapon/laser/disruptor_projector.wav",
	soundStartVolume        = 3,
	soundTrigger            = true,
	sweepfire               = false,
	texture1                = "disruptor",
	texture2                = "flare",
	texture3                = "flare",
	texture4                = "smallflare",
	thickness               = 8,
	tolerance               = 18000,
	turret                  = true,
	weaponType              = "BeamLaser",
	weaponVelocity          = 500,
}

return name, weaponDef