return { 
	amphimpulse = {
		unitname               = "amphimpulse",
		name                   = "Ripple",
		description            = "Amphibious Riot Bot",
		acceleration           = 0.6,
		activateWhenBuilt      = true,
		brakeRate              = 2.4,
		buildCostMetal         = 240,
		buildPic               = "amphimpulse.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canManualFire          = true,
		category               = "LAND SINK",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "45 45 45",
		selectionVolumeType    = "ellipsoid",
		corpse                 = "DEAD",
		customParams           = {
			amph_regen        = 15,
			amph_submerged_at = 40,
			sink_on_emp       = 1,
			floattoggle       = "1",
			selection_scale   = 0.8,
			aim_lookahead     = 120,
			bait_level_default = 1,
			manualfire_desc = "Gravity Lasso: Pull a unit towards you."
		},
		explodeAs              = "BIG_UNITEX",
		footprintX             = 3,
		footprintZ             = 3,
		iconType               = "amphraider",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		leaveTracks            = true,
		health                 = 1200,
		maxSlope               = 36,
		speed                  = 2.6,
		movementClass          = "AKBOT3",
		noChaseCategory        = "TERRAFORM FIXEDWING GUNSHIP",
		objectName             = "amphraider2.s3o",
		script                 = "amphimpulse.lua",
		selfDestructAs         = "BIG_UNITEX",
		sfxtypes               = {
			explosiongenerators = {
				"custom:sonicfire",
				"custom:bubbles_small",
			},
		},
		sightDistance          = 700,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ComTrack",
		trackWidth             = 22,
		turnRate               = 1440,
		upright                = true,
		weapons                = {
			{
				def                = "SONIC",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "GRAVITYLASSO",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def = "GravityLassoLaser",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs             = {
			SONIC         = {
				name                    = "Sonic Cannon",
				areaOfEffect            = 256,
				avoidFeature            = true,
				avoidFriendly           = true,
				burnblow                = true,
				craterBoost             = 0,
				craterMult              = 0,
				burst					= 2,
				burstrate				= 0.5,
				customParams            = {
					force_ignore_ground = "1",
					lups_explodelife = 1.0,
					lups_explodespeed = 0.8,
					light_radius = 120,
					blastwave_size = 8,
					blastwave_impulse = 4.2,
					blastwave_speed = 4,
					blastwave_life = 30,
					blastwave_lossfactor = 0.82,
					blastwave_damage = 120,
					damage_vs_shield = 200,
				},
				damage                  = {
					default = 55.01,
				},
				cegTag                  = "sonicarcher",
				cylinderTargeting       = 1,
				explosionGenerator      = "custom:sonic_128",
				edgeEffectiveness       = 0.5,
				fireStarter             = 150,
				impulseBoost            = 100,
				impulseFactor           = 0.5,
				interceptedByShieldType = 1,
				myGravity               = 0.01,
				noSelfDamage            = true,
				range                   = 340,
				reloadtime              = 2.2,
				size                    = 50,
				sizeDecay               = 0.2,
				soundStart              = "weapon/cannon/archer_fire",
				soundHit                = "weapon/cannon/archer_hit",
				soundStartVolume        = 6,
				soundHitVolume          = 10,
				stages                  = 1,
				texture1                = "sonic_glow2",
				texture2                = "null",
				texture3                = "null",
				rgbColor                = {0.2, 0.6, 0.8},
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 780,
				waterweapon             = true,
				duration                = 0.15,
			},
			GravityLasso = {
				name                    = "Gravity Lasso",
				areaOfEffect            = 8,
				avoidFriendly           = false,
				avoidFeature			= false,
				beamtime				= 1/30,
				commandFire				= true,
				canAttackGround         = false, --TODO: implement pulling.
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					impulse = "1900",
					stats_hide_damage = 1, -- continuous laser
					light_color = "0.33 0.33 1.28",
					light_radius = 140,
					can_target_allies  = 1,
					gravitylasso = 1,
				},
				damage                  = {
					default = 25.1,
				},
				explosionGenerator      = "custom:NONE",
				impactOnly              = true,
				intensity               = 0.7,
				interceptedByShieldType = 0,
				largeBeamLaser          = true,
				laserFlareSize          = 2,
				noSelfDamage            = true,
				proximityPriority       = -15,
				range                   = 600,
				reloadtime              = 20,
				rgbColor                = "0 0 1",
				rgbColor2               = "1 0.5 1",
				size                    = 2,
				soundStart              = "weapon/gravity_fire",
				thickness               = 4,
				tolerance               = 5000,
				turret                  = true,
				weaponType              = "LaserCannon",
				weaponVelocity          = 2250,
				texture1                = "largelaser",
				texture2                = "flare",
				texture3                = "flare",
				texture4                = "smallflare",
			},
			GravityLassoLaser = {
				name                    = "Gravity Lasso",
				areaOfEffect            = 8,
				avoidFriendly           = false,
				avoidFeature			= false,
				beamtime				= 1/30,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting 		= 100,
				customParams            = {
					impulse = "-400",
					impulserange = 180,
					impulseminheightdiff = 200,
					impulsemult = 3.2,
					stats_hide_damage = 1, -- continuous laser
					stats_hide_reload = 1,
					light_color = "0.33 0.33 1.28",
					light_radius = 140,
					can_target_allies  = 1,
					hideweapon = 1,
					combatrange = 100,
				},
				damage                  = {
					default = 0.001,
				},
				explosionGenerator      = "custom:NONE",
				impactOnly              = true,
				intensity               = 0.7,
				interceptedByShieldType = 0,
				largeBeamLaser          = true,
				laserFlareSize          = 2,
				noSelfDamage            = true,
				proximityPriority       = -15,
				range                   = 650,
				reloadtime              = 1/30,
				rgbColor                = "0 0 1",
				rgbColor2               = "1 0.5 1",
				sweepfire				= true,
				size                    = 2,
				soundStart              = "weapon/beam/newtonpull_fixed",
				thickness               = 4,
				tolerance               = 5000,
				turret                  = true,
				weaponType              = "BeamLaser",
				texture1                = "largelaser",
				texture2                = "flare",
				texture3                = "flare",
				texture4                = "smallflare",
			},
		},
		featureDefs            = {
			DEAD      = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "amphraider2_dead.s3o",
			},
			HEAP      = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},	
	}
}
