return { 
	amphskirm = {
		unitname               = "amphskirm",
		name                   = "Milta",
		description            = "Amphibious Light Skirmisher (Anti-Sub)",
		acceleration           = 0.54,
		activateWhenBuilt      = true,
		brakeRate              = 2.25,
		buildCostMetal         = 150,
		buildPic               = "amphraid.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND SINK",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "28 28 28",
		selectionVolumeType    = "ellipsoid",
		corpse                 = "DEAD",
		customParams           = {
			amph_regen        = 15,
			amph_submerged_at = 40,
			aim_lookahead     = 80,
		},
		explodeAs              = "BIG_UNITEX",
		footprintX             = 2,
		footprintZ             = 2,
		iconType               = "amphskirm",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		leaveTracks            = true,
		health                 = 480,
		maxSlope               = 36,
		speed                  = 1.8,
		movementClass          = "AKBOT2",
		noChaseCategory        = "TERRAFORM FIXEDWING GUNSHIP",
		objectName             = "amphraider3.s3o",
		script                 = "amphraid.lua",
		selfDestructAs         = "BIG_UNITEX",
		sfxtypes               = {
			explosiongenerators = {},
		},
		sightDistance          = 660,
		sonarDistance          = 660,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ComTrack",
		trackWidth             = 22,
		turnRate               = 2100,
		upright                = true,
		weapons                = {
			{
				def                = "TORPMISSILE",
				onlyTargetCategory = "SWIM HOVER LAND SINK TURRET FLOAT SHIP",
			},
			{
				def                = "TORPEDO",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "SWIM FIXEDWING HOVER LAND SINK TURRET FLOAT SHIP GUNSHIP SUB",
			},
		},
		weaponDefs             = {
			secondary = {
				name                    = "Hurricane Sonic Bomblet",
				areaOfEffect            = 80,
				avoidFriendly           = false,
				bouncerebound           = 0.5,
				bounceslip              = 0.4,
				canAttackGround         = false, -- also workaround for range hax
				craterBoost             = 0,
				craterMult              = 0,
				cegTag                  = "torpedo_trail",
				customParams			= {
					blastwave_size = 30,
					blastwave_impulse = 0,
					blastwave_speed = 10,
					blastwave_life = 5,
					blastwave_lossfactor = 0.88,
					blastwave_damage = 65,
					damage_vs_shield = 200,
				},
				damage                  = {
					default = 5.01,
				},
				edgeEffectiveness       = 0.6,
				explosionGenerator      = "custom:sonic_80",
				flightTime              = 3.5,
				groundbounce            = 1,
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				myGravity               = 0.1,
				model                   = "diskball.s3o",
				numBounce               = 3,
				range                   = 300,
				reloadtime              = 2,
				soundHit                = "weapon/cannon/ultrasonic_fire",
				soundHitVolume          = 8.6,
				soundStart              = "weapon/clusters/light_cluster_grenade_hit",
				--soundStart            = "weapon/torpedo",
				startVelocity           = 90,
				tracks                  = true,
				turnRate                = 70000,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 380,
			},
			TORPMISSILE = {
				name                    = "Sawhead Torpedo",
				areaOfEffect            = 32,
				--accuracy				= 220,
				--cegTag                  = "missiletrailyellow",
				craterBoost             = 1,
				craterMult              = 2,
				customparams = {
					numprojectiles1 = 3,
					projectile1 = "amphskirm_secondary",
					spawndist = 120,
					timeoutspawn = 0,
					velspread1 = "5.1, 1, 5.1",
					reaim_time = 60, -- Fast update not required (maybe dangerous)
					light_color = "1 0.6 0.2",
					light_radius = 180,
				},
				damage                  = {
					default = 130.01,
				},
				explosionGenerator      = "custom:INGEBORG",
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				leadlimit               = -1,
				model                   = "wep_m_ajax.s3o",
				noSelfDamage            = true,
				--predictboost			= 1,
				projectiles             = 1,
				range                   = 600,
				reloadtime              = 4,
				mygravity				= 0.09,
				smokeTrail              = true,
				soundHit                = "weapon/clusters/light_cluster_grenade_hit",
				soundHitVolume          = 4,
				soundStart              = "weapon/missile/air_launched_missile",
				startVelocity           = 140,
				texture2                = "lightsmoketrail",
				tolerance               = 1000,
				--highTrajectory          = 1,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 270,
			},
			TORPEDO = {
				name                    = "Sawhead Torpedo",
				areaOfEffect            = 32,
				avoidFriendly           = false,
				bouncerebound           = 0.5,
				bounceslip              = 0.8,
				craterBoost             = 1,
				craterMult              = 2,
				cegTag                  = "torpedo_trail",
				customParams            = {
					numprojectiles1 = 3,
					projectile1 = "amphskirm_secondary",
					spawndist = 90,
					velspread1 = "2.55, 1, 2.55",
					proxy = 1, 
					reaim_time = 60, -- Fast update not required (maybe dangerous)
					cruisealt = -0.05,
					cruisedist = 150,
					cruise_ascendradius = 80,
					cruisetracking = 1,
					cruise_nolock = 1,
					stays_underwater = 1,
					cas_nocruisecheck = "periksiantamattomuus ja omista virheistään oppiminen ovat kaiken a ja o", -- katseletko? :D
					--keepinwater = 1,
				},
				damage                  = {
					default = 130.01,
				},
				edgeEffectiveness       = 0.99,
				explosionGenerator      = "custom:TORPEDO_HIT",
				flightTime              = 30.0,
				groundbounce            = 1,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				leadlimit               = 0,
				model                   = "wep_m_ajax.s3o",
				numbounce               = 4,
				noSelfDamage            = true,
				projectiles             = 1,
				range                   = 570,
				reloadtime              = 4,
				soundHit                = "weapon/torpedo/torpedohit_light",
				soundStart              = "weapon/torpedo/torp_launch_amph_light",
				soundStartVolume        = 0.7,
				soundHitVolume          = 0.7,
				startVelocity           = 40,
				tolerance               = 1000,
				tracks                  = true,
				turnRate                = 35000,
				turret                  = true,
				waterWeapon             = true,
				weaponAcceleration      = 75,
				weaponType              = "TorpedoLauncher",
				weaponVelocity          = 280,
			},
		},
		featureDefs            = {
			DEAD      = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "amphraider3_dead.s3o",
			},
			HEAP      = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},
	} 
}
