return { 
	amphimpulse = {
		unitname               = "amphimpulse",
		name                   = "Ripple",
		description            = "Amphibious Riot Bot",
		acceleration           = 0.6,
		activateWhenBuilt      = true,
		brakeRate              = 2.4,
		buildCostMetal         = 240,
		buildPic               = "amphimpulse.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND SINK",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "30 30 30",
		selectionVolumeType    = "ellipsoid",
		corpse                 = "DEAD",
		customParams           = {
			amph_regen        = 15,
			amph_submerged_at = 40,
			sink_on_emp       = 1,
			floattoggle       = "1",
			selection_scale   = 0.8,
			aim_lookahead     = 120,
			bait_level_default = 1,
		},
		explodeAs              = "BIG_UNITEX",
		footprintX             = 3,
		footprintZ             = 3,
		iconType               = "amphraider",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		leaveTracks            = true,
		health                 = 1200,
		maxSlope               = 36,
		speed                  = 2.5,
		movementClass          = "AKBOT3",
		noChaseCategory        = "TERRAFORM FIXEDWING GUNSHIP",
		objectName             = "amphraider2.s3o",
		script                 = "amphimpulse.lua",
		selfDestructAs         = "BIG_UNITEX",
		sfxtypes               = {
			explosiongenerators = {
				"custom:sonicfire",
				"custom:bubbles_small",
			},
		},
		sightDistance          = 600,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ComTrack",
		trackWidth             = 22,
		turnRate               = 1440,
		upright                = true,
		weapons                = {
			{
				def                = "SONIC",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs             = {
			SONIC         = {
				name                    = "Sonic Cannon",
				areaOfEffect            = 256,
				avoidFeature            = true,
				avoidFriendly           = true,
				burnblow                = true,
				craterBoost             = 0,
				craterMult              = 0,
				burst					= 2,
				burstrate				= 0.5,
				customParams            = {
					force_ignore_ground = "1",
					lups_explodelife = 1.0,
					lups_explodespeed = 0.8,
					light_radius = 120,
					blastwave_size = 8,
					blastwave_impulse = 4.2,
					blastwave_speed = 4,
					blastwave_life = 30,
					blastwave_lossfactor = 0.82,
					blastwave_damage = 120,
					damage_vs_shield = 200,
				},
				damage                  = {
					default = 55.01,
				},
				cegTag                  = "sonicarcher",
				cylinderTargeting       = 1,
				explosionGenerator      = "custom:sonic_128",
				edgeEffectiveness       = 0.5,
				fireStarter             = 150,
				impulseBoost            = 100,
				impulseFactor           = 0.5,
				interceptedByShieldType = 1,
				myGravity               = 0.01,
				noSelfDamage            = true,
				range                   = 340,
				reloadtime              = 2.2,
				size                    = 50,
				sizeDecay               = 0.2,
				soundStart              = "weapon/cannon/archer_fire",
				soundHit                = "weapon/cannon/archer_hit",
				soundStartVolume        = 6,
				soundHitVolume          = 10,
				stages                  = 1,
				texture1                = "sonic_glow2",
				texture2                = "null",
				texture3                = "null",
				rgbColor                = {0.2, 0.6, 0.8},
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 780,
				waterweapon             = true,
				duration                = 0.15,
			},
		},
		featureDefs            = {
			DEAD      = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "amphraider2_dead.s3o",
			},
			HEAP      = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},	
	}
}
