return { 
	assaultcruiser = {
		unitname               = [[assaultcruiser]],
		name                   = [[Vanquisher]],
		description            = [[Heavy Cruiser (Assault)]],
		acceleration           = 0.384,
		activateWhenBuilt      = true,
		brakeRate              = 0.42,
		buildCostMetal         = 2500,
		builder                = false,
		buildPic               = [[assaultcruiser.png]],
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = [[SHIP]],
		collisionVolumeOffsets = [[0 4 -2]],
		collisionVolumeScales  = [[72 42 128]],
		collisionVolumeType    = [[Box]],
		corpse                 = [[DEAD]],
		customParams           = {},
		explodeAs              = [[BIG_UNIT]],
		floater                = true,
		footprintX             = 5,
		footprintZ             = 5,
		iconType               = [[vanquisher]],
		idleAutoHeal           = 5,
		idleTime               = 1800,
		maxDamage              = 11000,
		maxVelocity            = 1.5,
		minWaterDepth          = 15,
		movementClass          = [[BOAT5]],
		noAutoFire             = false,
		noChaseCategory        = [[TERRAFORM FIXEDWING SATELLITE SUB SINK TURRET]],
		objectName             = [[cremcrus.s3o]],
		script                 = [[assaultcruiser.lua]],
		selfDestructAs         = [[BIG_UNIT]],

		sfxtypes               = {
			explosiongenerators = {
				[[custom:brawlermuzzle]],
				[[custom:pulvmuzzle]],
			},
		},
		sightDistance          = 800,
		sonarDistance          = 800,
		turninplace            = 0,
		turnRate               = 260,
		workerTime             = 0,
		weapons                = {
			{
				def                = [[FAKELASER]],
				mainDir            = [[0 0 1]],
				maxAngleDif        = 120,
			},
			{
				def                = [[GAUSS]],
				mainDir            = [[-1 0 1]],
				maxAngleDif        = 240,
				badTargetCategory  = [[FIXEDWING]],
				onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
			},
			{
				def                = [[GAUSS]],
				mainDir            = [[1 0 1]],
				maxAngleDif        = 240,
				badTargetCategory  = [[FIXEDWING]],
				onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
			},
			{
				def                = [[GAUSS]],
				mainDir            = [[-1 0 -1]],
				maxAngleDif        = 240,
				badTargetCategory  = [[FIXEDWING]],
				onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
			},
			{
				def                = [[GAUSS]],
				mainDir            = [[1 0 -1]],
				maxAngleDif        = 240,
				badTargetCategory  = [[FIXEDWING]],
				onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
			},
			{
				def                = [[MISSILE]],
				mainDir            = [[-1 0 0]],
				maxAngleDif        = 240,
				badTargetCategory  = [[FIXEDWING]],
				onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER SUB]],
			},
			{
				def                = [[MISSILE]],
				mainDir            = [[1 0 0]],
				maxAngleDif        = 240,
				badTargetCategory  = [[FIXEDWING]],
				onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER SUB]],
			},
		},
		weaponDefs             = {
			FAKELASER     = {
				name                    = [[Fake Laser]],
				areaOfEffect            = 12,
				beamTime                = 0.1,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,
				damage                  = {
					default = 0,
				},
				duration                = 0.11,
				fireStarter             = 70,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				laserFlareSize          = 5.53,
				range                   = 400,
				reloadtime              = 0.1,
				rgbColor                = [[0 1 0]],
				texture1                = [[largelaser]],
				texture2                = [[flare]],
				texture3                = [[flare]],
				texture4                = [[smallflare]],
				thickness               = 5,
				turret                  = true,
				weaponType              = [[BeamLaser]],
			},
			GAUSS         = {
				name                    = [[Heavy Sonic Cannon]],
				areaOfEffect            = 190,
				avoidFeature            = true,
				avoidFriendly           = true,
				burnblow                = true,
				burst					= 3,
				burstRate				= 1/3,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					muzzleEffectFire = [[custom:HEAVY_CANNON_MUZZLE]],
					miscEffectFire   = [[custom:RIOT_SHELL_L]],
					lups_explodelife = 1.5,
					lups_explodespeed = 0.8,
					light_radius = 240,
				},

				damage                  = {
					default = 120.1,
				},
				
				cegTag                  = [[sonictrail]],
				cylinderTargeting       = 5.0,
				explosionGenerator      = [[custom:sonic_80]],
				edgeEffectiveness       = 0.5,
				fireStarter             = 150,
				impulseBoost            = 300,
				impulseFactor           = 0.5,
				interceptedByShieldType = 1,
				myGravity               = 0.01,
				noSelfDamage            = true,
				range                   = 550,
				reloadtime              = 1.7,
				size                    = 64,
				sizeDecay               = 0.2,
				soundStart              = [[weapon/cannon/heavy_sonic]],
				soundHit                = [[weapon/sonicgun_hit]],
				soundStartVolume        = 6,
				soundHitVolume          = 10,
				stages                  = 1,
				texture1                = [[sonic_glow2]],
				texture2                = [[null]],
				texture3                = [[null]],
				rgbColor                = {0.2, 0.6, 0.8},
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 320,
				waterweapon             = true,
				duration                = 0.15,
			},
			MISSILE      = {
				name                    = [[Cruise Missiles]],
				areaOfEffect            = 48,
				burst                   = 4,
				burstRate               = 0.233,
				cegTag                  = [[missiletrailyellow]],
				craterBoost             = 1,
				craterMult              = 2,
				customParams			= {
					combatrange = 400,
				},
				damage                  = {
					default = 200,
				},

				edgeEffectiveness       = 0.5,
				fireStarter             = 100,
				fixedLauncher           = true,
				flightTime              = 8,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = [[wep_m_hailstorm.s3o]],
				noSelfDamage            = true,
				range                   = 620,
				reloadtime              = 4.2,
				smokeTrail              = true,
				soundHit                = [[weapon/missile/missile_fire12]],
				soundStart              = [[weapon/missile/aurora_missile_fire]],
				startVelocity           = 300,
				tolerance               = 4000,
				tracks                  = true,
				trajectoryHeight        = 0.5,
				turnrate                = 30000,
				turret                  = true,
				waterWeapon             = true,
				weaponAcceleration      = 300,
				weaponType              = [[MissileLauncher]],
				weaponVelocity          = 600,
			},
		},
		featureDefs            = {
			DEAD = {
				blocking         = false,
				featureDead      = [[HEAP]],
				footprintX       = 5,
				footprintZ       = 5,
				object           = [[cremcrus_dead.s3o]],
			},
			HEAP = {
				blocking         = false,
				footprintX       = 4,
				footprintZ       = 4,
				object           = [[debris4x4a.s3o]],
			},
		},
	} 
}
