return { 
	athena = {
		unitname            = "athena",
		name                = "Athena",
		description         = "Airborne SpecOps Engineer",
		acceleration        = 0.1,
		airStrafe           = 0,
		brakeRate           = 0.2,
		buildCostMetal      = 750,
		buildDistance       = 400,
		builder             = true,
		buildoptions        = {
			"staticmex",
			"turretaalaser",
			"turretlaser",
			"turretmissile",
			"staticcon",
			"staticradar",
			"staticjammer",
			"turretdecloak",
			"cloakcon",
			"jumpbomb",
			"cloakraid",
			"cloakheavyraid",
			"cloaksnipe",
			"spiderantiheavy",
			"shieldbomb",
			"cloakbomb",
			"cloakaa",
			"cloakjammer",
			"vehcapture",
			"amphtele",
			"striderantiheavy",
			"staticmissilesilo",
			"energypylon",
			"staticenergyrtg",
			"energywind",
			"energysolar",
			"staticrearm",
			"turretaaclose",
			"turretemp",
			"turretriot",
			"turrettorp",
			"turretimpulse",
			"staticantinuke",
			"energygeo",
			"staticshield",
			"turretgauss",
			"wolverine_mine_buildable",
		},
		buildPic            = "athena.png",
		buildRange3D        = false,
		canFly              = true,
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		canResurrect        = true,
		canSubmerge         = false,
		category            = "GUNSHIP UNARMED",
		cloakCost           = 4,
		cloakCostMoving     = 15,
		collide             = true,
		corpse              = "DEAD",
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "30 20 60",
		collisionVolumeType    = "ellipsoid",
		cruiseAlt           = 110,
		customParams        = {
			airstrafecontrol = "1",
			modelradius    = "15",
			isfakefactory = 1,
			notreallyafactory = 1,
			cloakregen	= 20,
			recloaktime = 240,
			outline_x = 90,
			outline_y = 90,
			outline_yoff = 12,
			area_cloak = 1,
			area_cloak_init = 0,
			area_cloak_upkeep = 4,
			area_cloak_radius = 450,
			area_cloak_decloak_distance = 75,
			area_cloak_self_decloak_distance = 100,
			area_cloak_grow_rate = 450,
			area_cloak_shrink_rate = 1400,
		},
		energyUse           = 0,
		explodeAs           = "GUNSHIPEX",
		floater             = true,
		footprintX          = 2,
		footprintZ          = 2,
		hoverAttack         = true,
		iconType            = "t3builder",
		initCloaked         = false,
		health              = 2300,
		maxSlope            = 36,
		speed               = 7,
		minCloakDistance    = 100,
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET",
		objectName          = "selene.s3o",
		radarDistance       = 1800,
		radarDistanceJam    = 600,
		script              = "athena.lua",
		selfDestructAs      = "GUNSHIPEX",
		showNanoSpray       = false,
		sightDistance       = 800,
		resurrectSpeed      = 15,
		turnRate            = 148,
		workerTime          = 30,
		featureDefs         = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				collisionVolumeOffsets = "0 0 0",
				collisionVolumeScales  = "30 20 60",
				collisionVolumeType    = "ellipsoid",
				object           = "selene_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},
	} 
}
