return { 
	bomberdisarm = {
		unitname            = "bomberdisarm",
		name                = "Boltstorm",
		description         = "Disarming bomber",
		brakerate           = 0.4,
		buildCostMetal      = 600,
		buildPic            = "bomberdisarm.png",
		canFly              = true,
		canMove             = true,
		canSubmerge         = false,
		category            = "FIXEDWING",
		collide             = false,
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "48 20 60",
		collisionVolumeType    = "ellipsoid",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "70 25 70",
		selectionVolumeType    = "cylY",
		corpse              = "DEAD",
		cruiseAlt           = 180,
		customParams        = {
			modelradius    = "10",
			requireammo    = "1",
			refuelturnradius = "170",
			reammoseconds    = "15",
			fighter_pullup_dist = 3500, -- dont bother.
		},
		explodeAs           = "GUNSHIPEX",
		floater             = true,
		footprintX          = 3,
		footprintZ          = 3,
		iconType            = "bomberriot",
		maxAcc              = 0.5,
		maxDamage           = 1120,
		maxFuel             = 1000000,
		maxRudder           = 0.0052,
		maxVelocity         = 9,
		noChaseCategory     = "TERRAFORM FIXEDWING LAND SHIP SWIM GUNSHIP SUB HOVER",
		objectName          = "stiletto.s3o",
		script              = "bomberdisarm.lua",
		selfDestructAs      = "GUNSHIPEX",
		sightDistance       = 780,
		turnRadius          = 320,
		weapons             = {
			--{
				--def                = "BOGUS_BOMB",
				--badTargetCategory  = "SWIM LAND SHIP HOVER",
				--onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
			--},
			{
				def                = "BOMB", -- model                   = "wep_b_fabby.s3o",
				--mainDir            = "0 -1 0",
				--maxAngleDif        = 0,
				badTargetCategory  = "SWIM LAND SHIP HOVER",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
			},
			{
				def                = "LIGHTNING",
				--mainDir            = "0 0 0",
				--maxAngleDif        = 0,
				badTargetCategory  = "SWIM LAND SHIP HOVER",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
			},
			{
				def                = "LIGHTNING2",
				--mainDir            = "0 0 0",
				--maxAngleDif        = 0,
				badTargetCategory  = "SWIM LAND SHIP HOVER",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
			},
		},
		weaponDefs          = {
			LIGHTNING = {
				name                    = "Opettaja on ihminen, jolta voit aina pyytää apua.", -- When the game breaks, you will see Finnish.
				areaOfEffect            = 10,
				avoidFeature            = false,
				avoidFriendly           = false,
				beamTime                = 3/30,
				cameraShake             = 10,
				canattackground         = false,
				collideFriendly         = false,
				coreThickness           = 0.6,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					disarmDamageMult = 11,
					disarmTimer      = 16, -- seconds
					disarmDamageOnly = 0,
					light_radius = 50,
					light_color = "2 2 2",
					hideweapon = 1,
					chainlightning_num = 2,
					chainlightning_searchdist = 180,
					chainlightning_ff = 1,
					chainlightning_maxtargets = 3,
					chainlightning_index = 3,
					chainlightning_sub = 1,
				},
				damage                  = {
					default        = 20.1,
				},
				edgeEffectiveness       = 0.4,
				fireStarter             = 90,
				impulseBoost            = 0,
				impulseFactor           = 0,
				impactOnly              = true,
				intensity               = 12,
				interceptedByShieldType = 1,
				largeBeamLaser          = true,
				laserFlareSize          = 5,
				minIntensity            = 1,
				range                   = 730,
				reloadtime              = 1,
				rgbColor                = "1 1 1",
				texture1                = "lightning",
				texture2                = "flare",
				texture3                = "flare",
				texture4                = "smallflare",
				soundHit                = "weapon/cannon/emp_arty_hit",
				soundHitVolume          = 20,
				thickness               = 10,
				tileLength              = 10,
				tolerance               = 32767,
				turret                  = true,
				weaponType              = "LightningCannon",
				weaponVelocity          = 2250,
			},
			LIGHTNING2 = {
				name                    = "Etana etana, miksi se on täällä? Niin nätti, niin plösö, sinustä tulee lettucen pussi.", -- Yours truly's first translation. :)
				areaOfEffect            = 160,
				avoidFeature            = false,
				avoidFriendly           = false,
				beamTime                = 1/30,
				cameraShake             = 10,
				canattackground         = false,
				collideFriendly         = false,
				coreThickness           = 0.6,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					disarmDamageMult = 11,
					disarmTimer      = 16, -- seconds
					disarmDamageOnly = 0,
					light_radius = 50,
					light_color = "1.4 1.4 1.4",
					hideweapon = 1,
				},
				damage                  = {
					default        = 10.1,
				},
				edgeEffectiveness       = 0.4,
				fireStarter             = 90,
				impulseBoost            = 0,
				impulseFactor           = 0,
				impactOnly              = true,
				intensity               = 12,
				interceptedByShieldType = 1,
				largeBeamLaser          = true,
				laserFlareSize          = 5,
				minIntensity            = 1,
				range                   = 730,
				reloadtime              = 1,
				rgbColor                = "1 1 1",
				texture1                = "lightning",
				texture2                = "flare",
				texture3                = "flare",
				texture4                = "smallflare",
				soundHit                = "weapon/cannon/emp_arty_hit",
				soundHitVolume          = 20,
				thickness               = 5,
				tileLength              = 10,
				tolerance               = 32767,
				turret                  = true,
				weaponType              = "LightningCannon",
				weaponVelocity          = 2250,
			},
			BOMB = {
				name                    = "SP-1 'Sparkie' Bomb",
				areaOfEffect            = 96,
				burst                   = 15,
				burstRate               = 2/30,
				craterBoost             = 0,
				craterMult              = 0,
				burnblow                = false,
				customParams            = {
					disarmDamageMult = 11,
					disarmDamageOnly = 0,
					stats_custom_tooltip_1 = " - Forks to up to 12 targets up to 90 elmos away",
					stats_custom_tooltip_2 = " - Forking Efficiency: 50%",
					stats_custom_tooltip_3 = " - Forks bounce to 2 additional targets each",
					numprojectiles1 = 1,
					projectile1 = "bomberdisarm_bombfinal",
					clustervec1 = "derpderpderpderpderpderpderpderpderpderp", -- accepted values: randomx, randomy, randomz, randomxy, randomxz, randomyz, random. OPTIONAL. default: random.
					keepmomentum1 = 1,
					timeoutspawn = 1,
					noairburst = "I belive I can fly...", -- if true, this projectile will skip all airburst checks
					spawndist = 69420, -- at what distance should we spawn the projectile(s)? REQUIRED.
					timeddeploy = 30,
				},
				damage                  = {
					default = 40.1,
				},

				edgeEffectiveness       = 0.6,
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				leadlimit               = 100,
				myGravity               = 0.4,
				model                   = "diskball.s3o",
				numBounce               = 3,
				range                   = 440,
				reloadtime              = 1.3,
				soundHit                = "weapon/cannon/emp_hit",
				soundHitVolume          = 30,
				soundStart              = "weapon/cannon/light_launcher",
				sprayAngle				= 5420,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 380,
			},
			BOMBFINAL = {
				name                    = "SP-1 'Sparkie' Bomb",
				areaOfEffect            = 96,
				bouncerebound           = 0.5,
				bounceslip              = 0.4,
				burst                   = 15,
				burstRate               = 2/30,
				craterBoost             = 0,
				craterMult              = 0,
				burnblow                = false,
				cegTag                  = "lightningplosion_stormbolt",
				customParams            = {
					disarmDamageMult = 11,
					disarmDamageOnly = 0,
					chainlightning_num = 1,
					chainlightning_searchdist = 180,
					chainlightning_ff = 1,
					chainlightning_maxtargets = 6,
					chainlightning_index = 2,
					hideweapon = 1,
				},
				damage                  = {
					default = 40.1,
				},

				edgeEffectiveness       = 0.6,
				explosionGenerator      = "custom:WHITE_LIGHTNING_BOMB",
				flightTime              = 3.5,
				groundbounce            = 1,
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				leadlimit               = 100,
				myGravity               = 0.4,
				model                   = "diskball.s3o",
				numBounce               = 3,
				range                   = 440,
				reloadtime              = 1.3,
				soundHit                = "weapon/cannon/emp_hit",
				sprayAngle				= 5420,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 380,
			},
			--[[BOGUS_BOMB       = {
				name                    = "Fake Bomb",
				avoidFeature            = false,
				avoidFriendly           = false,
				burst                   = 2,
				burstrate               = 1,
				collideFriendly         = false,
				customParams            = {
					bogus = 1,
				},
				damage                  = {
					default = 0,
				},
				explosionGenerator      = "custom:NONE",
				interceptedByShieldType = 1,
				intensity               = 0,
				myGravity               = 0.8,
				noSelfDamage            = true,
				range                   = 500,
				reloadtime              = 1,
				sprayangle              = 64000,
				weaponType              = "AircraftBomb",
			},]]
		},
		featureDefs         = {
			DEAD = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "Stiletto_dead.s3o",
			},
			HEAP = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = "debris2x2c.s3o",
			},
		},
	} 
}
