return {
	chickenspire = {
		name                          = "Chicken Spire",
		description                   = "Static Artillery",
		activateWhenBuilt             = true,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 12,
		buildingGroundDecalSizeY      = 12,
		buildingGroundDecalType       = "chickenspire_aoplane.dds",
		buildPic                      = "chickenspire.png",
		buildTime                     = 10500,
		category                      = "SINK",
		collisionVolumeOffsets        = "0 96 0",
		collisionVolumeScales         = "112 352 112",
		collisionVolumeType           = "CylY",

		customParams                  = {
			chicken = "uwu",
			chicken_menace = "^w^",
			outline_x = 310,
			outline_y = 400,
			outline_yoff = 150,
			model_rescale_script = 2,
			reveal_losunit = "los_menace",
			reveal_onprogress = 0.1,
		},

		energyMake                    = 0,
		explodeAs                     = "NOWEAPON",
		floater                       = true,
		footprintX                    = 8,
		footprintZ                    = 8,
		highTrajectory                = 1,
		iconType                      = "chickenminiq",
		losEmitHeight                 = 100,
		idleAutoHeal                  = 20,
		idleTime                      = 300,
		levelGround                   = false,
		health                        = 58200,
		maxSlope                      = 36,
		speed                         = 0,
		maxWaterDepth                 = 20,
		noAutoFire                    = false,
		noChaseCategory               = "FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER",
		objectName                    = "spire.s3o",
		onoffable                     = true,
		reclaimable                   = false,
		selfDestructAs                = "NOWEAPON",
		script                        = "chickenspire.lua",

		sfxtypes                      = {

			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},

		},
		sightDistance                 = 4096,
		sightDistance                 = 4096,
		upright                       = false,
		useBuildingGroundDecal        = true,
		yardMap                       = "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",

		weapons                       = {
			{
				def                = "SLAMSPORE",
				badTargetCategory  = "MOBILE",
				onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER",
			},
		},

		weaponDefs                    = {
			SLAMSPORE = {
				name                    = "Greater Helioplasm Launcher",
				areaOfEffect            = 200,
				avoidGround             = false,
				avoidFeature            = false,
				avoidFriendly           = false,
				collideFriendly         = false,
				craterBoost             = 1,
				craterMult              = 2,
							
				customParams            = {
					light_radius = 0,
					cruisealt = 1600,
					cruisedist = 2400,
					cruise_ascendradius = 400,
					reveal_unit = 24,
					cruisetracking = 0,
					cruise_nolock = 1,
					cruiserandomradius = 400,
					cruise_ignoreterrain = "1",
					armorpiercing = 0.4,
					gatherradius = "234",
					smoothradius = "180",
					detachmentradius = "180",
					smoothmult   = "0.5",
					smoothexponent = "0.75",
					movestructures = "0.25",
					light_color = "1.2 1.6 0.55",
					light_radius = 550,
				},

				damage                  = {
					default = 275,
				},

				dance                   = 40,
				explosionGenerator      = "custom:goo_v2_green_large",
				fireStarter             = 0,
				flightTime              = 100,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickenegggreen_big.s3o",
				projectiles             = 8,
				range                   = 1000000,
				reloadtime              = 6,
				smokeTrail              = true,
				startVelocity           = 0,
				texture1                = "none",
				texture2                = "sporetrail2",
				tolerance               = 10000,
				tracks                  = true,
				turnRate                = 10000,
				turret                  = true,
				waterweapon             = true,
				weaponAcceleration      = 40,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 10000,
				wobble                  = 16000,
			},
		},
	}
}
