return {
	chicken_shield = {
		name                = "Blooper",
		description         = "Shield/Anti-Air",
		acceleration        = 1.08,
		activateWhenBuilt   = true,
		brakeRate           = 1.23,
		builder             = false,
		buildPic            = "chicken_shield.png",
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		category            = "LAND",
		
		customParams        = {
			chicken = "uwu",
			chicken_shield = "uwu",
			chicken_needs_bogus_defs = "something normal for once",
			shield_emit_height = 26,
			shield_emit_offset = 0,
			model_rescale = 1.8,
			outline_x = 145,
			outline_y = 145,
			outline_yoff = 27.5,
			singuimmune = 1,
			chicken_spawncost = 4900,
		},

		health              = 20000,
		explodeAs           = "NOWEAPON",
		footprintX          = 4,
		footprintZ          = 4,
		iconType            = "walkershield",
		idleAutoHeal        = 90,
		idleTime            = 300,
		leaveTracks         = true,
		maxSlope            = 90,
		maxWaterDepth       = 5000,
		buildTime           = 2750,
		movementClass       = "ATKBOT4",
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB",
		objectName          = "chicken_shield.s3o",
		reclaimable         = false,
		selfDestructAs      = "NOWEAPON",
		sfxtypes            = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},

		},
		sightDistance       = 512,
		sonarDistance       = 512,
		script              = "chicken_shield.lua",
		speed               = 136,
		trackOffset         = 7,
		trackStrength       = 9,
		trackStretch        = 1,
		trackType           = "ChickenTrack",
		trackWidth          = 34,
		turnRate            = 967,
		upright             = false,
		workerTime          = 0,

		weapons             = {
			{
				def                = "HELIOSPORES",
				badTargetCategory  = "SWIM LAND SHIP HOVER",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def = "SHIELD",
			},
			{
				def                = "AEROSPORES",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
		},


		weaponDefs          = {
			AEROSPORES  = {
				name                    = "Anti-Air Spores",
				areaOfEffect            = 96,
				avoidFriendly           = false,
				burst                   = 7,
				burstrate               = 0.2,
				canAttackGround         = false,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.2,
					isaa = ">w<",
					combatrange = 750,
				},
				
				damage                  = {
					default  = 600,
				},

				dance                   = 120,
				explosionGenerator      = "custom:goo_v2_blue_large",
				explosionScar           = false,
				fireStarter             = 0,
				fixedlauncher           = 1,
				flightTime              = 3,
				groundbounce            = 1,
				heightmod               = 0.5,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggblue.s3o",
				noSelfDamage            = true,
				range                   = 1600,
				reloadtime              = 7,
				smokeTrail              = true,
				startVelocity           = 300,
				texture1                = "",
				texture2                = "sporetrailblue",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1,
				turnRate                = 60000,
				turret                  = true,
				waterweapon             = true,
				weaponAcceleration      = 150,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 2000,
				wobble                  = 96000,
			},
			SHIELD      = {
				name                    = "Shield",
				craterMult              = 0,

				customParams            = {
					unlinked = true,
				},
				
				damage                  = {
					default = 10,
				},

				exteriorShield          = true,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				shieldAlpha             = 0.15,
				shieldBadColor          = "1.0 1 0.1 1",
				shieldGoodColor         = "0.1 1.0 0.1 1",
				shieldInterceptType     = 3,
				shieldPower             = 79500,
				shieldPowerRegen        = 360,
				shieldPowerRegenEnergy  = 0,
				shieldRadius            = 550,
				shieldRepulser          = false,	
				shieldStartingPower     = 79500,
				smartShield             = true,
				visibleShield           = false,
				visibleShieldRepulse    = false,
				--texture1                = "wakelarge",
				--visibleShield           = true,
				--visibleShieldHitFrames  = 30,
				--visibleShieldRepulse    = false,
				weaponType              = "Shield",
			},
			HELIOSPORES       = {
				name                    = "Helioplasm Launcher",
				areaOfEffect            = 200,
				avoidFriendly           = false,
				burst                   = 5,
				burstrate               = 0.266,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					light_radius = 0,
					armorpiercing = 0.3,
				},

				damage                  = {
					default = 700,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_green_large",
				fireStarter             = 0,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				metalpershot            = 0,
				model                   = "chickenegggreen_big.s3o",
				noSelfDamage            = true,
				range                   = 1000,
				reloadtime              = 8,
				smokeTrail              = true,
				sprayangle              = 0,
				startVelocity           = 271,
				texture1                = "",
				texture2                = "sporetrail2",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1.3,
				turnRate                = 24000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 32000,
			},
		},
	}
}
