return {
	chicken_tiamat = {
		name                = "Tiamat",
		description         = "Heavy Assault/Riot",
		acceleration        = 1.08,
		activateWhenBuilt   = true,
		autoheal            = 135,
		brakeRate           = 1.23,
		builder             = false,
		buildPic            = "chicken_tiamat.png",
		buildTime           = 7200,
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		category            = "LAND FIREPROOF",

		customParams        = {
			chicken = "uwu",	
			chicken_shield = ">w<",
			chicken_needs_bogus_defs = "something normal for once",
			fireproof          = 1,
			shield_emit_height = 32,
			shield_emit_offset = -4,
			model_rescale = 2,
			outline_x = 185,
			outline_y = 185,
			outline_yoff = 27.5,
			singuimmune = 1,
			chicken_spawncost = 7200,
		},

		explodeAs           = "NOWEAPON",
		footprintX          = 4,
		footprintZ          = 4,
		health              = 79500,
		iconType            = "t3generic",
		idleAutoHeal        = 20,
		idleTime            = 300,
		leaveTracks         = true,
		maxSlope            = 90,
		maxWaterDepth       = 5000,
		movementClass       = "ATKBOT4",
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM FIXEDWING SATELLITE GUNSHIP STUPIDTARGET MINE",
		objectName          = "chickenbroodqueen.s3o",
		reclaimable         = false,
		selfDestructAs      = "NOWEAPON",

		sfxtypes            = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
				"custom:RAIDMUZZLE",
			},
		},
		sightDistance       = 1500,
		sonarDistance       = 1500,
		script              = "chicken_tiamat.lua",
		speed               = 142, -- nice
		trackOffset         = 7,
		trackStrength       = 9,
		trackStretch        = 1,
		trackType           = "ChickenTrack",
		trackWidth          = 34,
		turninplace         = 0,
		turnRate            = 967,
		upright             = false,
		workerTime          = 0,

		weapons             = {
			{
				def                = "DISINTEGRATOR",
				mainDir            = "0 0 1",
				maxAngleDif        = 90,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP SUB HOVER FIXEDWING GUNSHIP",
			},
			{
				def                = "AEROSPORES",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
			{
				def                = "SPORES",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def = "SHIELD",
			},
		},


		weaponDefs          = {
			DISINTEGRATOR = {
				name                    = "Disintegrator",
				areaOfEffect            = 48,
				avoidFeature            = false,
				avoidFriendly           = true,
				avoidGround             = false,
				avoidNeutral            = false,
				commandfire             = false,
				craterBoost             = 1,
				craterMult              = 6,
				customParams            = {
					mass = 350.5,
				},
				damage                  = {
					default = 1000,
				},
				explosionGenerator      = "custom:DGUNTRACE",
				heightMod               = 1,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 0,
				leadLimit               = 10,
				noExplode               = true,
				noSelfDamage            = true,
				range                   = 250,
				reloadtime              = 1.5,
				size                    = 6,
				soundHit                = "explosion/ex_med6",
				soundStart              = "weapon/laser/heavy_laser4",
				soundTrigger            = true,
				tolerance               = 10000,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "DGun",
				weaponVelocity          = 300,
			},
			SHIELD       = {
				name                    = "Shield",
				craterMult              = 0,

				customParams            = {
					unlinked = true,
				},
				
				damage                  = {
					default = 10,
				},

				exteriorShield          = true,
				impulseFactor           = 0,
				interceptedByShieldType = 3,
				shieldAlpha             = 0.15,
				shieldBadColor          = "1.0 1 0.1 1",
				shieldGoodColor         = "0.1 1.0 0.1 1",
				shieldInterceptType     = 3,
				shieldPower             = 91200,
				shieldPowerRegen        = 360,
				shieldPowerRegenEnergy  = 0,
				shieldRadius            = 400,
				shieldRepulser          = false,	
				shieldStartingPower     = 91200,
				smartShield             = true,
				visibleShield           = false,
				visibleShieldRepulse    = false,
				--texture1                = "wake",
				--visibleShield           = true,
				--visibleShieldHitFrames  = 30,
				--visibleShieldRepulse    = false,
				weaponType              = "Shield",
			},
			AEROSPORES  = {
				name                    = "Anti-Air Spores",
				areaOfEffect            = 96,
				avoidFriendly           = false,
				burst                   = 8,
				burstrate               = 0.2,
				canAttackGround         = false,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.5,
					isaa = ">w<",
				},
				
				damage                  = {
					default  = 1500,
				},

				dance                   = 120,
				explosionGenerator      = "custom:goo_v2_blue_large",
				fireStarter             = 0,
				fixedlauncher           = 1,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggblue.s3o",
				noSelfDamage            = true,
				range                   = 1700,
				reloadtime              = 4,
				smokeTrail              = true,
				startVelocity           = 300,
				texture1                = "",
				texture2                = "sporetrailblue",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1,
				turnRate                = 72000,
				turret                  = true,
				waterweapon             = true,
				weaponAcceleration      = 150,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 2000,
				wobble                  = 96000,
			},
			SPORES = {
				name                    = "Explosive Spores",
				areaOfEffect            = 96,
				avoidFriendly           = false,
				burst                   = 8,
				burstrate               = 2/30,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					light_radius = 0,
					armorpiercing = 0.5,
					combatrange = 150,
				},

				damage                  = {
					default = 400,
					planes  = 400,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_red",
				fireStarter             = 0,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggyellow.s3o",
				range                   = 800,
				reloadtime              = 3,
				smokeTrail              = true,
				startVelocity           = 500,
				texture1                = "",
				texture2                = "sporetrail",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 0.5,
				turnRate                = 24000,
				turret                  = true,
				waterweapon             = true,
				weaponAcceleration      = 100,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 48000,
			},
		},
	}
}
