return {
	chicken_sporeshooter = {
		name                = "Sporeshooter",
		description         = "All-Terrain Spores (Anti-Air/Skirm)",
		acceleration        = 1.08,
		activateWhenBuilt   = true,
		brakeRate           = 1.23,
		builder             = false,
		buildPic            = "chicken_sporeshooter.png",
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		category            = "LAND",

		customParams        = {
			chicken = "uwu",
			
			outline_x = 130,
			outline_y = 130,
			outline_yoff = 30,
			model_rescale = 1.4,
			singuimmune = 1,
		},

		explodeAs           = "NOWEAPON",
		footprintX          = 3,
		footprintZ          = 3,
		health              = 17500,
		iconType            = "spiderskirm",
		idleAutoHeal        = 20,
		idleTime            = 300,
		leaveTracks         = true,
		maxSlope            = 84,
		waterline           = 22,
		buildTime           = 2250,
		movementClass       = "ATKBOT4",
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM LAND SINK TURRET SHIP SATELLITE SWIM FLOAT SUB HOVER STUPIDTARGET",
		objectName          = "chicken_sporeshooter.s3o",
		reclaimable         = false,
		selfDestructAs      = "NOWEAPON",

		sfxtypes            = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},
		},
		sightDistance       = 512,
		sonarDistance       = 512,
		script              = "chicken_sporeshooter.lua",
		speed               = 162,
		trackOffset         = 0.5,
		trackStrength       = 9,
		trackStretch        = 1,
		trackType           = "ChickenTrackPointy",
		trackWidth          = 70,
		turnRate            = 1440,
		upright             = false,
		workerTime          = 0,

		weapons             = {
			{
				def                = "HELIOSPORES",
				badTargetCategory  = "SWIM LAND SHIP HOVER",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},

		weaponDefs          = {
			HELIOSPORES       = {
				name                    = "Helioplasm Launcher",
				areaOfEffect            = 200,
				avoidFriendly           = false,
				burst                   = 5,
				burstrate               = 0.266,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.2,
				},

				damage                  = {
					default = 700,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_green_large",
				fireStarter             = 0,
				fixedlauncher           = true,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				metalpershot            = 0,
				model                   = "chickenegggreen_big.s3o",
				noSelfDamage            = true,
				range                   = 1000,
				reloadtime              = 5,
				smokeTrail              = true,
				sprayangle              = 0,
				startVelocity           = 271,
				texture1                = "",
				texture2                = "sporetrail2",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1.3,
				turnRate                = 24000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 32000,
			},
		},
	}
}
