return { 
	chicken_pigeon = {
		unitname            = "chicken_pigeon",
		name                = "Pigeon",
		description         = "Biological Flying Pest",
		activateWhenBuilt   = true,
		acceleration        = 0.8,
		brakeRate           = 0.32,
		buildCostMetal      = 1,
		builder             = false,
		buildPic            = "chicken_pigeon.png",
		buildTime           = 260,
		canFly              = true,
		canGuard            = true,
		canLand             = true,
		canMove             = true,
		canPatrol           = true,
		canSubmerge         = false,
		category            = "FIXEDWING",
		collide             = false,
		cruiseAlt           = 250,
		customParams        = {
			chicken = "uwu",
			model_rescale = 1.1,
			chicken_spawncost = 130,
		},
		explodeAs           = "NOWEAPON",
		floater             = true,
		footprintX          = 1,
		footprintZ          = 1,
		iconType            = "scoutplane",
		idleAutoHeal        = 30,
		idleTime            = 90,
		health              = 410,
		maxSlope            = 18,
		speed               = 430,
		movestate           = 2,
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM FIXEDWING GUNSHIP SATELLITE",
		objectName          = "chicken_pigeon.s3o",
		reclaimable         = false,
		selfDestructAs      = "NOWEAPON",
		script              = "chicken_pigeon.lua",
		sfxtypes            = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},
		},
		sightDistance       = 800,
		turnRate            = 6000,
		weapons             = {
			{
				def                = "SPORES",
				mainDir            = "0 -1 0",
				maxAngleDif        = 120,
				onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER",
			},
		},
		weaponDefs          = {
			SPORES     = {
				name                    = "Acidic Spit",
				areaOfEffect            = 96,
				avoidFriendly           = false,
				alphaDecay              = 0.8,
				burst                   = 7,
				burstRate               = 2/30,
				collideFriendly         = false,
				colorMap                = "0 0.952941 0.3843  0.08627 0.8509803 0.3960784   0.18039 0.70588 0.392156   0.1764705 0.52941 0.32156  0.12941 0.372549 0.22745  0.219607 0.549019 0.352941",
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					light_radius = 0,
				},
				damage                  = {
					default = 30.01,
				},
				dance                   = 60,
				explosionGenerator      = "custom:goo_v2_green",
				fireStarter             = 0,
				fixedlauncher           = 1,
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				myGravity				= 1.2,
				interceptedByShieldType = 2,
				range                   = 10,
				reloadtime              = 4,
				smokeTrail              = true,
				startVelocity           = 100,
				size                    = 8,
				stages                  = 10,
				seperation				= 3,
				soundHit                = "chickens/acid_hit",
				soundStart              = "weapon/chickens/small_attack",
				texture1                = "",
				texture2                = "sporetrail",
				tolerance               = 32000,
				turret                  = true,
				waterWeapon             = true,
				weaponAcceleration      = 100,
				weaponType              = "AircraftBomb",
			},
		},
	}
}
