return {
	chicken_tiamat = {
		name                = "Tiamat",
		description         = "Heavy Assault/Riot",
		acceleration        = 1.08,
		activateWhenBuilt   = true,
		autoheal            = 135,
		brakeRate           = 1.23,
		builder             = false,
		buildPic            = "chicken_tiamat.png",
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		category            = "LAND FIREPROOF",

		customParams        = {
			chicken = "uwu",	
			chicken_shield = ">w<",
			fireproof          = 1,
			shield_emit_height = 32,
			shield_emit_offset = -4,
			model_rescale = 1.6,
			outline_x = 185,
			outline_y = 185,
			outline_yoff = 27.5,
			singuimmune = 1,
		},

		explodeAs           = "NOWEAPON",
		footprintX          = 4,
		footprintZ          = 4,
		health              = 52400,
		iconType            = "t3generic",
		idleAutoHeal        = 20,
		idleTime            = 300,
		leaveTracks         = true,
		maxSlope            = 84,
		maxWaterDepth       = 5000,
		buildTime           = 5600,
		movementClass       = "ATKBOT4",
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM FIXEDWING SATELLITE GUNSHIP STUPIDTARGET MINE",
		objectName          = "chickenbroodqueen.s3o",
		reclaimable         = false,
		selfDestructAs      = "NOWEAPON",

		sfxtypes            = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
				"custom:RAIDMUZZLE",
			},
		},
		sightDistance       = 1500,
		sonarDistance       = 1500,
		script              = "chicken_tiamat.lua",
		speed               = 142, -- nice
		trackOffset         = 7,
		trackStrength       = 9,
		trackStretch        = 1,
		trackType           = "ChickenTrack",
		trackWidth          = 34,
		turninplace         = 0,
		turnRate            = 967,
		upright             = false,
		workerTime          = 0,

		weapons             = {
			{
				def                = "JAWS",
				mainDir            = "0 0 1",
				maxAngleDif        = 120,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP SUB HOVER FIXEDWING GUNSHIP",
			},
			{
				def                = "AEROSPORES",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
			{
				def                = "FLAMETHROWER",
				mainDir            = "0 0 1",
				maxAngleDif        = 120,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP FIXEDWING",
			},
			{
				def = "SHIELD",
			},
		},


		weaponDefs          = {

			FLAMETHROWER = {
				name                    = "Primordial Fire",
				areaOfEffect            = 64,
				avoidGround             = false,
				avoidFeature            = false,
				avoidFriendly           = true,
				collideFeature          = false,
				collideGround           = false,
				coreThickness           = 0,
				craterBoost             = 0,
				craterMult              = 0,
				cegTag                  = "superflamer",
				customParams            = {
					flamethrower = "1",
					setunitsonfire = "1",
					burnchance = "1", -- Per-impact
					burntime = "1000",
					light_camera_height = 2800,
					light_color = "0.01 1.000 0.705",
					light_radius = 260,
					light_fade_time = 10,
					light_beam_mult_frames = 5,
					light_beam_mult = 5,
					combatrange = 200,
					armorpiercing = 0.3,
				},
				damage                  = {
					default = 328,
				},
				duration                = 0.01,
				explosionGenerator      = "custom:SMOKE",
				fallOffRate             = 1,
				fireStarter             = 100,
				heightMod               = 1,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 0.3,
				interceptedByShieldType = 1,
				leadLimit               = 10,
				noExplode               = true,
				noSelfDamage            = true,
				range                   = 588,
				reloadtime              = 1/30,
				rgbColor                = "0.01 1.000 0.705",
				size                    = 12,
				soundHit                = "flamethrowerhit",
				soundStart              = "flamethrowerfire",
				soundStart              = "weapon/flamethrower",
				soundTrigger            = true,
				sprayangle              = 1000,
				texture1                = "flame",
				thickness               = 0,
				tolerance               = 5000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "LaserCannon",
				weaponVelocity          = 840,
			},
			JAWS         = {
				name                    = "Jaws",
				areaOfEffect            = 8,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					armorpiercing = 1,
				},

				damage                  = {
					default = 12000,
				},

				explosionGenerator      = "custom:NONE",
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 0,
				noSelfDamage            = true,
				range                   = 240,
				reloadtime              = 1.5,
				size                    = 0,
				soundHit                = "chickens/chickenbig2",
				soundStart              = "chickens/chickenbig2",
				targetborder            = 1,
				tolerance               = 5000,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 500,
			},
			SHIELD       = {
				name                    = "Shield",
				craterMult              = 0,

				customParams            = {
					unlinked = true,
				},
				
				damage                  = {
					default = 10,
				},

				exteriorShield          = true,
				impulseFactor           = 0,
				interceptedByShieldType = 3,
				shieldAlpha             = 0.15,
				shieldBadColor          = "1.0 1 0.1 1",
				shieldGoodColor         = "0.1 1.0 0.1 1",
				shieldInterceptType     = 3,
				shieldPower             = 45920,
				shieldPowerRegen        = 360,
				shieldPowerRegenEnergy  = 0,
				shieldRadius            = 400,
				shieldRepulser          = false,	
				shieldStartingPower     = 45920,
				smartShield             = true,
				visibleShield           = false,
				visibleShieldRepulse    = false,
				--texture1                = "wake",
				--visibleShield           = true,
				--visibleShieldHitFrames  = 30,
				--visibleShieldRepulse    = false,
				weaponType              = "Shield",
			},
			AEROSPORES  = {
				name                    = "Anti-Air Spores",
				areaOfEffect            = 200,
				avoidFriendly           = false,
				burst                   = 8,
				burstrate               = 0.2,
				canAttackGround         = false,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.3,
					isaa = ">w<",
				},
				
				damage                  = {
					default  = 1150,
				},

				dance                   = 120,
				explosionGenerator      = "custom:goo_v2_blue_large",
				fireStarter             = 0,
				fixedlauncher           = 1,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggblue.s3o",
				noSelfDamage            = true,
				range                   = 1700,
				reloadtime              = 6,
				smokeTrail              = true,
				startVelocity           = 300,
				texture1                = "",
				texture2                = "sporetrailblue",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1,
				turnRate                = 72000,
				turret                  = true,
				waterweapon             = true,
				weaponAcceleration      = 150,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 2000,
				wobble                  = 96000,
			},
		},
	}
}
