return { 
	chicken = {
		unitname            = "chicken",
		name                = "Chicken",
		description         = "Swarmer",
		acceleration        = 1.08,
		autoheal            = 10,
		activateWhenBuilt   = true,
		brakeRate           = 1.23,
		buildCostEnergy     = 0,
		buildCostMetal      = 0,
		builder             = false,
		buildPic            = "chicken.png",
		buildTime           = 50,
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		category            = "LAND SWIM SMALL",
		customParams        = {
			chicken = "uwu",
			outline_x = 70,
			outline_y = 70,
			outline_yoff = 15,
		},
		explodeAs           = "NOWEAPON",
		footprintX          = 2,
		footprintZ          = 2,
		iconType            = "chicken",
		idleAutoHeal        = 20,
		idleTime            = 180,
		leaveTracks         = true,
		health              = 800,
		maxSlope            = 84,
		maxWaterDepth       = 5000,
		speed               = 200,
		movementClass       = "ATKBOT2",
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM FIXEDWING SATELLITE GUNSHIP",
		objectName          = "chicken.s3o",
		power               = 50,
		reclaimable         = false,
		selfDestructAs      = "NOWEAPON",
		sfxtypes            = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},
		},
		sightDistance       = 450,
		script              = "chicken.lua",
		trackOffset         = 0,
		trackStrength       = 8,
		trackStretch        = 1,
		trackType           = "ChickenTrack",
		trackWidth          = 18,
		turnRate            = 1400,
		upright             = false,
		waterline           = 16,
		weapons             = {
			{
				def                = "WEAPON",
				mainDir            = "0 0 1",
				maxAngleDif        = 120,
				onlyTargetCategory = "SWIM LAND SUB SINK TURRET FLOAT SHIP HOVER FIXEDWING GUNSHIP",
			},
			{
				def                = "SILK",
				mainDir            = "0 0 1",
				maxAngleDif        = 120,
				onlyTargetCategory = "SWIM LAND SUB SINK TURRET FLOAT SHIP HOVER FIXEDWING GUNSHIP",
			},
		},
		weaponDefs          = {
			WEAPON = {
				name                    = "Claws",
				avoidFeature            = false,
				avoidFriendly           = false,
				collideFeature          = false,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				beamtime                = 1/30,
				
				customParams			= {
					combatrange = 50,
					light_radius = 0,
				},
				damage                  = {
					default = 60.01,
				},

				explosionGenerator      = "custom:NONE",
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 1.5,
				interceptedByShieldType = 0,
				range                   = 85,
				reloadtime              = 0.7,
				size                    = 0,
				soundHit                = "chickens/chickenbig2",
				soundStart              = "chickens/chicken",
				targetborder            = 1,
				thickness               = 0,
				tolerance               = 10000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "BeamLaser",
			},
			SILK = {
				name                    = "Webshot",
				avoidFeature            = false,
				areaOfEffect            = 32,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					light_radius = 0,
					timeslow_damagefactor = 10,
					combatrange = 50,
				},

				damage                  = {
					default = 30.01,
				},

				duration                = 0.1,
				edgeEffectiveness       = 0.4,
				explosionGenerator      = "custom:spidersilk",
				explosionScar           = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				hardStop                = false,
				fallOffRate             = 0.5,
				largebeamlaser			= true,
				range                   = 400,
				reloadtime              = 6.8,
				targetborder            = 1,
				texture1                = "bloodblastwhite",
				texture2                = "bloodblastwhite",
				tileLength              = 50,
				thickness               = 20,
				rgbColor                = "1 1 1",
				soundHit                = "chickens/web",
				soundHitVolume          = 0.7,
				soundStart              = "weapon/chickens/newweb",
				soundStartVolume        = 10,
				soundTrigger            = true,
				sprayangle				= 1000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "LaserCannon",
				weaponVelocity          = 1200,
			},
		},
	} 
}
