return {
	chickenflyerqueen = {
		name                = "Chicken Queen",
		description         = "Clucking Hell!",
		acceleration        = 1.2,
		activateWhenBuilt   = true,
		airHoverFactor      = 0,
		brakeRate           = 0.8,
		builder             = false,
		buildPic            = "chickenflyerqueen.png",
		buildTime           = 360000,
		canFly              = true,
		canGuard            = true,
		canLand             = true,
		canMove             = true,
		canPatrol           = true,
		canSubmerge         = false,
		category            = "GUNSHIP",
		collide             = false,
		cruiseAlt           = 200,
		collisionSphereScale   = 1,
		collisionVolumeOffsets = "0 160 30",
		collisionVolumeScales  = "175 175 520",
		collisionVolumeType    = "cylZ",

		customParams        = {
			chicken = "uwu",
			chicken_menace = "^w^",
			chicken_queen = "~w~",
			chicken_needs_bogus_defs = "something normal for once",
			statsname = "chickenlandqueen",
			
			aimposoffset   = "0 160 30",
			modelradius = 200,

			outline_x = 1200,
			outline_y = 1200,
			outline_yoff = 270,
			reveal_losunit = "los_superwep",
			reveal_onprogress = 0.1,
			model_rescale = 3,
			singuimmune = 1,
		},

		explodeAs           = "NOWEAPON",
		floater             = true,
		footprintX          = 8,
		footprintZ          = 8,
		hoverattack         = true,
		iconType            = "chickenq",
		idleAutoHeal        = 200,
		idleTime            = 300,
		leaveTracks         = true,
		maneuverleashlength = "64000",
		health              = 20000000,
		maxSlope            = 36,
		speed               = 90,
		metalCost           = 0,
		energyCost          = 0,
		minCloakDistance    = 250,
		noAutoFire          = false,
		noChaseCategory     = "",
		objectName          = "chickenflyerqueen.s3o",
		power               = 45000,
		reclaimable         = false,
		script              = "chickenflyerqueen.lua",
		selfDestructAs      = "NOWEAPON",

		sfxtypes            = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},
		},
		sightDistance       = 4096,
		turnRate            = 900,
		workerTime          = 0,

		weapons             = {
			{
				def                = "GOO",
				badTargetCategory  = "GUNSHIP",
				mainDir            = "0 0 1",
				maxAngleDif        = 120,
				onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "SPORES",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "AEROSPORES",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
			{
				def                = "HIGHSPORES",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},

		weaponDefs          = {
			GOO          = {
				name                    = "Blob",
				areaOfEffect            = 128,
				burst                   = 8,
				burstrate               = 0.033,
				projectiles             = 6,
				cegTag                  = "queen_trail",
				craterBoost             = 0,
				craterMult              = 0,
							
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.4,
					combatrange = 750,
				},
							
				damage                  = {
					default = 500,
					planes  = 500,
				},

				explosionGenerator      = "custom:goo_v2_green_large",
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				proximityPriority       = -4,
				range                   = 1000,
				reloadtime              = 6,
				rgbColor                = "0.2 0.6 0",
				size                    = 8,
				sizeDecay               = 0,
				soundStart              = "chickens/bigchickenroar",
				sprayAngle              = 10000,
				tolerance               = 5000,
				turret                  = true,
				weaponType              = "Cannon",
				waterWeapon             = true,
				weaponVelocity          = 600,
			},
			COCKATRICE          = {
				name                    = "Cockatrice Bomb",
				areaOfEffect            = 384,
				burnblow                = false,
				cegTag                  = "queen_trail",
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					spawns_name = "chickena",
					spawns_expire = 300,
					gatherradius = "312",
					smoothradius = "240",
					detachmentradius = "240",
					smoothmult   = "1",
					smoothexponent = "0.75",
					movestructures = "1",
					light_radius = 0,
					armorpiercing = 0.4,
					combatrange = 750,
				},

				damage                  = {
					default = 500,
					planes  = 500,
				},

				explosionGenerator      = "custom:330rlexplode",
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				intensity               = 0.7,
				interceptedByShieldType = 0,
				model                   = "chickena.s3o",
				noSelfDamage            = true,
				proximityPriority       = -4,
				range                   = 100000,
				reloadtime              = 6,
				size                    = 8,
				sizeDecay               = 0,
				soundStart              = "chickens/bigchickenroar",
				sprayAngle              = 10000,
				tolerance               = 5000,
				turret                  = true,
				weaponType              = "Cannon",
				waterWeapon             = true,
				weaponVelocity          = 600,
			},
			SPORES = {
				name                    = "Explosive Spores",
				areaOfEffect            = 192,
				avoidFriendly           = false,
				burst                   = 24,
				burstrate               = 1/30,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.4,
					combatrange = 750,
				},
				
				damage                  = {
					default = 400,
					planes  = 400,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_green_large",
				fireStarter             = 0,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickenegggreen_big.s3o",
				range                   = 1000,
				reloadtime              = 3,
				smokeTrail              = true,
				startVelocity           = 271,
				texture1                = "",
				texture2                = "sporetrail2",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 0.5,
				turnRate                = 20000,
				turret                  = true,
				waterweapon             = true,
				--weaponAcceleration      = 100,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 48000,
			},
			HIGHSPORES = {
				name                    = "Explosive Spores (alt)",
				areaOfEffect            = 192,
				avoidFriendly           = false,
				burst                   = 32,
				burstrate               = 1/30,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.4,
					combatrange = 750,
				},
				
				damage                  = {
					default = 400,
					planes  = 400,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_green_large",
				fireStarter             = 0,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickenegggreen_big.s3o",
				range                   = 1000,
				reloadtime              = 4,
				smokeTrail              = true,
				startVelocity           = 271,
				texture1                = "",
				texture2                = "sporetrail2",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1.5,
				turnRate                = 20000,
				turret                  = true,
				waterweapon             = true,
				--weaponAcceleration      = 100,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 48000,
			},
			AEROSPORES  = {
				name                    = "Anti-Air Spores",
				areaOfEffect            = 200,
				avoidFriendly           = false,
				burst                   = 30,
				burstrate               = 2/30,
				canAttackGround         = false,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.4,
					isaa = ">w<",
					combatrange = 750,
				},
				
				damage                  = {
					default  = 1200,
				},

				dance                   = 120,
				explosionGenerator      = "custom:goo_v2_blue_large",
				explosionScar           = false,
				fireStarter             = 0,
				fixedlauncher           = 1,
				flightTime              = 3,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggblue.s3o",
				noSelfDamage            = true,
				range                   = 2600,
				reloadtime              = 3,
				smokeTrail              = true,
				startVelocity           = 300,
				texture1                = "",
				texture2                = "sporetrailblue",
				tolerance               = 10000,
				tracks                  = true,
				turnRate                = 72000,
				turret                  = true,
				waterweapon             = true,
				weaponAcceleration      = 150,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 2000,
				wobble                  = 96000,
			},
		},
	}
}
