return {
	chicken_dragon = {
		name                   = "White Dragon",
		description            = "Prime Assault Chicken",
		acceleration           = 6.0,
		activateWhenBuilt      = true,
		autoHeal               = 0,
		brakeRate              = 36.0,
		builder                = false,
		buildPic               = "chicken_dragon.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canSubmerge            = false,
		cantBeTransported      = true,
		category               = "LAND SWIM",
		collisionSphereScale   = 1,
		collisionVolumeOffsets = "0 -7.5 -7.5",
		collisionVolumeScales  = "45 105 105",
		collisionVolumeType    = "box",

		customParams           = {
			chicken = "uwu",
			chicken_menace = ">w<",
			outline_x = 405,
			outline_y = 405,
			outline_yoff = 60,
			model_rescale = 1.5,
			reveal_losunit = "los_menace",
			reveal_onprogress = 0.1,
			singuimmune = 1,
		},

		explodeAs              = "SMALL_UNITEX",
		footprintX             = 4,
		footprintZ             = 4,
		iconType               = "chickenminiq",
		idleAutoHeal           = 100,
		idleTime               = 300,
		leaveTracks            = true,
		health                 = 144000,
		maxSlope               = 36,
		speed                  = 93,
		metalCost              = 0,
		energyCost             = 0,
		buildTime              = 10500,
		minCloakDistance       = 225,
		movementClass          = "ATKBOT4",
		noAutoFire             = false,
		noChaseCategory        = "TERRAFORM SATELLITE FIXEDWING GUNSHIP STUPIDTARGET MINE",
		objectName             = "chicken_dragon.s3o",
		power                  = 10500,
		reclaimable            = false,
		script                 = "chicken_dragon.cob",
		selfDestructAs         = "SMALL_UNITEX",

		sfxtypes               = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},
		},
		sightDistance          = 1200,
		script                 = "chicken_dragon.lua",
		trackOffset            = 18,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ChickenTrack",
		trackWidth             = 100,
		turninplace            = 0,
		turnRate               = 640,
		upright                = false,
		waterLine              = 42,
		workerTime             = 0,

		weapons                = {
			{
				def                = "MELEE",
				mainDir            = "0 0 1",
				maxAngleDif        = 150,
				onlyTargetCategory = "SWIM LAND SUB SINK TURRET FLOAT SHIP HOVER",
			},
			{
				def                = "SPORES",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "AEROSPORES",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
			{
				def                = "HIGHSPORES",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "GOO",
				mainDir            = "0 0 1",
				maxAngleDif        = 120,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER",
			},
			{
				def                = "QUEENCRUSH",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER",
			},
		},


		weaponDefs             = {
			GOO        = {
				name                    = "Blob",
				areaOfEffect            = 280,
				avoidFeature            = false,
				avoidGround             = false,
				burst                   = 10,
				burstrate               = 0.033,
				projectiles             = 2,
				cegTag                  = "queen_trail",
				craterBoost             = 0,
				craterMult              = 0,
							
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.3,
					combatrange = 150,
					force_ignore_ground = [[1]],
					light_camera_height = 2500,
					light_color = [[0.35 0.17 0.04]],
					light_radius = 400,
					gatherradius = "208",
					smoothradius = "160",
					detachmentradius = "240",
					smoothmult   = "1",
					smoothexponent = "0.75",
					movestructures = "1",
				},

				damage                  = {
					default = 300,
				},

				explosionGenerator      = "custom:goo_v2_green_large",
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				proximityPriority       = -4,
				range                   = 540,
				reloadtime              = 6,
				rgbColor                = "0.2 0.6 0",
				size                    = 5,
				sizeDecay               = 0,
				soundStart              = "chickens/bigchickenroar",
				sprayAngle              = 6100,
				tolerance               = 5000,
				turret                  = true,
				weaponType              = "Cannon",
				waterWeapon             = true,
				weaponVelocity          = 720,
			},
			MELEE      = {
				name                    = "Chicken Jaws",
				areaOfEffect            = 32,
				craterBoost             = 1,
				craterMult              = 0,
				
				customParams            = {
					armorpiercing = 1,
				},
				
				damage                  = {
					default = 12000,
					planes  = 12000,
				},

				explosionGenerator      = "custom:NONE",
				impulseBoost            = 0,
				impulseFactor           = 1,
				interceptedByShieldType = 0,
				range                   = 192,
				reloadtime              = 3,
				size                    = 0,
				soundStart              = "chickens/bigchickenbreath",
				targetborder            = 1,
				tolerance               = 5000,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 600,
			},
			QUEENCRUSH = {
				name                    = "Chicken Kick",
				areaOfEffect            = 360,
				collideFriendly         = false,
				craterBoost             = 0.001,
				craterMult              = 0.002,
							
				customParams            = {
					armorpiercing = 0.3,
					combatrange = 150,
				},

				damage                  = {
					default    = 100,
					chicken    = 0.001,
					planes     = 100,
				},

				edgeEffectiveness       = 1,
				explosionGenerator      = "custom:NONE",
				impulseBoost            = 300,
				impulseFactor           = 1,
				intensity               = 1,
				interceptedByShieldType = 1,
				range                   = 384,
				reloadtime              = 1,
				rgbColor                = "1 1 1",
				thickness               = 1,
				tolerance               = 100,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 0.8,
			},
			SPORES = {
				name                    = "Explosive Spores",
				areaOfEffect            = 96,
				avoidFriendly           = false,
				burst                   = 12,
				burstrate               = 2/30,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.3,
					combatrange = 150,
				},
				
				damage                  = {
					default = 100,
					planes  = 100,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_red",
				fireStarter             = 0,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggyellow.s3o",
				range                   = 670,
				reloadtime              = 3,
				smokeTrail              = true,
				startVelocity           = 271,
				texture1                = "",
				texture2                = "sporetrail",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 0.5,
				turnRate                = 20000,
				turret                  = true,
				waterweapon             = true,
				--weaponAcceleration      = 100,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 48000,
			},
			HIGHSPORES = {
				name                    = "Explosive Spores (alt)",
				areaOfEffect            = 96,
				avoidFriendly           = false,
				burst                   = 16,
				burstrate               = 2/30,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.3,
					combatrange = 150,
				},
				
				damage                  = {
					default = 100,
					planes  = 100,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_red",
				fireStarter             = 0,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggyellow.s3o",
				range                   = 670,
				reloadtime              = 4,
				smokeTrail              = true,
				startVelocity           = 271,
				texture1                = "",
				texture2                = "sporetrail",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1.5,
				turnRate                = 20000,
				turret                  = true,
				waterweapon             = true,
				--weaponAcceleration      = 100,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 48000,
			},
			AEROSPORES  = {
				name                    = "Anti-Air Spores",
				areaOfEffect            = 200,
				avoidFriendly           = false,
				burst                   = 10,
				burstrate               = 0.1,
				canAttackGround         = false,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				
				customParams            = {
					light_radius = 0,
					armorpiercing = 0.3,
					isaa = ">w<",
					combatrange = 150,
				},
				
				damage                  = {
					default  = 500,
				},

				dance                   = 120,
				explosionGenerator      = "custom:goo_v2_blue_large",
				explosionScar           = false,
				fireStarter             = 0,
				fixedlauncher           = 1,
				flightTime              = 3,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggblue.s3o",
				noSelfDamage            = true,
				range                   = 1600,
				reloadtime              = 3,
				smokeTrail              = true,
				startVelocity           = 300,
				texture1                = "",
				texture2                = "sporetrailblue",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1,
				turnRate                = 60000,
				turret                  = true,
				waterweapon             = true,
				weaponAcceleration      = 150,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 2000,
				wobble                  = 96000,
			},
		},
	}
}
