return { chickenflyerqueen = {
	name                = [[Chicken Queen]],
	description         = [[Clucking Hell!]],
	acceleration        = 1.2,
	activateWhenBuilt   = true,
	airHoverFactor      = 0,
	brakeRate           = 0.8,
	builder             = false,
	buildPic            = [[chickenflyerqueen.png]],
	canFly              = true,
	canGuard            = true,
	canLand             = true,
	canMove             = true,
	canPatrol           = true,
	canSubmerge         = false,
	category            = [[GUNSHIP]],
	collide             = false,
	cruiseAlt           = 200,
	collisionSphereScale   = 1,
	collisionVolumeOffsets = [[0 160 30]],
	collisionVolumeScales  = [[175 175 520]],
	collisionVolumeType    = [[cylZ]],

	customParams        = {
		statsname = "chickenlandqueen",
		
		aimposoffset   = "0 160 30",
		modelradius = 200,

		outline_x = 1200,
		outline_y = 1200,
		outline_yoff = 270,
	},

	explodeAs           = [[NOWEAPON]],
	floater             = true,
	footprintX          = 8,
	footprintZ          = 8,
	hoverattack         = true,
	iconType            = [[chickenq]],
	idleAutoHeal        = 200,
	idleTime            = 300,
	leaveTracks         = true,
	maneuverleashlength = [[64000]],
	health              = 1600000,
	maxSlope            = 36,
	speed               = 3,
	metalCost           = 0,
	energyCost          = 0,
	buildTime           = 240000,
	minCloakDistance    = 250,
	noAutoFire          = false,
	noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP STUPIDTARGET MINE]],
	objectName          = [[chickenflyerqueen.s3o]],
	power               = 45000,
	reclaimable         = false,
	script              = [[chickenflyerqueen.lua]],
	selfDestructAs      = [[NOWEAPON]],

	sfxtypes            = {

		explosiongenerators = {
			[[custom:blood_spray]],
			[[custom:blood_explode]],
			[[custom:dirt]],
		},

	},
	sightDistance       = 4096,
	sonarDistance       = 4096,
	turnRate            = 900,
	workerTime          = 0,

	weapons             = {

		{
			def                = [[GOO]],
			badTargetCategory  = [[GUNSHIP]],
			mainDir            = [[0 0 1]],
			maxAngleDif        = 120,
			onlyTargetCategory = [[LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
		},
		{
			def                = [[SPORES]],
			onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
		},
		{
			def                = [[SPORES]],
			onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
		},
		{
			def                = [[SPORES]],
			onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
		},
		{
			def                = [[DODOBOMB]],
			onlyTargetCategory = [[NONE]],
		},
		{
			def                = [[BASILISKBOMB]],
			onlyTargetCategory = [[NONE]],
		},
		{
			def                = [[TIAMATBOMB]],
			onlyTargetCategory = [[NONE]],
		},
		{
			def                = [[AEROSPORES]],
			onlyTargetCategory = [[FIXEDWING GUNSHIP]],
		},
		{
			def                = [[AEROSPORES]],
			onlyTargetCategory = [[FIXEDWING GUNSHIP]],
		},
		{
			def                = [[AEROSPORES]],
			onlyTargetCategory = [[FIXEDWING GUNSHIP]],
		},
	},


	weaponDefs          = {

		BASILISKBOMB = {
			name                    = [[Basilisk Bomb]],
			accuracy                = 60000,
			areaOfEffect            = 48,
			avoidFeature            = false,
			avoidFriendly           = false,
			burnblow                = true,
			collideFriendly         = false,
			craterBoost             = 1,
			craterMult              = 2,
			
			customparams            = {
					spawns_name = "chickenc",
					spawns_expire = 300,
			},

			damage                  = {
				default = 180,
			},

			explosionGenerator      = [[custom:none]],
			fireStarter             = 70,
			flightTime              = 0,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 0,
			model                   = [[chickenc.s3o]],
			projectiles             = 10,
			range                   = 500,
			reloadtime              = 10,
			smokeTrail              = false,
			startVelocity           = 200,
			tolerance               = 8000,
			tracks                  = false,
			turnRate                = 4000,
			turret                  = true,
			waterweapon             = true,
			weaponAcceleration      = 200,
			weaponType              = [[AircraftBomb]],
			weaponVelocity          = 200,
		},
		DODOBOMB     = {
			name                    = [[Dodo Bomb]],
			accuracy                = 60000,
			areaOfEffect            = 1,
			avoidFeature            = false,
			avoidFriendly           = false,
			burnblow                = true,
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			
			customparams            = {
					spawns_name = "chicken_dodo",
					spawns_expire = 300,
			},

			damage                  = {
				default = 1,
			},

			explosionGenerator      = [[custom:none]],
			fireStarter             = 70,
			flightTime              = 0,
			impactOnly              = true,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 0,
			model                   = [[chicken_dodobomb.s3o]],
			projectiles             = 10,
			range                   = 500,
			reloadtime              = 10,
			smokeTrail              = false,
			startVelocity           = 200,
			tolerance               = 8000,
			tracks                  = false,
			turnRate                = 4000,
			turret                  = true,
			waterweapon             = true,
			weaponAcceleration      = 200,
			weaponType              = [[AircraftBomb]],
			weaponVelocity          = 200,
		},
		GOO          = {
			name                    = [[Blob]],
			areaOfEffect            = 200,
			burst                   = 8,
			burstrate               = 0.033,
			projectiles             = 8,
			cegTag                  = [[queen_trail]],
			craterBoost             = 0,
			craterMult              = 0,
						
			customParams            = {
				light_radius = 0,
				armorpiercing = 0.2,
			},
						
			damage                  = {
				default = 750,
				planes  = 750,
			},

			explosionGenerator      = [[custom:large_green_goo]],
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			intensity               = 0.7,
			interceptedByShieldType = 1,
			noSelfDamage            = true,
			proximityPriority       = -4,
			range                   = 1000,
			reloadtime              = 6,
			rgbColor                = [[0.2 0.6 0]],
			size                    = 8,
			sizeDecay               = 0,
			soundStart              = [[chickens/bigchickenroar]],
			sprayAngle              = 6100,
			tolerance               = 5000,
			turret                  = true,
			weaponType              = [[Cannon]],
			waterWeapon             = true,
			weaponVelocity          = 600,
		},
		AEROSPORES  = {
			name                    = [[Anti-Air Spores]],
			areaOfEffect            = 200,
			avoidFriendly           = false,
			burst                   = 16,
			burstrate               = 1/30,
			canAttackGround         = false,
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			
			customParams            = {
				light_radius = 0,
				armorpiercing = 0.4,
			},
			
			damage                  = {
				default = 250/20,
				planes  = 250,
			},

			dance                   = 120,
			explosionGenerator      = [[custom:large_green_goo]],
			fireStarter             = 0,
			fixedlauncher           = 1,
			flightTime              = 5,
			groundbounce            = 1,
			heightmod               = 0.5,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 2,
			model                   = [[chickeneggblue.s3o]],
			noSelfDamage            = true,
			range                   = 1400,
			reloadtime              = 2,
			smokeTrail              = true,
			startVelocity           = 50,
			texture1                = [[]],
			texture2                = [[sporetrailblue]],
			tolerance               = 10000,
			tracks                  = true,
			turnRate                = 72000,
			turret                  = true,
			waterweapon             = true,
			weaponAcceleration      = 400,
			weaponType              = [[MissileLauncher]],
			weaponVelocity          = 2000,
			wobble                  = 96000,
		},
		SPORES       = {
			name                    = [[Spores]],
			areaOfEffect            = 96,
			avoidFriendly           = false,
			burst                   = 16,
			burstrate               = 2/30,
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			
			customParams            = {
				light_radius = 0,
				armorpiercing = 0.4,
			},

			damage                  = {
				default = 75,
			},

			dance                   = 90,
			explosionGenerator      = [[custom:green_goo]],
			fireStarter             = 0,
			fixedlauncher           = true,
			flightTime              = 5,
			groundbounce            = 1,
			heightmod               = 0.5,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 2,
			metalpershot            = 0,
			model                   = [[chickeneggpink.s3o]],
			noSelfDamage            = true,
			range                   = 1000,
			reloadtime              = 2,
			smokeTrail              = true,
			sprayangle              = 4096,
			startVelocity           = 50,
			texture1                = [[]],
			texture2                = [[sporetrail]],
			tolerance               = 10000,
			tracks                  = true,
			turnRate                = 24000,
			turret                  = true,
			waterweapon             = true,
			weaponAcceleration      = 200,
			weaponType              = [[MissileLauncher]],
			weaponVelocity          = 1000,
			wobble                  = 48000,
		},
		TIAMATBOMB   = {
			name                    = [[Tiamat Bomb]],
			accuracy                = 60000,
			areaOfEffect            = 72,
			avoidFeature            = false,
			avoidFriendly           = false,
			burnblow                = true,
			collideFriendly         = false,
			craterBoost             = 1,
			craterMult              = 2,
			
			customparams            = {
					spawns_name = "chicken_tiamat",
					spawns_expire = 300,
			},

			damage                  = {
				default = 350,
			},

			explosionGenerator      = [[custom:none]],
			fireStarter             = 70,
			flightTime              = 0,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 0,
			model                   = [[chickenbroodqueen.s3o]],
			projectiles             = 10,
			noSelfDamage            = true,
			range                   = 500,
			reloadtime              = 10,
			smokeTrail              = false,
			startVelocity           = 200,
			tolerance               = 8000,
			tracks                  = false,
			turnRate                = 4000,
			turret                  = true,
			waterweapon             = true,
			weaponAcceleration      = 200,
			weaponType              = [[AircraftBomb]],
			weaponVelocity          = 200,
		},

	},

} }
