return { chickenlandqueen = {
		name                   = "Chicken Queen",
		description            = "Clucking Hell!",
		acceleration           = 3.0,
		activateWhenBuilt      = true,
		autoHeal               = 0,
		brakeRate              = 18.0,
		builder                = false,
		buildPic               = "chickenflyerqueen.png",
		buildTime              = 360000,
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canSubmerge            = false,
		cantBeTransported      = true,
		category               = "LAND",
		collisionSphereScale   = 1,
		collisionVolumeOffsets = "0 160 30",
		collisionVolumeScales  = "175 175 520",
		collisionVolumeType    = "cylZ",

		customParams           = {
			chicken = "uwu",
			chicken_menace = "^w^",
			chicken_queen = "~w~",
			chicken_needs_bogus_defs = "something normal for once",
			selection_scale       = 2,
			
			aimposoffset   = "0 160 30",
			modelradius = 200,

			outline_x = 400,
			outline_y = 400,
			outline_yoff = 90,
			reveal_losunit = "los_superwep",
			reveal_onprogress = 0.1,
			model_rescale = 3,
			singuimmune = 1,
		},

		explodeAs              = "SMALL_UNITEX",
		footprintX             = 4,
		footprintZ             = 4,
		iconType               = "chickenq",
		idleAutoHeal           = 200,
		idleTime               = 300,
		leaveTracks            = true,
		health                 = 7000000,
		speed                  = 75,
		minCloakDistance       = 250,
		movementClass          = "TKBOT4",
		noAutoFire             = false,
		noChaseCategory        = "",
		objectName             = "chickenflyerqueen.s3o",
		power                  = 65536,
		reclaimable            = false,
		script                 = "chickenlandqueen.lua",
		selfDestructAs         = "SMALL_UNITEX",

		sfxtypes               = {

			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},

		},
		sightDistance          = 2048,
		trackOffset            = 18,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ChickenTrack",
		trackWidth             = 100,
		turnRate               = 480,
		upright                = true,
		workerTime             = 0,

		weapons                = {
			{
				def                = "FIREGOO",
				mainDir            = "0 0 1",
				maxAngleDif        = 150,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER",
			},
			{
				def                = "SPORES",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "AEROSPORES",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
			{
				def                = "HIGHSPORES",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},


		weaponDefs             = {
			FIREGOO    = {
				name                    = "Napalm Goo",
				areaOfEffect            = 256,
				burst                   = 8,
				burstrate               = 0.033,
				projectiles             = 8,
				cegTag                  = "queen_trail_fire",
				
				customParams            = {
					light_radius = 500,
					armorpiercing = 0.4,
					combatrange = 750,
				},
				
				craterBoost             = 0,
				craterMult              = 0,

				damage                  = {
					default = 400,
					planes  = 400,
				},

				explosionGenerator      = "custom:napalm_koda",
				firestarter             = 400,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				proximityPriority       = -4,
				range                   = 1440,
				reloadtime              = 6,
				rgbColor                = "0.8 0.4 0",
				size                    = 8,
				sizeDecay               = 0,
				soundHit                = "weapon/burn_mixed",
				soundStart              = "chickens/bigchickenroar",
				sprayAngle              = 6100,
				tolerance               = 5000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 720,
			},
			SPORES = {
				name                    = "Explosive Spores",
				areaOfEffect            = 192,
				avoidFriendly           = false,
				burst                   = 24,
				burstrate               = 1/30,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					light_radius = 0,
					armorpiercing = 0.4,
					combatrange = 750,
				},

				damage                  = {
					default = 400,
					planes  = 400,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_green_large",
				fireStarter             = 0,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickenegggreen_big.s3o",
				range                   = 1000,
				reloadtime              = 3,
				smokeTrail              = true,
				startVelocity           = 271,
				texture1                = "",
				texture2                = "sporetrail2",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 0.5,
				turnRate                = 20000,
				turret                  = true,
				waterweapon             = true,
				--weaponAcceleration      = 100,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 48000,
			},
			HIGHSPORES = {
				name                    = "Explosive Spores (alt)",
				areaOfEffect            = 192,
				avoidFriendly           = false,
				burst                   = 32,
				burstrate               = 1/30,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					light_radius = 0,
					armorpiercing = 0.4,
					combatrange = 750,
				},

				damage                  = {
					default = 400,
					planes  = 400,
				},

				dance                   = 90,
				explosionGenerator      = "custom:goo_v2_green_large",
				fireStarter             = 0,
				flightTime              = 5,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickenegggreen_big.s3o",
				range                   = 1000,
				reloadtime              = 4,
				smokeTrail              = true,
				startVelocity           = 271,
				texture1                = "",
				texture2                = "sporetrail2",
				tolerance               = 10000,
				tracks                  = true,
				trajectoryHeight        = 1.5,
				turnRate                = 20000,
				turret                  = true,
				waterweapon             = true,
				--weaponAcceleration      = 100,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 271,
				wobble                  = 48000,
			},
			AEROSPORES  = {
				name                    = "Anti-Air Spores",
				areaOfEffect            = 200,
				avoidFriendly           = false,
				burst                   = 30,
				burstrate               = 2/30,
				canAttackGround         = false,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					light_radius = 0,
					armorpiercing = 0.4,
					isaa = ">w<",
					combatrange = 750,
				},

				damage                  = {
					default  = 1200,
				},

				dance                   = 120,
				explosionGenerator      = "custom:goo_v2_blue_large",
				explosionScar           = false,
				fireStarter             = 0,
				fixedlauncher           = 1,
				flightTime              = 3,
				groundbounce            = 1,
				heightmod               = 0.5,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "chickeneggblue.s3o",
				noSelfDamage            = true,
				range                   = 2600,
				reloadtime              = 3,
				smokeTrail              = true,
				startVelocity           = 300,
				texture1                = "",
				texture2                = "sporetrailblue",
				tolerance               = 10000,
				tracks                  = true,
				turnRate                = 72000,
				turret                  = true,
				waterweapon             = true,
				weaponAcceleration      = 150,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 2000,
				wobble                  = 96000,
			},
		},

	}
}
