return {
	chicken_sporeshooter = {
		name                = "Sporeshooter",
		description         = "All-Terrain Spores (Anti-Air/Skirm)",
		acceleration        = 1.08,
		activateWhenBuilt   = true,
		brakeRate           = 1.23,
		builder             = false,
		buildPic            = "chicken_sporeshooter.png",
		buildTime           = 2250,
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		category            = "LAND",

		customParams        = {
			chicken = "uwu",
			chicken_shield = ">w<",
			chicken_needs_bogus_defs = "^w^",
			
			outline_x = 130,
			outline_y = 130,
			outline_yoff = 30,
			model_rescale = 1.8,
			singuimmune = 1,
			chicken_spawncost = 3900,
		},

		explodeAs           = "NOWEAPON",
		footprintX          = 3,
		footprintZ          = 3,
		health              = 17500,
		iconType            = "spiderskirm",
		idleAutoHeal        = 20,
		idleTime            = 300,
		leaveTracks         = true,
		maxSlope            = 90,
		waterline           = 22,
		movementClass       = "ATKBOT4",
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM SATELLITE STUPIDTARGET",
		objectName          = "chicken_sporeshooter.s3o",
		reclaimable         = false,
		selfDestructAs      = "NOWEAPON",

		sfxtypes            = {
			explosiongenerators = {
				"custom:blood_spray",
				"custom:blood_explode",
				"custom:dirt",
			},
		},
		sightDistance       = 512,
		sonarDistance       = 512,
		script              = "chicken_sporeshooter.lua",
		speed               = 162,
		trackOffset         = 0.5,
		trackStrength       = 9,
		trackStretch        = 1,
		trackType           = "ChickenTrackPointy",
		trackWidth          = 70,
		turnRate            = 1440,
		upright             = false,
		workerTime          = 0,

		weapons             = {
			{
				def                = "FLAMETHROWER",
				mainDir            = "0 0 1",
				maxAngleDif        = 90,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP SUB HOVER FIXEDWING GUNSHIP",
			},
			{
				def = "SHIELD",
			},
		},

		weaponDefs          = {
			FLAMETHROWER = {
				name                    = "Primordial Fire",
				areaOfEffect            = 64,
				avoidGround             = false,
				avoidFeature            = false,
				avoidFriendly           = true,
				collideFeature          = false,
				collideGround           = false,
				coreThickness           = 0,
				craterBoost             = 0,
				craterMult              = 0,
				cegTag                  = "superflamer",
				customParams            = {
					flamethrower = "1",
					setunitsonfire = "1",
					burnchance = "1", -- Per-impact
					burntime = "1000",
					light_camera_height = 2800,
					light_color = "0.01 1.000 0.705",
					light_radius = 260,
					light_fade_time = 10,
					light_beam_mult_frames = 5,
					light_beam_mult = 5,
					armorpiercing = 0.3,
				},
				damage                  = {
					default = 50,
				},
				duration                = 0.01,
				explosionGenerator      = "custom:SMOKE",
				fallOffRate             = 1,
				fireStarter             = 100,
				heightMod               = 1,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 0.3,
				interceptedByShieldType = 1,
				leadLimit               = 10,
				noExplode               = true,
				noSelfDamage            = true,
				range                   = 588,
				reloadtime              = 2/30,
				rgbColor                = "0.01 1.000 0.705",
				size                    = 12,
				soundHit                = "flamethrowerhit",
				soundStart              = "flamethrowerfire",
				soundStart              = "weapon/flamethrower",
				soundTrigger            = true,
				sprayangle              = 1000,
				texture1                = "flame",
				thickness               = 0,
				tolerance               = 5000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "LaserCannon",
				weaponVelocity          = 840,
			},
			SHIELD      = {
				name                    = "Shield",
				craterMult              = 0,

				customParams            = {
					unlinked = true,
				},

				damage                  = {
					default = 5,
				},

				exteriorShield          = true,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				shieldAlpha             = 0.15,
				shieldBadColor          = "1.0 1 0.1 1",
				shieldGoodColor         = "0.1 1.0 0.1 1",
				shieldInterceptType     = 3,
				shieldPower             = 28400,
				shieldPowerRegen        = 360,
				shieldPowerRegenEnergy  = 0,
				shieldRadius            = 250,
				shieldRepulser          = false,
				shieldStartingPower     = 16400,
				smartShield             = true,
				visibleShield           = false,
				visibleShieldRepulse    = false,
				--texture1                = "wakelarge",
				--visibleShield           = true,
				--visibleShieldHitFrames  = 30,
				--visibleShieldRepulse    = false,
				weaponType              = "Shield",
			},
		},
	}
}
