return { 
	cloakjammer = {
		unitname               = "cloakjammer",
		name                   = "Iris",
		description            = "Area Cloaker/Jammer Walker",
		acceleration           = 0.75,
		activateWhenBuilt      = true,
		brakeRate              = 4.5,
		buildCostMetal         = 500,
		buildPic               = "cloakjammer.png",
		canMove                = true,
		category               = "LAND UNARMED",
		corpse                 = "DEAD",
		customParams           = {
			morphto = "staticjammer",
			morphtime = 5,
			area_cloak = 1,
			area_cloak_upkeep = 5,
			area_cloak_radius = 450,
			area_cloak_decloak_distance = 150,
			priority_misc = 1,
			cus_noflashlight = 1,
		},
		energyUse              = 5,
		explodeAs              = "BIG_UNITEX",
		footprintX             = 2,
		footprintZ             = 2,
		iconType               = "kbotjammer",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		leaveTracks            = true,
		health                 = 2000,
		maxSlope               = 36,
		speed                  = 2.5,
		minCloakDistance       = 100,
		movementClass          = "AKBOT2",
		objectName             = "spherecloaker.s3o",
		onoffable              = true,
		pushResistant          = 0,
		script                 = "cloakjammer.lua",
		radarDistanceJam       = 450,
		selfDestructAs         = "BIG_UNITEX",
		sightDistance          = 450,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ComTrack",
		trackWidth             = 18,
		turnRate               = 2520,
		featureDefs            = {
			DEAD = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "eraser_d.dae",
			},
			HEAP = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2a.s3o",
			},
		},

	} 
}
