return { 
	cloakriot = {
		unitname               = "cloakriot",
		name                   = "Assailant",
		description            = "Stealthy Machine Gun Bot",
		acceleration           = 0.54,
		brakeRate              = 2.25,
		buildCostMetal         = 260,
		buildPic               = "cloakriot.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canCloak			   = true,
		category               = "LAND",
		collisionVolumeOffsets = "0 1 -1",
		collisionVolumeScales  = "35 45 35",
		collisionVolumeType    = "cylY",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "68 68 68",
		selectionVolumeType    = "ellipsoid",
		corpse                 = "DEAD",
		stealth = true,
		activateWhenBuilt = true,
		initCloaked = true,
		cloakCostMoving = 3,
		cloakCost    = 0.3,
		customParams           = {
			modelradius       = "7",
			cus_noflashlight  = 1,
			selection_scale   = 0.85,
			aim_lookahead     = 120,
			cloakregen		  = 15,
			recloaktime 	  = 300,
			cloaker_bestowed_radius = 92,
			outline_x = 80,
			outline_y = 80,
			outline_yoff = 15.5,
			needsfirecontrol = 1,
			cloakstrikeduration = 60,
			cloakstrikespeed = 1.33,
			cloakstrikeslow = 0.85,
		},
		explodeAs              = "SMALL_UNITEX",
		footprintX             = 3,
		footprintZ             = 3,
		iconType               = "kbotriot",
		leaveTracks            = true,
		health                 = 1200,
		maxSlope               = 36,
		speed                  = 2.9,
		maxReverseVelocity     = 2.9,
		maxWaterDepth          = 22,
		minCloakDistance       = 230,
		movementClass          = "KBOT3",
		noChaseCategory        = "TERRAFORM FIXEDWING SUB",
		objectName             = "Spherewarrior.dae",
		script                 = "cloakriot.lua",
		selfDestructAs         = "SMALL_UNITEX",
		sfxtypes               = {
			explosiongenerators = {
				"custom:RAIDMUZZLE",
				"custom:emg_shells_l",
			},
		},
		sightDistance          = 500,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 0.8,
		trackType              = "ComTrack",
		trackWidth             = 20,
		turnRate               = 1377,
		upright                = true,
		weapons                = {
			{
				def                = "WARRIOR_WEAPON",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs             = {
			WARRIOR_WEAPON = {
				name                    = "Heavy Chaingun",
				accuracy                = 1000,
				alphaDecay              = 0.7,
				areaOfEffect            = 96,
				burnblow                = false,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					light_camera_height = 1600,
					light_color = "0.8 0.76 0.38",
					light_radius = 30,
					script_reload = "0.6",
					sweepfire = 1,
					sweepfire_maxangle = 30,
					sweepfire_step = 3,
					sweepfire_maxrangemult = 0.95,
					recycler = 1,
					recycle_reductiontime = 0.1,
					recycle_reduction = 0.1,
					recycle_bonus = 0.4,
					recycle_reductionframes = 0.5,
					recycle_maxbonus = 18,
					isFlak = 3,
					flaktime = 5,
					cloakstrike = 1.5,
				},
				damage                  = {
					default = 41.61,
				},
				edgeEffectiveness       = 0.5,
				explosionGenerator      = "custom:EMG_HIT_HE",
				firestarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 310,
				reloadtime              = 1/30,
				mygravity				= 0.02,
				rgbColor                = "1 0.95 0.4",
				separation              = 0.67,
				soundHit                = "weapon/cannon/emg_hit",
				soundStart              = "weapon/sd_emgv7",
				stages                  = 18,
				size					= 0.9,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 950,
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "spherewarrior_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris3x3a.s3o",
			},
		},
	} 
}
