-- Original UnitDef by Tankium

return { 
	dronecarry = {
		unitname            = "dronecarry",
		name                = "Gull",
		description         = "Carrier Drone",
		acceleration        = 0.3,
		airHoverFactor      = 4,
		brakeRate           = 0.24,
		buildCostMetal      = 75,
		builder             = false,
		buildPic            = "dronecarry.png",
		canBeAssisted       = false,
		canFly              = true,
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		canSubmerge         = false,
		category            = "GUNSHIP DRONE",
		collisionVolumeOffsets   = "0 0 0",
		collisionVolumeScales    = "26 26 26",
		collisionVolumeType      = "ellipsoid",
		collide             = false,
		cruiseAlt           = 100,
		explodeAs           = "TINY_BUILDINGEX",
		floater             = true,
		footprintX          = 2,
		footprintZ          = 2,
		hoverAttack         = true,
		iconType            = "smallgunship",
		maneuverleashlength = "5000",
		idleAutoHeal        = 10,
		idleTime            = 180,
		health              = 460,
		speed               = 8.56,
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM FIXEDWING SATELLITE SUB",
		objectName          = "carrydrone.s3o",
		reclaimable         = false,
		repairable          = false, -- mostly not to waste constructor attention on area-repair; has regen anyway
		script              = "dronecarry.lua",
		selfDestructAs      = "TINY_BUILDINGEX",
		customParams        = {
			bait_level_target      = 1,
			is_drone = 1,
			modelradius    = "13",
		},
		sfxtypes            = {
			explosiongenerators = {
				"custom:brawlermuzzle",
				"custom:emg_shells_m",
			},
		},
		sightDistance       = 500,
		turnRate            = 792,
		upright             = true,
		weapons                = {
			{
				def                = "STORM_ROCKET",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER",
			},
			{
				def                = "GAUSSREPEATER",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
			   def                = "ARMRL_MISSILE",
			   --badTargetCategory  = "HOVER SWIM LAND SINK FLOAT SHIP",
			   onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
		    },
			{
				def                = "SHIELD",
			},
		},
		weaponDefs             = {
			STORM_ROCKET = {
				name                    = "Neptune Anti-Ship Rocket",
				areaOfEffect            = 90,
				cegTag                  = "rocket_trail_bar_flameboosted",
				craterBoost             = 1,
				craterMult              = 2,
				customParams        = {
					burst = Shared.BURST_RELIABLE,
					light_camera_height = 1800,
				},
				damage                  = {
					default = 100,
				},
				explosionGenerator      = "custom:xamelimpact",
				fireStarter             = 70,
				flightTime              = 3.5,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 2,
				model                   = "wep_m_hailstorm.s3o",
				noSelfDamage            = true,
				predictBoost            = 0.75,
				range                   = 540,
				reloadtime              = 6,
				smokeTrail              = false,
				soundHit                = "weapon/missile/ex_med4",
				soundHitVolume          = 8,
				soundStart              = "weapon/missile/missile2_fire_bass",
				soundStartVolume        = 7,
				startVelocity           = 192,
				trajectoryHeight        = 1.25,
				turnrate                = 12000,
				turret                  = true,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 600,
				weaponAcceleration		= 145,
			},
			GAUSSREPEATER = {
				name                    = "Gauss Repeater",
				alphaDecay              = 0.12,
				areaOfEffect            = 16,
				avoidfeature            = false,
				bouncerebound           = 0.15,
				bounceslip              = 1,
				cegTag                  = "gauss_tag_l",
				craterBoost             = 0,
				craterMult              = 0,
			
				customParams            = {
					is_unit_weapon = 1,
					slot = "5",
					muzzleEffectFire = "custom:flashmuzzle1",
					reaim_time = 1,
					antibaitbypass = "ärsytät minua",
				},
			
				damage                  = {
					default = 25.1,
				},
			
				explosionGenerator      = "custom:gauss_hit_m",
				groundbounce            = 1,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				noExplode               = true,
				noSelfDamage            = true,
				numbounce               = 10,
				range                   = 380,
				reloadtime              = 0.5,
				rgbColor                = "0.5 1 1",
				separation              = 0.5,
				size                    = 0.8,
				sizeDecay               = -0.25,
				soundHit                = "weapon/gauss_hit",
				soundHitVolume          = 3,
				soundStart              = "weapon/cannon/gauss_rapid.wav",
				soundStartVolume        = 2.5,
				stages                  = 32,
				turret                  = true,
				waterweapon				= true,
				weaponType              = "Cannon",
				weaponVelocity          = 2200,
			},
			ARMRL_MISSILE = {
				name                    = "Light Missiles",
				areaOfEffect            = 8,
				avoidFeature            = true,
				cegTag                  = "missiletrailyellow",
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting       = 5,
				customParams            = {
					burst = Shared.BURST_RELIABLE,
					isaa = "1",
					light_camera_height = 2000,
					light_radius = 200,
				},
				damage                  = {
					default = 50.1,
				},
				explosionGenerator      = "custom:FLASH2",
				fireStarter             = 70,
				flightTime              = 4,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 2,
				metalpershot            = 0,
				model                   = "hobbes.s3o",
				noSelfDamage            = true,
				range                   = 610,
				reloadtime              = 2,
				smokeTrail              = true,
				soundHit                = "explosion/ex_med12",
				soundStart              = "weapon/missile/missile_fire7",
				startVelocity           = 500,
				texture2                = "lightsmoketrail",
				tolerance               = 10000,
				tracks                  = true,
				turnRate                = 60000,
				turret                  = true,
				weaponAcceleration      = 300,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 750,
		    },
			SHIELD = {
				name                    = "Energy Shield",	
				damage                  = {	
					default = 10,	
				},	
				exteriorShield          = true,	
				shieldAlpha             = 0.2,	
				shieldBadColor          = "1 0.1 0.1 1",	
				shieldGoodColor         = "0.1 0.1 1 1",	
				shieldInterceptType     = 3,	
				shieldPower             = 850,	
				shieldPowerRegen        = 6,	
				shieldPowerRegenEnergy  = 0.1,	
				shieldRadius            = 40,	
				shieldRepulser          = false,	
				shieldStartingPower     = 550,	
				smartShield             = true,	
				visibleShield           = false,	
				visibleShieldRepulse    = false,	
				weaponType              = "Shield",	
			},
		},
	} 
}
