return { 
	droneassault = {
		unitname            = "droneassault",
		name                = "Python",
		description         = "Cannon Drone",
		acceleration        = 0.3,
		airHoverFactor      = 4,
		brakeRate           = 0.24,
		buildCostMetal      = 75,
		builder             = false,
		buildPic            = "droneassault.png",
		canBeAssisted       = false,
		canFly              = true,
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		canSubmerge         = false,
		category            = "GUNSHIP DRONE",
		collide             = false,
		cruiseAlt           = 120,
		explodeAs           = "TINY_BUILDINGEX",
		floater             = true,
		footprintX          = 2,
		footprintZ          = 2,
		hoverAttack         = true,
		iconType            = "fighter",
		idleAutoHeal        = 10,
		idleTime            = 300,
		maxDamage           = 1050,
		maxVelocity         = 4.5,
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM SATELLITE SUB",
		objectName          = "assaultdrone.dae",
		reclaimable         = false,
		repairable          = false, -- mostly not to waste constructor attention on area-repair; has regen anyway
		refuelTime          = 10,
		script              = "droneassault.lua",
		selfDestructAs      = "TINY_BUILDINGEX",
		customParams        = {
			bait_level_target      = 1,
			is_drone = 1,
		},
		sfxtypes            = {
			explosiongenerators = {},
		},
		sightDistance       = 600,
		turnRate            = 792,
		upright             = true,
		weapons             = {
			{
				def                = "CANNON",
				badTargetCategory  = "FIXEDWING",
				mainDir            = "0 0 1",
				maxAngleDif        = 90,
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs          = {
			CANNON      = {
				name                    = "Cannon",
				areaOfEffect            = 32,
				avoidFeature            = true,
				avoidFriendly           = true,
				damage                  = {
					default = 300.1,
				},
				explosionGenerator      = "custom:FLASH64",
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 310,
				reloadtime              = 2,
				soundHit                = "weapon/cannon/generic_cannon",
				soundStart              = "weapon/cannon/outlaw_gun",
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 650,
			},
		},
	} 
}
