local dronecarry = {
	unitname            = "dronecarry",
	name                = "Coatl",
	description         = "Carrier Drone",
	acceleration        = 0.3,
	airHoverFactor      = 4,
	brakeRate           = 0.24,
	buildCostMetal      = 5,
	builder             = false,
	buildPic            = "dronecarry.png",
	canBeAssisted       = false,
	canFly              = true,
	canGuard            = true,
	canMove             = true,
	canPatrol           = true,
	canSubmerge         = false,
	category            = "GUNSHIP DRONE",
	collisionVolumeOffsets   = "0 0 0",
	collisionVolumeScales    = "26 26 26",
	collisionVolumeType      = "ellipsoid",
	collide             = false,
	cruiseAlt           = 100,
	explodeAs           = "TINY_BUILDINGEX",
	floater             = true,
	footprintX          = 2,
	footprintZ          = 2,
	hoverAttack         = true,
	iconType            = "smallgunship",
	maneuverleashlength = "5000",
	idleAutoHeal        = 10,
	idleTime            = 180,
	health              = 1160,
	speed               = 256.8,
	noAutoFire          = false,
	noChaseCategory     = "TERRAFORM FIXEDWING SATELLITE SUB",
	objectName          = "carrydrone.s3o",
	reclaimable         = false,
	repairable          = false, -- mostly not to waste constructor attention on area-repair; has regen anyway
	script              = "dronecarry.lua",
	selfDestructAs      = "TINY_BUILDINGEX",
	customParams        = {
		bait_level_target      = 1,
		is_drone = 1,
		modelradius    = "13",
	},
	sfxtypes            = {
		explosiongenerators = {
			"custom:brawlermuzzle",
			"custom:emg_shells_m",
		},
	},
	sightDistance       = 500,
	turnRate            = 792,
	upright             = true,
	weapons                = {
		{
			def                = "SKYWANCE",
			badTargetCategory  = "FIXEDWING",
			onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
		},
		{
			def                = "SHIELD",
		},
	},
	weaponDefs             = {
		SKYWANCE = {
			name                    = "Skylance",
			areaOfEffect            = 16,
			accuracy				= 250,
			coreThickness           = 0.8,
			beamTime                = 2/30,
			craterBoost             = 0,
			craterMult              = 0,
			customParams        = {
				light_camera_height = 1200,
				light_radius = 60,
				light_color = "0.078 0.5803 0.89019",
				extra_damage = 25,
			},
			damage                  = {
				default = 10,
			},
			duration                = 3/30,
			explosionGenerator      = "custom:ion_beam",
			fireStarter             = 100,
			impactOnly              = true,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 1,
			noSelfDamage            = true,
			paralyzeTime			= 5,
			range                   = 500,
			reloadtime              = 2/30,
			texture1                = "ecmnoise",
			rgbColor                = "0.078 0.5803 0.89019",
			rgbColor2				= "0.1176 0.4705 0.6902",
			soundStart              = "weapon/laser/ion_burn",
			soundstartvolume	    = 0.1,
			thickness               = 3,
			tolerance               = 10000,
			turret                  = true,
			waterWeapon             = true,
			weaponType              = "BeamLaser",
			weaponVelocity          = 880,
		},
		SHIELD = {
			name                    = "Energy Shield",	
			damage                  = {	
				default = 10,	
			},	
			exteriorShield          = true,	
			shieldAlpha             = 0.2,	
			shieldBadColor          = "1 0.1 0.1 1",	
			shieldGoodColor         = "0.1 0.1 1 1",	
			shieldInterceptType     = 3,	
			shieldPower             = 1550,
			shieldPowerRegen        = 6,	
			shieldPowerRegenEnergy  = 0.1,	
			shieldRadius            = 40,	
			shieldRepulser          = false,	
			shieldStartingPower     = 1550,
			smartShield             = true,	
			visibleShield           = false,	
			visibleShieldRepulse    = false,	
			weaponType              = "Shield",	
		},
	},
}

return {dronecarry = dronecarry}
