return { 
	factorytank = {
		unitname                      = "factorytank",
		name                          = "Tank Foundry",
		description                   = "Armed Tank Production Facility",
		buildCostMetal                = Shared.FACTORY_COST,
		buildDistance                 = Shared.FACTORY_PLATE_RANGE,
		builder                       = true,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 11,
		buildingGroundDecalSizeY      = 11,
		buildingGroundDecalType       = "factorytank_aoplane.dds",
		buildoptions                  = {
			"tankcon",
			"tankraid",
			"tankheavyraid",
			"tankriot",
			"tankassault",
			"tankheavyassault",
			"tankarty",
			"tankheavyarty",
			"tankaa",
		},
		buildPic                      = "factorytank.png",
		canMove                       = true,
		canPatrol                     = true,
		category                      = "SINK UNARMED",
		corpse                        = "DEAD",
		collisionVolumeOffsets        = "0 0 -25",
		collisionVolumeScales         = "110 28 44",
		collisionVolumeType           = "box",
		selectionVolumeOffsets        = "0 0 10",
		selectionVolumeScales         = "120 28 120",
		selectionVolumeType           = "box",
		customParams                  = {
			sortName = "6",
			solid_factory = "4",
			default_spacing = 8,
			aimposoffset   = "0 15 -35",
			midposoffset   = "0 15 -10",
			modelradius    = "100",
			unstick_help   = 1,
			selectionscalemult = 1,
			factorytab       = 1,
			shared_energy_gen = 1,
			parent_of_plate   = "platetank",
			nanoregen = 15,
			nano_maxregen = 6,
			aim_lookahead = 80,
			outline_x = 250,
			outline_y = 250,
			outline_yoff = 5,
		},
		energyUse                     = 0,
		explodeAs                     = "LARGE_BUILDINGEX",
		footprintX                    = 8,
		footprintZ                    = 8,
		iconType                      = "factank",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		levelGround                   = false,
		health                        = 9500,
		maxSlope                      = 15,
		maxWaterDepth                 = 0,
		moveState                     = 1,
		noAutoFire                    = false,
		objectName                    = "factorytank.s3o",
		script                        = "factorytank.lua",
		selfDestructAs                = "LARGE_BUILDINGEX",
		showNanoSpray                 = false,
		sightDistance                 = 750,
		useBuildingGroundDecal        = true,
		workerTime                    = Shared.FACTORY_BUILDPOWER,
		yardMap                       = "oooooooo oooooooo oooooooo oooooooo yccccccy yccccccy yccccccy yccccccy",
		weapons             = {
			{
				def                = "CANNON",
				--maxAngleDif        = 45,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
			},
		},
		weaponDefs          = {
			CANNON = {
				name                    = "Fragmentation Shell",
				accuracy                = 0,
				areaOfEffect            = 32,
				avoidFeature            = false,
				avoidFriendly           = false,
				avoidGround             = true,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					restrict_in_widgets = 1,
					-- light_color = "3 2.33 1.5", Not quite sure which ones are intentionally supposed to be here.
					-- light_radius = 150,			 Usually the last index is whats set at runtime, so i'll just leave it as commented out for future reference?
					light_camera_height = 3500,
					light_color = "0.75 0.4 0.15",
					light_radius = 220,
					numprojectiles1 = 20,
					projectile1 = "factorytank_fragment_dummy",
					velspread1 = "1.59, 3, 1.59, _, 5, _",
					noairburst = "March of progress",
					onexplode = "The unity prevails",
					shield_damage = (100*20) + 1200,
					stats_shield_damage = (100*20) + 1200,
				},
				damage                  = {
					default = 1200.2,
				},
				explosionGenerator      = "custom:DOT_Pillager_Explo",
				fireTolerance           = 1820, -- 10 degrees
				impulseBoost            = 0.5,
				impulseFactor           = 0.2,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 600,
				reloadtime              = 4.7,
				rgbColor                = "0.2 0.2 0.2",
				soundHit                = "weapon/cannon/frag_impact",
				soundStart              = "explosion/ex_large5",
				size                    = 8,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 880,
			},
			FRAGMENT_DUMMY = {
				name                    = "Plasma Bomblet",
				accuracy                = 400,
				areaOfEffect            = 162,
				avoidFeature            = false,
				craterBoost             = 1,
				craterMult              = 2,
				--cegTag                  = "flamer",
				customParams              = {
					numprojectiles1 = 1,
					projectile1 = "factorytank_final",
					keepmomentum1 = 1,
					noairburst = "Burning time",
					timeddeploy = 12,
					light_camera_height = 2500,
					light_color = "0.25 0.13 0.05",
					light_radius = 500,
					shield_damage = 35,
				},
				damage                  = {
					default = 0,
				},
				--explosionGenerator      = "custom:napalm_firewalker_small",
				firestarter             = 180,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				myGravity               = 0.25,
				noExplode               = true,
				projectiles             = 10,
				range                   = 900,
				reloadtime              = 12,
				rgbColor                = "1 0.95 0.4",
				size 					= 2,
				soundHit                = "nosound",
				soundStart              = "weapon/cannon/frag_impact",
				soundStartVolume        = 3.2,
				sprayangle              = 2500,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 320,
			},
			FINAL = {
				name                    = "Plasma Flechette",
				--cegTag                  = "flak_trail",
				areaOfEffect            = 96,
				alphaDecay              = 0.7,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					light_camera_height = 2000,
					light_color = "1 0.2 0.2",
					isaa = "1",
					isFlak = 3,
					flaktime = 15,
				},
				damage = {
					default = 100.1,
				},
				edgeEffectiveness       = 0.8,
				explosionGenerator      = "custom:EMG_HIT_HE",
				fireStarter             = 50,
				heightMod               = 1,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				range                   = 300,
				reloadtime              = 0.8,
				rgbColor                = "1 0.95 0.4",
				soundHit                = "weapon/cannon/emg_hit",
				soundHitVolume	        = 0.4,
				sprayangle              = 1500,
				size 					= 2,
				thickness               = 2,
				tolerance               = 10000,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 880,
			},
		},
		featureDefs                   = {
			DEAD = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 8,
				footprintZ       = 8,
				object           = "factorytank_dead.s3o",
				collisionVolumeOffsets = "0 14 -34",
				collisionVolumeScales  = "110 28 44",
				collisionVolumeType    = "box",
			},
			HEAP = {
				blocking         = false,
				footprintX       = 6,
				footprintZ       = 6,
				object           = "debris4x4a.s3o",
			},
		},
	} 
}
