return { 
	factorysub = {
		unitname               = "factorysub",
		name                   = "Sub Pen",
		description            = "Produces Submarines",
		buildCostMetal         = Shared.FACTORY_COST,
		buildDistance          = Shared.FACTORY_PLATE_RANGE,
		builder                = true,
		buildoptions           = {
			"subraid",
			"subarty",
			"subscout",
			"subtacmissile",
		},
		buildPic               = "FACTORYSHIP.png",
		canMove                = true,
		canPatrol              = true,
		category               = "SUB FIREPROOF",
		collisionVolumeOffsets = "-22 5 0",
		collisionVolumeScales  = "48 48 276",
		collisionVolumeType    = "cylZ",
		selectionVolumeOffsets = "18 0 0",
		selectionVolumeScales  = "130 50 184",
		selectionVolumeType    = "box",
		corpse                 = "DEAD",
		customParams           = {
			sortName       = "7",
			unstick_help   = 1,
			aimposoffset   = "60 0 -15",
			midposoffset   = "0 0 -15",
			solid_factory = "3",
			modelradius    = "100",
			solid_factory_rotation = "1", -- 90 degrees counter clockwise
			default_spacing = 8,
			factorytab       = 1,
			shared_energy_gen = 1,
			cus_noflashlight = 1,
			--parent_of_plate   = "platesub",
			outline_x = 340,
			outline_y = 340,
			outline_yoff = 25,
			buggeroff_offset    = 0,
			buggeroff_radius    = 42,
		},
		energyUse              = 0,
		explodeAs              = "LARGE_BUILDINGEX",
		footprintX             = 8,
		footprintZ             = 12,
		iconType               = "facship",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		maxDamage              = 7200,
		maxSlope               = 15,
		minCloakDistance       = 150,
		minWaterDepth          = 21,
		moveState              = 1,
		objectName             = "subfactory.dae",
		script                 = "factorysub.lua",
		selfDestructAs         = "LARGE_BUILDINGEX",
		showNanoSpray          = false,
		sightDistance          = 700,
		waterline              = 60,
		workerTime             = Shared.FACTORY_BUILDPOWER,
		yardMap                = "oocccccc oocccccc oocccccc oocccccc oocccccc oocccccc oocccccc oocccccc oocccccc oocccccc oocccccc oocccccc",
		weapons             = {
			{
				def                = "TORPEDO",
				--maxAngleDif        = 45,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
			},
		},
		weaponDefs             = {
			TORPEDO = {
				name                    = "Stingray Torpedo",
				areaOfEffect            = 16,
				avoidFriendly           = false,
				burnblow                = true,
				canattackground         = false,
				collideFriendly         = false,
				cegtag				    = "serpent_trail",
				craterBoost             = 0,
				craterMult              = 0,
				customParams			= {
					reveal_unit = 6,
					cruisealt = -10,
					cruisetracking = 1,
					cruise_nolock = 1,
					cruisedist = 140,
				},
				damage                  = {
					default = 900.5,
				},
				explosionGenerator      = "custom:serpent_hit",
				fireSubmersed           = true,
				flightTime              = 20,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				leadlimit               = 0,
				model                   = "wep_t_barracuda.s3o",
				range                   = 600,
				reloadtime              = 8,
				soundHit                = "weapon/torpedo/torparty_hit",
				soundHitVolume          = 20,
				soundStart              = "weapon/torpedo/torplaunch_underwater",
				soundStartVolume        = 40,
				startVelocity           = 150,
				tolerance               = 32767,
				tracks                  = true,
				turnRate                = 3800,
				turret                  = true,
				waterWeapon             = true,
				weaponAcceleration      = 25,
				weaponType              = "TorpedoLauncher",
				weaponVelocity          = 120,
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = false,
				featureDead      = "HEAP",
				footprintX       = 9,
				footprintZ       = 14,
				object           = "seafac_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 8,
				footprintZ       = 8,
				object           = "debris4x4c.s3o",
			},
		},
	}
}
