return { 
	factoryplane = {
		unitname                      = "factoryplane",
		name                          = "Airplane Plant",
		description                   = "Produces Airplanes",
		activateWhenBuilt             = false,
		buildCostMetal                = Shared.FACTORY_COST,
		buildDistance                 = Shared.FACTORY_PLATE_RANGE,
		builder                       = true,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 11,
		buildingGroundDecalSizeY      = 11,
		buildingGroundDecalType       = "factoryplane_aoplane.dds",
		buildoptions                  = {
			"planecon",
			"planefighter",
			"planeheavyfighter",
			"bomberprec",
			"bomberstrike",
			"bomberriot",
			"bomberdisarm",
			"bomberheavy",
			"planescout",
			"planelightscout",
		},
		buildPic                      = "factoryplane.png",
		canMove                       = true,
		canPatrol                     = true,
		category                      = "FLOAT UNARMED",
		collisionVolumeOffsets        = "0 -8 -25",
		collisionVolumeScales         = "110 46 0",
		collisionVolumeType           = "cylX",
		corpse                        = "DEAD",
		customParams                  = {
			pad_count = 1,
			landflystate   = "1",
			sortName = "4",
			modelradius    = "51", -- at 50 planefighter won't respond to Bugger Off calls
			factory_land_state = 1,
			aimposoffset   = "0 23 -25",
			midposoffset   = "0 20 0",
			default_spacing = 8,
			factorytab       = 1,
			pad_bp           = 30,
			shared_energy_gen = 1,
			ispad         = 1,
			parent_of_plate   = "plateplane",
			outline_x = 250,
			outline_y = 250,
			outline_yoff = 5,
			buggeroff_radius    = 40,
			buggeroff_offset    = 15,
		},
		energyUse                     = 0,
		explodeAs                     = "LARGE_BUILDINGEX",
		fireState                     = 0,
		footprintX                    = 8,
		footprintZ                    = 7,
		iconType                      = "facair",
		health                        = 5600,
		maxSlope                      = 15,
		speed                         = 0,
		minCloakDistance              = 150,
		noAutoFire                    = false,
		objectName                    = "CORAP.s3o",
		script                        = "factoryplane.lua",
		selfDestructAs                = "LARGE_BUILDINGEX",
		showNanoSpray                 = false,
		sightDistance                 = 500,
		useBuildingGroundDecal        = true,
		waterline                     = 0,
		workerTime                    = Shared.FACTORY_BUILDPOWER,
		weapons					= {
			{
				def					= "MISSILE",
				onlyTargetCategory	= "GUNSHIP FIXEDWING",
			},
		},
		weaponDefs             = {
			MISSILE = {
				name					= "AA Launcher",
				areaOfEffect			= 48,
				avoidFriendly			= false,
				canAttackGround			= false,
				collideFriendly			= false,
				cegTag					= "missiletrailblue",
				craterBoost				= 0,
				craterMult				= 0,
				cylinderTargeting		= 1,
				customParams			= {
					isaa					= "1",
					light_color				= "0.5 0.6 0.6",
					light_radius			= 75,
				},
				dance					= 55,
				damage					= {
					default					= 375.1,
				},
				explosionGenerator		= "custom:FLASH2",
				fireStarter				= 70,
				flightTime				= 16,
				impactOnly				= false,
				impulseBoost			= 0,
				impulseFactor			= 0,
				interceptedByShieldType	= 1,
				model					= "wep_m_phoenix.s3o",
				noSelfDamage			= true,
				range					= 1400,
				reloadtime				= 94/30,
				smokeTrail				= true,
				soundHit				= "weapon/missile/rocket_hit",
				soundStart				= "weapon/missile/large_missile_fire",
				startVelocity			= 350,
				texture2				= "AAsmoketrail",
				fireTolerance 			= 65000,
				tolerance				= 65000,
				tracks					= true,
				turnRate				= 23000,
				turret					= true,
				weaponAcceleration		= 200,
				weaponType				= "MissileLauncher",
				weaponVelocity			= 950,
			},
		},
		yardMap                       = "oooooooo oooooooo oooooooo occooooo occooooo oooooooo oooooooo",
		featureDefs                   = {
			DEAD = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 7,
				footprintZ       = 6,
				object           = "corap_dead.s3o",
			},
			HEAP = {
				blocking         = false,
				footprintX       = 6,
				footprintZ       = 6,
				object           = "debris4x4c.s3o",
			},
		},
	} 
}
