return { 
	grebe = {
		unitname               = "grebe",
		name                   = "Grebe",
		description            = "Amphibious Raider Bot",
		acceleration           = 0.6,
		activateWhenBuilt      = true,
		brakeRate              = 2.4,
		buildCostMetal         = 120,
		buildPic               = "grebe.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND SINK",
		corpse                 = "DEAD",
		customParams           = {},
		explodeAs              = "BIG_UNITEX",
		footprintX             = 2,
		footprintZ             = 2,
		iconType               = "walkerraider",
		leaveTracks            = true,
		maxDamage              = 500,
		maxSlope               = 36,
		maxVelocity            = 2.9,
		maxWaterDepth          = 5000,
		movementClass          = "AKBOT2",
		noChaseCategory        = "TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET",
		objectName             = "amphraider.s3o",
		script                 = "grebe.lua",
		selfDestructAs         = "BIG_UNITEX",
		sfxtypes               = {
			explosiongenerators = {
				"custom:waketrail_small",
			},
		},
		sightDistance          = 700,
		sonarDistance          = 700,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ComTrack",
		trackWidth             = 22,
		turnRate               = 1440,
		upright                = true,
		weapons                = {
			{
				def                = "GAUSS",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs             = {
			GAUSS = {
				name                    = "Light Railgun",
				alphaDecay              = 0.12,
				areaOfEffect            = 16,
				avoidfeature            = false,
				--cegTag                  = "waketrail_small",
				colorMap				= [[0 0.1843 0.4235  0.7294 0.04705 0.1843  0 0.125 0.3568]],
				craterBoost             = 0,
				craterMult              = 0,
				customParams = {
					light_camera_height = 1200,
					light_radius        = 180,
				},
				damage                  = {
					default = 80.1,
				},
				explosionGenerator      = "custom:MARY_SUE",
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 260,
				reloadtime              = 20/30,
				rgbColor                = "0.5 1 1",
				separation              = 0.4,
				size                    = 3,
				sizeDecay               = -0.8,
				soundHit                = "explosion/ex_med5",
				soundHitVolume          = 2.5,
				soundStart              = "weapon/cannon/amphtest",
				soundTrigger            = true,
				soundStartVolume        = 1,5,
				stages                  = 8,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 650,
			},
		},
		featureDefs            = {
			DEAD      = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "wreck2x2b.s3o",
			},
			HEAP      = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},

		},
	} 
}
