return { 
	gunshipassault = {
		unitname            = "gunshipassault",
		name                = "Dusk",
		description         = "Heavy Fire Support Gunship",
		acceleration        = 0.4,
		brakeRate           = 0.8,
		buildCostMetal      = 1200,
		builder             = false,
		buildPic            = "gunshipassault.png",
		canFly              = true,
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		canSubmerge         = false,
		category            = "GUNSHIP",
		collide             = true,
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "50 15 50",
		collisionVolumeType    = "cylY",
		corpse              = "DEAD",
		cruiseAlt           = 300,
		customParams        = {
			airstrafecontrol = "1",
			modelradius    = "10",
			bait_level_default = 1,
		},
		explodeAs           = "GUNSHIPEX",
		floater             = true,
		footprintX          = 3,
		footprintZ          = 3,
		hoverAttack         = true,
		iconType            = "heavygunshipassault",
		health              = 10000,
		speed               = 5.5,
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB",
		objectName          = "Black_Dawn.s3o",
		script              = "gunshipassault.lua",
		selfDestructAs      = "GUNSHIPEX",
		sightDistance       = 700,
		turnRate            = 1400,
		weapons             = {
			{
				def                = "VTOL_SALVO",
				mainDir            = "0 -0.35 1",
				maxAngleDif        = 45,
				onlyTargetCategory = "GUNSHIP PLANE SWIM LAND SHIP SINK TURRET FLOAT HOVER",
				badTargetCategory  = "GUNSHIP PLANE",
			},
		},
		weaponDefs          = {
			VTOL_SALVO = {
				name                    = "Hailstorm Support Cannon",
				areaOfEffect            = 40,
				avoidFeature            = false,
				avoidFriendly           = false,
				accuracy                = 750,
				burst                   = 7,
				burstrate               = 2/30,
				collideFriendly         = false,
				cegtag					= "hailstorm_trail",
				craterBoost             = 20,
				craterMult              = 2.1,
				customparams = {
					burst = Shared.BURST_UNRELIABLE,
					light_camera_height = 2500,
					light_color = "0.55 0.27 0.05",
					light_radius = 160,
				},
				damage                  = {
					default = 100.01,
				},
				edgeEffectiveness       = 0.5,
				explosionGenerator      = "custom:bomb_hit_40",
				fireStarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 2,
				model                   = "hobbes.s3o",
				noSelfDamage            = true,
				range                   = 480,
				sprayAngle              = 750,
				reloadtime              = 3.2,
				smokeTrail              = false,
				soundHitVolume          = 6,
				soundHit                = "weapon/cannon/cannonfire_006",
				soundStart              = "weapon/cannon/cannonfire_007",
				soundStartVolume        = 8.3,
				tolerance               = 15000,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 750,
			},
		},
		featureDefs         = {
			DEAD  = {
				blocking         = true,
				collisionVolumeScales  = "65 20 65",
				collisionVolumeType    = "CylY",
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "blackdawn_d.dae",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},
	} 
}
