return { 
	gunshipcon = {
		unitname            = "gunshipcon",
		name                = "Wasp",
		description         = "Heavy Gunship Constructor",
		acceleration        = 0.8,
		airStrafe           = 0,
		brakeRate           = 0.8,
		buildCostMetal      = 300,
		buildDistance       = 400,
		builder             = true,
		buildoptions        = {},
		buildPic            = "GUNSHIPCON.png",
		buildRange3D        = false,
		canFly              = true,
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		canSubmerge         = false,
		canmanualfire		= true,
		category            = "GUNSHIP UNARMED",
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "20 55 55",
		collisionVolumeType    = "cylX",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "78 78 78",
		selectionVolumeType    = "ellipsoid",
		collide             = true,
		corpse              = "DEAD",
		cruiseAlt           = 120,
		customParams        = {
			airstrafecontrol = "0",
			modelradius    = "15",
			aimposoffset   = "0 35 0",
			midposoffset   = "0 35 0",
			custom_height  = "55",
			outline_x = 105,
			outline_y = 105,
			outline_yoff = 25,
		},
		energyUse           = 0,
		explodeAs           = "GUNSHIPEX",
		floater             = true,
		footprintX          = 2,
		footprintZ          = 2,
		hoverAttack         = true,
		iconType            = "builderair",
		health              = 1900,
		speed               = 2.7,
		noAutoFire          = false,
		noChaseCategory     = "TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET",
		objectName          = "bumblebee.dae",
		script              = "gunshipcon.lua",
		selfDestructAs      = "GUNSHIPEX",
		showNanoSpray       = false,
		sightDistance       = 500,
		turnRate            = 500,
		workerTime          = 15,
		weapons             = {
			{
				def                = "deployturret",
				--maxAngleDif        = 270,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP FIXEDWING",
			},
		},
		weaponDefs			= {
			deployturret = {
				name                    = "Pistin canister",
				accuracy                = 300,
				areaOfEffect            = 96,
				craterBoost             = 0,
				craterMult              = 0,
				commandfire				= true,
				customParams            = {
					reaim_time = 8, -- COB
					spawns_name = "pistin",
					spawns_expire = 45,
					spawn_blocked_by_shield = 0,
					light_radius = 0,
					nofriendlyfire = "needs hax",
					reveal_unit = 3,
				},

				damage                  = {
					default = 20,
				},

				explosionGenerator      = "custom:dirt",
				explosionScar		= false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				model                   = "clawshell.s3o",
				myGravity               = 0.34,
				noSelfDamage            = true,
				range                   = 600,
				reloadtime              = 30,
				soundHit                = "weapon/cannon/badger_hit",
				soundStart              = "weapon/cannon/badger_fire",
				soundHitVolume          = 8,
				soundStartVolume        = 12,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 500,
			},
		},
		featureDefs         = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				collisionVolumeOffsets = "0 0 -20",
				collisionVolumeScales  = "90 90 60",
				collisionVolumeType    = "ellipsoid",
				object           = "bumblebee_d.dae",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2b.s3o",
			},
		},
	} 
}
