return { 
	hovertransport = {
		unitname            = [[hovertransport]],
		name                = [[Hoverboard]],
		description         = [[Hovering Weapons Platform]],
		acceleration        = 0.51,
		activateWhenBuilt   = true,
		brakeRate           = 1.15,
		buildCostMetal      = 200,
		builder             = false,
		buildPic            = [[shiptransport.png]],
		canMove             = true,
		canPatrol			= true,
		canGuard			= true,
		cantBeTransported   = true,
		category            = [[HOVER UNARMED]],
		collisionVolumeOffsets = [[0 0 -3]],
		collisionVolumeScales  = [[35 20 55]],
		collisionVolumeType    = [[ellipsoid]],
		corpse              = [[DEAD]],

		customParams        = {
			turnatfullspeed = [[1]],
			modelradius    = [[15]],
		},

		explodeAs           = [[BIG_UNITEX]],
		footprintX          = 4,
		footprintZ          = 4,
		holdSteady          = true,
		iconType            = [[shiptransport]],
		idleAutoHeal        = 5,
		idleTime            = 1800,
		isFirePlatform      = true,
		maxDamage           = 2400,
		maxVelocity         = 3.0,
		maxSlope            = 36,
		minCloakDistance    = 100,
		movementClass       = [[HOVER4]],
		noChaseCategory     = [[TERRAFORM FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET]],
		objectName          = [[shiptransport]],
		releaseHeld         = true,
		script              = [[hovertransport.lua]],
		selfDestructAs      = [[BIG_UNITEX]],
		sightDistance       = 500,
		sonarDistance       = 500,
		transportCapacity   = 1,
		transportSize       = 3,
		transportByEnemy    = false,
		turnRate            = 590,
		featureDefs         = {
			DEAD  = {
				blocking         = false,
				featureDead      = [[HEAP]],
				footprintX       = 4,
				footprintZ       = 4,
				object           = [[shiptransport_dead.dae]],
			},

			HEAP  = {
				blocking         = false,
				footprintX       = 4,
				footprintZ       = 4,
				object           = [[debris3x3a.s3o]],
			},
		},
	} 
}