return { 
	jumparty = {
		unitname               = "jumparty",
		name                   = "Firewall",
		description            = "Area Denial Artillery (Line)",
		acceleration           = 0.36,
		brakeRate              = 1.44,
		buildCostMetal         = 1100,
		builder                = false,
		buildPic               = "jumparty.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "83 83 83",
		selectionVolumeType    = "ellipsoid",
		corpse                 = "DEAD",
		customParams           = {
			selection_scale   = 0.92,
			fireproof      = "1",
			outline_x = 125,
			outline_y = 125,
			outline_yoff = 21,
			jump_delay         = 60,
			jump_speed         = 8,
			jump_reload        = 16,
			canjump            = 1,
			jump_range         = 650,
		},

		explodeAs              = "BIG_UNITEX",
		footprintX             = 4,
		footprintZ             = 4,
		iconType               = "fatbotarty",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		leaveTracks            = true,
		health                 = 1250,
		maxSlope               = 36,
		speed                  = 1.4,
		maxWaterDepth          = 22,
		movementClass          = "KBOT4",
		noAutoFire             = false,
		noChaseCategory        = "TERRAFORM SATELLITE SUB",
		objectName             = "firewalker.s3o",
		script                 = "jumparty.lua",
		selfDestructAs         = "BIG_UNITEX",
		sfxtypes               = {

			explosiongenerators = {
				"custom:shellshockflash",
				"custom:SHELLSHOCKSHELLS",
				"custom:SHELLSHOCKGOUND",
				"custom:flamer",
			},
		},
		sightDistance          = 660,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 0.6,
		trackType              = "ComTrack",
		trackWidth             = 33,
		turnRate               = 720,
		upright                = true,
		workerTime             = 0,
		weapons                = {
			{
				def                = "NAPALM_SPRAYER",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER",
			},
			{
				def                = "JUMP",
			},
		},
		weaponDefs             = {
			NAPALM_FRAGMENT = {
				name                    = "Thermite Trail",
				accuracy                = 400,
				areaOfEffect            = 162,
				avoidFeature            = false,
				craterBoost             = 1,
				craterMult              = 2,
				cegTag                  = "flamer",
				customParams              = {
					setunitsonfire = "1",
					burntime = 60,

					area_damage = 1,
					area_damage_radius = 70,
					area_damage_dps = 40,
					area_damage_duration = 14,

					--lups_heat_fx = "firewalker",
					light_camera_height = 2500,
					light_color = "0.25 0.13 0.05",
					light_radius = 500,
				},
				damage                  = {
					default = 40,
				},

				explosionGenerator      = "custom:napalm_firewalker_small",
				firestarter             = 180,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				myGravity               = 0.1,
				range                   = 900,
				reloadtime              = 12,
				rgbColor                = "1 0.5 0.2",
				size                    = 5,
				soundHit                = "weapon/burn_mixed",
				soundStart              = "weapon/cannon/wolverine_fire",
				soundStartVolume        = 3.2,
				sprayangle              = 2500,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 320,
			},
			JUMP = {
				name                    = "Thermite (Jump)",
				areaOfEffect            = 40,
				craterBoost             = 0,
				craterMult              = 0,
				cegTag                  = "flamer",
				customParams            = {
					light_camera_height = 2000,
					light_color = "1 0.5 0.2",
					light_radius = 120,
					setunitsonfire = "1",
					stats_custom_tooltip_1 = " - Falls from jumpjets",
					groundnoexplode = 1,
				},
				damage                  = {
					default = 30.1,
				},
				explosionGenerator      = "custom:napalmthrower_small",
				fireStarter             = 100,
				flighttime              = 10,
				noExplode               = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 880,
				reloadtime              = 1/3,
				mygravity               = 1.5,
				rgbColor                = "1 0.5 0.2",
				soundHit				= "flamethrowerhit",
				soundHitVolume          = 2.2,
				soundStart              = "flamethrowerfire",
				soundStartVolume        = 3.5,
				stages                  = 10,
				separation              = 1.5,
				size					= 4.5,
				weaponType              = "Cannon",
				weaponVelocity          = 400,
			},
			NAPALM_SPRAYER = {
				name                    = "Incendiary Mortar",
				areaOfEffect            = 128,
				avoidFeature            = false,
				craterBoost             = 1,
				craterMult              = 2,
				cegTag                  = "flamer",
				customParams              = {
					--lups_heat_fx = "firewalker",
					light_camera_height = 2500,
					light_color = "0.25 0.13 0.05",
					light_radius = 460,
					numprojectiles1 = 1,
					projectile1 = "jumparty_napalm_fragment",
					keepmomentum1 = 0,
					spawndist = 500,
					timeoutspawn = 1, 
					velspread1 = "2.55, -4, 2.55, _, 0, _",
					useheight = 1,
					clustercharges = 40,
					clusterdelay = 2,
					
					setunitsonfire = "1",
					burntime = 200,

					area_damage = 1,
					area_damage_radius = 100,
					area_damage_dps = 80,
					area_damage_duration = 14,
					
					sweepfire = 1,
					sweepfire_maxangle = 12,
					sweepfire_step = 6,
					sweepfire_maxrangemult = 0.98,
					reveal_unit = 3,
					shield_damage = 300 + 33*40
				},
				damage                  = {
					default = 300,
				},

				explosionGenerator      = "custom:napalm_koda_small",
				flightTime              = 10,
				model					= "wep_napalm.s3o",
				firestarter             = 180,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				--myGravity               = 0.1,
				--projectiles             = 10,
				range                   = 1280,
				reloadtime              = 6,
				rgbColor                = "1 0.5 0.2",
				--size                    = 5,
				soundHit                = "weapon/clusters/cluster_light_napalm",
				soundStart              = "weapon/missile/air_launched_missile",
				soundStartVolume        = 3.2,
				trajectoryHeight		= 1.2,
				turret                  = true,
				weaponAcceleration		= 420,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 320,
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "firewalker_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 4,
				footprintZ       = 4,
				object           = "debris4x4c.s3o",
			},

		},
	} 
}
