return { 
	jumpbomb = {
		unitname               = "jumpbomb",
		name                   = "Skuttle",
		description            = "Cloaked Jumping Anti-Heavy Bomb",
		acceleration           = 0.54,
		brakeRate              = 3.24,
		buildCostMetal         = 625,
		builder                = false,
		buildPic               = "jumpbomb.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND",
		cloakCost              = 3,
		cloakCostMoving        = 30,
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "20 20 20",
		collisionVolumeType    = "ellipsoid",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "42 42 42",
		selectionVolumeType    = "ellipsoid",
		corpse                 = "DEAD",
		customParams           = {
			canjump          = 1,
			jump_range       = 550,
			jump_height      = 280,
			jump_speed       = 10,
			jump_reload      = 6,
			jump_from_midair = 0,
			aimposoffset   = "0 2 0",
			midposoffset   = "0 2 0",
			modelradius    = "10",
			selection_scale = 1, -- Maybe change later
			cloakregen	= 20,
			recloaktime = 300,
			cloaker_bestowed_radius = 75,
		},
		explodeAs              = "jumpbomb_DEATH",
		fireState              = 0,
		footprintX             = 2,
		footprintZ             = 2,
		iconType               = "jumpjetbomb",
		idleAutoHeal           = 0,
		idleTime               = 1800,
		leaveTracks            = true,
		initCloaked            = true,
		kamikaze               = true,
		kamikazeDistance       = 25,
		kamikazeUseLOS         = true,
		maneuverleashlength    = "140",
		health                 = 200,
		maxSlope               = 36,
		speed                  = 2.4,
		maxWaterDepth          = 15,
		minCloakDistance       = 125,
		movementClass          = "SKBOT2",
		noAutoFire             = false,
		noChaseCategory        = "FIXEDWING LAND SINK TURRET SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER",
		objectName             = "skuttle.s3o",
		selfDestructAs         = "jumpbomb_DEATH",
		selfDestructCountdown  = 0,
		script                 = "jumpbomb.lua",
		sightDistance          = 400,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ChickenTrackPointy",
		trackWidth             = 34,
		turnRate               = 2400,
		featureDefs            = {
			DEAD      = {
				blocking         = false,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "skuttle_dead.s3o",
			},
			HEAP      = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},
		weaponDefs = {
			jumpbomb_DEATH = {
				areaOfEffect       = 180,
				craterBoost        = 4,
				craterMult         = 5,
				edgeEffectiveness  = 0.3,
				explosionGenerator = "custom:NUKE_150",
				explosionSpeed     = 10000,
				impulseBoost       = 0,
				impulseFactor      = 0,
				name               = "Explosion",
				soundHit           = "explosion/mini_nuke",
				customParams       = {
					lups_explodelife = 1.5,
					blastwave_size = 75,
					blastwave_impulse = 4.5,
					blastwave_speed = 10,
					blastwave_life = 15,
					blastwave_lossfactor = 0.81,
					blastwave_damage = 4500,
				},
				damage = {
					default          = 250.1,
				},
			},
		}
	} 
}
