local unitDef = {
	unitname                      = "missilekinetic",
	name                          = "Apogee",
	description                   = "Kinetic Penetrator",
	buildCostMetal                = 220,
	builder                       = false,
	buildingGroundDecalDecaySpeed = 30,
	buildingGroundDecalSizeX      = 3,
	buildingGroundDecalSizeY      = 3,
	buildingGroundDecalType       = "napalmmissile_aoplane.dds",
	buildPic                      = "missilekinetic.png",
	category                      = "SINK UNARMED",
	collisionVolumeOffsets        = "0 10 0",
	collisionVolumeScales         = "10 33 10",
	collisionVolumeType	          = "CylY",
	customParams                  = {
		aimposoffset   = "0 55 -15",
		midposoffset   = "0 45 -15",
		mobilebuilding = "1",
		outline_x = 55,
		outline_y = 80,
		outline_yoff = 55,
		istacmissile = 1,
	},
	explodeAs                     = "BIG_UNIT",
	footprintX                    = 1,
	footprintZ                    = 1,
	iconType                      = "cruisemissilesmall",
	idleAutoHeal                  = 5,
	idleTime                      = 1800,
	maxDamage                     = 1000,
	maxSlope                      = 18,
	minCloakDistance              = 150,
	objectName                    = "wep_kinetic_driver.dae",
	script                        = "missilekinetic.lua",
	selfDestructAs                = "BIG_UNIT",
	sfxtypes                      = {
		explosiongenerators = {
			"custom:RAIDMUZZLE",
		},
	},
	sightDistance                 = 0,
	useBuildingGroundDecal        = false,
	yardMap                       = "o",
	weapons                       = {
		{
			def                = "WEAPON",
			badTargetCategory  = "SWIM LAND SHIP HOVER",
			onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
		},
	},
	weaponDefs                    = {
		SECONDARY = {
			name 			        = "Hypervelocity Driver",
			cegTag                  = "snipercooloff",
			areaOfEffect            = 50,
			avoidFeature            = false,
			avoidFriendly           = false,
			collideFeature          = false,
			collideFriendly         = false,
			craterAreaOfEffect      = 300,
			craterBoost             = 500,
			craterMult              = 6,
			customParams            = {},
			--model                   = "wep_b_fabby.s3o",
			damage                  = {
				default = 3000.01,
			},
			customParams              = {
				light_camera_height = 2500,
				light_color = "0.25 0.13 0.05",
			},
			edgeEffectiveness       = 1,
			explosionGenerator      = "custom:100rlexplode",
			fireStarter             = 250,
			model                   = "wep_kinetic_driver.dae",
			impulseBoost            = 0,
			impulseFactor           = 1,
			interceptedByShieldType = 1,
			soundHit                = "weapon/missile/kinetic_kill_hit",
			soundHitVolume          = 80,
			--soundStart              = "weapon/flak_hit2",
			myGravity               = 0.2,
			weaponType              = "Cannon",
			weaponVelocity          = 320,
		},
		WEAPON = {
			name                    = "Kinetic Kill Vehicle",
			cegTag                  = "tactrail",
			areaOfEffect            = 50,
			avoidFriendly           = false,
			avoidground             = false,
			avoidfeature            = false,
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			customParams        	  = {
				numprojectiles1 = 1, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
				projectile1 = "missilekinetic_secondary",
				use2ddist = 1,
				spawndist = 2850,
				timeoutspawn = 0,
				keepmomentum1 = 1,
				useheight = 1,
				minvelocity = -4,
				reaim_time = 60, -- Fast update not required (maybe dangerous)
				restrict_in_widgets = 1,
				reveal_unit = 8,
				stats_hide_dps = 1, -- one use
				stats_hide_reload = 1,		
				light_color = "1.35 0.5 0.36",
				light_radius = 550,
				cruise_minterrainheight = 300,
				cruisealt = 3500,
				cruisedist = 480,
			},
			damage                  = {
				default = 3000.01,
			},
			edgeEffectiveness       = 0.4,
			explosionGenerator      = "custom:snipercooloff",
			fireStarter             = 220,
			flightTime              = 30,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 1,
			model                   = "wep_kinetic_driver.dae",
			noSelfDamage            = true,
			range                   = 3500,
			reloadtime              = 10,
			smokeTrail              = false,
			soundHit                = "weapon/impacts/kinetic_kill_entry",
			soundHitVolume          = 120,
			soundStart              = "SiloLaunch",
			startVelocity           = 20,
			tolerance               = 4000,
			turnrate                = 64000,
			tracks                  = true,
			weaponAcceleration      = 400,
			weaponType              = "StarburstLauncher",
			weaponVelocity          = 1500,
		},
	},
	featureDefs                   = {},
}

return { missilekinetic = unitDef }
