return { 
	missileslow = {
		name                          = "Wraith",
		description                   = "Reconnaissance tactical missile",
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 3,
		buildingGroundDecalSizeY      = 3,
		buildingGroundDecalType       = "napalmmissile_aoplane.dds",
		buildPic                      = "missileslow.png",
		category                      = "SINK UNARMED",
		collisionVolumeOffsets        = "0 15 0",
		collisionVolumeScales         = "20 60 20",
		collisionVolumeType            = "CylY",
		customParams                  = {
			mobilebuilding = "1",
			ignore_for_loss_stats = "1",
			midposoffset   = "0 72 0",
			outline_x = 55,
			outline_y = 80,
			outline_yoff = 55,
		},
		explodeAs                     = "WEAPON",
		footprintX                    = 1,
		footprintZ                    = 1,
		health                        = 1300,
		iconType                      = "cruisemissilesmall",
		maxSlope                      = 18,
		metalCost                     = 850,
		objectName                    = "slowmissile.dae",
		script                        = "cruisemissile.lua",
		selfDestructAs                = "WEAPON",
		sfxtypes                      = {
			explosiongenerators = {
				"custom:RAIDMUZZLE",
			},
		},
		sightDistance                 = 0,
		useBuildingGroundDecal        = false,
		yardMap                       = "o",
		weapons                       = {
			{
				def                = "WEAPON",
				badTargetCategory  = "SWIM LAND SHIP HOVER GUNSHIP FIXEDWING",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP FIXEDWING",
			},
		},
		weaponDefs                    = {
			WEAPON = {
				name                    = "Reconnaissance Missile",
				cegTag                  = "slam_trail",
				avoidFriendly           = false,
				areaOfEffect            = 600,
				customParams            = {
					light_color = "0.53 0.54 0.125",
					light_radius = 250,
					stats_hide_dps = 1, -- one use
					stats_hide_reload = 1,
					cruisealt = 500,
					cruisedist = 400,
					generates_los = 650,
					generates_radar = 1800,
					sensortag = 40,
				},
				damage                  = {
					default = 100,
				},
				explosionGenerator      = "custom:scanner_ping_600",
				explosionSpeed          = 600,
				flightTime              = 60,
				impulseBoost            = 0,
				impulseFactor           = 0,
				impactOnly              = false,
				interceptedByShieldType = 1,
				model                   = "slowmissile.dae",
				noSelfDamage            = true,
				range                   = 5000,
				reloadtime              = 10,
				smokeTrail              = false,
				soundHit                = "weapon/aoe_aura2",
				soundHitVolume          = 15,
				soundStart              = "SiloLaunch",
				tolerance               = 4000,
				tracks                  = true,
				turnrate                = 32000,
				weaponAcceleration      = 110,
				weaponTimer             = 0.2,
				weaponType              = "StarburstLauncher",
				weaponVelocity          = 900,
			},
		},

		featureDefs                   = {},
	} 
}
