unitDef = {
	unitname                      = "napalmmissile",
	name                          = "Inferno",
	description                   = "Thermite Missile",
	buildCostMetal                = 1000,
	builder                       = false,
	buildingGroundDecalDecaySpeed = 30,
	buildingGroundDecalSizeX      = 3,
	buildingGroundDecalSizeY      = 3,
	buildingGroundDecalType       = "napalmmissile_aoplane.dds",
	buildPic                      = "napalmmissile.png",
	category                      = "SINK UNARMED",
	collisionVolumeOffsets        = "0 15 0",
	collisionVolumeScales         = "20 60 20",
	collisionVolumeType	        = "CylY",
	customParams                  = {
		aimposoffset   = "0 35 0",
		mobilebuilding = "1",
		outline_x = 55,
		outline_y = 80,
		outline_yoff = 55,
		istacmissile = 1,
	},
	explodeAs                     = "WEAPON",
	footprintX                    = 1,
	footprintZ                    = 1,
	iconType                      = "cruisemissilesmall",
	idleAutoHeal                  = 5,
	idleTime                      = 1800,
	health                        = 1000,
	maxSlope                      = 18,
	minCloakDistance              = 150,
	objectName                    = "wep_napalm.s3o",
	script                        = "cruisemissile.lua",
	selfDestructAs                = "WEAPON",
	sfxtypes                      = {
		explosiongenerators = {
			"custom:RAIDMUZZLE",
		},
	},
	sightDistance                 = 0,
	useBuildingGroundDecal        = false,
	yardMap                       = "o",
	weapons                       = {
		{
			def                = "WEAPON",
			badTargetCategory  = "SWIM LAND SHIP HOVER",
			onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
		},
	},
	weaponDefs                    = {
		SECONDARY = {
			name 					= "Thermite Fireball",
			cegTag                  = "flamer",
			areaOfEffect            = 216,
			avoidFeature            = false,
			avoidFriendly           = false,
			collideFeature          = false,
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			--model                   = "wep_b_fabby.s3o",
			damage                  = {
				default = 25,
			},
			customParams              = {
				setunitsonfire = "1",
				burntime = 30,
				area_damage = 1,
				area_damage_radius = 108,
				area_damage_dps = 18,
				area_damage_duration = 16,
				light_camera_height = 2500,
				light_color = "0.25 0.13 0.05",
				light_radius = 460,
				lups_napalm_fx = 1,
				reveals_unit = 3,
			},
			explosionGenerator      = "custom:napalm_koda",
			fireStarter             = 250,
			impulseBoost            = 0,
			impulseFactor           = 0.1,
			interceptedByShieldType = 1,
			soundHit                = "weapon/burn_mixed",
			--soundStart              = "weapon/flak_hit2",
			myGravity               = 0.2,
			rgbColor                = "1 0.5 0.2",
			weaponType              = "Cannon",
			weaponVelocity          = 320,
		},
		WEAPON = {
			name                    = "Thermite Missile",
			cegTag                  = "napalmtrail",
			areaOfEffect            = 512,
			craterAreaOfEffect      = 0,
			avoidFriendly           = false,
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			customParams        	  = {
				numprojectiles1 = 5,
				projectile1 = "napalmmissile_weapon2",
				spawndist = 1000,
				timeoutspawn = 0, 
				velspread1 = "10.09, 4, 10.09",
				useheight = 1,
				reaim_time = 60, -- Fast update not required (maybe dangerous)
				setunitsonfire = "1",
				burntime = 90,
				cruisealt = 1700,
				cruisedist = 400,
				restrict_in_widgets = 1,
				stats_hide_dps = 1, -- one use
				stats_hide_reload = 1,
				light_color = "1.35 0.5 0.36",
				light_radius = 550,
				cruise_ignoreterrain = "1",
			},
			damage                  = {
				default = 151,
			},
			edgeEffectiveness       = 0.4,
			--explosionGenerator      = "custom:napalm_missile",
			fireStarter             = 220,
			flightTime              = 100,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 1,
			model                   = "wep_napalm.s3o",
			noSelfDamage            = true,
			range                   = 3500,
			reloadtime              = 10,
			smokeTrail              = false,
			soundHit                = "weapon/cannon/plasma_hit",
			soundStart              = "SiloLaunch",
			tolerance               = 4000,
			turnrate                = 40000,
			weaponAcceleration      = 180,
			tracks = true,
			weaponType              = "StarburstLauncher",
			weaponVelocity          = 1200,
		},
		WEAPON2 = {
			name                    = "Incendiary Warhead",
			cegTag                  = "napalmtrail",
			areaOfEffect            = 512,
			craterAreaOfEffect      = 64,
			avoidFriendly           = false,
			collideFriendly         = false,
			craterBoost             = 4,
			craterMult              = 3.5,
			customParams        	  = {
				numprojectiles1 = 8,
				projectile1 = "napalmmissile_secondary",
				spawndist = 450,
				timeoutspawn = 0,
				velspread1 = "25.37, 16, 25.37",
				reaim_time = 60, -- Fast update not required (maybe dangerous)
				useheight = 1,
				setunitsonfire = "1",
				burntime = 90,
				restrict_in_widgets = 1,
				reveal_unit = 3,
				stats_hide_dps = 1, -- one use
				stats_hide_reload = 1,		
				light_color = "1.35 0.5 0.36",
				light_radius = 550,
			},
			damage                  = {
				default = 151,
			},
			edgeEffectiveness       = 0.4,
			--explosionGenerator      = "custom:napalm_missile",
			fireStarter             = 220,
			flightTime              = 100,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 1,
			model                   = "wep_napalm.s3o",
			noSelfDamage            = true,
			range                   = 3500,
			reloadtime              = 10,
			smokeTrail              = false,
			soundHit                = "weapon/cannon/plasma_hit",
			soundStart              = "SiloLaunch",
			tolerance               = 4000,
			turnrate                = 18000,
			weaponAcceleration      = 180,
			weaponTimer             = 3,
			weaponType              = "StarburstLauncher",
			weaponVelocity          = 1200,
		},
	},
	featureDefs                   = {},
}

return { napalmmissile = unitDef }
