return { 
	nebula = {
		unitname               = "nebula",
		name                   = "Nebula",
		description            = "Atmospheric Mothership",
		acceleration           = 0.02,
		activateWhenBuilt      = true,
		airStrafe              = 0,
		bankingAllowed         = false,
		brakeRate              = 0.48,
		buildCostMetal         = 14000,
		builder                = false,
		buildPic               = "nebula.png",
		canFly                 = true,
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canSubmerge            = false,
		category               = "GUNSHIP",
		collide                = true,
		collisionVolumeOffsets = "0 00 0",
		collisionVolumeScales  = "40 50 220",
		collisionVolumeType    = "box",
		corpse                 = "DEAD",
		cruiseAlt              = 280,
		customParams           = {
			cantuseairpads = 1,
			modelradius    = "40",
			shield_emit_height = 20,
			outline_x = 420,
			outline_y = 420,
			outline_yoff = 40,
			landflystate = 1,
		},
		explodeAs              = "LARGE_BUILDINGEX",
		floater                = true,
		footprintX             = 5,
		footprintZ             = 5,
		hoverAttack            = true,
		iconType               = "nebula",
		idleAutoHeal           = 440,
		idleTime               = 1800,
		health                 = 60000,
		speed                  = 1.5,
		noAutoFire             = false,
		noChaseCategory        = "TERRAFORM FIXEDWING SATELLITE SUB",
		objectName             = "nebula.s3o",
		script                 = "nebula.lua",
		selfDestructAs         = "LARGE_BUILDINGEX",
		sfxtypes               = {
			explosiongenerators = {
				"custom:brawlermuzzle",
				"custom:plasma_hit_96",
				"custom:EXP_MEDIUM_BUILDING_SMALL",
			},
		},
		sightDistance          = 1500,
		turnRate               = 100,
		upright                = true,
		turninplace			   = false,
		weapons                = {
			{
				def                = "MISSILETOP",
				mainDir            = "0 1 0", -- top
				maxAngleDif        = 210,
				onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER",
			},
			{
				def                = "MISSILEBOTTOM",
				mainDir            = "0 -1 0", -- bottom
				maxAngleDif        = 210,
				onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER",
			},
			{
				def                = "CANNON",
				mainDir            = "-1 0 0", -- left
				maxAngleDif        = 210,
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "CANNON",
				mainDir            = "1 0 0", -- right
				maxAngleDif        = 210,
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def         = "SHIELD",
			},
		},
		weaponDefs             = {
			MISSILETOP = {
				name                    = "Typhoon Missile Barrage",
				areaOfEffect            = 60,
				sprayAngle				= 800,
				accuracy				= 800,
				dance					= 200,
				burst					= 6,
				projectiles				= 2,
				burstRate				= 4/30,
				avoidFriendly           = true,
				canattackground         = true,
				cegTag                  = "missiletrailblue",
				collideFriendly         = false,
				craterBoost             = 1,
				craterMult              = 2,
				--cylinderTargeting       = 6,
				customParams        	  = {
					burst = Shared.BURST_RELIABLE,
					light_color = "0.5 0.6 0.6",
					reaim_time = 60, -- Fast update not required (maybe dangerous)
					cruisealt = 440,
					airlaunched = 1,
					cruisedist = "300",
					cruiserandomradius = 100,
					cruise_randomizationtype = "circular",
					cruise_nolock = 1,
					cruisetracking = 1,
					cruise_ignoreterrain = 1,
				},
				damage                  = {
					default = 400.01,
				},
				edgeEffectiveness		= 0.2,
				explosionGenerator      = "custom:EMG_HIT_HE",
				fireStarter             = 70,
				flightTime              = 7,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 2,
				model                   = "wep_m_avalanche.s3o",
				noSelfDamage            = true,
				range                   = 900,
				reloadtime              = 6,
				smokeTrail              = true,
				soundHit                = "weapon/missile/sabot_fire",
				soundStart              = "weapon/missile/large_missile_fire",
				startVelocity           = 100,
				texture2                = "darksmoketrail",
				tolerance               = 22000,
				tracks                  = false,
				turnRate                = 40000,
				weaponAcceleration      = 200,
					trajectoryHeight        = 0.60,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 650,
			},
			MISSILEBOTTOM = {
				name                    = "Typhoon Missile Barrage",
				areaOfEffect            = 60,
				sprayAngle				= 800,
				accuracy				= 800,
				dance					= 200,
				burst					= 6,
				projectiles				= 2,
				burstRate				= 4/30,
				avoidFriendly           = true,
				canattackground         = true,
				cegTag                  = "missiletrailblue",
				collideFriendly         = false,
				craterBoost             = 1,
				craterMult              = 2,
				--cylinderTargeting       = 6,
				customParams        	  = {
					burst = Shared.BURST_RELIABLE,
					light_color = "0.5 0.6 0.6",
					reaim_time = 60, -- Fast update not required (maybe dangerous)
					cruisealt = 440,
					airlaunched = 1,
					cruisedist = "300",
					cruiserandomradius = 50,
					cruise_randomizationtype = "circular",
					cruise_nolock = 1,
					cruisetracking = 1,
				},
				damage                  = {
					default = 400.01,
				},
				edgeEffectiveness		= 0.2,
				explosionGenerator      = "custom:EMG_HIT_HE",
				fireStarter             = 70,
				flightTime              = 7,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 2,
				model                   = "wep_m_avalanche.s3o",
				noSelfDamage            = true,
				range                   = 900,
				reloadtime              = 6,
				smokeTrail              = true,
				soundHit                = "weapon/missile/sabot_fire",
				soundStart              = "weapon/missile/large_missile_fire",
				startVelocity           = 100,
				texture2                = "darksmoketrail",
				tolerance               = 22000,
				tracks                  = false,
				turnRate                = 40000,
				weaponAcceleration      = 200,
					trajectoryHeight        = 0.15,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 650,
			},
			fragment = {
				name                    = "Plasma Fragment",
				areaOfEffect            = 144,
				avoidFeature            = true,
				avoidFriendly           = true,
				burnblow                = true,
				craterBoost             = 1,
				craterMult              = 0.5,
				customParams            = {
					force_ignore_ground = "1",
					isFlak = 3,
					flaktime = 1/30,
					light_camera_height = 1500,
				},
				damage                  = {
					default = 50.1,
				},
				edgeEffectiveness       = 0.75,
				explosionGenerator      = "custom:FLASH64",
				impulseBoost            = 30,
				impulseFactor           = 0.6,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				soundHit                = "weapon/cannon/generic_cannon",
				soundStart              = "weapon/cannon/outlaw_gun",
				soundStartVolume        = 3,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 750,
			},
			CANNON = {
				name                    = "Heavy Canister Driver",
				alphaDecay              = 0.1,
				areaOfEffect            = 0.1,
				colormap                = "1 0.95 0.4 1   1 0.95 0.4 1    0 0 0 0.01    1 0.7 0.2 1",
				craterBoost             = 0,
				craterMult              = 0,
				customParams = {
					numprojectiles1 = 6, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
					projectile1 = "nebula_fragment",
					spawndist = 210,
					timeoutspawn = 1, 
					velspread1 = "7.64, -3, 7.64", -- velocity that is randomly added. covers range of +-velspread. OPTIONAL. Default: 4.2
					groundimpact = 1, -- check the distance between ground and projectile? OPTIONAL.
					proxy = 1, 	
				},
				damage                  = {
					default = 50.1 * 6,
				},
				explosionGenerator      = "custom:plasma_hit_32",
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				intensity               = 0.7,
				model                   = "depthcharge.s3o",
				interceptedByShieldType = 1,
				noGap                   = false,
				noSelfDamage            = true,
				range                   = 970,
				reloadtime              = 2/3,
				rgbColor                = "1 0.95 0.4",
				separation              = 2,
				size                    = 2.5,
				sizeDecay               = 0,
				soundStart              = "weapon/cannon/cannon_fire8",
				soundHit                = "explosion/ex_small14",
				sprayAngle              = 360,
				stages                  = 12,
				tolerance               = 5000,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 1200,
			},
			SHIELD = {
				name                    = "Energy Shield",
				damage                  = {
					default = 10,
				},
				customParams            = {
					unlinked                = true,
				},
				exteriorShield          = true,
				shieldAlpha             = 0.2,
				shieldBadColor          = "1 0.1 0.1 1",
				shieldGoodColor         = "0.1 0.1 1 1",
				shieldInterceptType     = 3,
				shieldPower             = 60000,
				shieldPowerRegen        = 600,
				shieldPowerRegenEnergy  = 135,
				shieldRadius            = 400,
				shieldRepulser          = false,
				smartShield             = true,
				visibleShield           = false,
				visibleShieldRepulse    = false,
				weaponType              = "Shield",
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				collisionVolumeOffsets = "0 0 0",
				collisionVolumeScales  = "40 50 220",
				collisionVolumeType    = "box",
				featureDead      = "HEAP",
				footprintX       = 5,
				footprintZ       = 5,
				object           = "nebula_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 4,
				footprintZ       = 4,
				object           = "debris4x4a.s3o",
			},
		},
	}
}
