return { 
	pistin = {
		unitname            = "pistin",
		name                = "Pistin",
		description         = "Deployable Repair/Stun Turret",
		brakerate           = 0.00001,
		acceleration           = 0.00001,
		buildCostMetal      = 25,
		buildPic            = "pistin.png",
		buildDistance	    = 300,
		canMove             = true,
		canassist			= false,
		canPatrol			= false,
		canGuard			= false,
		canRepair			= true,
		canReclaim		    = false,
		canSubmerge         = false,
		cantBeTransported	= false,
		category            = "FLOAT",
		collide             = false,
		collisionVolumeOffsets = "0 9.5 4.6",
		collisionVolumeScales  = "18.4 19 22",
		collisionVolumeType    = "cylY",
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "18.4 19 22",
		selectionVolumeType    = "cylY",
		customParams        = {
			notselectable = "1",
			massoverride = 110,
			modelradius	= "19",
		},
		explodeAs           = "GUNSHIPEX",
		floater             = true,
		footprintX          = 2,
		footprintZ          = 2,
		movementClass          = "KBOT2",
		idleAutoHeal           = 10,
		idleTime               = 300,
		iconType            = "deployablesupport",
		maxDamage           = 800,
		maxVelocity         = 0.0001,
		noChaseCategory     = "FIXEDWING LAND SINK TURRET SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER",
		objectName          = "pistin.dae",
		reclaimable            = false,
		repairable             = false,
		script              = "pistin.lua",
		selfDestructAs      = "GUNSHIPEX",
		sightDistance       = 700,
		blocking			= true,
		minCloakDistance       = 75,
		turnRate               = 0.001,
		weapons             = {
			{
				def                = "ION_BEAM",
				--maxAngleDif        = 270,
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP FIXEDWING",
			},
		},
		workerTime			= 10,
		weaponDefs          = {
			ION_BEAM = {
				name                    = "Ion Beam",
				areaOfEffect            = 8,
				accuracy				= 250,
				coreThickness           = 0.4,
				beamTime                = 2/30,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					light_camera_height = 1200,
					light_radius = 20,
					light_color = "1 0.7843 0.1647",
					sweepfire = 1,
					sweepfire_maxangle = 45,
					sweepfire_step = 0.5,
					sweepfire_fastupdate = 1,
					
				},
				damage                  = {
					default = 13.3333333334,
				},
				duration                = 3/30,
				explosionGenerator      = "custom:ion_beam",
				fireStarter             = 100,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				paralyzer				= true,
				paralyzeTime			= 1,
				range                   = 600,
				reloadtime              = 2/30,
				texture1                = "ecmnoise",
				rgbColor                = "0.078 0.5803 0.89019",
				rgbColor2				= "0.1176 0.4705 0.6902",
				soundStart              = "weapon/laser/ion_burn",
				soundstartvolume	    = 65,
				thickness               = 1.25,
				tolerance               = 10000,
				turret                  = true,
				weaponType              = "BeamLaser",
				weaponVelocity          = 880,
			},
		},
	} 
}
