local unitDef = {
	unitname               = "planefighter",
	name                   = "Deserter",
	description            = "Early Response Fighter-Bomber",
	brakerate              = 0.4,
	buildCostMetal         = 250,
	buildPic               = "planefighter.png",
	canFly                 = true,
	canGuard               = true,
	canMove                = true,
	canPatrol              = true,
	canSubmerge            = false,
	category               = "FIXEDWING",
	collide                = false,
	collisionVolumeOffsets = "0 0 5",
	collisionVolumeScales  = "25 8 40",
	collisionVolumeType    = "box",
	selectionVolumeOffsets = "0 0 10",
	selectionVolumeScales  = "68 68 95",
	selectionVolumeType    = "cylZ",
	corpse                 = "DEAD",
	crashDrag              = 0.01,
	cruiseAlt              = 350,
	customParams           = {
		--specialreloadtime = "850",
		--boost_speed_mult = 5,
		--boost_accel_mult = 6,
		--boost_duration = 30, -- frames
		--refuelturnradius = "80",
		requireammo    = "1",
		reammoseconds    = "6",
		midposoffset   = "0 3 0",
		modelradius    = "5",
		refuelturnradius = "500",
		bait_level_default = 1,
		outline_x = 85,
		outline_y = 85,
		outline_yoff = 16,
		fighter_pullup_dist = 140, -- dont bother.
		
		ammocount = 2,
		ammotexture_1 = "States/ammostates/deserter_rockets.png",
		ammotexture_2 = "States/ammostates/generic_bomb.png",
		ammoname_1 = "Missile Loadout",
		ammoname_2 = "Medium Bomb (Anti-Structure)",
		ammodesc_1 = "Fires a bunch of missiles at air targets or ground targets. Deserter's speed is reduced by 50% upon firing.",
		ammodesc_2 = "Drops a medium anti-structure bomb, dealing moderate area damage. Deserter's top speed is reduced by 50%, and a further 50% upon firing.",
	},
	explodeAs              = "GUNSHIPEX",
	fireState              = 2,
	floater                = true,
	footprintX             = 2,
	footprintZ             = 2,
	frontToSpeed           = 0,
	iconType               = "fighter",
	idleAutoHeal           = 5,
	idleTime               = 1800,
	maneuverleashlength    = "1280",
	maxAcc                 = 0.5,
	health                 = 400,
	maxRudder              = 0.007,
	speed                  = 8,
	mygravity              = 1,
	noAutoFire             = false,
	noChaseCategory        = "TERRAFORM SATELLITE SUB FIXEDWING GUNSHIP",
	objectName             = "fighter.dae",
	script                 = "planefighter.lua",
	selfDestructAs         = "GUNSHIPEX",
	sfxtypes               = {
		explosiongenerators = {
			"custom:MUZZLE_ORANGE",
			"custom:FF_PUFF",
			"custom:BEAMWEAPON_MUZZLE_RED",
			"custom:FLAMER",
		},
	},
	sightDistance          = 900,
	speedToFront           = 0,
	turnRadius             = 150,
	turnRate               = 839,
	weapons                = {
		{
			def                = "MISSILE_AA",
			badTargetCategory  = "GUNSHIP",
			onlyTargetCategory = "FIXEDWING GUNSHIP",
			maxAngleDif        = 180,
		},
		{
			def                = "BOMB",
			onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER SINK SUB",
			mainDir            = "0 -1 0",
			maxAngleDif        = 180,
		},
		{
			def                = "ROCKETS",
			onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER SINK SUB",
			mainDir            = "0 -1 0",
			maxAngleDif        = 80,
		},
		{
			def                = "ROCKETS",
			onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER SINK SUB",
			mainDir            = "0 -1 0",
			maxAngleDif        = 80,
		},
	},
	weaponDefs             = {
		ROCKETS = {
			name                    = "Hurricane Surface Attack Rockets",
			areaOfEffect            = 96,
			accuracy				= 1100,
			avoidFriendly           = true,
			canattackground         = true,
			cegTag                  = "rocket_trail_bar",
			collideFriendly         = false,
			craterBoost             = 1,
			craterMult              = 2,
			cylinderTargeting       = 100,
			customParams        	  = {
				burst = Shared.BURST_RELIABLE,
				light_color = "0.5 0.6 0.6",
				canttargetair = 1,
				script_burst        = 12, -- 8
				script_reload       = 0.5,
			},
			damage                  = {
				default = 160.01,
			},
			dance					= 30,
			edgeEffectiveness		= 0.2,
			explosionGenerator      = "custom:DOT_Merl_Explo",
			fireStarter             = 70,
			flightTime              = 8,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 2,
			model                   = "hobbes_nohax.s3o",
			noSelfDamage            = true,
			range                   = 1050,
			reloadtime              = 2/30,
			smokeTrail              = true,
			sprayAngle              = 1100,
			soundHit                = "explosion/ex_med4",
			soundStart              = "weapon/missile/deserter_missile_launch",
			startVelocity           = 100,
			texture2                = "darksmoketrail",
			tolerance               = 5000,
			tracks                  = true,
			turnRate                = 6800,
			turret				    = false,
			weaponAcceleration      = 1400,
			weaponType              = "MissileLauncher",
			weaponVelocity          = 750,
			wobble                  = 15000,
		},
		BOMB  = {
			name                    = "Medium Bomb (Anti Structure)",
			areaOfEffect            = 32,
			avoidFeature            = false,
			avoidFriendly           = false,
			cegTag                  = "KBOTROCKETTRAIL",
			collideFeature          = false,
			collideFriendly         = false,
			craterBoost             = 0.3,
			craterMult              = 0.5,
			cylinderTargeting          = 1,

			damage                  = {
				default = 1000.1,
			},

			customParams            = {
				light_color = "1.1 0.9 0.45",
				light_radius = 220,
				burst = Shared.BURST_RELIABLE,
				canttargetair = 1,
			},

			explosionGenerator      = "custom:xamelimpact",
			fireStarter             = 70,
			flightTime              = 7,
			heightmod               = 0,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 2,
			model                   = "wep_b_paveway.s3o",
			leadLimit               = 10,
			range                   = 180,
			reloadtime              = 5,
			smokeTrail              = false,
			soundHit                = "weapon/bomb_hit",
			soundStart              = "weapon/bomb_drop",
			startVelocity           = 270,
			tolerance               = 8000,
			tracks                  = false,
			turnRate                = 0,
			turret                  = true,
			waterweapon             = true,
			weaponAcceleration      = 80,
			weaponType              = "MissileLauncher",
			weaponVelocity          = 270,
		},
		MISSILE_AA = {
			name                    = "Skyfall Missiles",
			areaOfEffect            = 40,
			avoidFriendly           = true,
			accuracy				= 100,
			canattackground         = false,
			cegTag                  = "missiletrailblue",
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			--cylinderTargeting       = 6,
			customParams        	  = {
				burst = Shared.BURST_RELIABLE,
				isaa = "1",
				reaim_time = 60,
				script_burst        = 12, -- 8
				script_reload       = 0.5,
			},
			damage                  = {
				default = 90.1,
			},
			explosionGenerator      = "custom:WEAPEXP_PUFF",
			fireStarter             = 70,
			flightTime              = 6,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 2,
			model                   = "wep_m_avalanche.s3o",
			noSelfDamage            = true,
			range                   = 1100,
			reloadtime              = 1/30,
			smokeTrail              = true,
			soundHit                = "weapon/missile/rocket_hit",
			soundStart              = "weapon/missile/sidewinder",
			startVelocity           = 700,
			sprayAngle				= 100,
			texture2                = "AAsmoketrail",
			tolerance               = 22000,
			tracks                  = true,
			turnRate                = 60000,
			weaponAcceleration      = 2200,
			weaponType              = "MissileLauncher",
			weaponVelocity          = 1850,
		},
	},
	featureDefs            = {
		DEAD  = {
			blocking         = true,
			featureDead      = "HEAP",
			footprintX       = 2,
			footprintZ       = 2,
			object           = "fighter_dead.s3o",
		},
		HEAP  = {
		  blocking         = false,
		  footprintX       = 2,
		  footprintZ       = 2,
		  object           = "debris2x2c.s3o",
		},
	},
}
return { planefighter = unitDef }
