local unitDef = {
	unitname               = "planefighter",
	name                   = "Deserter",
	description            = "Early Response Fighter-Bomber",
	brakerate              = 0.4,
	buildCostMetal         = 200,
	buildPic               = "planefighter.png",
	canFly                 = true,
	canGuard               = true,
	canMove                = true,
	canPatrol              = true,
	canSubmerge            = false,
	category               = "FIXEDWING",
	collide                = false,
	collisionVolumeOffsets = "0 0 5",
	collisionVolumeScales  = "25 8 40",
	collisionVolumeType    = "box",
	selectionVolumeOffsets = "0 0 10",
	selectionVolumeScales  = "50 50 70",
	selectionVolumeType    = "cylZ",
	corpse                 = "DEAD",
	crashDrag              = 0.01,
	cruiseAlt              = 350,
	customParams           = {
		--specialreloadtime = "850",
		--boost_speed_mult = 5,
		--boost_accel_mult = 6,
		--boost_duration = 30, -- frames
		--refuelturnradius = "80",
		requireammo    = "1",
		fighter_pullup_dist = 300,
		reammoseconds    = "3",
		midposoffset   = "0 3 0",
		modelradius    = "5",
		refuelturnradius = "80",
		bait_level_default = 1,
		outline_x = 85,
		outline_y = 85,
		outline_yoff = 16,
		
		ammocount = 3,
		ammotexture_1 = "States/ammostates/hades_aa.png",
		ammotexture_2 = "States/ammostates/generic_bomb.png",
		ammotexture_3 = "States/ammostates/deserter_rockets.png",
		ammoname_1 = "Skyfall Missile (Anti-Air)",
		ammoname_2 = "Medium Bomb",
		ammoname_3 = "Rocket Barrage",
		ammodesc_1 = "Fires a bunch of missiles at air targets. Deserter's speed is reduced by 50% upon firing.",
		ammodesc_2 = "Drops a medium bomb, dealing moderate area damage. Deserter's top speed is reduced by 50%, and a further 50% upon firing.",
		ammodesc_3 = "Fires a barrage of rockets at ground targets at medium range. Deserter has normal speed.",
	},
	explodeAs              = "GUNSHIPEX",
	fireState              = 2,
	floater                = true,
	footprintX             = 2,
	footprintZ             = 2,
	frontToSpeed           = 0,
	iconType               = "fighter",
	idleAutoHeal           = 5,
	idleTime               = 1800,
	maneuverleashlength    = "1280",
	maxAcc                 = 0.5,
	maxDamage              = 350,
	maxRudder              = 0.007,
	maxVelocity            = 7,
	mygravity              = 1,
	noAutoFire             = false,
	noChaseCategory        = "TERRAFORM SATELLITE SUB LAND SINK TURRET SHIP SWIM FLOAT HOVER",
	objectName             = "fighter.s3o",
	script                 = "planefighter.lua",
	selfDestructAs         = "GUNSHIPEX",
	sfxtypes               = {
		explosiongenerators = {
			"custom:MUZZLE_ORANGE",
			"custom:FF_PUFF",
			"custom:BEAMWEAPON_MUZZLE_RED",
			"custom:FLAMER",
		},
	},
	sightDistance          = 900,
	speedToFront           = 0,
	turnRadius             = 150,
	turnRate               = 839,
	weapons                = {
		{
			def                = "MISSILE_AA",
			badTargetCategory  = "GUNSHIP",
			onlyTargetCategory = "FIXEDWING GUNSHIP",
			maxAngleDif        = 180,
		},
		{
			def                = "BOMB",
			onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER SINK UNARMED SUB",
			mainDir            = "0 -1 0",
			maxAngleDif        = 180,
		},
		{
			def                = "ROCKETS",
			onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER SINK UNARMED SUB",
			maxAngleDif        = 80,
		},
	},
	weaponDefs             = {
		CANNON = {
			name                    = "Main Cannon",
			alphaDecay              = 0.1,
			areaOfEffect            = 8,
			burst                   = 6,
			burstrate               = 0.03333334,
			projectiles = 4,
			colormap                = "1 0.95 0.4 1   1 0.95 0.4 1    0 0 0 0.01    1 0.7 0.2 1",
			craterBoost             = 0,
			craterMult              = 0,
			customParams        = {
				light_camera_height = 1200,
				light_color = "0.8 0.76 0.38",
				light_radius = 120,
			},
			damage                  = {
				default = 4,
			},
			explosionGenerator      = "custom:FLASHPLOSION",
			impactOnly              = true,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			intensity               = 0.7,
			interceptedByShieldType = 1,
			noGap                   = false,
			noSelfDamage            = true,
			range                   = 185,
			reloadtime              = 0.3,
			rgbColor                = "1 0.95 0.4",
			separation              = 1.5,
			size                    = 1.75,
			sizeDecay               = 0,
			soundStart              = "weapon/brawler_emg_v2",
			soundStartVolume        = 4,
			sprayAngle              = 1180,
			stages                  = 10,
			tolerance               = 5000,
			turret                  = true,
			weaponType              = "Cannon",
			weaponVelocity          = 500,
		},
		ROCKETS = {
			burst = 12,
			burstRate = 2/30,
			name                    = "Hurricane Surface Attack Rockets",
			areaOfEffect            = 96,
			accuracy				= 1100,
			avoidFriendly           = true,
			canattackground         = true,
			cegTag                  = "rocket_trail_bar",
			collideFriendly         = false,
			craterBoost             = 1,
			craterMult              = 2,
			--cylinderTargeting       = 6,
			customParams        	  = {
				burst = Shared.BURST_RELIABLE,
				light_color = "0.5 0.6 0.6",
				cruisealt = 350,
				airlaunched = 1,
				cruisedist = "250",
				cruiserandomradius = 75,
				cruise_randomizationtype = "circular",
				cruise_nolock = 1,
				cruisetracking = 1,
				cruise_ignoreterrain = 1,
			},
			damage                  = {
				default = 120,
			},
			dance					= 100,
			edgeEffectiveness		= 0.2,
			explosionGenerator      = "custom:DOT_Merl_Explo",
			fireStarter             = 70,
			flightTime              = 7,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 2,
			model                   = "wep_m_avalanche.s3o",
			noSelfDamage            = true,
			range                   = 700,
			reloadtime              = 5.2,
			smokeTrail              = true,
			sprayAngle              = 500,
			soundHit                = "explosion/ex_med4",
			soundStart              = "weapon/missile/deserter_missile_launch",
			startVelocity           = 100,
			texture2                = "darksmoketrail",
			tolerance               = 22000,
			tracks                  = false,
			turnRate                = 20000,
			weaponAcceleration      = 1400,
			weaponType              = "MissileLauncher",
			weaponVelocity          = 750,
		},
		BOMB  = {
			name                    = "Medium Bomb",
			areaOfEffect            = 32,
			avoidFeature            = false,
			avoidFriendly           = false,
			cegTag                  = "KBOTROCKETTRAIL",
			collideFeature          = false,
			collideFriendly         = false,
			craterBoost             = 1,
			craterMult              = 2,
			cylinderTargeting          = 1,

			damage                  = {
				default = 905.1,
			},

			customParams            = {
				light_color = "1.1 0.9 0.45",
				light_radius = 220,
				burst = Shared.BURST_RELIABLE,
			},

			explosionGenerator      = "custom:xamelimpact",
			fireStarter             = 70,
			flightTime              = 3,
			heightmod               = 0,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 2,
			leadlimit               = 0,
			model                   = "wep_b_paveway.s3o",
			leadLimit               = 20,
			range                   = 180,
			reloadtime              = 5,
			smokeTrail              = false,
			soundHit                = "weapon/bomb_hit",
			soundStart              = "weapon/bomb_drop",
			startVelocity           = 200,
			tolerance               = 8000,
			tracks                  = false,
			turnRate                = 2500,
			turret                  = true,
			waterweapon             = true,
			weaponAcceleration      = 50,
			weaponType              = "MissileLauncher",
			weaponVelocity          = 200,
		},
		MISSILE_AA = {
			burst = 6,
			burstRate = 2/30,
			name                    = "Skyfall Missiles",
			areaOfEffect            = 40,
			avoidFriendly           = true,
			accuracy				= 100,
			canattackground         = false,
			cegTag                  = "missiletrailblue",
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			--cylinderTargeting       = 6,
			customParams        	  = {
				burst = Shared.BURST_RELIABLE,
				isaa = "1",
				light_color = "0.5 0.6 0.6",
				reaim_time = 60, -- Fast update not required (maybe dangerous)
				--groundimpact = 1, -- check the distance between ground and projectile? OPTIONAL.
				--proxy = 1, -- check for nearby units?
				--proxydist = 100, -- how far to check for units? Default: spawndist
				--damage_vs_shield = "475",
			},
			damage                  = {
				default = 150.1,
			},
			explosionGenerator      = "custom:WEAPEXP_PUFF",
			fireStarter             = 70,
			flightTime              = 6,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 2,
			model                   = "wep_m_avalanche.s3o",
			noSelfDamage            = true,
			range                   = 1100,
			reloadtime              = 1,
			smokeTrail              = true,
			soundHit                = "weapon/missile/rocket_hit",
			soundStart              = "weapon/missile/sidewinder",
			startVelocity           = 700,
			sprayAngle				= 100,
			texture2                = "AAsmoketrail",
			tolerance               = 22000,
			tracks                  = true,
			turnRate                = 60000,
			weaponAcceleration      = 2200,
			weaponType              = "MissileLauncher",
			weaponVelocity          = 1850,
		},
		AA = {
			burst = 2,
			burstRate = 0.5,
			name                    = "ATA Sidewinder",
			areaOfEffect            = 96,
			avoidFriendly           = true,
			canattackground         = false,
			cegTag                  = "missiletrailblue",
			collideFriendly         = false,
			craterBoost             = 1,
			craterMult              = 2,
			--cylinderTargeting       = 6,
			customParams        	  = {
				burst = Shared.BURST_RELIABLE,
				isaa = "1",
				light_color = "0.5 0.6 0.6",
				reaim_time = 60, -- Fast update not required (maybe dangerous)
				--CAS--
				--numprojectiles1 = 4, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
				--projectile1 = "proliferator_aa",
				--spreadradius1 = 8, -- used in clusters. OPTIONAL. Default: 100.
				--clustervec1 = "evenx", -- accepted values: randomx, randomy, randomz, randomxy, randomxz, randomyz, random. OPTIONAL. default: random.
				--use2ddist = 1, -- should we check 2d or 3d distance? OPTIONAL. Default: 0.
				--spawndist = 870, -- at what distance should we spawn the projectile(s)? REQUIRED.
				--timeoutspawn = 1, -- Can this missile spawn its subprojectiles when it times out? OPTIONAL. Default: 1.
				--vradius1 = 5, -- velocity that is randomly added. covers range of +-vradius. OPTIONAL. Default: 4.2
				--groundimpact = 1, -- check the distance between ground and projectile? OPTIONAL.
				--proxy = 1, -- check for nearby units?
				--proxydist = 100, -- how far to check for units? Default: spawndist
				--damage_vs_shield = "475",
			},

			damage                  = {
				default = 240.1,
			},
			explosionGenerator      = "custom:WEAPEXP_PUFF",
			fireStarter             = 70,
			flightTime              = 7,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 2,
			metalpershot            = 0,
			model                   = "wep_m_avalanche.s3o",
			noSelfDamage            = true,
			range                   = 700,
			reloadtime              = 5.2,
			smokeTrail              = true,
			soundHit                = "weapon/missile/rocket_hit",
			soundStart               = "weapon/missile/sidewinder",
			startVelocity           = 100,
			texture2                = "AAsmoketrail",
			tolerance               = 22000,
			tracks                  = true,
			turnRate                = 40000,
			weaponAcceleration      = 200,
			weaponType              = "MissileLauncher",
			weaponVelocity          = 550,
		},
	},
	featureDefs            = {
		DEAD  = {
			blocking         = true,
			featureDead      = "HEAP",
			footprintX       = 2,
			footprintZ       = 2,
			object           = "fighter_dead.s3o",
		},
		HEAP  = {
		  blocking         = false,
		  footprintX       = 2,
		  footprintZ       = 2,
		  object           = "debris2x2c.s3o",
		},
	},
}
return { planefighter = unitDef }
