return { 
	platetank = {
		unitname                      = "platetank",
		name                          = "Tank Plate",
		description                   = "Parallel Unit Production",
		buildCostMetal                = Shared.FACTORY_PLATE_COST,
		buildDistance                 = Shared.FACTORY_PLATE_RANGE,
		builder                       = true,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 11,
		buildingGroundDecalSizeY      = 11,
		buildingGroundDecalType       = "platetank_aoplane.dds",
		buildoptions                  = {
			"tankcon",
			"tankraid",
			"tankheavyraid",
			"tankriot",
			"tankassault",
			"tankheavyassault",
			"tankarty",
			"tankheavyarty",
			"tankaa",
		},
		buildPic                      = "platetank.png",
		canMove                       = true,
		canPatrol                     = true,
		category                      = "SINK UNARMED",
		corpse                        = "DEAD",
		collisionVolumeOffsets        = "0 10 4",
		collisionVolumeScales         = "72 24 38",
		collisionVolumeType           = "box",
		selectionVolumeOffsets        = "0 2 35",
		selectionVolumeScales         = "80 40 120",
		selectionVolumeType           = "box",
		customParams                  = {
			sortName           = "6",
			solid_factory      = "4",
			default_spacing    = 4,
			aimposoffset       = "0 10 -35",
			midposoffset       = "0 0 -35",
			modelradius        = "50",
			unstick_help       = 1,
			child_of_factory   = "factorytank",
			outline_x = 165,
			outline_y = 165,
			outline_yoff = 27.5,
			buggeroff_offset   = 45,
		},
		energyUse                     = 0,
		explodeAs                     = "FAC_PLATEEX",
		footprintX                    = 6,
		footprintZ                    = 8,
		iconType                      = "padtank",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		levelGround                   = false,
		health                        = 3500,
		maxSlope                      = 15,
		maxWaterDepth                 = 0,
		moveState                     = 1,
		noAutoFire                    = false,
		objectName                    = "plate_tank.s3o",
		script                        = "platetank.lua",
		selfDestructAs                = "FAC_PLATEEX",
		showNanoSpray                 = false,
		sightDistance                 = 273,
		useBuildingGroundDecal        = true,
		workerTime                    = Shared.FACTORY_BUILDPOWER,
		yardMap                       = "oooooo oooooo oooooo oooooo yyyyyy yyyyyy yyyyyy yyyyyy",
		weapons                = {
			{
				def                = "EMG",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weapondefs = {
			EMG = {
				name                    = "Light Autocannon",
				alphaDecay              = 0.7,
				areaOfEffect            = 32,
				craterBoost             = 1,
				craterMult              = 2,
				cegtag					= "light_plasma_trail",
				damage                  = {
					default = 25.01,
				},
				explosionGenerator      = "custom:EMG_HIT",
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 600,
				reloadtime              = 5/30,
				rgbColor                = "1 0.95 0.4",
				separation              = 1.5,
				size                    = 1.7,
				soundHit                = "weapon/cannon/emg_hit",
				soundStart              = "weapon/cannon/cannonfire_001",
				soundStartVolume        = 4,
				stages                  = 10,
				tolerance               = 5000,
				turret                  = true,
				weaponTimer             = 0.1,
				weaponType              = "Cannon",
				weaponVelocity          = 850,
			},
		},
		featureDefs                   = {
			DEAD = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 6,
				footprintZ       = 8,
				object           = "plate_tank_dead.s3o",
				collisionVolumeOffsets = "0 14 -34",
				collisionVolumeScales  = "110 28 44",
				collisionVolumeType    = "box",
			},
			HEAP = {
				blocking         = false,
				footprintX       = 6,
				footprintZ       = 8,
				object           = "debris4x4a.s3o",
			},
		},
	} 
}
