return { 
	raveparty = {
		unitname                      = [[raveparty]],
		name                          = [[Disco Rave Party]],
		description                   = [[Destructive Rainbow Projector]],
		acceleration                  = 0,
		brakeRate                     = 0,
		buildCostMetal                = 60000,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 6,
		buildingGroundDecalSizeY      = 6,
		buildingGroundDecalType       = [[staticheavyarty_aoplane.dds]],
		buildPic                      = [[raveparty.png]],
		category                      = [[SINK]],
		collisionVolumeOffsets        = [[0 0 0]],
		collisionVolumeScales         = [[70 194 70]],
		collisionVolumeType           = [[cylY]],
		corpse                        = [[DEAD]],
		customParams                  = {
			modelradius    = [[35]],
			bait_level_default = 0,
			draw_blueprint_facing = 1,
			superweapon = 1,
			neededLink = 400,
			keeptooltip = [[any string i want]],
			pylonrange  = 280,
		},
		explodeAs                     = [[ATOMIC_BLAST]],
		footprintX                    = 7,
		footprintZ                    = 7,
		highTrajectory                = 2,
		iconType                      = [[mahlazer]],
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		levelGround                   = false,
		losEmitHeight                 = 100,
		maxDamage                     = 16000,
		maxSlope                      = 18,
		maxVelocity                   = 0,
		maxWaterDepth                 = 0,
		noChaseCategory               = [[FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER]],
		objectName                    = [[raveparty.s3o]],
		--onoffable                        = true,
		script                        = [[raveparty.lua]],
		selfDestructAs                = [[ATOMIC_BLAST]],
		sfxtypes                      = {
			explosiongenerators = {
				[[custom:staticheavyarty_SHOCKWAVE]],
				[[custom:staticheavyarty_SMOKE]],
				[[custom:staticheavyarty_FLARE]],
			},
		},
		sightDistance                 = 660,
		turnRate                      = 0,
		useBuildingGroundDecal        = true,
		workerTime                    = 0,
		yardMap                       = [[ooooooo ooooooo ooooooo ooooooo ooooooo ooooooo ooooooo]],
		weapons                       = {
			{
				def                = [[RED_KILLER]],
				onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
			},
			{
				def                = [[ORANGE_ROASTER]],
				onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
			},
			{
				def                = [[YELLOW_SLAMMER]],
				onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
			},
			{
				def                = [[GREEN_STAMPER]],
				onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
			},
			{
				def                = [[BLUE_SHOCKER]],
				onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
			},
			{
				def                = [[VIOLET_SLUGGER]],
				onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
			},
			{
				def                = [[FAKE_TIMEKEEPER]],
				onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP]],
			},
		},
		weaponDefs                    = {
			RED_KILLER = {
				name                    = [[Radioactive Red]],
				accuracy                = 750,
				avoidFeature            = false,
				avoidGround             = false,
				areaOfEffect            = 800,
				craterBoost             = 4,
				craterMult              = 10,
				customParams = {
					script_reload = [[6]],
					light_color = [[1 0.1 0.1]],
					light_radius = 40,
					light_camera_height = 1500,
				},
				damage                  = {
					default = 10000.1,
				},

				edgeeffectiveness       = 0.1,
				explosionGenerator      = [[custom:nukebigland]],
				impulseBoost            = 0,
				impulseFactor           = 2.3,
				interceptedByShieldType = 1,
				myGravity               = 0.18,
				range                   = 10000,
				rgbColor                = [[1 0.1 0.1]],
				reloadtime              = 1/30,
				size                    = 15,
				sizeDecay               = 0.03,
				soundHit                = [[weapon/missile/mininuke_hit]],
				soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
				stages                  = 30,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 1100,
			},
			ORANGE_ROASTER = {
				name                    = [[Orange Obliterator]],
				accuracy                = 750,
				areaOfEffect            = 640,
				craterAreaOfEffect      = 80,
				avoidFeature            = false,
				avoidGround             = false,
				craterBoost             = 0.25,
				craterMult              = 0.5,
				customParams              = {
					script_reload = [[6]],
					numprojectiles1 = 30, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
					projectile1 = "raveparty_orange_secondary",
					--spreadradius1 = 4, -- used in clusters. OPTIONAL. Default: 100.
					clustervec1 = "randomxyz", -- accepted values: randomx, randomy, randomz, randomxy, randomxz, randomyz, random. OPTIONAL. default: random.
					use2ddist = 0, -- should we check 2d or 3d distance? OPTIONAL. Default: 0.
					spawndist = 1000, -- at what distance should we spawn the projectile(s)? REQUIRED.
					timeoutspawn = 1, -- Can this missile spawn its subprojectiles when it times out? OPTIONAL. Default: 1.
					useheight = 1,
					vradius1 = "-5,-3,-5,5,3,5", -- velocity that is randomly added. covers range of +-vradius. OPTIONAL. Default: 4.2
					light_camera_height = 1500,
					light_color = [[0.9 0.3 0]],
					light_radius = 40,
				},
				damage                  = {
					default = 300.1*30,
				},
				edgeeffectiveness       = 0.25,
				explosionGenerator      = [[custom:MEDMISSILE_EXPLOSION]],
				impulseBoost            = 0.2,
				impulseFactor           = 0.1,
				interceptedByShieldType = 1,
				myGravity               = 0.18,
				range                   = 10000,
				rgbColor                = [[0.9 0.3 0]],
				reloadtime              = 1/30,
				size                    = 15,
				sizeDecay               = 0.03,
				soundHit                = [[weapon/cannon/mini_cannon]],
				soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
				stages                  = 30,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 1100,
			},
			ORANGE_SECONDARY = {
				name                    = [[Orange Obliterator Particle]],
				accuracy                = 350,
				alphaDecay              = 0.7,
				areaOfEffect            = 96,
				burnblow                = true,
				craterBoost             = 1,
				craterMult              = 2,

				customParams        = {
					light_camera_height = 1500,
					light_color = [[0.9 0.3 0]],
					light_radius = 40,
				},
				
				damage                  = {
					default = 300.1,
				},

				edgeEffectiveness       = 0.5,
				explosionGenerator      = [[custom:DOT_Pillager_Explo]],
				firestarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				intensity               = 0.7,
				size                    = 5,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 400,
				reloadtime              = 0.5,
				rgbColor                = [[0.9 0.3 0]],
				separation              = 1.5,
				soundHit                = [[weapon/cannon/rhino3]],
				soundStart              = [[weapon/heavy_emg]],
				stages                  = 10,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 550,
			},
			YELLOW_SLAMMER = {
				name                    = [[Yellow Yeeter]],
				accuracy                = 750,
				areaOfEffect            = 360,
				craterAreaOfEffect      = 96,
				avoidFeature            = false,
				avoidGround             = false,
				craterBoost             = 0.5,
				craterMult              = 1,

				customParams = {
					script_reload = [[6]],
					lups_explodelife = 1.0,
					lups_explodespeed = 0.8,
					light_radius = 360,
					blastwave_size = 30,
					blastwave_impulse = 15,
					blastwave_speed = 20,
					blastwave_life = 15,
					blastwave_lossfactor = 0.99,
					blastwave_damage = 60,
					damage_vs_shield = 200,
				},

				damage                  = {
					default = 401.1,
				},
				edgeeffectiveness       = 0.5,
				explosionGenerator      = [[custom:sonic_360]],
				explosionSpeed          = 500,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				myGravity               = 0.18,
				range                   = 10000,
				rgbColor                = [[0.7 0.7 0]],
				reloadtime              = 1/30,
				size                    = 15,
				sizeDecay               = 0.03,
				soundHit                = [[weapon/cannon/earthshaker]],
				soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
				stages                  = 30,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 1100,
			},
			GREEN_STAMPER = {
				name                    = [[Green Mangler]],
				accuracy                = 750,
				areaOfEffect            = 384,
				avoidFeature            = false,
				avoidGround             = false,
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					script_reload = [[6]],
					numprojectiles1 = 40, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
					projectile1 = "raveparty_green_secondary",
					--spreadradius1 = 4, -- used in clusters. OPTIONAL. Default: 100.
					clustervec1 = "randomxyz", -- accepted values: randomx, randomy, randomz, randomxy, randomxz, randomyz, random. OPTIONAL. default: random.
					use2ddist = 0, -- should we check 2d or 3d distance? OPTIONAL. Default: 0.
					spawndist = 1000, -- at what distance should we spawn the projectile(s)? REQUIRED.
					timeoutspawn = 1, -- Can this missile spawn its subprojectiles when it times out? OPTIONAL. Default: 1.
					useheight = 1,
					vradius1 = "-8,-3,-8,8,0,8", -- velocity that is randomly added. covers range of +-vradius. OPTIONAL. Default: 4.2
					light_camera_height = 1500,
					light_color = [[0.1 1 0.1]],
					light_radius = 40,
				},
				damage                  = {
					default = 40*800.1,
				},
				explosionGenerator      = [[custom:MEDMISSILE_EXPLOSION]],
				impulseBoost            = 0.7,
				impulseFactor           = 0.5,
				interceptedByShieldType = 1,
				myGravity               = 0.18,
				range                   = 10000,
				rgbColor                = [[0.1 1 0.1]],
				reloadtime              = 1/30,
				size                    = 15,
				sizeDecay               = 0.03,
				soundHit                = [[explosion/ex_large4]],
				soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
				stages                  = 30,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 1100,
			},
			GREEN_SECONDARY = {
				name                    = [[Perkele]],
				accuracy                = 750,
				areaOfEffect            = 128,
				avoidFeature            = false,
				avoidGround             = false,
				craterBoost             = 80,
				craterMult              = 70,
				customParams            = {
					script_reload = [[6]],
					light_camera_height = 1500,
					light_color = [[0.1 1 0.1]],
					light_radius = 40,
				},
				damage                  = {
					default = 800.1,
				},
				explosionGenerator      = [[custom:implosion_beam_green]],
				impulseBoost            = 0.7,
				impulseFactor           = 0.5,
				interceptedByShieldType = 1,
				myGravity               = 0.18,
				range                   = 10000,
				rgbColor                = [[0.1 1 0.1]],
				reloadtime              = 1/30,
				size                    = 5,
				sizeDecay               = 0.03,
				soundHit                = [[explosion/ex_large4]],
				soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
				stages                  = 30,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 1100,
			},
			BLUE_SHOCKER = {
				name                    = [[Blue Bolter]],
				accuracy                = 750,
				areaOfEffect            = 320,
				avoidFeature            = false,
				avoidGround             = false,
				craterBoost             = 0.25,
				craterMult              = 0.5,
				cegTag                  = [[drp_blue_trail]],

				customParams = {
					script_reload = [[6]],
				},

				damage                  = {
				--[[ huge value to burst Funnelweb shields, since most of DRP's
					power is in effects normally crappy vs them but we don't want
					DRP to arbitrarily suck vs Funnel if the other supers don't ]]
					default        = 30000,
				},

				edgeEffectiveness       = 0.75,
				explosionGenerator      = [[custom:POWERPLANT_EXPLOSION]],
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				myGravity               = 0.18,
				paralyzer               = true,
				paralyzeTime            = 25,
				range                   = 10000,
				rgbColor                = [[0.1 0.1 1]],
				reloadtime              = 1/30,
				size                    = 15,
				sizeDecay               = 0.03,
				soundHit                = [[weapon/more_lightning]],
				soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
				stages                  = 30,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 1100,
			},
			BLUE_FRAGMENT = {
				name                    = [[Bolter Fragment]],
				areaOfEffect            = 120,
				avoidFeature            = true,
				cegTag                  = [[beamweapon_muzzle_purple]],
				commandFire             = true,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					timeslow_damagefactor = 1.5,
					timeslow_overslow_frames = 5*30, --5 seconds before slow decays
					nofriendlyfire = 1,
					light_camera_height = 3500,
					light_color = [[0.5 0.0 0.5]],
					light_radius = 220,
					shield_damage = 150,
				},

				damage                  = {
					default = 200,
				},
				fireStarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				explosionGenerator      = [[custom:riotballplus2_purple_small]],
				range                   = 1100,
				reloadtime              = 4.4,
				myGravity				= 0.09,
				size					= 4,
				rgbColor				= [[0.5 0 0.5]],
				soundHit				= [[weapon/aoe_aura2]],
				soundHitVolume          = 4,
				soundStart              = [[weapon/cannon/funnel_fire]],
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 450,
			},
			VIOLET_SLUGGER = {
				name                    = [[Violent Violet]],
				accuracy                = 750,
				areaOfEffect            = 720,
				craterAreaOfEffect      = 90,
				avoidFeature            = false,
				avoidGround             = false,
				craterBoost             = 0.25,
				craterMult              = 0.5,

				customparams = {
					timeslow_damagefactor = 10,
					nofriendlyfire = "needs hax",
					script_reload = [[6]],
					timeslow_overslow_frames = 2*30, --2 seconds before slow decays
					nofriendlyfire = 1,
					numprojectiles1 = 24, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
					projectile1 = "raveparty_purple_fragment_fake",
					--spreadradius = 8, -- used in clusters. OPTIONAL. Default: 100.
					clustervec1 = "randomxyz", -- accepted values: randomx, randomy, randomz, randomxy, randomxz, randomyz, random. OPTIONAL. default: random.
					keepmomentum1 = 0,
					timeoutspawn = 0,
					vradius1 = "-3,2,-3,3,4,3",
					noairburst = "EI", -- if true, this projectile will skip all airburst checks
					onexplode = "RUOTSI", -- if true, this projectile will cluster when it explodes
					spawndist = 69420, -- at what distance should we spawn the projectile(s)? REQUIRED.
					useheight = 1, -- check the distance between ground and projectile? OPTIONAL.
					stats_damage = 450.1 + (200 * 24),
					shield_damage = 1, -- we want it to impact the shield to cause a lot of projectiles to spawn on it and damage it.
					stats_shield_damage = (200 * 24) + 450.1,
				},
      
				damage                  = {
					default = 450.1,
				},

				edgeeffectiveness       = 0.8,
				explosionGenerator      = [[custom:riotballplus2_purple]],
				explosionScar           = false,
				explosionSpeed          = 6.5,
				impulseBoost            = 0.2,
				impulseFactor           = 0.1,
				interceptedByShieldType = 1,
				myGravity               = 0.18,
				range                   = 10000,
				rgbColor                = [[0.7 0 0.7]],
				reloadtime              = 1/30,
				size                    = 15,
				sizeDecay               = 0.03,
				soundHit                = [[weapon/aoe_aura2]],
				soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
				stages                  = 30,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 1100,
			},
			PURPLE_FRAGMENT = {
				name                    = [[Shield Buster Chaff]],
				areaOfEffect            = 120,
				avoidFeature            = true,
				cegTag                  = [[beamweapon_muzzle_purple]],
				commandFire             = true,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					timeslow_damagefactor = 1.5,
					timeslow_overslow_frames = 5*30, --5 seconds before slow decays
					nofriendlyfire = 1,
					light_camera_height = 3500,
					light_color = [[0.5 0.0 0.5]],
					light_radius = 220,
					shield_damage = 150,
				},

				damage                  = {
					default = 200,
				},
				fireStarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				explosionGenerator      = [[custom:riotballplus2_purple_small]],
				range                   = 1100,
				reloadtime              = 4.4,
				myGravity				= 0.09,
				size					= 4,
				rgbColor				= [[0.5 0 0.5]],
				soundHit				= [[weapon/aoe_aura2]],
				soundHitVolume          = 4,
				soundStart              = [[weapon/cannon/funnel_fire]],
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 450,
			},
			
			PURPLE_FRAGMENT_FAKE = {
				name                    = [[Shield Buster Chaff]],
				areaOfEffect            = 120,
				avoidFeature            = true,
				cegTag                  = [[beamweapon_muzzle_purple]],
				commandFire             = true,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					light_camera_height = 3500,
					light_color = [[0.5 0.0 0.5]],
					light_radius = 220,
					numprojectiles1 = 1, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
					projectile1 = "raveparty_purple_fragment",
					clustervec1 = "derpderpderpderpderpderpderpderpderpderp", -- accepted values: randomx, randomy, randomz, randomxy, randomxz, randomyz, random. OPTIONAL. default: random.
					keepmomentum1 = 1,
					timeoutspawn = 0,
					noairburst = "I belive I can fly...", -- if true, this projectile will skip all airburst checks
					spawndist = 69420, -- at what distance should we spawn the projectile(s)? REQUIRED.
					timeddeploy = 20,
					shield_damage = 200,
					bogus = 1
				},

				damage                  = {
					default = 0,
				},
				fireStarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				myGravity               = 0.1,
				noExplode               = true,
				explosionGenerator      = [[custom:riotballplus2_purple_small]],
				range                   = 700,
				reloadtime              = 3,
				rgbColor				= [[0.7 0 0.7]],
				size					= 4,
				soundHit                = [[nosound]],
				soundHitVolume          = 0,
				soundStart              = [[weapon/cannon/funnel_fire]],
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 350,
			},
			FAKE_TIMEKEEPER = {
				name                    = [[Metronome (Fake Weapon)]],
				accuracy                = 750,
				avoidFeature            = false,
				avoidGround             = false,
				areaOfEffect            = 800,
				craterBoost             = 4,
				craterMult              = 10,
				customParams = {
					script_reload = [[2]],
					light_color = [[1 0.1 0.1]],
					light_radius = 40,
					light_camera_height = 1500,
				},
				damage                  = {
					default = 10000.1,
				},

				edgeeffectiveness       = 0.1,
				explosionGenerator      = [[custom:nukebigland]],
				impulseBoost            = 0,
				impulseFactor           = 2.3,
				interceptedByShieldType = 1,
				myGravity               = 0.18,
				range                   = 10000,
				rgbColor                = [[1 0.1 0.1]],
				reloadtime              = 1/30,
				size                    = 15,
				sizeDecay               = 0.03,
				soundHit                = [[weapon/missile/mininuke_hit]],
				soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
				stages                  = 30,
				turret                  = true,
				weaponType              = [[Cannon]],
				weaponVelocity          = 1100,
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = [[HEAP]],
				footprintX       = 3,
				footprintZ       = 3,
				object           = [[raveparty_dead.s3o]],
			},

			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = [[debris4x4c.s3o]],
			},
		},
	} 
}
