return { 
	shieldfelon = {
		unitname            = "shieldfelon",
		name                = "Guardian",
		description         = "Heavy Shield Assault/Riot",
		acceleration        = 0.75,
		activateWhenBuilt   = true,
		brakeRate           = 1.32,
		buildCostMetal      = 3200,
		buildPic            = "shieldfelon.png",
		canGuard            = true,
		canMove             = true,
		canPatrol           = true,
		category            = "LAND",
		corpse              = "DEAD",
		customParams        = {
			shield_emit_height = 25,
			shield_color_mult = 1.1,
			dontfireatradarcommand = '1',
		},
		explodeAs           = "BIG_UNITEX",
		footprintX          = 3,
		footprintZ          = 3,
		iconType            = "walkersupport",
		idleAutoHeal        = 5,
		idleTime            = 1800,
		leaveTracks         = true,
		losEmitHeight       = 40,
		health              = 7000,
		maxSlope            = 36,
		speed               = 1.5,
		maxWaterDepth       = 22,
		minCloakDistance    = 75,
		movementClass       = "KBOT3",
		noChaseCategory     = "TERRAFORM FIXEDWING SUB",
		objectName          = "shieldfelon.s3o",
		onoffable           = false,
		script              = "shieldfelon.lua",
		selfDestructAs      = "BIG_UNITEX",
		sfxtypes            = {
			explosiongenerators = {
				"custom:lightningplosion_smallbolts_purple",
			},
		},
		sightDistance       = 650,
		trackOffset         = 0,
		trackStrength       = 8,
		trackStretch        = 1,
		trackType           = "ComTrack",
		trackWidth          = 30,
		turnRate            = 1200,
		upright             = true,
		weapons             = {
			{
				def                = "SHIELDGUN",
				badTargetCategory  = "UNARMED",
				onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER LOWFLYING",
				--mainDir            = "0 0 0",
				--maxAngleDif        = 180,
			},
			{
				def                = "SUBLIGHTNING",
				--mainDir            = "0 0 0",
				--maxAngleDif        = 180,
			},
			{
				def                = "SUBLIGHTNING_END",
				--mainDir            = "0 0 0",
				--maxAngleDif        = 180,
			},
			{
				def = "SHIELD",
			},
		},
		weaponDefs          = {
			SHIELD      = {
				name                    = "Energy Shield",
				damage                  = {
					default = 9.79,
				},
				exteriorShield          = true,
				shieldAlpha             = 0.4,
				shieldBadColor          = "1 0.1 0.1 1",
				shieldGoodColor         = "0.1 0.1 1 1",
				shieldInterceptType     = 3,
				shieldPower             = 12000,
				shieldPowerRegen        = 90,
				shieldPowerRegenEnergy  = 35,
				shieldRadius            = 450,
				shieldRepulser          = false,
				shieldStartingPower     = 6000,
				smartShield             = true,
				visibleShield           = false,
				visibleShieldRepulse    = false,
				weaponType              = "Shield",
			},
			SHIELDGUN = {
				name                    = "Heavy Keksian Discharge",
				areaOfEffect            = 8,
				avoidFeature            = false,
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting       = 0.3,
				customParams            = {
					shield_drain = 100,
					light_camera_height = 2500,
					light_color = "0.66 0.32 0.90",
					light_radius = 120,
					chainlightning_searchdist = 250,
					chainlightning_ff = 0,
					chainlightning_num = 1,
					chainlightning_maxtargets = 5,
					chainlightning_index = 2,
					chainlightning_spawn = "shieldfelon_sublightning",
					chainlightning_donttargetfeature = ">w<",
					stats_custom_tooltip_1 = " - Forks to 5 different targets up to 250 elmos away at 10% efficency",
					stats_custom_tooltip_3 = " - Forks bounce to 3 additional targets each",
				},
				damage                  = {
					default        = 150,
				},
				--explosionGenerator      = "custom:flash2purple",
				fireStarter             = 50,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 12,
				interceptedByShieldType = 1,
				range                   = 600,
				reloadtime              = 3/30,
				rgbColor                = "0.5 0 0.7",
				soundStart              = "weapon/constant_electric",
				soundStartVolume        = 27,
				soundTrigger            = true,
				texture1                = "lightning",
				texture2                = "null",
				texture3                = "null",
				texture4                = "null",
				thickness               = 20,
				turret                  = true,
				weaponType              = "LightningCannon",
			},
			SUBLIGHTNING = {
				name                    = "Forked Discharge",
				areaOfEffect            = 30,
				avoidFeature            = false,
				avoidFriendly           = false,
				avoidGround             = false,
				beamTTL                 = 12,
				beamDecay               = 0.85,
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					light_camera_height = 2500,
					light_color = "0.66 0.32 0.90",
					light_radius = 90,
					hideweapon = 1,
					chainlightning_num = 2,
					chainlightning_searchdist = 250,
					chainlightning_ff = 0,
					chainlightning_maxtargets = 5,
					chainlightning_index = 3,
					chainlightning_sub = 1,
					chainlightning_spawn = "shieldfelon_sublightning_end",
					chainlightning_donttargetfeature = "^w^",
				},
				damage                  = {
					default        = 37.5,
				},
				--explosionGenerator      = "custom:flash2purple",
				fireStarter             = 50,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 9,
				interceptedByShieldType = 1,
				range                   = 225,
				reloadtime              = 5/30,
				rgbColor                = "0.75 0 0.75",
				soundHit                = "weapon/constant_electric",
				soundHitVolume          = 9,
				thickness               = 4,
				texture1                = "lightning",
				texture2                = "null",
				texture3                = "null",
				texture4                = "null",
				turret                  = true,
				weaponType              = "LightningCannon",
			},
			SUBLIGHTNING_END = {
				name                    = "Secondary Forked Discharge",
				areaOfEffect            = 30,
				avoidFeature            = false,
				avoidFriendly           = false,
				avoidGround             = false,
				beamTTL                 = 12,
				beamDecay               = 0.85,
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					light_camera_height = 2500,
					light_color = "0.66 0.32 0.90",
					light_radius = 30,
					hideweapon = 1,
				},
				damage                  = {
					default        = 9.375,
				},
				--explosionGenerator      = "custom:flash2purple",
				fireStarter             = 50,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 6,
				interceptedByShieldType = 1,
				range                   = 225,
				reloadtime              = 10/30,
				rgbColor                = "0.66 0 0.66",
				soundHit                = "weapon/constant_electric",
				soundHitVolume          = 9,
				thickness               = 4,
				texture1                = "lightning",
				texture2                = "null",
				texture3                = "null",
				texture4                = "null",
				turret                  = true,
				weaponType              = "LightningCannon",
			},
		},
		featureDefs         = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "shieldfelon_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},
	} 
}
