shiparty = {
	unitname               = "shiparty",
	name                   = "Dominion Destroyer",
	description            = "Boob Supremecy Vessel", -- Okay??
	acceleration           = 0.25,
	activateWhenBuilt      = true,
	brakeRate              = 1.7,
	buildCostMetal         = 1000,
	builder                = false,
	buildPic               = "shiparty.png",
	canMove                = true,
	category               = "SHIP",
	--collisionVolumeOffsets = "-33 0 -75",
	collisionVolumeScales  = "60 47 137",
	collisionVolumeType    = "ellipsoid",
	corpse                 = "DEAD",

	customParams           = {
		midposoffset = "0 0 -20",
		aimposoffset = "0 0 -20",
		extradrawrange = 200,
		modelradius    = 65,
		modelheight    = 50,
		turnatfullspeed = "1",
		outline_x = 160,
		outline_y = 160,
		outline_yoff = 25,
	},

	explodeAs              = "BIG_UNITEX",
	floater                = true,
	footprintX             = 4,
	footprintZ             = 4,
	iconType               = "shiplightcarrier",
	idleAutoHeal           = 5,
	idleTime               = 1800,
	losEmitHeight          = 25,
	health                 = 6800,
	speed                  = 2.25,
	minWaterDepth          = 10,
	movementClass          = "BOAT4",
	moveState              = 0,
	noChaseCategory        = "TERRAFORM FIXEDWING GUNSHIP TOOFAST",
	objectName             = "boat-hardpoint.dae",
	script                 = "shiparty.lua",
	selfDestructAs         = "BIG_UNITEX",
	sightDistance          = 660,
	turninplace            = 0,
	turnRate               = 370,
	waterline              = 0,

	weapons                = {
		{
			def                = "PLASMA",
			badTargetCategory  = "GUNSHIP",
			onlyTargetCategory = "SWIM LAND SHIP SINK TURRET FLOAT GUNSHIP HOVER",
		},
	},

	weaponDefs             = {
		PLASMA = {
			name                    = "Railgun Artillery", -- wish this had more guns, that'd be fun.
			accuracy                = 480,
			alphadecay			  = 1.5,
			areaOfEffect            = 96,
			craterBoost             = 0,
			craterMult              = 3,
			colorMap				= [[0.7843 0.0627 0.1803  0 0.1843 0.4235  0.7294 0.04705 0.1843  0 0.125 0.3568]],
			cegtag                  = "waketrail_small",
			customParams        = {
				light_camera_height = 1400,
				light_color = "0.80 0.54 0.23",
				light_radius = 230,
				reveal_unit = 20,
				armorpiercing = 0.50,
			},
			damage                  = {
				default = 450.1,
			},
			edgeEffectiveness       = 0.1,
			explosionGenerator      = "custom:bigbulletimpact",
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 1,
			myGravity               = 0.1,
			noSelfDamage            = true,
			range                   = 1900,
			reloadtime              = 1.5,
			sizeDecay				= -1.4,
			seperation				= 8,
			soundHit                = "explosion/ex_small14",
			soundStart              = "weapon/cannon/amphsupport_fire",
			stages                  = 15,
			turret                  = true,
			weaponType              = "Cannon",
			weaponVelocity          = 650,
			waterWeapon             = true,
		},
	},
	featureDefs            = {

		DEAD  = {
			blocking         = false,
			featureDead      = "HEAP",
			footprintX       = 4,
			footprintZ       = 4,
			object           = "boat-hardpoint-dead.dae",
		},

		HEAP  = {
			blocking         = false,
			footprintX       = 4,
			footprintZ       = 4,
			object           = "debris4x4b.s3o",
		},

	},
}

return { shiparty = shiparty }
