local shiplightcarrier = {
	unitname               = "shiplightcarrier",
	name                   = "Siren",
	description            = "Destroyer (Riot/Assault)",
	acceleration           = 0.384,
	activateWhenBuilt      = true,
	brakeRate              = 0.5,
	buildCostMetal         = 800,
	builder                = false,
	buildPic               = "shiplightcarrier.png",
	canGuard               = true,
	canMove                = true,
	canPatrol              = true,
	canManualFire          = true,
	category               = "SHIP",
	collisionVolumeOffsets = "0 6 0",
	collisionVolumeScales  = "55 55 110",
	collisionVolumeType    = "ellipsoid",
	corpse                 = "DEAD",
	--Core_color.dds Core_other.dds
	customParams           = {
		modelradius    = "55",
		turnatfullspeed = "1",
		extradrawrange = 800,
		outline_x = 160,
		outline_y = 160,
		outline_yoff = 25,
	},

	explodeAs              = "BIG_UNITEX",
	floater                = true,
	footprintX             = 4,
	footprintZ             = 4,
	iconType               = "shipassault",
	idleAutoHeal           = 5,
	idleTime               = 1800,
	losEmitHeight          = 25,
	health                 = 6800,
	speed                  = 60,
	minCloakDistance       = 75,
	minWaterDepth          = 5,
	movementClass          = "BOAT4",
	noAutoFire             = false,
	noChaseCategory        = "TERRAFORM FIXEDWING SATELLITE SUB SINK TURRET",
	objectName             = "shipassault.s3o",
	script                 = "shiplightcarrier.lua",
	selfDestructAs         = "BIG_UNITEX",

	sfxtypes               = {
		explosiongenerators = {
			"custom:sonicfire_80",
			"custom:emg_shells_l",
		},
	},

	sightDistance          = 440,
	turninplace            = 0,
	turnRate               = 240,
	workerTime             = 0,

	weapons                = {
		{
			def                = "BISCUIT_GUN",
			badTargetCategory  = "FIXEDWING",
			onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			mainDir            = "0 -1 0",
			maxAngleDif        = 240,
		},

		{
			def                = "CANDY",
			badTargetCategory  = "GUNSHIP",
			onlyTargetCategory = "SWIM LAND SHIP SINK TURRET FLOAT GUNSHIP HOVER",
		},
	},


	weaponDefs             = {
		BISCUIT_GUN  = {
			name                    = "High Intensity Scattergun",
			areaOfEffect            = 30,
			avoidFeature            = false,
			canattackground         = true,
			collideFriendly         = false,
			coreThickness           = 0.8,
			craterBoost             = 0,
			craterMult              = 0,
			projectiles				= 8,
			burst					= 2,
			burstRate				= 10/30,
			sprayangle				= 1390,
			edgeeffectiveness		= 0.4,
			minIntensity            = 0.5,
			customParams        = {
				light_camera_height = 1800,
				light_radius = 160,
				combatrange	= 300,
			},

			damage                  = {
				default = 70.1,
			},

			duration                = 0.1,
			explosionGenerator      = "custom:beamlaser_hit_emerald",
			fireStarter             = 50,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 1,
			range                   = 520,
			reloadtime              = 3,
			rgbColor                = "0.043 0.7 0.274",
			soundHit                = "weapon/laser/emerald_hit",
			soundStart              = "weapon/laser/emerald_fire",
			soundStartVolume        = 0.7,
			soundTrigger            = false,
			thickness               = 4.25,
			tolerance               = 10000,
			turret                  = true,
			largebeamlaser          = true,
			texture1                = "lightlaser",
			texture2                = "flare",
			texture3                = "flare",
			beamDecay               = 0.8,
			beamBurst               = true,
			beamTTL                 = 13,
			weaponType              = "BeamLaser",
			waterweapon             = true
			--weaponVelocity          = 880,
		},
		CANDY      = {
			name                    = "Launch Drones",
			craterBoost             = 0,
			craterMult              = 0,
			avoidGround             = false,
			avoidFriendly           = false,
			avoidFeature            = false,
			collideFriendly         = false,
			commandfire             = true,
			customParams            = {
				is_unit_weapon = 1,
				manualfire = 1,
				light_camera_height = 500,
				light_color = "0 .8 1",
				light_radius = 120,
				stats_hide_damage = 1,
				stats_custom_tooltip_1 = " - Launches all stockpiled drones at the target",
				stats_custom_tooltip_entry_1 = "",
				drone_launch = "boobs are soft and warm",
				drone_launch_rate = 20,
			},
			damage                  = {
				default = 0,
			},
			explosionGenerator      = "custom:BEAMWEAPON_HIT_ORANGE",
			impulseBoost            = 0,
			impulseFactor           = 0,
			impactOnly              = true,
			interceptedByShieldType = 1,
			myGravity               = 0.05,
			range                   = 5000,
			reloadtime              = 15,
			soundStart              = "misc/teleport",
			turret                  = true,
			weaponType              = "Cannon",
			weaponVelocity          = 2250,
			waterweapon         	= true,
		},
	},
	featureDefs            = {
		DEAD = {
			blocking         = false,
			featureDead      = "HEAP",
			footprintX       = 4,
			footprintZ       = 4,
			object           = "shipassault_dead.s3o",
		},
		HEAP = {
			blocking         = false,
			footprintX       = 4,
			footprintZ       = 4,
			object           = "debris4x4a.s3o",
		},
	},
} 
return {shiplightcarrier = shiplightcarrier}
