shiplightcarrier = {
	unitname               = "shiplightcarrier",
	name                   = "Dominion Destroyer",
	description            = "Boob Supremecy Vessel",
	acceleration           = 0.25,
	activateWhenBuilt      = true,
	brakeRate              = 1.7,
	buildCostMetal         = 1200,
	builder                = false,
	buildPic               = "shiplightcarrier.png",
	canMove                = true,
	category               = "SHIP",
	collisionVolumeOffsets = "0 1 3",
	collisionVolumeScales  = "151 47 67",
	collisionVolumeType    = "ellipsoid",
	corpse                 = "DEAD",

	customParams           = {
		extradrawrange = 200,
		modelradius    = 75,
		turnatfullspeed = "1",
		outline_x = 160,
		outline_y = 160,
		outline_yoff = 25,
	},

	explodeAs              = "BIG_UNITEX",
	fireState              = 0,
	floater                = true,
	footprintX             = 4,
	footprintZ             = 4,
	iconType               = "shiplightcarrier",
	idleAutoHeal           = 5,
	idleTime               = 1800,
	losEmitHeight          = 25,
	health                 = 6800,
	speed                  = 1.4,
	minWaterDepth          = 10,
	movementClass          = "BOAT4",
	moveState              = 0,
	noChaseCategory        = "TERRAFORM FIXEDWING GUNSHIP TOOFAST",
	objectName             = "boat-hardpoint.dae",
	script                 = "shiplightcarrier.lua",
	selfDestructAs         = "BIG_UNITEX",
	sightDistance          = 660,
	turninplace            = 0,
	turnRate               = 370,
	waterline              = 0,

	weapons                = {
		{
			def                = "BOOBS",
			badTargetCategory  = "GUNSHIP",
			onlyTargetCategory = "SWIM LAND SHIP SINK TURRET FLOAT GUNSHIP HOVER",
		},
	},

	weaponDefs             = {
		BOOBS      = {
			name                    = "Launch Drones",
			craterBoost             = 0,
			craterMult              = 0,
			avoidGround             = false,
			avoidFriendly           = false,
			avoidFeature            = false,
			collideFriendly         = false,
			commandfire             = true,
			customParams            = {
				is_unit_weapon = 1,
				manualfire = 1,
				light_camera_height = 500,
				light_color = "0 .8 1",
				light_radius = 120,
				stats_hide_damage = 1,
				stats_custom_tooltip_1 = " - Launches all stockpiled drones at the target",
				stats_custom_tooltip_entry_1 = "",
				drone_launch = "boobs are soft and warm",
				drone_launch_rate = 10,
			},
			damage                  = {
				default = 0,
			},
			explosionGenerator      = "custom:BEAMWEAPON_HIT_ORANGE",
			impulseBoost            = 0,
			impulseFactor           = 0,
			impactOnly              = true,
			interceptedByShieldType = 1,
			myGravity               = 0.05,
			range                   = 5000,
			reloadtime              = 15,
			soundStart              = "misc/teleport",
			turret                  = true,
			weaponType              = "Cannon",
			weaponVelocity          = 2250,
			waterweapon         	= true,
		},
	},
	featureDefs            = {

		DEAD  = {
			blocking         = false,
			featureDead      = "HEAP",
			footprintX       = 4,
			footprintZ       = 4,
			object           = "shiplightcarrier_dead.s3o",
		},

		HEAP  = {
			blocking         = false,
			footprintX       = 4,
			footprintZ       = 4,
			object           = "debris4x4b.s3o",
		},

	},
}

return { shiplightcarrier = shiplightcarrier }
