return { 
	shipcarrier = {
		unitname               = "shipcarrier",
		name                   = "Reef",
		description            = "Aircraft Carrier, stockpiles disarm missiles at 7.5 m/s",
		acceleration           = 0.21,
		activateWhenBuilt      = true,
		brakeRate              = 0.56,
		buildCostMetal         = 7000,
		builder                = false,
		buildPic               = "shipcarrier.png",
		canMove                = true,
		--canManualFire          = true,
		category               = "SHIP",
		CollisionSphereScale   = 0.6,
		collisionVolumeOffsets = "10 -10 0",
		collisionVolumeScales  = "80 80 240",
		collisionVolumeType    = "CylZ",
		corpse                 = "DEAD",
		customParams           = {
			midposoffset   = "0 -10 0",
			modelradius    = "80",
			stockpiletime  = "40",
			stockpilecost  = "300",
			priority_misc = 2, -- High
			extradrawrange = 3000,
			ispad         = 1,
			pad_bp = 40,
			pad_count     = 8,
			outline_x = 300,
			outline_y = 300,
			outline_yoff = 55,
			isradar        = 1,
			no_auto_keep_target = 1,
		},
		energyUse              = 7.5,
		explodeAs              = "ATOMIC_BLASTSML",
		fireState              = 0,
		floater                = true,
		footprintX             = 5,
		footprintZ             = 5,
		iconType               = "shipcarrier",
		health                 = 11000,
		speed                  = 42,
		minWaterDepth          = 10,
		movementClass          = "BOAT5",
		noAutoFire             = false,
		objectName             = "shipcarrier.dae",
		script                 = "shipcarrier.lua",
		radarDistance          = 3000, -- consistant with anti
		radarEmitHeight        = 250,
		selfDestructAs         = "ATOMIC_BLASTSML",
		sfxtypes               = {
			explosiongenerators = {
				"custom:xamelimpact",
				"custom:ROACHPLOSION",
				"custom:shellshockflash",
			},
		},
		showNanoSpray          = false,
		sightDistance          = 900,
		turninplace            = 0,
		turnRate               = 372,
		waterline              = 20,
		weapons                = {
			{
				def                = "DISARM_ROCKET",
				badTargetCategory  = "SWIM LAND SUB SHIP HOVER GUNSHIP FIXEDWING",
				onlyTargetCategory = "SWIM LAND SUB SINK TURRET FLOAT SHIP HOVER GUNSHIP FIXEDWING",
			},
			{
				def = "AMD_ROCKET",
			},
		},
		weaponDefs             = {
			DISARM_ROCKET        = {
				name                    = "Disarm Missile",
				areaOfEffect            = 280,
				avoidFriendly           = false,
				collideFriendly         = false,
				commandfire             = true,
				cegTag                  = "bigdisarmtrail",
				--commandfire             = true,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					burst = Shared.BURST_RELIABLE,
					combatrange = 950,
					disarmDamageMult = 1.0,
					disarmDamageOnly = 1,
					disarmTimer      = 10, -- seconds
					--radar_homing_distance = 600,
					light_color = "1 1 1",
					cruisealt = 1300,
					cruisedist = 400,
					--cruisetracking = true,
					reveal_unit = 10,
				},

				damage                  = {
					default = 42000,
				},
				edgeEffectiveness       = 1,
				explosionGenerator      = "custom:DISARMMISSILE_EXPLOSION",
				fireStarter             = 0,
				flightTime              = 10,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				model                   = "wep_empmissile.s3o",
				noSelfDamage            = true,
				range                   = 3000,
				reloadtime              = 5,
				smokeTrail              = true,
				soundHit                = "weapon/missile/emp_missile_hit",
				soundStart              = "weapon/missile/tacnuke_launch",
				stockpile               = true,
				stockpileTime           = 10^5,
				tolerance               = 4000,
				tracks                  = true,
				startVelocity           = 200,
				turnrate                = 30000,
				waterWeapon             = false,
				weaponAcceleration      = 400,
				weaponTimer             = 1.4,
				weaponType              = "StarburstLauncher",
				weaponVelocity          = 1200,
			},
			AMD_ROCKET = {
				name                    = "Anti-Nuke Missile Fake",
				areaOfEffect            = 420,
				avoidFriendly           = false,
				avoidGround             = false,
				avoidFeature            = false,
				collideFriendly         = false,
				collideGround           = false,
				collideFeature          = false,
				coverage                = 100000,
				craterBoost             = 1,
				craterMult              = 2,
				customParams            = {
					restrict_in_widgets = 1,
					reaim_time = 15,
					nuke_coverage = 2500,
				},
				damage                  = {
					default = 1500,
				},
				--spawning the intercept explosion is handled by exp_nuke_effect_chooser.lua
				explosionGenerator      = "custom:lrpc_expl",
				fireStarter             = 100,
				flightTime              = 20,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				interceptor             = 1,
				model                   = "staticantinuke_projectile.s3o",
				noSelfDamage            = true,
				range                   = 3800,
				reloadtime              = 4,
				smokeTrail              = true,
				soundHit                = "weapon/missile/vlaunch_hit",
				soundStart              = "weapon/missile/missile_launch",
				startVelocity           = 400,
				tolerance               = 4000,
				tracks                  = true,
				turnrate                = 65535,
				weaponAcceleration      = 800,
				weaponTimer             = 0.4,
				weaponType              = "StarburstLauncher",
				weaponVelocity          = 1600,
			},
		},
		featureDefs            = {
			DEAD  = {
				CollisionSphereScale   = 0.6,
				collisionVolumeOffsets = "-5 -10 0",
				collisionVolumeScales  = "80 80 240",
				collisionVolumeType    = "CylZ",
				blocking         = false,
				featureDead      = "HEAP",
				footprintX       = 6,
				footprintZ       = 6,
				object           = "shipcarrier_dead.dae",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 6,
				footprintZ       = 6,
				object           = "debris4x4b.s3o",
			},
		},
	}
}
