return { 
	spiderskirm = {
		unitname               = "spiderskirm",
		name                   = "Twilight",
		description            = "Skirmisher Spider (Indirect Line Fire)",
		acceleration           = 0.234,
		brakeRate              = 1.38,
		buildCostMetal         = 300,
		buildPic               = "spiderskirm.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND",
		corpse                 = "DEAD",
		customParams           = {
			turnatfullspeed = "1",
			modelradius     = "24",
		},
		explodeAs              = "BIG_UNITEX",
		footprintX             = 3,
		footprintZ             = 3,
		iconType               = "spiderskirm",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		leaveTracks            = true,
		health                 = 750,
		maxSlope               = 72,
		speed                  = 2.1,
		maxWaterDepth          = 22,
		movementClass          = "TKBOT3",
		noChaseCategory        = "TERRAFORM FIXEDWING GUNSHIP SATELLITE SUB",
		objectName             = "recluse.s3o",
		script                 = "spiderskirm.lua",
		selfDestructAs         = "BIG_UNITEX",
		sightDistance          = 627,
		trackOffset            = 0,
		trackStrength          = 10,
		trackStretch           = 1,
		trackType              = "ChickenTrackPointyShort",
		trackWidth             = 52,
		turnRate               = 1400,
		weapons                = {
			{
				def                = "ADV_ROCKET",
				onlyTargetCategory = "LAND SINK TURRET SHIP SWIM FLOAT HOVER",
			},
		},
		weaponDefs             = {
			ADV_ROCKET = {
				name                    = "Disruptor Rocket",
				areaOfEffect            = 48,
				cegTag                  = "missiletrailpurple",
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					light_camera_height = 2500,
					light_color = "0.90 0.65 0.30",
					light_radius = 250,
					numprojectiles1 = 1,
					projectile1 = "spiderskirm_disruptorbomb",
					use2ddist = 1,
					keepmomentum1 = 0,
					spawndist = 180,
					timeoutspawn = 0, 
					velspread1 = "-1.27, -5, -1.27, _, -3, _",
					clustercharges = 10,
					clusterdelay = 3,
					cruisealt = 200,
					airlaunched = 1,
					cruisedist = -1,
					timeslow_damagefactor = 2.5,
					reveal_unit = 5,
				},
				damage                  = {
					default = 75.01*7,
				},
				edgeEffectiveness       = 0.5,
				fireStarter             = 70,
				flightTime              = 4,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				model                   = "recluse_missile.s3o",
				noSelfDamage            = true,
				predictBoost            = 0.75,
				range                   = 700,
				reloadtime              = 4,
				smokeTrail              = false,
				soundHit                = "weapon/laser/small_laser_fire3",
				soundHitVolume          = 2.2,
				soundStart              = "weapon/missile/missile_fire4",
				soundTrigger            = true,
				startVelocity           = 125,
				trajectoryHeight        = 2,
				turnRate                = 55000,
				turret                  = true,
				weaponAcceleration      = 150,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 450,
			},
			DISRUPTORBOMB = {
				name                    = "Disruptor Bomblet",
				accuracy                = 200,
				areaOfEffect            = 140,
				cegTag                  = "beamweapon_muzzle_purple",
				craterBoost             = 0,
				craterMult              = 0,
				customparams = {
					timeslow_damagefactor = 2.5,
					timeslow_overslow_frames = 3*30,
					nofriendlyfire = 1,
				},
				damage                  = {
					default = 75.01,
				},
				explosionGenerator      = "custom:riotballplus2_purple_small120",
				fireStarter             = 180,
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0.2,
				interceptedByShieldType = 2,
				myGravity               = 1,
				range                   = 700,
				reloadtime              = 1.8,
				size                    = 5,
				rgbcolor                = "0.9 0.1 0.9",
				soundHit                = "weapon/aoe_aura2",
				soundHitVolume          = 3.5,
				stages                  = 7,
				soundTrigger            = true,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 340,
			},
		},
		
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				collisionVolumeOffsets = "0 0 0",
				collisionVolumeScales  = "50 30 50",
				collisionVolumeType    = "ellipsoid",
				object           = "recluse_wreck.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = "debris3x3a.s3o",
			},
		},
	} 
}
