return { 
	spiderassault = {
		unitname               = "spiderassault",
		name                   = "Hermit", -- TODO: Name.
		description            = "All Terrain Assault Bot",
		acceleration           = 0.54,
		autoheal               = 20,
		brakeRate              = 1.32,
		buildCostMetal         = 225,
		buildPic               = "spiderassault.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND",
		collisionVolumeOffsets = "0 -3 0",
		collisionVolumeScales  = "24 30 24",
		collisionVolumeType    = "cylY",
		corpse                 = "DEAD",
		customParams           = {
			bait_level_default = 0,
			modelradius    = "12",
			cus_noflashlight = 1,
		},
		explodeAs              = "BIG_UNITEX",
		footprintX             = 2,
		footprintZ             = 2,
		iconType               = "spiderassault",
		leaveTracks            = true,
		health                 = 2100,
		maxSlope               = 36,
		speed                  = 2.0,
		maxWaterDepth          = 22,
		movementClass          = "TKBOT3",
		--highTrajectory         = 2,
		noChaseCategory        = "TERRAFORM FIXEDWING SATELLITE SUB DRONE",
		objectName             = "hermit.s3o",
		selfDestructAs         = "BIG_UNITEX",
		script                 = "spiderassault.lua",
		sfxtypes               = {
			explosiongenerators = {
				"custom:RAIDMUZZLE",
				"custom:RAIDDUST",
				"custom:THUDDUST",
			},
		},
		sightDistance          = 440,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ChickenTrackPointy",
		trackWidth             = 30,
		turnRate               = 1920,
		weapons                = {
			{
				def                = "THUD_WEAPON",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "THUD_WEAPON",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs             = {
			THUD_WEAPON = {
				name                    = "Plasma Cannon",
				areaOfEffect            = 36,
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					light_camera_height = 1800,
					light_color = "0.80 0.54 0.23",
					light_radius = 200,
				},
				damage                  = {
					default = 150.01,
				},
				explosionGenerator      = "custom:MARY_SUE",
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 410,
				reloadtime              = 2.0,
				soundHit                = "weapon/cannon/cannonfire_004",
				soundStart              = "weapon/cannon/med_rifle_fire",
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 800,
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "hermit_wreck.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},
	} 
}
