return { 
	spiderantiheavy = {
		name                  = "Shade",
		description           = "Cloaked Scout/Anti-Heavy",
		acceleration          = 0.9,
		activateWhenBuilt     = true,
		brakeRate             = 5.4,
		buildPic              = "spiderantiheavy.png",
		canGuard              = true,
		canMove               = true,
		canPatrol             = true,
		canManualFire		  = true,
		category              = "LAND",
		cloakCost              = 7,
		cloakCostMoving        = 20,
		selectionVolumeOffsets = "0 0 0",
		selectionVolumeScales  = "45 45 45",
		selectionVolumeType    = "ellipsoid",
		corpse                = "DEAD",
		customParams          = {
			bait_level_default = 2,
			dontfireatradarcommand = '1',
			cus_noflashlight = 1,
			cloakregen	= 10,
			recloaktime 	   = 240,
		},
		decloakOnFire         = false,
		explodeAs             = "BIG_UNITEX",
		fireState             = 0,
		footprintX            = 2,
		footprintZ            = 2,
		health                = 450,
		iconType              = "spiderspecialscout",
		leaveTracks           = true,
		initCloaked           = true,
		maxSlope              = 36,
		maxWaterDepth         = 22,
		metalCost             = 1000,
		minCloakDistance      = 60,
		movementClass         = "TKBOT2",
		moveState             = 0,
		noChaseCategory       = "TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET",
		objectName            = "infiltrator.s3o",
		script                = "spiderantiheavy.lua",
		selfDestructAs        = "BIG_UNITEX",
		sightDistance         = 650,
		speed                 = 3.0,
		trackOffset           = 0,
		trackStrength         = 8,
		trackStretch          = 1,
		trackType             = "ChickenTrackPointyShort",
		trackWidth            = 45,
		turnRate              = 2160,
		weapons               = {
			{
				def                = "spy",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER FIXEDWING GUNSHIP",
			},
			{
				def                = "sensorhack",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER FIXEDWING GUNSHIP",
			},
		},
		weaponDefs            = {
			spy = {
				name                    = "Electro-Stunner",
				areaOfEffect            = 8,
				collideFriendly         = false,
				burst                   = 10,
				burstrate               = 1/30,
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					burst = Shared.BURST_RELIABLE,
					light_color = "1.85 1.85 0.45",
					light_radius = 300,
				},
				damage                  = {
					default        = 2000.1,
				},
				duration                = 8,
				explosionGenerator      = "custom:YELLOW_LIGHTNINGPLOSION",
				fireStarter             = 0,
				heightMod               = 1,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 12,
				interceptedByShieldType = 1,
				paralyzer               = true,
				paralyzeTime            = 20,
				range                   = 140,
				reloadtime              = 20,
				rgbColor                = "1 1 0.25",
				soundStart              = "weapon/LightningBolt",
				soundTrigger            = true,
				targetborder            = 0.9,
				texture1                = "lightning",
				thickness               = 10,
				tolerance               = 10000,
				turret                  = true,
				weaponType              = "LightningCannon",
				weaponVelocity          = 450,
			},
			sensorhack = {
				name                    = "Sensor Exploiter",
				areaOfEffect            = 8,
				avoidFriendly           = false,
				avoidFeature            = false,
				collideFriendly         = false,
				collideFeature			= false,
				coreThickness			= 0,
				commandfire             = true,
				--cegTag                  = "orangelaser",
				craterBoost             = 0,
				craterMult              = 0,
				customParams        = {
					light_radius = 120,
					stats_hide_damage = 1,
					sensorsteal = 20,
					sensortag = 20,
					norealdamage = 1,
				},
				damage                  = {
					default = 0,
				},
				explosionGenerator      = "",
				fireStarter             = 0,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 0,
				lodDistance             = 10000,
				minIntensity            = 1,
				noSelfDamage            = true,
				range                   = 700,
				reloadtime              = 10,
				rgbColor                = "1 0.25 0",
				soundStart              = "weapon/laser/pulse_laser2",
				soundStartVolume		= 45,
				thickness               = 0,
				tolerance               = 10000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "BeamLaser",
				weaponVelocity          = 2000,
			},
		},
		featureDefs           = {
			DEAD = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "Infiltrator_wreck.s3o",
			},
			HEAP = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2a.s3o",
			},
		},
	} 
}
