return { 
	staticheavyarty = {
		unitname                      = "staticheavyarty",
		name                          = "Liberator",
		description                   = "Canister Barrage Artillery",
		buildCostMetal                = 10500,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 6,
		buildingGroundDecalSizeY      = 6,
		buildingGroundDecalType       = "staticheavyarty_aoplane.dds",
		buildPic                      = "staticheavyarty.png",
		category                      = "SINK",
		collisionVolumeOffsets        = "0 -20 0",
		collisionVolumeScales         = "90 80 90",
		collisionVolumeType           = "cylY",
		corpse                        = "DEAD",
		customParams                  = {
			aimposoffset = "0 20 0",
			midposoffset   = "0 20 -45",
			modelradius    = "35",
			selectionscalemult = 1,
    		superweapon    = 1,
    		neededlink     = 250,
   			pylonrange     = 150,
			outline_x = 270,
			outline_y = 270,
			outline_yoff = 90,
			bait_level_default = 4,
		},
		explodeAs                     = "ATOMIC_BLAST",
		footprintX                    = 4,
		footprintZ                    = 4,
		iconType                      = "lrpc",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		levelGround                   = false,
		losEmitHeight                 = 90,
		maxDamage                     = 10500,
		maxSlope                      = 18,
		maxWaterDepth                 = 0,
		minCloakDistance              = 150,
		noChaseCategory               = "FIXEDWING LAND SHIP SWIM GUNSHIP SUB HOVER",
		objectName                    = "armbrtha.dae",
		script                        = "staticheavyarty.lua",
		selfDestructAs                = "ATOMIC_BLAST",
		sfxtypes                      = {
			explosiongenerators = {
				"custom:staticheavyarty_SHOCKWAVE",
				"custom:staticheavyarty_SMOKE",
				"custom:staticheavyarty_FLARE",
			},
		},
		sightDistance                 = 660,
		selectionVolumeScales  = "90 90 90",
		selectionVolumeType    = "ellipsoid",
		useBuildingGroundDecal        = true,
		yardMap                       = "oooo oooo oooo oooo",
		weapons                       = {
			{
				def                = "PLASMA",
				badTargetCategory  = "LAND SHIP HOVER SWIM",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER",
			},
		},
		weaponDefs                    = {
			tritary = {
				name                    = "High Energy Plasma",
				alphaDecay              = 0.7,
				areaOfEffect            = 176,
				craterBoost             = 0,
				craterMult              = 3.2,
				cegtag                  = "waketrail_small",
				--colorMap				= "0 0.1843 0.4235  0.7294 0.04705 0.1843  0 0.125 0.3568",
				customParams        = {
					lups_noshockwave = "1",
					light_camera_height = 1600,
					light_color = "0.8 0.76 0.38",
					light_radius = 110,
				},
				damage                  = {
					default = 850.01,
				},
				explosionScar           = false,
				edgeEffectiveness       = 0.5,
				explosionGenerator      = "custom:lrpc_expl", --"custom:artillery_explosion",
				firestarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				mygravity				= 0.5,
				noSelfDamage            = true,
				range                   = 275,
				reloadtime              = 0.5,
				rgbColor                = "1 0.95 0.4",
				seperation				= 1,
				sizeDecay				= -1.4,
				soundHit                = "weapon/cannon/rhino4",
				soundStart              = "weapon/heavy_emg",
				stages                  = 15,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 550,
			},
			secondary = {
				name                    = "Unstable Plasma",
				accuracy                = 350,
				alphaDecay              = 0.7,
				areaOfEffect            = 0,
				burnblow                = true,
				craterBoost             = 0.15,
				craterMult              = 0.3,
				customParams        = {
					lups_noshockwave = "1",
					light_camera_height = 1600,
					light_color = "0.8 0.76 0.38",
					light_radius = 110,
					numprojectiles1 = 6, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
					projectile1 = "staticheavyarty_tritary",
					--spreadradius1 = 4, -- used in clusters. OPTIONAL. Default: 100.
					clustervec1 = "randomxyz", -- accepted values: randomx, randomy, randomz, randomxy, randomxz, randomyz, random. OPTIONAL. default: random.
					use2ddist = 0, -- should we check 2d or 3d distance? OPTIONAL. Default: 0.
					spawndist = 1200, -- at what distance should we spawn the projectile(s)? REQUIRED.
					keepmomentum1 = true,
					timeoutspawn = 1, -- Can this missile spawn its subprojectiles when it times out? OPTIONAL. Default: 1.
					vradius1 = "-8,-3,-8,8,3,8", -- velocity that is randomly added. covers range of +-vradius. OPTIONAL. Default: 4.2
					useheight = 1, -- check the distance between ground and projectile? OPTIONAL.
				},
				damage                  = {
					default = 850.01*6,
				},
				edgeEffectiveness       = 0.5,
				explosionGenerator      = "custom:tremor",
				firestarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 4,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				mygravity				= 0.5,
				noSelfDamage            = true,
				range                   = 275,
				reloadtime              = 0.5,
				rgbColor                = "1 0.95 0.4",
				separation              = 2.2,
				sizeDecay				= -3.4,
				soundHit                = "weapon/clusters/cluster_light",
				soundStart              = "weapon/heavy_emg",
				stages                  = 20,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 550,
			},
			PLASMA = {
				name                    = "Volatile Plasma Round",
				highTrajectory		    = 1,
				areaOfEffect            = 0,
				avoidFeature            = false,
				avoidGround             = false,
				cegTag                  = "vulcanfx",
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					restrict_in_widgets = 1,
					numprojectiles1 = 8, -- how many of the weapondef we spawn. OPTIONAL. Default: 1.
					projectile1 = "staticheavyarty_secondary",
					--spreadradius1 = 4, -- used in clusters. OPTIONAL. Default: 100.
					clustervec1 = "randomxyz", -- accepted values: randomx, randomy, randomz, randomxy, randomxz, randomyz, random. OPTIONAL. default: random.
					use2ddist = 0, -- should we check 2d or 3d distance? OPTIONAL. Default: 0.
					spawndist = 2200, -- at what distance should we spawn the projectile(s)? REQUIRED.
					keepmomentum1 = true,
					vradius1 = "-6,-4,-6,6,4,6", -- velocity that is randomly added. covers range of +-vradius. OPTIONAL. Default: 4.2
					useheight = 1, -- check the distance between ground and projectile? OPTIONAL.
					light_camera_height = 1500,
					light_radius = 120,
					script_reload = "22", -- NB: Superweapon field in CP makes this handled by FireControl.
					light_color = "2.4 1.5 0.6",
					reveal_unit = 36,
				},
				damage                  = {
					default = 19200,
				},
				explosionGenerator      = "custom:MEDMISSILE_EXPLOSION",
				fireTolerance           = 1820, -- 10 degrees
				impulseBoost            = 0.5,
				impulseFactor           = 0.2,
				interceptedByShieldType = 1,
				mygravity				= 0.5,
				sprayAngle				= 120,
				noSelfDamage            = true,
				range                   = 7800,
				reloadtime              = 1/30, -- force render our reload progress?
				soundHit                = "weapon/clusters/cluster_heavy",
				soundStart              = "weapon/cannon/large_cannon_fire",
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 1900,
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				collisionVolumeOffsets        = "0 0 -7",
				collisionVolumeScales         = "70 194 70",
				collisionVolumeType           = "cylY",
				featureDead      = "HEAP",
				footprintX       = 4,
				footprintZ       = 4,
				object           = "armbrtha_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 4,
				footprintZ       = 4,
				object           = "debris4x4c.s3o",
			},
		},
	}
}
