return { 
	staticradar = {
		unitname                      = "staticradar",
		name                          = "Radar Tower",
		description                   = "Early Warning System",
		activateWhenBuilt             = true,
		buildCostMetal                = 50,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 4,
		buildingGroundDecalSizeY      = 4,
		buildingGroundDecalType       = "staticradar_aoplane.dds",
		buildPic                      = "staticradar.png",
		canMove                       = false,
		category                      = "FLOAT UNARMED",
		collisionVolumeOffsets        = "0 -32 0",
		collisionVolumeScales         = "32 90 32",
		collisionVolumeType           = "CylY",
		corpse                        = "DEAD",
		customParams = {
			morphto        = "staticheavyradar",
			morphtime      = 30,
			modelradius    = "16",
			priority_misc  = 2, -- High
			isradar        = 1,
			removewait     = 1,
			removestop     = 1,
			outline_x = 90,
			outline_y = 125,
			outline_yoff = 35,
			outline_sea_x = 90,
			outline_sea_y = 160,
			outline_sea_yoff = 20,
		},
		energyUse                     = 0.5,
		explodeAs                     = "SMALL_BUILDINGEX",
		floater                       = true,
		footprintX                    = 2,
		footprintZ                    = 2,
		iconType                      = "radar",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		levelGround                   = false,
		health                        = 200,
		maxSlope                      = 36,
		minCloakDistance              = 150,
		noAutoFire                    = false,
		objectName                    = "ARADARLVL1.s3o",
		script                        = "staticradar.lua",
		onoffable                     = true,
		radarDistance                 = 2100,
		radarEmitHeight               = 32,
		selfDestructAs                = "SMALL_BUILDINGEX",
		sightDistance                 = 600,
		useBuildingGroundDecal        = true,
		yardMap                       = "oooo",
		sfxtypes               = {
			explosiongenerators = {
				"custom:scanner_ping"
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "ARADARLVL1_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},
	} 
}
