return {
	staticantinuke = {
		unitname                      = "staticantinuke",
		name                          = "Antinuke",
		description                   = "Nuclear Interceptor (Needs Grid: 90E)",
		activateWhenBuilt             = true,
		buildCostMetal                = 1800,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 6,
		buildingGroundDecalSizeY      = 6,
		buildingGroundDecalType       = "antinuke_decal.dds",
		buildPic                      = "staticantinuke.png",
		category                      = "FLOAT",
		collisionVolumeOffsets        = "0 0 0",
		collisionVolumeScales         = "70 55 110",
		collisionVolumeType           = "box",
		selectionVolumeOffsets        = "0 0 0",
		selectionVolumeScales         = "70 55 110",
		selectionVolumeType           = "box",
		corpse                        = "DEAD",
		customParams                  = {
			removewait     = 1,
			removestop     = 1,
			nuke_coverage  = 2500,
			modelradius      = "50",
			neededlink  = 90,
			pylonrange  = 450,
			keeptooltip = "by janitor's request, please don't remove the tooltips Machine God.", -- Do we actually need this with the new tooltips?
			outline_x = 185,
			outline_y = 185,
			outline_yoff = 25,
		},
		explodeAs                     = "LARGE_BUILDINGEX",
		footprintX                    = 5,
		footprintZ                    = 8,
		iconType                      = "antinuke",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		levelGround                   = false,
		health                        = 3300,
		maxSlope                      = 18,
		objectName                    = "staticantinuke.s3o",
		radarDistance                 = 2500,
		radarEmitHeight               = 24,
		script                        = "staticantinuke.lua",
		selfDestructAs                = "LARGE_BUILDINGEX",
		sightDistance                 = 660,
		useBuildingGroundDecal        = true,
		yardmap                       = "oooooooooooooooooooooooooooooooooooooooo",
		floater                       = true,
		weapons                       = {
			{
				def = "AMD_ROCKET",
			},
		},
		weaponDefs                    = {
			AMD_ROCKET = {
				name                    = "Strategic Missile Defense Laser",
				areaOfEffect            = 420,
				avoidFeature            = false,
				collideFriendly         = false,
				collideFeature          = false,
				collisionSize           = 2,
				cylinderTargeting       = 15000,
				coreThickness           = 2.5,
				coverage                = 3500,
				duration                = 0,
				craterBoost             = 1,
				craterMult              = 2,
				customParams            = {
					light_color = "0.110 0.005 2.525",
					light_radius = 1200,
					restrict_in_widgets = 1,
					reaim_time = 15,
					nuke_coverage = 2500,
					antinukelaser = "staticantinuke_laser_render",
				},
				damage                  = {
					default = 9500,
				},
				--spawning the intercept explosion is handled by exp_nuke_effect_chooser.lua
				explosionGenerator      = "custom:none",
				fireStarter             = 100,
				flightTime              = 20,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				interceptor             = 1,
				fireStarter             = 100,
				impactOnly              = true,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				laserFlareSize          = 0,
				minIntensity            = 0.8,
				noSelfDamage            = true,
				range                   = 2500,
				reloadtime              = 3.8,
				rgbColor                = "0.110 0.005 0.85",
				soundStart              = "weapon/laser/antinuke_laser",
				soundStartVolume        = 7,
				thickness               = 0.01,
				tolerance               = 8192,
				turret                  = true,
				weaponType              = "LaserCannon",
				weaponVelocity          = 2000,
			},
			laser_render = {
				name                    = "SMD Laser",
				areaOfEffect            = 420,
				avoidFeature            = false,
				beamdecay               = 0.9,
				beamttl                 = 80,
				beamTime				= 2/30,
				collideFriendly         = false,
				collideFeature          = false,
				collisionSize           = 2,
				cylinderTargeting       = 15000,
				coreThickness           = 2.5,
				coverage                = 2500,
				craterBoost             = 1,
				craterMult              = 2,
				customParams            = {
					light_color = "0.110 0.005 2.525",
					light_radius = 1200,
					restrict_in_widgets = 1,
					reaim_time = 15,
					nuke_coverage = 2500,
				},
				damage                  = {
					default = 9500,
				},
				--spawning the intercept explosion is handled by exp_nuke_effect_chooser.lua
				explosionGenerator      = "custom:none",
				fireStarter             = 100,
				flightTime              = 20,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				interceptor             = 1,
				fireStarter             = 100,
				impactOnly              = true,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				laserFlareSize          = 30,
				minIntensity            = 0.8,
				noSelfDamage            = true,
				range                   = 2500,
				reloadtime              = 3.8,
				rgbColor                = "0.110 0.005 0.85",
				soundStart              = "weapon/laser/antinuke_laser",
				soundStartVolume        = 7,
				thickness               = 20,
				tolerance               = 8192,
				turret                  = true,
				weaponType              = "BeamLaser",
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 5,
				footprintZ       = 8,
				object           = "staticantinuke_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 5,
				footprintZ       = 8,
				object           = "debris4x4a.s3o",
			},
		},
	} 
}
