return { 
	staticheavyradar = {
		unitname                      = "staticheavyradar",
		name                          = "Advanced Radar",
		description                   = "Over-the-Horizon Radar",
		activateWhenBuilt             = true,
		buildCostMetal                = 350,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 4,
		buildingGroundDecalSizeY      = 4,
		buildingGroundDecalType       = "staticheavyradar_aoplane.dds",
		buildPic                      = "staticheavyradar.png",
		category                      = "UNARMED FLOAT",
		collisionVolumeOffsets        = "0 -8 0",
		collisionVolumeScales         = "32 83 32",
		collisionVolumeType           = "CylY",
		corpse                        = "DEAD",
		customParams                  = {
			modelradius    = "16",
			removewait     = 1,
			removestop     = 1,
			priority_misc  = 2, -- High
			isradar        = 1,
			outline_x = 110,
			outline_y = 120,
			outline_yoff = 32.5,
		},
		energyUse                     = 1.5,
		explodeAs                     = "SMALL_BUILDINGEX",
		floater                       = true,
		footprintX                    = 2,
		footprintZ                    = 2,
		iconType                      = "advradar",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		levelGround                   = false,
		health                        = 1400,
		maxSlope                      = 36,
		minCloakDistance              = 150,
		objectName                    = "novaradar.s3o",
		script                        = "staticheavyradar.lua",
		onoffable                     = true,
		radarDistance                 = 5000,
		radarEmitHeight               = 150,
		selfDestructAs                = "SMALL_BUILDINGEX",
		sightDistance                 = 1800,
		useBuildingGroundDecal        = true,
		yardMap                       = "oooo",
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "novaradar_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2b.s3o",
			},
		},
	}
}
