local unitDef = {
	unitname               = "striderbantha",
	name                   = "Mogul",
	description            = "Ultraheavy Siege Engine",
	acceleration           = 0.1047,
	autoheal               = 300,
	brakeRate              = 0.2212,
	buildCostMetal         = 16000,
	builder                = false,
	buildPic               = "striderbantha.png",
	canGuard               = true,
	canManualFire          = false,
	canMove                = true,
	canPatrol              = true,
	category               = "LAND",
	collisionVolumeOffsets = "0 0 -2",
	collisionVolumeScales  = "60 80 60",
	collisionVolumeType    = "CylY",
	corpse                 = "DEAD",

	customParams           = {
		extradrawrange = 1500,
		aimposoffset   = "0 -8 0",
		midposoffset   = "0 -8 0",
		modelradius    = "17",
	},

	explodeAs              = "ATOMIC_BLAST",
	footprintX             = 4,
	footprintZ             = 4,
	iconType               = "t3generic",
	leaveTracks            = true,
	losEmitHeight          = 60,
	health                 = 96000,
	maxSlope               = 36,
	speed                  = 1.25,
	maxWaterDepth          = 22,
	movementClass          = "KBOT4",
	noAutoFire             = false,
	noChaseCategory        = "FIXEDWING SATELLITE SUB",
	objectName             = "Bantha.s3o",
	selfDestructAs         = "ATOMIC_BLAST",
	script                 = "striderbantha.lua",
	sfxtypes               = {
		explosiongenerators = {
			"custom:zeusmuzzle",
			"custom:zeusgroundflash",
			"custom:opticblast_charge"
		},
	},
	sightDistance          = 720,
	trackOffset            = 0,
	trackStrength          = 8,
	trackStretch           = 0.5,
	trackType              = "ComTrack",
	trackWidth             = 42,
	turnRate               = 1056,
	upright                = true,
	workerTime             = 0,
	weapons                = {
		{
			def                = "TRACKER",
			--badTargetCategory  = "FIXEDWING GUNSHIP",
			onlyTargetCategory = "SWIM LAND SHIP SINK TURRET FLOAT HOVER",
		},

		{
		  def                = "LIGHTNING",
		  badTargetCategory  = "FIXEDWING",
		  onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
		},

		{
		  def                = "EMP_MISSILE",
		  onlyTargetCategory = " LAND SINK TURRET SHIP SWIM FLOAT HOVER",
		},
	},
	weaponDefs             = {
		SECONDARY = {
			name                    = "LGM-220 Warhead",
			areaOfEffect            = 144,
			craterBoost             = 20,
			craterMult              = 2,
			customParams            = {
				burst = Shared.BURST_RELIABLE,
				force_ignore_ground = "1",

				light_color = "3 2.33 1.5",
				light_radius = 150,
			},
      
			damage                  = {
				default = 1000,
			},
			edgeEffectiveness = 0.2,
			explosionGenerator      = "custom:FLASH64",
			impulseBoost            = 0,
			impulseFactor           = 2,
			interceptedByShieldType = 1,
			noSelfDamage            = true,
			range                   = 450,
			reloadtime              = 3.5,
			soundHit                = "explosion/ex_large9.wav",
			soundHitVolume          = 0.75,
			--soundStart              = "weapon/cannon/rhino",
			turret                  = true,
			weaponType              = "Cannon",
			weaponVelocity          = 470,
		},
		TRACKER = {
			name                    = "Missile Target Painter",
			areaOfEffect            = 20,
			beamTime                = 1/15,
			coreThickness           = 2.5,
			craterBoost             = 0,
			craterMult              = 0,

			customParams            = {
				targeter = 1,
				--burst = Shared.BURST_RELIABLE,
				stats_hide_damage = 1, -- continuous laser
				stats_hide_reload = 1,
				light_color = "1.25 0 0",
				light_radius = 120,
			},
			damage                  = {
				default = 0.00,
			},
			--explosionGenerator      = "custom:flash1red",
			fireTolerance           = 8192, -- 45 degrees
			impactOnly              = true,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 0,
			largeBeamLaser          = true,
			laserFlareSize          = 2,
			leadLimit               = 18,
			minIntensity            = 0.01,
			noSelfDamage            = true,
			range                   = 1400,
			reloadtime              = 1/15,
			--sweapfire = false,
			rgbColor                = "0.3 0 0",
			rgbColor2				  = "0.5 0 0",
			soundStart              = "weapon/laser/mogul-uplink",
			--soundHit				  = "trackercompleted.wav"
			soundStartVolume        = 15,
			texture1                = "largelaser",
			texture2                = "flare",
			texture3                = "flare",
			texture4                = "smallflare",
			thickness               = 10,
			tolerance               = 10000,
			turret                  = true,
			weaponType              = "BeamLaser",
			weaponVelocity          = 1500,
		},
		EMP_MISSILE = {
			name                    = "LGM-220 Barrage",
			areaOfEffect            = 128,
			accuracy                = 512,
			avoidFeature            = false,
			avoidFriendly           = false,
			burst                   = 4,
			burstrate               = 0.7,
			cegTag                  = "tactrail",
			--commandFire             = true,
			craterBoost             = 0,
			craterMult              = 0,

			customParams            = {
				tracker = 1,
				combatrange = 2000,
				numprojectiles1 = 5,
				projectile1 = "striderbantha_secondary",
				spawndist = 300,
				velspread1 = "6.37, 3, 6.37",
				light_color = "0.65 0.65 0.18",
				light_radius = 380,
				useheight = 1,
				laserguidance_failtime = 1,
			},
			damage                  = {
				default        = 5*1000,
			},
			dance                   = 20,
			edgeEffectiveness       = 0.5,
			explosionGenerator      = "custom:TORPEDOHITHUGE",
			fireStarter             = 100,
			fixedlauncher           = true,
			flightTime              = 25,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 2,
			model                   = "banthamissile.s3o",
			noSelfDamage            = true,
			range                   = 1400,
			reloadtime              = 15,
			smokeTrail              = false,
			soundHit                = "explosion/ex_large9.wav",
			soundStart              = "weapon/missile/bantha_launch.wav",
			soundStartVolume        = 15,
			startVelocity           = 50,
			tracks                  = true,
			trajectoryHeight        = 20,
			tolerance               = 512,
			turnRate                = 32000,
			turret                  = true,
			weaponAcceleration      = 500,
			weaponType              = "StarburstLauncher",
			weaponTimer			    = 1.5,
			weaponVelocity          = 1150,
			--wobble                = 18000,
		},	
		EMPSECONDARY = {
			name                    = "EMP Shockwave",
			accuracy                = 80,
			movingAccuracy			= 400,
			areaOfEffect            = 120,
			cegtag					= "artillery_spark_small",
			craterBoost             = 0,
			craterMult              = 0,
			--highTrajectory			= 1,
			burst					= 1,

			customParams        = {
				light_camera_height = 1400,
				light_color = "0.3 0.3 0.7",
				light_radius = 100,
				extra_damage = 300*4,
			},

			damage                  = {
				default = 300,
			},

			edgeEffectiveness       = 0.1,
			paralyzeTime            = 3,
			explosionGenerator      = "custom:lightningplosion_nopost",
			impactOnly              = false,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 1,
			myGravity               = 0.07,
			noSelfDamage            = true,
			range                   = 400,
			reloadtime              = 6,
			size					= 0.01,
			soundHit                = "weapon/cannon/emp_arty_hit",
			soundStart              = "weapon/cannon/emparty_fire",
			turret                  = true,
			weaponType              = "Cannon",
			weaponVelocity          = 235,
		},
		LIGHTNING = {
			name                    = "Unstable Plasmatic Energy Launcher",
			areaOfEffect            = 64,
			craterBoost             = 0,
			craterMult              = 0,
			burst					= 3,
			burstrate				= 2,
			cegtag					= "antagonist_spark_bigger",
			customParams            = {
				extra_damage = 300*4*6,
				numprojectiles1 = 6,
				light_camera_height = 2000,
				projectile1 = "striderbantha_empsecondary",
				spawndist = 300, 
				velspread1 = "5.09, -1, 5.09, _, 2, _",
				light_color = "0.65 0.65 0.18",
				light_radius = 380,
			},

			cylinderTargeting      = 0,

			damage                  = {
				default        = 300*6,
			},

			duration                = 10,
			explosionGenerator      = "custom:hammer_artillery_hit",
			edgeeffectiveness		= 0.05,
			fireStarter             = 50,
			impulseBoost            = 0,
			impulseFactor           = 0,
			intensity               = 12,
			interceptedByShieldType = 1,
			paralyzeTime            = 1,
			range                   = 550,
			reloadtime              = 0.5,
			size 					= 0.3,
			mygravity			    = 0.06,
			rgbColor                = "0.54 0.54 1",
			soundHit				= "weapon/cannon/emp_hit",
			soundStart              = "weapon/cannon/bantha_fire",
			soundStartVolume        = 2,
			sprayAngle              = 400,
			thickness               = 10,
			turret                  = true,
			waterweapon             = false,
			weaponType              = "Cannon",
			weaponVelocity          = 770,
		},
	},
	featureDefs            = {
		DEAD  = {
			blocking         = true,
			featureDead      = "HEAP",
			footprintX       = 4,
			footprintZ       = 4,
			object           = "bantha_wreck.s3o",
		},
		HEAP  = {
			blocking         = false,
			footprintX       = 4,
			footprintZ       = 4,
			object           = "debris4x4b.s3o",
		},
	},
}

return { striderbantha = unitDef }
