unitDef = {
	unitname               = [[striderrazorback]],
	name                   = [[Champion]],
	description            = [[Shielded Assault/Riot Strider]],
	acceleration           = 0.156,
	brakeRate              = 0.262,
	buildCostMetal         = 5000,
	builder                = false,
	buildPic               = [[striderrazorback.png]],
	canAttack              = true,
	canGuard               = true,
	canMove                = true,
	canPatrol              = true,
	canstop                = [[1]],
	category               = [[LAND]],
	collisionVolumeOffsets = [[0 0 0]],
	collisionVolumeScales  = [[65 65 65]],
	collisionVolumeTest    = 1,
	collisionVolumeType    = [[ellipsoid]],
	corpse                 = [[DEAD]],
	customParams           = {
		description_fr = [[Mechwarrior d'Assaut]],
		description_de = [[Sturm/Riot Läufer]],
		description_pl = [[Robot szturmowy]],
		helptext       = [[The Razorback features twin multi-barelled pulse cannons for extreme crowd control, as well as a head-mounted short-range laser for close in work. Don't use recklessly - its short range can be a real liability.]],
		helptext_fr    = [[Le Razorback est un Robot au blindage lourd arm? de deux Miniguns et d'un canon laser continu ind?pendant. Son blindage et sa pr?cision le rendent utile contre nimporte quel type d'arm?e, ? l'exception des unit?s longues port?e. V?ritable rouleau compresseur, il est pourtant le moins cher et le plus faible des Mechs.]],
		helptext_de    = [[Der Razorback ist ausgerüstet mit doppelläufien Impulskanonen als Gegenwehr gegen viele Einheiten, sowie einen, am Kopf befestigten, Laser für den Nahbereich. Nutze ihn nicht unbesonnen - seine kurze Reichweite erzeugt eine große Anfälligkeit.]],
		helptext_pl    = [[Razorback posiada podwojne dzialka obrotowe, ktore pozwalaja mu walczyc z hordami mniejszych jednostek, oraz mocny laser krotkiego zasiegu. Mimo ze jego sila jest duza, w jej uzytku moze przeszkadzac jego krotki zasieg.]],
	},
	explodeAs              = [[CRAWL_BLASTSML]],
	footprintX             = 4,
	footprintZ             = 4,
	iconType               = [[t3generic]],
	maxDamage              = 11000,
	maxSlope               = 36,
	maxVelocity            = 1.9,
	maxWaterDepth          = 22,
	movementClass          = [[KBOT4]],
	noAutoFire             = false,
	noChaseCategory        = [[TERRAFORM SATELLITE SUB]],
	objectName             = [[ARMRAZ.s3o]],
	script                 = "striderrazorback.lua",
	selfDestructAs         = [[CRAWL_BLASTSML]],
	sfxtypes               = {
		explosiongenerators = {
			[[custom:WARMUZZLE]],
			[[custom:razorbackejector]],
		},
	},
	sightDistance          = 578,
	turnRate               = 515,
	upright                = true,
	weapons                = {

		{
			def                = [[RAZORBACK_EMG]],
			badTargetCategory  = [[FIXEDWING]],
			onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
		},
		{
			def                = [[RAZORBACK_EMG]],
			badTargetCategory  = [[FIXEDWING]],
			onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
			slaveTo            = 1,
		},
		{
			def                = [[LASER]],
			onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
		},
		{
			def                = [[SHIELD]],
		},
	},


	weaponDefs             = {
		LASER         = {
			name                    = [[High Intensity Laserbeam]],
			areaOfEffect            = 8,
			beamTime                = 0.1,
			coreThickness           = 0.5,
			craterBoost             = 0,
			craterMult              = 0,
			damage                  = {
				default = 25,
			},

			explosionGenerator      = [[custom:flash1green]],
			fireStarter             = 30,
			impactOnly              = true,
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			interceptedByShieldType = 1,
			largeBeamLaser          = true,
			laserFlareSize          = 5.43,
			minIntensity            = 1,
			noSelfDamage            = true,
			range                   = 350,
			reloadtime              = 0.1,
			rgbColor                = [[0 1 0]],
			soundStart              = [[weapon/laser/laser_burn10]],
			soundTrigger            = true,
			sweepfire               = false,
			texture1                = [[largelaser]],
			texture2                = [[flare]],
			texture3                = [[flare]],
			texture4                = [[smallflare]],
			thickness               = 5.43426627982104,
			tolerance               = 18000,
			turret                  = true,
			weaponType              = [[BeamLaser]],
			weaponVelocity          = 500,
		},
		RAZORBACK_EMG = {
			name                    = [[Heavy Minigun]],
			alphaDecay              = 0.7,
			areaOfEffect            = 32,
			craterBoost             = 1,
			craterMult              = 2,
			customParams = {
				script_reload = [[1.1]],
				recycler = 1,
				recycle_reductiontime = 0.1,
				recycle_reduction = 0.1,
				recycle_bonus = 0.45,
				recycle_reductionframes = 0.5,
				recycle_maxbonus = 24,
				recycle_maxbonus = 20,
			},
			damage                  = {
				default = 12.01,
			},
			explosionGenerator      = [[custom:EMG_HIT]],
			impulseBoost            = 0,
			impulseFactor           = 0.4,
			intensity               = 0.7,
			interceptedByShieldType = 1,
			noSelfDamage            = true,
			range                   = 400,
			reloadtime              = 0.03333334,
			rgbColor                = [[1 0.95 0.4]],
			separation              = 1.5,
			size                    = 1.7,
			soundHit                = [[weapon/cannon/emg_hit]],
			soundStart              = [[weapon/cannon/minigun_1]],
			soundStartVolume        = 4,
			sprayAngle              = 2048,
			stages                  = 10,
			tolerance               = 5000,
			turret                  = true,
			weaponTimer             = 0.1,
			weaponType              = [[Cannon]],
			weaponVelocity          = 550,
		},
		SHIELD      = {
				name                    = [[Energy Shield]],
				damage                  = {
					default = 10,
				},
				customParams			= {
					--shield_recharge_delay   = 10,
					unlinked            = true,
				},
				exteriorShield          = true,
				shieldAlpha             = 0.2,
				shieldBadColor          = [[1 0.1 0.1 1]],
				shieldGoodColor         = [[0.1 0.1 1 1]],
				shieldInterceptType     = 3,
				shieldPower             = 25000,
				shieldPowerRegen        = 80,
				shieldPowerRegenEnergy  = 20,
				shieldRadius            = 270,
				shieldRepulser          = false,
				shieldStartingPower     = 15000,
				smartShield             = true,
				visibleShield           = false,
				visibleShieldRepulse    = false,
				weaponType              = [[Shield]],
			},
	},
	featureDefs            = {
		DEAD  = {
			blocking         = true,
			featureDead      = [[HEAP]],
			footprintX       = 3,
			footprintZ       = 3,
			object           = [[armraz_dead.s3o]],
		},
		HEAP  = {
			blocking         = false,
			footprintX       = 3,
			footprintZ       = 3,
			object           = [[debris3x3a.s3o]],
		},
	},
}

return { striderrazorback = unitDef }