return {
	striderraider = {
		unitname               = "striderraider",
		name                   = "Marauder",
		description            = "Ultraheavy Raider",
		acceleration           = 0.14,
		brakeRate              = 0.28,
		buildCostEnergy        = 3000,
		buildPic               = "striderraider.png",
		canAttack              = true,
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canManualFire          = true,
		category               = "LAND",
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "50 85 50",
		collisionVolumeTest    = 1,
		collisionVolumeType    = "CylY",
		corpse                 = "DEAD",
		customParams           = {
			canjump            = 1,
			jump_range         = 750,
			jump_speed         = 9,
			jump_reload        = 15,
			jump_from_midair   = 1,
			soundok = "heavy_bot_move",
			soundselect = "bot_select",
		},
		explodeAs              = "ESTOR_BUILDING",
		footprintX             = 3,
		footprintZ             = 3,
		iconType               = "t3generic", -- TODO: make actual icons to differentiate striders.
		idleAutoHeal           = 200,
		idleTime               = 450, -- 15s
		leaveTracks            = true,
		maxDamage              = 7000,
		maxSlope               = 36,
		maxVelocity            = 3.0,
		maxWaterDepth          = 36,
		minCloakDistance       = 75,
		movementClass          = "AKBOT4",
		noChaseCategory        = "TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET",
		objectName             = "cadenza.s3o",
		script                 = "cadenza.lua",
		selfDestructAs         = "ESTOR_BUILDING",
		sfxtypes               = {
			explosiongenerators = {
				"custom:THUDMUZZLE",
				"custom:THUDSHELLS",
				"custom:THUDDUST",
				"custom:STORMMUZZLE",
				"custom:VINDIBACK",
			},
		},
		sightDistance          = 800,
		trackOffset            = 0,
		trackStrength          = 8,
		trackStretch           = 1,
		trackType              = "ComTrack",
		trackWidth             = 32,
		turnRate               = 672,
		upright                = true,
		weapons                = {
			{
				def                = "CANNON",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "MISSILE",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "LANDING",
				mainDir            = "1 0 0",
				maxAngleDif        = 0,
				onlyTargetCategory = "NULL",
			},
			{
				def                = "VACUUM",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs             = {
			CANNON = {
				name                    = "Heavy Railgun",
				alphaDecay              = 0.12,
				areaOfEffect            = 70,
				avoidFeature            = false,
				avoidFriendly           = true,
				avoidGround             = false,
				avoidNeutral            = false,
				colorMap				= [[0.7843 0.0627 0.1803  0 0.1843 0.4235  0.7294 0.04705 0.1843  0 0.125 0.3568]],
				cegtag                  = "amphraid_trail",
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting       = 0.5,
				customParams = {
					light_camera_height = 1200,
					light_radius        = 30,
					light_color = "0 0.1843 0.4235",
					armorpiercing = 0.75,
					groundnoexplode = 1,
				},
				damage                  = {
					default = 300.1,
				},
				explosionGenerator      = "custom:70rlexplode_blue",
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				noExplode               = true,
				range                   = 480,
				reloadtime              = 18/30,
				rgbColor                = "0.329 0.78 0.8196",
				size                    = 6.5,
				sizeDecay				= -1.4,
				seperation				= 3,
				nogap					= true,
				soundHit                = "weapon/cannon/amph_light_mg_hit",
				soundHitVolume          = 2.5,
				soundStart              = "weapon/cannon/plasma_fire",
				soundStartVolume        = 1.5,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "Cannon",
				weaponVelocity          = 950,
			},
			MISSILE = {
				name                    = "Missile Battery",
				areaOfEffect            = 96,
				burst		            = 4,
				burstRate               = 5/30,
				cegTag                  = "missiletrailyellow",
				craterBoost             = 1,
				craterMult              = 2,
				damage                  = {
					default = 300,
				},
				fireStarter             = 70,
				fixedlauncher           = true,
				flightTime              = 4.5,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				model                   = "wep_m_maverick.s3o",
				range                   = 650,
				reloadtime              = 6,
				smokeTrail              = true,
				soundHit                = "explosion/ex_med5",
				soundHitVolume          = 8,
				soundStart              = "weapon/missile/rapid_rocket_fire2",
				soundStartVolume        = 7,
				startsmoke              = "1",
				startVelocity           = 180,
				texture2                = "lightsmoketrail",
				tracks                  = true,
				trajectoryHeight        = 0.4,
				turnRate                = 24000,
				turret                  = true,
				weaponAcceleration      = 120,
				weaponTimer             = 3,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 700,
			},
			VACUUM = {
				name                    = "Vacuum Gun",
				areaOfEffect            = 400,
				commandfire             = true,
				avoidFeature            = false,
				avoidFriendly           = false,
				burnblow                = false,
				craterBoost             = 0,
				craterMult              = 0,
				cegtag                  = "energeticblackhole_trail",
				customParams            = {
					light_color = "0 .8 1 .1",
					light_radius = 500,
					lups_explodelife = 1.0,
					lups_explodespeed = 0.5,
					light_radius = 80,
					blastwave_size = 200,
					blastwave_impulse = -3.5,
					blastwave_speed = -6.6,
					blastwave_life = 30,
					blastwave_lossfactor = 0.85,
					blastwave_damage = 40,
				},

				damage                  = {
					default = 500, --make it not suck vs shields
				},

				explosionGenerator      = "custom:energeticblackhole_112", -- technically it's 400, but i can't be assed to rename.
				explosionSpeed          = 50,
				impulseBoost            = 150,
				impulseFactor           = -2.5,
				intensity               = 0.9,
				interceptedByShieldType = 1,
				myGravity               = 0.1,
				projectiles             = 1,
				range                   = 500,
				reloadtime              = 20,
				rgbColor                = "0.05 0.05 0.05",
				size                    = 3,
				soundHit                = "weapon/impacts/impulsewave1",
				soundStart              = "weapon/cannon/commblackhole_fire",
				soundStartVolume        = 100,
				soundHitVolume          = 100,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 550,
				waterweapon             = true,
			},
			LANDING = {
				name                    = "Jump Impact",
				areaOfEffect            = 300,
				canattackground         = false,
				craterBoost             = 4,
				craterMult              = 6,
				damage                  = {
					default = 2500,
				},
				edgeEffectiveness       = 0,
				explosionGenerator      = "custom:FLASH64",
				impulseBoost            = 1,
				impulseFactor           = 0.8,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 5,
				reloadtime              = 20,
				soundHit                = "krog_stomp",
				soundStart              = "krog_stomp",
				soundStartVolume        = 3,
				startsmoke              = "1",
				turret                  = false,
				weaponType              = "Cannon",
				weaponVelocity          = 5,
				waterweapon             = true,
			},    
		},
		featureDefs            = {
			DEAD      = {
				description      = "Wreckage - Cadenza",
				blocking         = true,
				category         = "corpses",
				damage           = 6400,
				energy           = 0,
				featureDead      = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintX       = 4,
				footprintZ       = 4,
				height           = "20",
				hitdensity       = "100",
				metal            = 1200,
				object           = "wreck4x4b.s3o",
				reclaimable      = true,
				reclaimTime      = 1200,
				seqnamereclamate = "TREE1RECLAMATE",
				world            = "All Worlds",
			},
			HEAP      = {
				description      = "Debris - Cadenza",
				blocking         = false,
				category         = "heaps",
				damage           = 6400,
				energy           = 0,
				featurereclamate = "SMUDGE01",
				footprintX       = 2,
				footprintZ       = 2,
				hitdensity       = "100",
				metal            = 600,
				object           = "debris2x2c.s3o",
				reclaimable      = true,
				reclaimTime      = 600,
				seqnamereclamate = "TREE1RECLAMATE",
				world            = "All Worlds",
			},
		},
	}
}