return { 
	supernova_satellite = {
		name                   = "Supernova",
		description            = "Planetary Defense Satellite",
		acceleration           = 0.456,
		airStrafe              = false,
		airHoverFactor         = -0.01,
		brakeRate              = 2.736,
		bankingAllowed         = false,
		builder                = false,
		buildPic               = "satellite.png",
		canFly                 = true,
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		canLand                = false,
		canSubmerge            = false,
		category               = "satellite",
		collide                = false,
		corpse                 = "DEAD",
		cruiseAltitude         = 2000, -- Space, but low enough to select.
		explodeAs              = "GUNSHIPEX",
		floater                = true,
		footprintX             = 3,
		footprintZ             = 3,
		health                 = 9500,
		hoverAttack            = true,
		iconType               = "satellite",
		metalCost              = 2000,
		noChaseCategory        = "TERRAFORM SATELLITE FIXEDWING GUNSHIP",
		noAutoFire             = false,
		objectName             = "starlight_satellite.dae",
		script                 = "starlight_satellite.lua",
		selfDestructAs         = "GUNSHIPEX",
		sightDistance          = 700,
		customParams           = {
			dontcount = "1",
			outline_x = 100,
			outline_y = 100,
			outline_yoff = 0,
		},
		sfxtypes               = {
			explosiongenerators = {
				"custom:IMMA_LAUNCHIN_MAH_LAZER",
				"custom:xamelimpact",
			},
		},
		speed                  = 1.5,
		turnRate               = 500, -- some inertia, but not much.
		weapons                       = {
			{
				def                = "TRACKER",
				badTargetCategory  = "FIXEDWING GUNSHIP",
				onlyTargetCategory = "SWIM LAND SHIP SINK TURRET FLOAT GUNSHIP FIXEDWING HOVER",
			},
			{
				def                = "LASER",
				badTargetCategory  = "FIXEDWING GUNSHIP",
				onlyTargetCategory = "SWIM LAND SHIP SINK TURRET FLOAT GUNSHIP FIXEDWING HOVER",
			},
			{
				def                = "CUTTER",
				badTargetCategory  = "FIXEDWING GUNSHIP",
				onlyTargetCategory = "SWIM LAND SHIP SINK TURRET FLOAT GUNSHIP FIXEDWING HOVER",
			},
			{
				def                = "DEATHLASER",
				badTargetCategory  = "FIXEDWING GUNSHIP",
				onlyTargetCategory = "SWIM LAND SHIP SINK TURRET FLOAT GUNSHIP FIXEDWING HOVER",
			},
		},
		weaponDefs                    = {
			TRACKER = {
				name                    = "Targeting Beam",
				areaOfEffect            = 20,
				collideEnemy = false,
				avoidFeature = false,
				collideFeature = false,
				beamTime                = 1/30,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting       = 128, -- attack from space!!
				customParams            = {
					--burst = Shared.BURST_RELIABLE,
					stats_hide_damage = 1, -- continuous laser
					stats_hide_reload = 1,
					light_color = "1.25 0 0",
					light_radius = 90,
					norealdamage = 1,
					combatrange	= 10,
				},
				damage                  = {
					default = 0,
				},
				--explosionGenerator      = "custom:flash1red",
				fireTolerance           = 100, -- 45 degrees
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 0,
				largeBeamLaser          = true,
				laserFlareSize          = 2,
				leadLimit               = 18,
				minIntensity            = 0.01,
				noSelfDamage            = true,
				range                   = 100,
				reloadtime              = 1/30,
				rgbColor                = "0.7 0 0",
				soundStart              = "weapon/laser/tracker",
				soundStartVolume        = 15,
				sweepfire               = true,
				texture1                = "largelaser",
				texture2                = "flare",
				--texture3                = "flare",
				--texture4                = "smallflare",
				thickness               = 2,
				tolerance               = 10000,
				turret                  = true,
				waterweapon             = true,
				weaponType              = "BeamLaser",
				weaponVelocity          = 1500,
			},
			DEATHLASER    = {
				name                    = "10.7PW 'SuperNova' Laser",
				alwaysVisible           = 1,
				areaOfEffect            = 600,
				avoidFeature            = false,
				avoidNeutral            = false,
				avoidGround             = false,
				beamTime                = 1 + 1/3,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 30,
				cylinderTargeting       = 128, -- can attack from space into ocean
				customParams              = {
					light_color = "0.05 0.3 6",
					light_radius = 4000,
					light_beam_start = 0.1,
					stats_damage = 60000,
					combatrange	= 10,
				},
				damage                  = {
					default = 60000,
				},
				explosionGenerator      = "custom:beamlaser_hit_saphire",
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				largeBeamLaser          = true,
				laserFlareSize          = 12,
				minIntensity            = 1,
				range                   = 100,
				reloadtime              = 3,
				rgbColor                = "0.05 0.12 1",
				scrollSpeed             = 8,
				soundStartVolume        = 1,
				soundTrigger            = true,
				soundStart              = "weapon/laser/tracker",
				texture1                = "largelaser",
				texture2                = "flare",
				texture3                = "flare",
				texture4                = "smallflare",
				thickness               = 100,
				tolerance               = 65536,
				tileLength              = 10000,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "BeamLaser",
			},
			LASER    = {
				name                    = "5KW Output",
				alwaysVisible           = 1,
				areaOfEffect            = 30,
				avoidFeature            = false,
				avoidNeutral            = false,
				avoidGround             = false,
				beamTime                = 1/30,
				coreThickness           = 0.5,
				craterBoost             = 30,
				craterMult              = 30,
				customParams              = {
					light_color = "3 0.2 4",
					light_radius = 2000,
					light_beam_start = 0.8,
					aimdelay = 5*30,
					allowedpitcherror = 180,
					allowedheadingerror = 180,
					combatrange	= 10,
				},
				damage                  = {
					default = 50, -- 3000 damage (3s)
				},
				explosionGenerator      = "custom:FLASHLAZER",
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				largeBeamLaser          = true,
				laserFlareSize          = 20,
				minIntensity            = 1,
				range                   = 100,
				reloadtime              = 1/30,
				rgbColor                = "1 0.5 0",
				scrollSpeed             = 8,
				soundStartVolume        = 1,
				soundStart              = "weapon/laser/laser_burn10",
				soundTrigger            = true,
				texture1                = "largelaser",
				texture2                = "flare",
				texture3                = "flare",
				texture4                = "smallflare",
				thickness               = 50,
				tolerance               = 65536,
				tileLength              = 10000,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "BeamLaser",
			},
			CUTTER    = {
				name                    = "0.5TW Output",
				alwaysVisible           = 0,
				areaOfEffect            = 140,
				avoidFeature            = false,
				avoidNeutral            = false,
				avoidGround             = false,
				beamTime                = 1/30,
				coreThickness           = 0.5,
				craterBoost             = 30,
				craterMult              = 30,
				customParams              = {
					light_color = "3 0.2 4",
					light_radius = 1200,
					light_beam_start = 1/30,
					combatrange	= 10,
				},

				damage                  = {
					default = 150, -- 13,500 damage (3s)
				},
				explosionGenerator      = "custom:FLASHLAZER",
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				largeBeamLaser          = true,
				laserFlareSize          = 12,
				minIntensity            = 1,
				range                   = 100,
				reloadtime              = 1/30,
				rgbColor                = "0.2 1 0",
				scrollSpeed             = 8,
				soundStartVolume        = 1,
				soundStart              = "weapon/laser/heavy_laser6",
				soundTrigger            = true,
				texture1                = "largelaser",
				texture2                = "flare",
				texture3                = "flare",
				texture4                = "smallflare",
				thickness               = 50,
				tolerance               = 65536,
				tileLength              = 10000,
				turret                  = true,
				waterWeapon             = true,
				weaponType              = "BeamLaser",
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "satellite_d.dae",
				customParams = {
					unit = "mahlazer",
				},
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = "debris2x2c.s3o",
				customParams = {
					unit = "mahlazer",
				},
			},
		}, 
	} 
}
