return { 
	supernova_base = {
		unitname                      = "supernova_base",
		name                          = "Supernova Station",
		description                   = "Basestation for Supernova Satellites",
		activateWhenBuilt             = true,
		buildCostMetal                = 54000,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 11,
		buildingGroundDecalSizeY      = 11,
		buildingGroundDecalType       = "starlight_aoplate.dds",
		buildPic                      = "mahlazer.png",
		category                      = "SINK",
		collisionVolumeOffsets        = "0 0 0",
		collisionVolumeScales         = "120 100 120",
		collisionVolumeType           = "box",
		corpse                        = "DEAD",
		customParams                  = {
			modelradius    = "80",
			aimposoffset   = "0 35 0",
			midposoffset   = "0 0 0",
			select_no_rotate   = "1", -- tells selection widgets to treat the unit as if it has no rotation.
			bait_level_default = 0,
			draw_blueprint_facing = 1,
			reveal_losunit = "los_superwep",
			reveal_onprogress = 0.5,
		},
		explodeAs                     = "ATOMIC_BLAST", -- TODO: improved death explosion.
		footprintX                    = 10,
		footprintZ                    = 10,
		iconType                      = "mahlazer",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		health                        = 28000,
		maxSlope                      = 18,
		maxWaterDepth                 = 0,
		noChaseCategory               = "FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER",
		objectName                    = "starlight.dae",
		script                        = "mahlazer.lua",
		onoffable                     = true,
		selfDestructAs                = "ATOMIC_BLAST",
		sfxtypes                      = {
			explosiongenerators = {
				"custom:IMMA_LAUNCHIN_MAH_LAZER",
			},
		},
		sightDistance                 = 660,
		useBuildingGroundDecal        = true,
		yardMap                       = "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
		weapons                       = {},
		weaponDefs                    = {},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 10,
				footprintZ       = 10,
				object           = "starlight_dead.dae",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 10,
				footprintZ       = 10,
				object           = "debris3x3c.s3o",
			},
		},
	} 
}
