return { 
	tankheavyraid = {
		unitname               = "tankheavyraid",
		name                   = "Blitz",
		description            = "Lightning Assault/Raider Tank",
		acceleration           = 0.75,
		brakeRate              = 1.65,
		buildCostMetal         = 300,
		builder                = false,
		buildPic               = "tankheavyraid.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND TOOFAST",
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "28 12 28",
		collisionVolumeType    = "box",
		corpse                 = "DEAD",
		customParams           = {
			modelradius       = "10",
			selection_scale   = 0.85,
			aim_lookahead     = 120,
			bait_level_default = 0,
			outline_x = 80,
			outline_y = 80,
			outline_yoff = 12.5,
		},
		explodeAs              = "PANTHER_DEATH",
		footprintX             = 3,
		footprintZ             = 3,
		iconType               = "tankraider",
		leaveTracks            = true,
		maxDamage              = 1800,
		maxSlope               = 18,
		maxVelocity            = 3.4,
		maxWaterDepth          = 22,
		movementClass          = "TANK3",
		noAutoFire             = false,
		noChaseCategory        = "TERRAFORM FIXEDWING SATELLITE SUB",
		objectName             = "corseal.s3o",
		script                 = "tankheavyraid.lua",
		selfDestructAs         = "PANTHER_DEATH",
		sfxtypes               = {
			explosiongenerators = {
				"custom:PANTHER_SPARK",
				"custom:zeusmuzzle",
			},
		},
		sightDistance          = 600,
		trackOffset            = 6,
		trackStrength          = 5,
		trackStretch           = 1,
		trackType              = "StdTank",
		trackWidth             = 32,
		turninplace            = 0,
		turnRate               = 880,
		workerTime             = 0,
		weapons                = {
			{
				def                = "ARMLATNK_WEAPON",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs             = {
			panther_death = {
				areaOfEffect       = 352,
				craterBoost        = 0,
				craterMult         = 0,
				edgeEffectiveness  = 0.5,
				explosionGenerator = "custom:electric_explosion2",
				explosionSpeed     = 10,
				impulseBoost       = 0,
				impulseFactor      = 0,
				name               = "EMP Explosion",
				paralyzer          = true,
				paralyzeTime       = 16,
				soundHit           = "explosion/small_emp_explode",
				damage = {
					default          = 0,
				},
				customParams = {
					blastwave_speed = 15,
					blastwave_life = 10,
					blastwave_lossfactor = 0.88,
					blastwave_damage = 0,
					blastwave_empdmg = 1000,
					blastwave_emptime = 3,
					blastwave_slowdmg = 0,
					blastwave_size = 25,
					blastwave_impulse = 0,
				},
			},
			ARMLATNK_WEAPON = {
				name                    = "Lightning Cannon",
				areaOfEffect            = 64,
				craterBoost             = 0,
				craterMult              = 0,
				cegtag					= "antagonist_spark",

				customParams            = {
					extra_damage = 660,

					light_camera_height = 2000,
					light_color = "0.85 0.85 1.2",
					light_radius = 220,
				},

				cylinderTargeting      = 0,

				damage                  = {
					default        = 330.1,
				},

				duration                = 10,
				explosionGenerator      = "custom:lightningplosion_nopost",
				edgeeffectiveness		= 0.05,
				fireStarter             = 50,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 12,
				interceptedByShieldType = 1,
				paralyzeTime            = 1,
				range                   = 340,
				reloadtime              = 2,
				size                    = 0.6,
				mygravity				= 0.02,
				rgbColor                = "0.54 0.54 1",
				soundHit				= "weapon/emp/lightningcannon_hit",
				soundStart              = "weapon/emp/lightningcannon_fire",
				thickness               = 10,
				turret                  = true,
				waterweapon             = false,
				weaponType              = "Cannon",
				weaponVelocity          = 480,
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "corseal_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2c.s3o",
			},
		},
	} 
}