return { 
	tankcon = {
		unitname               = "tankcon",
		name                   = "Welder",
		description            = "Armed Construction Tank",
		acceleration           = 0.4,
		brakeRate              = 18.0,
		buildCostMetal         = 300,
		buildDistance          = 250,
		builder                = true,
		buildoptions           = {},
		buildPic               = "tankcon.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND",
		collisionVolumeOffsets = "0 6 0",
		collisionVolumeScales  = "34 18 46",
		collisionVolumeType    = "box",
		corpse                 = "DEAD",
		customParams           = {
			aimposoffset   = "0 0 0",
			midposoffset   = "0 -4 0",
			modelradius    = "30",
			selection_scale = 1.2,
			nanoregen = 10,
			nano_maxregen = 10,
			aim_lookahead = 120,
			needsfirecontrol = 1,
			outline_x = 80,
			outline_y = 80,
			outline_yoff = 12.5,
		},
		energyUse              = 0,
		explodeAs              = "BIG_UNITEX",
		footprintX             = 2,
		footprintZ             = 2,
		iconType               = "builder",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		leaveTracks            = true,
		health                 = 2500,
		maxSlope               = 18,
		speed                  = 1.7,
		maxWaterDepth          = 22,
		movementClass          = "TANK3",
		moveState              = 0,
		noAutoFire             = false,
		noChaseCategory        = "TERRAFORM FIXEDWING SATELLITE SUB",
		objectName             = "welder.s3o",
		script                 = "tankcon.lua",
		selfDestructAs         = "BIG_UNITEX",
		sfxtypes               = {
			explosiongenerators = {
				"custom:emg_shells_l",
				"custom:flashmuzzle1",
			},
		},
		showNanoSpray          = false,
		sightDistance          = 385,
		trackOffset            = 3,
		trackStrength          = 6,
		trackStretch           = 1,
		trackType              = "StdTank",
		trackWidth             = 38,
		turninplace            = 0,
		turnRate               = 1000,
		workerTime             = 10,
		weapons                = {
			{
				def                = "CANNON",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def                = "CANNON",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
		},
		weaponDefs             = {
			CANNON = {
				name                    = "Rotary Cannon",
				alphaDecay              = 0.1,
				areaOfEffect            = 24,
				colormap                = "1 0.95 0.4 1   1 0.95 0.4 1    0 0 0 0.01    1 0.7 0.2 1",
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting 		= 1,
				customParams        = {
					light_camera_height = 1200,
					light_color = "0.8 0.76 0.38",
					light_radius = 30,
					reaim_time = 1, -- fast update?
					script_reload = "0.8",
					recycler = 1,
					recycle_reductiontime = 0.2,
					recycle_reduction = 0.15,
					recycle_bonus = 0.15,
					recycle_reductionframes = 0.5,
					recycle_maxbonus = 20,
				},

				damage                  = {
					default = 10.1,
				},

				explosionGenerator      = "custom:EMG_HIT_HE",
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				noGap                   = false,
				noSelfDamage            = true,
				range                   = 350,
				reloadtime              = 1/30, -- 10 rnd per sec
				rgbColor                = "1 0.95 0.4",
				separation              = 2,
				size                    = 0.67,
				sizeDecay               = 0.0,
				soundhit			    = "weapon/cannon/cannon_hit1",
				soundStart              = "weapon/brawler_emg5",
				soundStartVolume        = 2,
				sprayAngle              = 600,
				stages                  = 10,
				tolerance               = 5000,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 720,
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "welder_dead.s3o",
				collisionVolumeOffsets        = "0 -2 0",
				collisionVolumeScales         = "34 18 46",
				collisionVolumeType           = "box",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = "debris3x3b.s3o",
			},
		},
	} 
}
