return { turretaaflak = {
		unitname                      = "turretaaflak",
		name                          = "Thresher",
		description                   = "Flak Canister AAA",
		buildCostMetal                = 575,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 5,
		buildingGroundDecalSizeY      = 5,
		buildingGroundDecalType       = "turretaaflak_aoplane.dds",
		buildPic                      = "turretaaflak.png",
		category                      = "FLOAT",
		collisionVolumeOffsets        = "0 11 -4",
		collisionVolumeScales         = "50 86 50",
		collisionVolumeType	        = "CylY",
		corpse                        = "DEAD",
		customParams                  = {
			aimposoffset   = "0 16 0",
		},
		explodeAs                     = "MEDIUM_BUILDINGEX",
		floater                       = true,
		footprintX                    = 3,
		footprintZ                    = 3,
		iconType                      = "staticaa",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		levelGround                   = false,
		health                        = 3500,
		maxSlope                      = 18,
		maxWaterDepth                 = 5000,
		noAutoFire                    = false,
		noChaseCategory               = "FIXEDWING LAND SINK TURRET SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER",
		objectName                    = "corflak.s3o",
		script                        = "turretaaflak.lua",
		selfDestructAs                = "MEDIUM_BUILDINGEX",
		sfxtypes               = {
			explosiongenerators = {
				"custom:heavy_cannon_muzzle",
			},
		},
		sightDistance                 = 720,
		useBuildingGroundDecal        = true,
		yardMap                       = "ooo ooo ooo",
		weapons                       = {
			{
				def                = "ARMFLAK_GUN",
				--badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
		},
		weaponDefs                    = {
			ARMFLAK_GUN = {
				name                    = "Flak Canister",
				areaOfEffect            = 0,
				burnblow                = true,
				canattackground         = false,
				--cegTag                  = "vulcanfx",
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting       = 1,
				cameraShake				= 0,
				customParams        	  = {
					isaa = "1", -- Weapondefs_post to set this to 10% for ground units.
					light_radius = 0,
					numprojectiles1 = 6,
					projectile1 = "turretaaflak_tritary",
					spawndist = 370,
					velspread1 = "6.37, 3, 6.37",
					proxy = 1, 
					damage_vs_shield = "300.3",
				},
				damage  = {
					default = 80.1*6,
				},
				--interceptor = 2,
				edgeEffectiveness       = 0.5,
				explosionGenerator      = "custom:EMG_HIT_HE",
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				leadLimit 				= 200,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 1200,
				reloadtime              = 1/2,
				size                    = 8,
				soundHit                = "weapon/cannon/cannon_fire4",
				soundHitVolume	        = 0.5,
				soundStart              = "weapon/cannon/cannon_fire9",
				soundStartVolume	= 1,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 1200,
				--coverage = 2200,
			},
			TRITARY = {
				name                    = "Flechette",
				cegTag                  = "flak_trail",
				areaOfEffect            = 160,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,
				cameraShake				= 0,
				customParams            = {
					light_camera_height = 2000,
					light_color = "1 0.2 0.2",
					reaim_time = 8, -- COB
					isaa = "1",
					light_radius = 0,
					isFlak = 1,
					cegtrail = "flak_trail",
				},
				damage = {
					default = 80.1,
				},
				--interceptor = 2,
				edgeEffectiveness       = 0.8,
				duration                = 0.02,
				explosionGenerator      = "custom:flakplosion",
				fireStarter             = 50,
				heightMod               = 1,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				range                   = 300,
				reloadtime              = 0.8,
				rgbColor                = "0.2 0.2 0.2",
				soundHit                = "weapon/flak_hit2",
				soundHitVolume	      = 0.4,
				--soundTrigger            = true,
				sprayangle              = 1500,
				size 					= 6,
				thickness               = 2,
				tolerance               = 10000,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 880,
				--coverage = 1000,
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "corflak_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = "debris3x3a.s3o",
			},
		},
	}
}
