return { 
	turretriot = {
		unitname                      = "turretriot",
		name                          = "Bombard",
		description                   = "Anti-Swarm Turret (Needs 4E Grid)",
		activateWhenBuilt             = true,
		buildCostMetal                = 200,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 5,
		buildingGroundDecalSizeY      = 5,
		buildingGroundDecalType       = "turretriot_aoplane.dds",
		buildPic                      = "turretriot.png",
		category                      = "FLOAT TURRET",
		collisionVolumeOffsets        = "0 0 0",
		collisionVolumeScales         = "45 45 45",
		collisionVolumeType           = "ellipsoid",
		corpse                        = "DEAD",
		customParams                  = {
			aimposoffset   = "0 12 0",
			midposoffset   = "0 4 0",
			aim_lookahead  = 100,
			neededlink  = 4,
			pylonrange  = 150,
			keeptooltip = "any string i want",
		},
		explodeAs                     = "LARGE_BUILDINGEX",
		floater                       = true,
		footprintX                    = 3,
		footprintZ                    = 3,
		iconType                      = "defenseriot",
		levelGround                   = false,
		health                        = 2000,
		maxSlope                      = 18,
		minCloakDistance              = 150,
		noChaseCategory               = "FIXEDWING LAND SHIP SWIM GUNSHIP SUB HOVER",
		objectName                    = "afury.s3o",
		script                        = "turretriot.lua",
		selfDestructAs                = "LARGE_BUILDINGEX",
		sfxtypes                      = {
			explosiongenerators = {
				"custom:RAIDMUZZLE",
				"custom:DEVA_SHELLS",
			},
		},
		sightDistance                 = 463, -- Range*1.1 + 48 for radar overshoot
		useBuildingGroundDecal        = true,
		yardMap                       = "ooo ooo ooo",
		weapons                       = {
			{
				def                = "WEAPON",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
				mainDir            = "0 1 0",
				maxAngleDif        = 320,
			},
		},
		weaponDefs                    = {
			secondary = {
				name                    = "Plasma Flechette",
				accuracy                = 350,
				alphaDecay              = 0.7,
				areaOfEffect            = 96,
				craterBoost             = 0.15,
				craterMult              = 0.3,
				customParams        = {
					light_camera_height = 1600,
					light_color = "0.8 0.76 0.38",
					light_radius = 40,
					isFlak = 3,
					flaktime = -15,
				},
				damage                  = {
					default = 11.1,
				},
				edgeEffectiveness       = 0.5,
				explosionGenerator      = "custom:EMG_HIT_HE",
				firestarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 275,
				reloadtime              = 0.5,
				rgbColor                = "1 0.95 0.4",
				size					= 0.65,
				separation              = 0.65,
				stages                  = 10,
				soundHit                = "weapon/cannon/emg_hit",
				soundStart              = "weapon/heavy_emg",
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 550,
			},
			WEAPON = {
				name                    = "Canister Autocannon",
				accuracy                = 200,
				alphaDecay              = 0.7,
				areaOfEffect            = 96,
				avoidFeature            = false,
				burnblow                = true,
				craterBoost             = 0.15,
				craterMult              = 0.3,
				customparams = {
					light_color = "0.8 0.76 0.38",
					light_radius = 180,
					numprojectiles1 = 6,
					projectile1 = "turretriot_secondary",
					spawndist = 200,
					timeoutspawn = 1, 
					velspread1 = "2.55, 2, 2.55",
					proxy = 1, 
					sweepfire = 1,
					sweepfire_maxangle = 30,
					sweepfire_step = 3,
					sweepfire_fastupdate = 1,
					sweepfire_maxrangemult = 0.98,
					overshoot = 1,
					overshoot_override = 70,
				},
				damage                  = {
					default = 11.1*6,
				},
				edgeEffectiveness       = 0.5,
				explosionGenerator      = "custom:NONE",
				firestarter             = 70,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 0.7,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 380,
				reloadtime              = 3/30,
				rgbColor                = "1 0.95 0.4",
				separation              = 1.5,
				soundHit                = "weapon/clusters/cluster_light",
				soundHitVolume			= 1.7,
				soundStart              = "weapon/heavy_emg",
				soundStartVolume        = 2.5,
				stages                  = 10,
				size					= 3.0,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 900,
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "afury_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = "debris4x4b.s3o",
			},
		},
	} 
}
