return { 
	turrettorp = {
		name              = "Starfish",
		description       = "Torpedo Launcher (Anti-Sub)",
		activateWhenBuilt = true,
		builder           = false,
		buildPic          = "turrettorp.png",
		category          = "SINK",
		collisionVolumeOffsets = "0 -5 0",
		collisionVolumeScales  = "42 50 42",
		collisionVolumeType    = "CylY",
		corpse            = "DEAD",
		customParams      = {
			aimposoffset   = "0 15 0",
			midposoffset   = "0 15 0",
		},
		explodeAs         = "MEDIUM_BUILDINGEX",
		footprintX        = 3,
		footprintZ        = 3,
		health            = 2500,
		iconType          = "defensetorp",
		maxSlope          = 18,
		metalCost         = 300,
		noAutoFire        = false,
		noChaseCategory   = "FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER",
		objectName        = "torpedo launcher.s3o",
		script            = "turrettorp.lua",
		selfDestructAs    = "MEDIUM_BUILDINGEX",
		sightDistance     = 750, -- Range*1.1 + 48 for radar overshoot
		yardMap           = "wwwwwwwww",
		weapons           = {
			{
				def                = "TORPEDO",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "SWIM FIXEDWING LAND SUB SINK TURRET FLOAT SHIP GUNSHIP HOVER",
			},
			{
				def                = "TORPEDOABOVEWATER",
				badTargetCategory  = "FIXEDWING",
				onlyTargetCategory = "SWIM FIXEDWING LAND SUB SINK TURRET FLOAT SHIP GUNSHIP HOVER",
			},
		},
		weaponDefs        = {
			TORPEDO = {
				name                    = "Torpedo Launcher",
				areaOfEffect            = 64,
				avoidFriendly           = false,
				canAttackGround         = false,
				collideFriendly         = false,
				craterBoost             = 0,
				craterMult              = 0,
				cegTag                  = "torpedo_trail",
				customparams = {
					stays_underwater = 1,
					cruise_torpedo = 1,
					cruisealt = -5,
					cruisetracking = 1,
					cruise_nolock = 1,
					cruisedist = 140,
					script_reload = "6.5",
					script_burst = "5",
				},
				damage                  = {
					default = 125,
				},
				explosionGenerator      = "custom:TORPEDO_HIT",
				edgeEffectiveness       = 0.6,
				flightTime              = 20,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				model                   = "wep_t_longbolt.s3o",
				range                   = 550,
				reloadtime              = 3/30,
				soundHit                = "explosion/wet/ex_underwater",
				soundStart              = "weapon/torpedo/torp_launch_amph_light",
				startVelocity           = 80,
				tracks                  = true,
				turnRate                = 27000,
				turret                  = true,
				waterWeapon             = true,
				weaponAcceleration      = 170,
				weaponType              = "TorpedoLauncher",
				weaponVelocity          = 600,
			},
			TORPEDOABOVEWATER = {
				name                    = "Torpedo Mortar",
				accuracy				= 400,
				avoidFriendly           = false,
				canAttackGround         = false,
				craterBoost             = 0,
				craterMult              = 0,
				customparams = {
					script_reload = "6.5",
					script_burst = "5",
					numprojectiles1 = 1,
					projectile1 = "turrettorp_torpedo",
					spawndist = 120,
					timeoutspawn = 1,
					useheight = 1,
					minvelocity = -0.35,
					velspread1 = "0, 0, 0",
					hideweapon = 1,
				},
				damage                  = {
					default = 125,
				},
				explosionGenerator      = "custom:none",
				groundbounce            = 1,
				edgeEffectiveness       = 0,
				highTrajectory          = 1,
				heightBoostFactor       = 0,
				impulseBoost            = 0,
				impulseFactor           = 0,
				impactOnly				= true,
				interceptedByShieldType = 1,
				model                   = "wep_t_longbolt.s3o",
				myGravity               = 0.125,
				range                   = 550,
				reloadtime              = 10/30,
				--soundHit                = "explosion/wet/ex_underwater",
				soundStart              = "weapon/cannon/medium_launcher",
				startVelocity           = 80,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 240,
				waterWeapon             = true,
			},
		},
		featureDefs       = {
			DEAD  = {
				blocking         = false,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "torpedo launcher_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = "debris3x3c.s3o",
			},
		},
	} 
}
