-- Also known as the "Leoj got rid of stuff, so let's recycle content" unit.

return { 
	turretheavy = {
		unitname						= "turretheavy",
		name							= "Bastion",
		description						= "Medium Range Defense Fortress - Power by connecting to a 50 energy grid",
		activateWhenBuilt					= true,
		buildCostMetal						= 2500,
		builder							= false,
		buildingGroundDecalDecaySpeed				= 30,
		buildingGroundDecalSizeX				= 5,
		buildingGroundDecalSizeY				= 5,
		buildingGroundDecalType					= "turretheavy_aoplane.dds",
		buildPic						= "turretheavy.png",
		category						= "SINK TURRET",
		collisionVolumeOffsets					= "0 0 0",
		collisionVolumeScales					= "45 100 45",
		collisionVolumeType					= "CylY",
		corpse							= "DEAD",
		customParams					= {
			keeptooltip			= "any string I want",
			neededlink			= 140,
			pylonrange			= 150,
			extradrawrange			= 450,
			aimposoffset			= "0 30 0",
			midposoffset			= "0 0 0",
			modelradius			= "20",
			outline_x			= 130,
			outline_y			= 150,
			outline_yoff			= 47.5,
			
			popupholdfirehp			= 0.35,
			popupunholdfirehp		= 0.60,
			popupusearmorstate		= 1,
			hasarmorstate 			= 1,
			armored_regen 			 = 68,
			armortype = 1, -- for context menu.
		},
		damageModifier						= 0.2,
		explodeAs						= "ESTOR_BUILDING",
		footprintX						= 3,
		footprintZ						= 3,
		iconType						= "staticassaultriot",
		levelGround						= false,
		losEmitHeight						= 70,
		health   						= 15000,
		maxSlope						= 18,
		maxWaterDepth						= 0,
		noChaseCategory						= "FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER",
		objectName						= "DDM.s3o",
		script							= "turretheavy.lua",
		selfDestructAs						= "ESTOR_BUILDING",
		sfxtypes						= {
			explosiongenerators	= {
				"custom:LARGE_MUZZLE_FLASH_FX",
			},
		},
		sightDistance						= 763, -- Range*1.1 + 48 for radar overshoot
		useBuildingGroundDecal					= true,
		yardMap							= "ooo ooo ooo",
		weapons							= {
			{
				def					= "PLASMA",
				badTargetCategory			= "FIXEDWING GUNSHIP",
				onlyTargetCategory			= "FIXEDWING SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
			},
			{
				def					= "HEATRAY",
				badTargetCategory			= "FIXEDWING",
				onlyTargetCategory			= "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def					= "HEATRAY",
				badTargetCategory			= "FIXEDWING",
				onlyTargetCategory			= "FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER",
			},
			{
				def					= "SHIELD",
			},
		},
		weaponDefs	= {
			HEATRAY = {
				name			= "Heavy Heat Ray",
				areaOfEffect		= 25,
				avoidFeature		= false,
				beamtime		= 4/30,
				coreThickness		= 0.9,
				craterBoost		= 0,
				craterMult		= 0,
				cylinderTargeting	= 0.6,
				explosionScar		= false,
				customParams        = {
					light_camera_height		= 1500,
					light_color			= "0.9 0.4 0.12",
					light_radius			= 100,
					light_fade_time			= 25,
					light_fade_offset		= 10,
					light_beam_mult_frames		= 9,
					light_beam_mult			= 8,
				},
				damage                  = {
					default = 95.1,
				},
				duration		= 0.3,
				dynDamageExp		= 1,
				dynDamageInverted	= false,
				explosionGenerator	= "custom:HEATRAY_HIT",
				fallOffRate		= 1,
				fireStarter		= 90,
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				leadLimit               = 0.1,
				lodDistance             = 10000,
				noSelfDamage            = true,
				proximityPriority       = 10,
				range                   = 450,
				reloadtime              = 0.1,
				rgbColor                = "1 0.54 0",
				rgbColor2               = "1 1 0.25",
				soundStart              = "weapon/heatray_fire",
				thickness               = 2,
				tolerance               = 5000,
				turret                  = true,
				weaponType              = "BeamLaser",
				weaponVelocity          = 500,
			},
			PLASMA = {
				name                    = "Oblivion Cannon",
				accuracy                = 0,
				areaOfEffect            = 128,
				avoidFeature            = false,
				avoidGround             = true,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					restrict_in_widgets = 1,
					light_camera_height = 3500,
					light_color = "0.75 0.4 0.15",
					light_radius = 220,
					numprojectiles1 = 12,
					projectile1 = "turretheavy_fragment_dummy",
					velspread1 = "3.18, 3, 3.18, _, 6, _",
					noairburst = "March of progress",
					onexplode = "The unity prevails",
					shield_damage = (300*12) + 3200,
				},

				damage                  = {
					default = 3200.01,
				},
				
				explosionGenerator      = "custom:nce_128",
				edgeEffectiveness	= 0.1,
				fireTolerance           = 1820, -- 10 degrees
				impulseBoost            = 2,
				impulseFactor           = 1.3,
				interceptedByShieldType = 1,
				noSelfDamage            = true,
				range                   = 720,
				reloadtime              = 6,
				rgbColor                = "0.615 0.447 0.412",
				soundHit                = "weapon/cannon/tankbuster_hit",
				soundStart              = "weapon/cannon/reaper_fire",
				size                    = 12,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 1200,
			},
			FRAGMENT_DUMMY = {
				name                    = "Fragment",
				accuracy                = 400,
				areaOfEffect            = 162,
				avoidFeature            = false,
				craterBoost             = 1,
				craterMult              = 2,
				customParams              = {

					numprojectiles1 = 1,
					projectile1 = "turretheavy_final",
					noairburst = "Burning time",
					timeddeploy = 9,
					light_camera_height = 2500,
					light_color = "0.25 0.13 0.05",
					light_radius = 500,
					shield_damage = 300,
					bogus = 1,
				},
				damage                  = {
					default = 0,
				},

				firestarter             = 180,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				myGravity               = 0.33,
				noExplode               = true,
				projectiles             = 10,
				range                   = 900,
				reloadtime              = 12,
				rgbColor                = "1 0.95 0.4",
				size 			= 6,
				soundHit                = "nosound",
				soundStart              = "weapon/cannon/frag_impact",
				soundStartVolume        = 3.2,
				sprayangle              = 2500,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 320,
			},
			FINAL = {
				name                    = "Oblivion Flechette",
				--cegTag                = "flak_trail",
				areaOfEffect            = 120,
				alphaDecay              = 0.7,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,

				customParams            = {
					light_camera_height = 2000,
					light_color = "1 0.2 0.2",
					isaa = "1",
					light_radius = 0,
				},

				damage = {
					default = 450.01,
				},
				edgeEffectiveness       = 0.8,
				explosionGenerator      = "custom:bigbulletimpact",
				fireStarter             = 50,
				flighttime		= 7,
				heightMod               = 1,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 1,
				range                   = 500,
				reloadtime              = 0.8,
				rgbColor                = "1 0.95 0.4",
				soundHit                = "explosion/ex_med6",
				soundHitVolume	        = 0.4,
				sprayangle              = 1500,
				size 			= 6,
				thickness               = 6,
				tolerance               = 10000,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 920,
				--coverage = 1000,
			},
			SHIELD      = {
				name                    = "Energy Shield",
				damage                  = {
					default = 10,
				},
				customParams			= {
					unlinked	= true,
				},
				exteriorShield          = true,
				shieldAlpha             = 0.2,
				shieldBadColor          = "1 0.1 0.1 1",
				shieldGoodColor         = "0.1 0.1 1 1",
				shieldInterceptType     = 3,
				shieldPower             = 8500,
				shieldPowerRegen        = 65,
				shieldPowerRegenEnergy  = 20,
				shieldRadius            = 250,
				shieldRepulser          = false,
				shieldStartingPower     = 1000,
				smartShield             = true,
				visibleShield           = false,
				visibleShieldRepulse    = false,
				weaponType              = "Shield",
			},
		},
		featureDefs                   = {
			DEAD = {
				blocking		= true,
				featureDead		= "HEAP",
				footprintX		= 3,
				footprintZ		= 3,
				object			= "ddm_dead.s3o",
			},
			HEAP = {
				blocking		= false,
				footprintX		= 3,
				footprintZ		= 3,
				object			= "debris3x3c.s3o",
			},
		},
	} 
}
