return { 
	turretaaheavy = {
		unitname                      = "turretaaheavy",
		name                          = "Skyshield",
		description                   = "Very Long-Range AA Maser Tower",
		activateWhenBuilt             = true,
		buildCostMetal                = 4000,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 6,
		buildingGroundDecalSizeY      = 6,
		buildingGroundDecalType       = "turretaaheavy_aoplane.dds",
		buildPic                      = "turretaaheavy.png",
		category                      = "SINK",
		collisionVolumeOffsets        = "0 0 0",
		collisionVolumeScales         = "74 74 74",
		collisionVolumeType           = "ellipsoid",
		corpse                        = "DEAD",
		customParams                  = {
			bait_level_default = 2,
			modelradius    = "37",
			dontfireatradarcommand = '0',
			superweapon    = 1,
			superweaponcoef    = 0.59,
			superweapondenom   = 22,
    		neededlink     = 300,
   			pylonrange     = 250,
			battery = 300,
			batterygain = 5,
		},
		explodeAs                     = "ESTOR_BUILDING",
		footprintX                    = 4,
		footprintZ                    = 4,
		iconType                      = "heavysam",
		idleAutoHeal                  = 5,
		idleTime                      = 1800,
		health                        = 8000,
		maxSlope                      = 18,
		maxWaterDepth                 = 0,
		noAutoFire                    = false,
		objectName                    = "SCREAMER.s3o",
		onoffable                     = false,
		script                        = "turretaaheavy.lua",
		selfDestructAs                = "ESTOR_BUILDING",
		sightDistance                 = 660,
		useBuildingGroundDecal        = true,
		yardMap                       = "oooooooooooooooo",
		weapons                       = {
			{
				def                = "ADVSAM",
				onlyTargetCategory = "FIXEDWING GUNSHIP SATELLITE",
			},
		},
		weaponDefs                    = {
			ADVSAM = {
				name                    = "Heavy AA Maser",
				areaOfEffect            = 240,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,
				canAttackGround         = false,
				cameraShake             = 10,
				customParams              = {
					isaa = "1",
					light_color = "0.1255 0.69804 0.66667",
					light_radius = 600,
					reveal_unit = 8,
					batterydrain = 4,
					batterychecklevel = 8,
					reaim_time = 1,
				},
				damage                  = {
					default    = 250.1,
				},
				beamTTL                 = 3/30,
				beamDecay               = 0.85,
				beamTime                = 1/30,
				explosionGenerator      = "custom:beamlaser_hit_maser",
				explosionscar           = false,
				fireStarter             = 100,
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 1,
				laserflaresize			= 5,
				noSelfDamage            = true,
				range                   = 2880,
				reloadtime              = 1/30,
				rgbColor                = "0.1255 0.69804 0.66667",
				soundStart              = "weapon/laser/maser_fire",
				soundstartvolume	    = 10,
				thickness               = 60.5,
				tolerance               = 32000,
				turret                  = true,
				weaponType              = "BeamLaser",
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 4,
				footprintZ       = 4,
				object           = "screamer_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 4,
				footprintZ       = 4,
				object           = "debris4x4a.s3o",
			},
		},
	} 
}
