return { 
	turretaaclose = {
		unitname                      = "turretaaclose",
		name                          = "Duster",
		description                   = "Laser Guided Anti-Air Turret",
		buildCostMetal                = 250,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 4,
		buildingGroundDecalSizeY      = 4,
		buildingGroundDecalType       = "turretaaclose_aoplane.dds",
		buildPic                      = "turretaaclose.png",
		category                      = "FLOAT",
		collisionVolumeOffsets        = "0 12 0",
		collisionVolumeScales         = "42 53 42",
		collisionVolumeType            = "CylY",
		corpse                        = "DEAD",
		customParams                  = {
			aim_lookahead      = 120,
			bait_level_default = 1,
		},
		explodeAs                     = "SMALL_BUILDINGEX",
		floater                       = true,
		footprintX                    = 3,
		footprintZ                    = 3,
		iconType                      = "defenseskirmaa",
		levelGround                   = false,
		losEmitHeight				  = 150,
		maxDamage                     = 2000,
		maxSlope                      = 18,
		minCloakDistance              = 150,
		noAutoFire                    = false,
		noChaseCategory               = "FIXEDWING LAND SINK TURRET SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER",
		objectName                    = "missiletower.dae",
		script                        = "turretaaclose.lua",
		selfDestructAs                = "SMALL_BUILDINGEX",
		sfxtypes                      = {
			explosiongenerators = {
				"custom:STORMMUZZLE",
				"custom:STORMBACK",
			},
		},
		sightDistance                 = 1300,
		useBuildingGroundDecal        = true,
		waterline                     = 10,
		yardMap                       = "ooooooooo",
		weapons                       = {
			{
				def                = "MISSILE",
				badTargetCategory  = "GUNSHIP",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
			{
				def                = "TRACKER",
				badTargetCategory  = "GUNSHIP",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
		},
		weaponDefs                    = {
			MISSILE = {
				name                    = "LGAAM-4 Salvo",
				areaOfEffect            = 24,
				canattackground         = false,
				cegTag                  = "missiletrailbluebig",
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting       = 3,
				customParams = {
					burst = Shared.BURST_RELIABLE,
					isaa = "1",
					script_reload = "4.7",
					script_burst = "4",
					light_color = "0.5 0.6 0.6",
					tracker = 1,
					laserguidance_failtime = 10,
				},
				damage                  = {
					default = 500.01,
				},
				explosionGenerator      = "custom:FLASH2",
				fireStarter             = 70,
				flightTime              = 14,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 2,
				leadLimit               = 0,
				model                   = "wep_m_phoenix.s3o",
				noSelfDamage            = true,
				range                   = 1300,
				reloadtime              = 3/30,
				smokeTrail              = true,
				soundHit                = "explosion/ex_med11",
				soundStart              = "weapon/missile/missile_fire3",
				startVelocity           = 420,
				texture2                = "AAsmoketrail",
				tracks                  = true,
				turnRate                = 170000,
				turret                  = true,
				weaponAcceleration      = 600,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 1020,
			},
			TRACKER = {
				name                    = "Missile Target Painter",
				areaOfEffect            = 20,
				beamTime                = 0.01,
				coreThickness           = 0.5,
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting       = 1,
				customParams            = {
					targeter = 1,
					--burst = Shared.BURST_RELIABLE,
					stats_hide_damage = 1, -- continuous laser
					stats_hide_reload = 1,
					light_color = "1.25 0 0",
					light_radius = 60,
				},
				damage                  = {
					default = 0.00,
				},
				--explosionGenerator      = "custom:flash1red",
				fireTolerance           = 8192, -- 45 degrees
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0.4,
				interceptedByShieldType = 0,
				largeBeamLaser          = true,
				laserFlareSize          = 2,
				leadLimit               = 18,
				minIntensity            = 0.01,
				noSelfDamage            = true,
				range                   = 1330,
				reloadtime              = 2/30,
				--sweapfire = false,
				rgbColor                = "0.8 0 0",
				rgbColor2				  = "0.5 0 0",
				soundStart              = "weapon/laser/archertracker",
				--soundHit		= "trackercompleted"
				soundStartVolume        = 15,
				texture1                = "tracker",
				texture2                = "null",
				texture3                = "flare",
				texture4                = "null",
				thickness               = 2,
				tolerance               = 65536/4,
				turret                  = true,
				weaponType              = "BeamLaser",
				weaponVelocity          = 1500,
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 3,
				footprintZ       = 3,
				object           = "turretaaclose_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = "debris3x3a.s3o",
			},
		},
	}
}
