return { 
	turretemp = {
		unitname                      = "turretemp",
		name                          = "Pulse",
		description                   = "EMP Turret",
		buildCostMetal                = 275,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 4,
		buildingGroundDecalSizeY      = 4,
		buildingGroundDecalType       = "turretemp_aoplane.dds",
		buildPic                      = "turretemp.png",
		category                      = "SINK TURRET",
		collisionVolumeOffsets        = "0 0 0",
		collisionVolumeScales         = "32 75 32",
		collisionVolumeType           = "CylY",
		corpse                        = "DEAD",
		customParams                  = {
			bait_level_default = 1,
			bait_level_target_armor = 1,
			aimposoffset   = "0 10 0",
			modelradius    = "16",
			aim_lookahead  = 50,
			popupholdfirehp = 0.45,
			popupunholdfirehp = 0.66,
			armortype = 1, -- for context menu.
		},
		damageModifier                = 0.2,
		explodeAs                     = "MEDIUM_BUILDINGEX",
		footprintX                    = 2,
		footprintZ                    = 2,
		iconType                      = "defensespecial",
		levelGround                   = false,
		health                        = 3000,
		maxSlope                      = 36,
		maxWaterDepth                 = 0,
		noChaseCategory               = "FIXEDWING LAND SHIP SWIM GUNSHIP SUB HOVER",
		objectName                    = "armartic.s3o",
		script                        = "turretemp.lua",
		selfDestructAs                = "MEDIUM_BUILDINGEX",
		sfxtypes                      = {
			explosiongenerators = {
				"custom:zeus_fire_fx",
				"custom:YELLOW_LIGHTNING_GROUNDFLASH",
			},
		},
		sightDistance                 = 600, -- Range*1.1 + 48 for radar overshoot
		useBuildingGroundDecal        = true,
		yardMap                       = "oo oo",
		weapons                       = {
			{
				def                = "emp",
				onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER FIXEDWING GUNSHIP",
			},
			{
				def                = "SUBLIGHTNING_END",
				--mainDir            = "0 0 0",
				--maxAngleDif        = 180,
			},
		},
		weaponDefs                    = {
			emp = {
				name                    = "Light EMP Bolter",
				areaOfEffect            = 120,
				cegtag					= "artillery_spark_small_commander",
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					light_camera_height = 1600,
					light_color = "0.85 0.85 1.2",
					light_radius = 200,
					extra_damage = 1400,
					chainlightning_num = 1,
					chainlightning_searchdist = 180,
					chainlightning_ff = 0,
					chainlightning_maxtargets = 5,
					chainlightning_index = 2,
					chainlightning_spawn = "turretemp_sublightning_end",
					chainlightning_efficency = 0.5,
				},
				damage                  = {
					default = 140.1,
				},
				cylinderTargeting       = 1,
				explosionGenerator      = "custom:hammer_artillery_hit",
				edgeEffectiveness       = 0.05,
				heightBoostFactor 		= 0,
				paralyzeTime            = 1,
				impactOnly              = false,
				interceptedByShieldType = 1,
				range					= 500,
				myGravity               = 0.02,
				reloadtime              = 1.8,
				soundHit                = "weapon/cannon/emp_arty_hit",
				soundStart              = "weapon/emp/commweapon_emplight_fire",
				size					= 0.01,
				turret                  = true,
				weaponType              = "Cannon",
				weaponVelocity          = 700,
			},
			SUBLIGHTNING_END = {
				name                    = "Discharge",
				areaOfEffect            = 30,
				avoidFeature            = false,
				avoidFriendly           = false,
				avoidGround             = false,
				beamTTL                 = 12,
				beamDecay               = 0.85,
				craterBoost             = 0,
				craterMult              = 0,
				customParams            = {
					light_camera_height = 2500,
					light_color = "0.66 0.32 0.90",
					light_radius = 30,
					hideweapon = 1,
					extra_damage = 700,
				},
				damage                  = {
					default        = 70.01,
				},
				--explosionGenerator      = "custom:hammer_artillery_hit",
				fireStarter             = 50,
				impactOnly              = true,
				impulseBoost            = 0,
				impulseFactor           = 0,
				intensity               = 6,
				interceptedByShieldType = 1,
				paralyzeTime            = 1,
				range                   = 225,
				reloadtime              = 10/30,
				rgbColor                = "0.85 0.85 1",
				soundHit                = "weapon/constant_electric",
				soundHitVolume          = 9,
				thickness               = 3,
				texture1                = "lightning",
				texture2                = "null",
				texture3                = "null",
				texture4                = "null",
				turret                  = true,
				weaponType              = "LightningCannon",
			},
		},
		featureDefs                   = {
			DEAD  = {
				blocking         = true,
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "armartic_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris3x3b.s3o",
			},
		},
	}
}
