return { 
	vehaa = {
		unitname               = "vehaa",
		name                   = "Gatekeeper",
		description            = "Anti-Air Rover",
		acceleration           = 0.36,
		brakeRate              = 1.8,
		buildCostMetal         = 200,
		builder                = false,
		buildPic               = "vehaa.png",
		canGuard               = true,
		canMove                = true,
		canPatrol              = true,
		category               = "LAND",
		collisionVolumeOffsets = "0 0 0",
		collisionVolumeScales  = "18 20 40",
		collisionVolumeType    = "box",
		corpse                 = "DEAD",
		customParams           = {
			modelradius    = "9",
			bait_level_default = 0,
			outline_x = 80,
			outline_y = 80,
			outline_yoff = 12.5,
		},
		explodeAs              = "BIG_UNITEX",
		footprintX             = 3,
		footprintZ             = 3,
		iconType               = "vehicleaa",
		idleAutoHeal           = 5,
		idleTime               = 1800,
		leaveTracks            = true,
		maneuverleashlength    = "30",
		health                 = 1200,
		maxSlope               = 18,
		speed                  = 4.1,
		maxReverseVelocity     = 4.1,
		maxWaterDepth          = 22,
		movementClass          = "TANK3",
		moveState              = 0,
		noAutoFire             = false,
		noChaseCategory        = "TERRAFORM LAND SINK TURRET SHIP SATELLITE SWIM FLOAT SUB HOVER",
		objectName             = "vehaa.s3o",
		script                 = "vehaa.lua",
		selfDestructAs         = "BIG_UNITEX",
		sfxtypes               = {
			explosiongenerators = {
				"custom:rapiermuzzle",
				"custom:STORMBACK",
			},
		},
		sightDistance          = 760,
		trackOffset            = 6,
		trackStrength          = 5,
		trackStretch           = 1,
		trackType              = "StdTank",
		trackWidth             = 32,
		turninplace            = 0,
		turnRate               = 1044,
		upright                = false,
		workerTime             = 0,
		weapons                       = {
			{
				def                = "MISSILE",
				onlyTargetCategory = "FIXEDWING GUNSHIP",
			},
		},
		weaponDefs                    = {
			MISSILE = {
				name                    = "Heavy Missile",
				areaOfEffect            = 120,
				canattackground         = false,
				cegTag                  = "missiletrailpurple",
				craterBoost             = 0,
				craterMult              = 0,
				cylinderTargeting       = 1,
				customParams              = {
					burst = Shared.BURST_RELIABLE,
					isaa = "1",
					light_color = "0.5 0.6 0.6",
					timeslow_damagefactor = 4,
				},
				damage                  = {
					default = 430.1,
				},
				edgeeffectiveness		= 0.2,
				explosionGenerator      = "custom:riotballplus2_purple_small_darker",
				fixedlauncher           = true,
				fireStarter             = 70,
				flightTime              = 3,
				impactOnly              = false,
				impulseBoost            = 0,
				impulseFactor           = 0,
				interceptedByShieldType = 2,
				model                   = "wep_m_phoenix.s3o",
				noSelfDamage            = true,
				range                   = 680,
				reloadtime              = 2.5,
				smokeTrail              = true,
				soundHit                = "weapon/missile/sabot_hit",
				soundStart              = "weapon/missile/missile_fire",
				startVelocity           = 300,
				texture2                = "purpletrail",
				tolerance               = 9000,
				tracks                  = true,
				turnRate                = 63000,
				turret                  = true,
				weaponAcceleration      = 1200,
				weaponType              = "MissileLauncher",
				weaponVelocity          = 700,
			},
		},
		featureDefs            = {
			DEAD  = {
				blocking         = true,
				collisionVolumeOffsets = "0 0 0",
				collisionVolumeScales  = "32 40 52",
				collisionVolumeType    = "box",
				featureDead      = "HEAP",
				footprintX       = 2,
				footprintZ       = 2,
				object           = "vehaa_dead.s3o",
			},
			HEAP  = {
				blocking         = false,
				footprintX       = 2,
				footprintZ       = 2,
				object           = "debris2x2a.s3o",
			},
		},
	} 
}
